force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Enrollment_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Document</label>
        <referenceTo>Enrollment_Document__c</referenceTo>
        <relationshipLabel>Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Enrollment_Component_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Component Affiliation</label>
    <referenceTo>Enrollment_Component_Affiliation__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Document_Status_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Document type identifier</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Peak_FileUploadControllerTest.cls
@IsTest
private class Peak_FileUploadControllerTest {
    public static Account testAccount = new Account();
    public static Attachment testAttachment = new Attachment();
    public static Enrollment_Component_Affiliation__c  eca = new Enrollment_Component_Affiliation__c();
    public static Enrollment_Component_Affiliation__c  eca1 = new Enrollment_Component_Affiliation__c();
    Public static Enrollment_Document__c ed1 = new Enrollment_Document__c();
    public static hed__Program_Enrollment__c ProgramEnrollmentTest = new hed__Program_Enrollment__c();
    Public static Enrollment_Component__c ecp = new Enrollment_Component__c();

    static void testSetup() {
        testAccount = Peak_TestUtils.createTestAccount();


        String base64Data = EncodingUtil.urlDecode(Peak_TestConstants.BASE64FILE, 'UTF-8');
        testAttachment.parentId = testAccount.Id;

        testAttachment.Body = EncodingUtil.base64Decode(base64Data);
        testAttachment.Name = Peak_TestConstants.FILENAME;
        testAttachment.ContentType = Peak_TestConstants.FILETYPE;


        insert testAttachment;
        
        //Swapna: test coverage
                Account houseHoldAccount = Peak_TestUtils.createAccountRecord('Testy5', 'Household'); 
        Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        Contact TestContact = Peak_TestUtils.createTestContact();
        String conId = TestContact.Id;
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('2018-2019', System.today());
        Account academicAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id, schlYear.Id);
        ProgramEnrollmentTest = Peak_TestUtils.createProgramEnrollment(academicAccount.Id, TestContact.Id, schlYear.Id, true);
         ecp = Peak_TestUtils.createEnrollmentComponent(academicAccount.Id, 'Form', true);
        Enrollment_Component__c ecc = Peak_TestUtils.createEnrollmentComponent(academicAccount.Id, 'Question', true);
        Enrollment_Component__c ecp1 = Peak_TestUtils.createEnrollmentComponent(academicAccount.Id, 'Form', true);
        Enrollment_Component__c ecd = Peak_TestUtils.createEnrollmentComponent(academicAccount.Id, 'Document', true);
        Enrollment_Component_Relationship__c ecr = Peak_TestUtils.createEnrollmentComponentRelationship(ecc.id,ecp.id);
        Enrollment_Component_Relationship__c ecr1 = Peak_TestUtils.createEnrollmentComponentRelationship(ecd.id,ecp1.id);
         eca = Peak_TestUtils.createEnrollmentComponentAffiliation(ProgramEnrollmentTest.Id, ecc.Id);
         eca1 = Peak_TestUtils.createEnrollmentComponentAffiliation(ProgramEnrollmentTest.Id, ecd.Id);
         ed1 = Peak_TestUtils.createEnrollmentDocumentRecord(ProgramEnrollmentTest.id);
        ed1.Type__c = '504 Plan';
        ed1.Status_Reason__c = 'Submitted';
        update ed1;
    }
    @isTest
    public static void testGetFileRestrictions() {
        Network testNetwork;
        List<Network> testNetworkList = [SELECT Id, MaxFileSizeKb, AllowedExtensions FROM Network];
        System.debug('testNetworkList ======  ' + testNetworkList);
        if (!Peak_Utils.isNullOrEmpty(testNetworkList)) {
            testNetwork = testNetworkList[0];
            if(testNetwork.MaxFileSizeKb == null || testNetwork.MaxFileSizeKb == 0 || testNetwork.MaxFileSizeKb > 4248){
                testNetwork.MaxFileSizeKb = 4248;
                //If the heap issue ever gets fixed then set the max size to the Salesforce max file size of 2GB.
                //curNetwork.MaxFileSizeKb = 2097152;
            }
        }
        Network testResults = (Network)Peak_FileUploadController.getFileRestrictions().results[0];
        String testString = testResults.AllowedExtensions + testResults.MaxFileSizeKb;
        String assertString = testNetwork.AllowedExtensions + testNetwork.MaxFileSizeKb;

        System.assertEquals(assertString, testString);
    }
    @isTest
    public static void saveChunkSaveTest() {
        testSetup();
        Peak_Response testResults = Peak_FileUploadController.saveChunk(testAccount.Id, Peak_TestConstants.FILENAME, Peak_TestConstants.BASE64FILE, Peak_TestConstants.FILETYPE, null);
        Peak_ContentObject testPeakResults = (Peak_ContentObject)testResults.peakResults[0];
        System.assertEquals(testResults.success, true);
        System.assertNotEquals(testPeakResults.contentID, null);
     
    }
    @isTest
    public static void saveChunkAppendTest() {
        testSetup();
        Peak_Response testResults = Peak_FileUploadController.saveChunk(testAccount.Id, Peak_TestConstants.FILENAME, Peak_TestConstants.BASE64FILE, Peak_TestConstants.FILETYPE, testAttachment.Id);
        Peak_ContentObject testPeakResults = (Peak_ContentObject)testResults.peakResults[0];

        System.assertEquals(testResults.success, true);
        System.assertNotEquals(testPeakResults.contentID, null);
       
    }
    @isTest
    public static void saveTheFileTest() {
        testSetup();

        Attachment testAttachment = Peak_FileUploadController.saveTheFile(testAccount.Id, Peak_TestConstants.FILENAME, Peak_TestConstants.BASE64FILE, Peak_TestConstants.FILETYPE);
        String testString = testAttachment.Name + testAttachment.ContentType;
        String assertString = Peak_TestConstants.FILENAME + Peak_TestConstants.FILETYPE;

        System.assertEquals(assertString, testString);
        System.assertNotEquals(null, testAttachment.Id);
    }
    @isTest
    public static void appendToFileTest() {
        testSetup();

        Attachment testResults = Peak_FileUploadController.appendToFile(testAttachment.Id, Peak_TestConstants.BASE64FILE);
        String testString = testResults.Id + testResults.Name + testResults.ContentType;
        String assertString = testAttachment.Id + Peak_TestConstants.FILENAME + Peak_TestConstants.FILETYPE;

        System.assertEquals(assertString, testString);
    }
    @isTest
    public static void deleteAttachmentTest() {
        testSetup();

        Peak_Response testResults = Peak_FileUploadController.deleteAttachment(testAttachment.Name, testAttachment.parentId);
        Attachment deletedAttachment = [SELECT Id, IsDeleted FROM Attachment WHERE Id = :testAttachment.Id ALL ROWS];

        System.assertEquals(true, testResults.success);
        System.assertEquals(true, deletedAttachment.IsDeleted);
        //Swapna:for test coverage
         Peak_Response testResults1 = Peak_FileUploadController.deleteAttachment(testAttachment.Name, '');
    }
    //Swapna:for GTM + test coverage
    @isTest
    public static void getFormTest() {
       testSetup();
     String frmname = Peak_FileUploadController.getFormName(eca.Id);
    }
     @isTest
    public static void getECATest() {
       testSetup();
     Peak_Response feca = Peak_FileUploadController.getECA(eca1.Id,ed1.Id);
         Peak_Response feca1 = Peak_FileUploadController.getECA('',ed1.Id);
        
    }
     @isTest
    public static void createEnrollmentDocumentTest() {
       testSetup();
        List<String> doclink = new List<String>{'test.jpg','test1.jpg'};
       
            Peak_Response ec = Peak_FileUploadController.createEnrollmentDocuments(eca1.Id,ed1.Id,doclink);
           
        
    }
    
     @isTest
    public static void grabURLredirectTest() {
       testSetup();
        
       Peak_Response ec = Peak_FileUploadController.grabURLredirect(ProgramEnrollmentTest.Id,eca.Id,ecp.Id);
         
      
    }
}