force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Confirmation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_End_Date__c</fullName>
    <description>The date/time that final confirmation stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <formula>&apos;&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Year</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ecrTree__c.object
<CustomObject>
    <description>Holds the JSON representation of Academic Program, built using ECR records.</description>
    <label>ecrTree</label>
    <nameField>
        <displayFormat>ECRT-{00000}</displayFormat>
        <label>rootNode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ecrTree</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Process_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic program associated with the component. This is exclusively used by components with a record type of Process to create a relationship between the account entity and it&apos;s required components. As the child components of the process could be used by multiple processes, there is not a direct relationship between them and a specific academic program and those relationships are inferred from their parent process.</description>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enrollment Components (Academic Program)</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question_Group</fullName>
        <active>true</active>
        <label>Question Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_ECDataImportExportTest.cls
/** 

    @author: Ali KM (Ness Tech)
    * Created this test class on 04/17/2020 for [US 166761]
    * Test coverage for 
        => NES_ECDataImportExport.cls (86% coverage)
        => NES_EnrollmentCompentBuilder.cls (100% coverage)

*/

@isTest(SeeAllData=false isParallel=true)
public with sharing class NES_ECDataImportExportTest {

    @TestSetup 
    static void setup() {

        Account account = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019', Date.parse('11/17/2018'));
        // School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018', Date.parse('11/17/2017'));


        // Create a contact with 'Students' record type
        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);


        // Create a account with 'Academic Program' record type
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(account.Id, currentSchoolYear.Id);
        academicProgram.Registration_End_Date__c=Date.today().addMonths(1);
        academicProgram.Registration_Start_Date__c=Date.newInstance(2017,11,11);
        academicProgram.Confirmation_End_Date__c = Date.today().addMonths(1);
        update academicProgram;


        // Create STUDENT PE
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, currentSchoolYear.Id, false);
        progEnrollment.Status__c='Inactive';
        insert progEnrollment;


        // NOT SURE WHY WE NEED Relationship
        User u = [SELECT Id,ContactId FROM User WHERE ContactId != NULL AND IsActive = TRUE LIMIT 1];
        hed__Relationship__c  relationship = Peak_TestUtils.createRelationship(u.ContactId, contact.Id, true);


        // Create nodes (w/ECs)
        Enrollment_Component__c processComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Process', false); // Level 1 process
        Enrollment_Component__c stageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Stage', false); // Level 2 stages 
        Enrollment_Component__c formComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Form', false); // Level 3 forms
        // Level 4 sections
        Enrollment_Component__c sectionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Section', false);
        Enrollment_Component__c documentComponentForForm = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Document', false);
        // Level 5 questionGroups / questions (for sections)
        Enrollment_Component__c questionGroupComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question_Group', false);
        Enrollment_Component__c questionComponentForSection1 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false); 
        Enrollment_Component__c questionComponentForSection2 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        Enrollment_Component__c messageComponentForSection = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Message', false);
        // Level 6 questions 
        Enrollment_Component__c questionComponentForQG1 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        Enrollment_Component__c questionComponentForQG2 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        Enrollment_Component__c questionComponentForQG3 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        

        // insert nodes
        List < Enrollment_Component__c > componentList = new List < Enrollment_Component__c > ();
        componentList.add(processComponent);
        componentList.add(stageComponent);
        componentList.add(formComponent);
        componentList.add(sectionComponent);
        componentList.add(documentComponentForForm);
        componentList.add(questionGroupComponent);
        componentList.add(questionComponentForSection1);
        componentList.add(questionComponentForSection2);
        componentList.add(messageComponentForSection);
        componentList.add(questionComponentForQG1);
        componentList.add(questionComponentForQG2);
        componentList.add(questionComponentForQG3);
        insert componentList;
        

        // tie the nodes (by ECRs)
        Enrollment_Component_Relationship__c stageECR = Peak_TestUtils.createEnrollmentComponentRelationship(stageComponent.Id, processComponent.Id); // level-1
        Enrollment_Component_Relationship__c formECR = Peak_TestUtils.createEnrollmentComponentRelationship(formComponent.Id, stageComponent.Id); // level-2
        Enrollment_Component_Relationship__c sectionECR = Peak_TestUtils.createEnrollmentComponentRelationship(sectionComponent.Id, formComponent.Id); // level-3
        Enrollment_Component_Relationship__c documentECR = Peak_TestUtils.createEnrollmentComponentRelationship(documentComponentForForm.Id, formComponent.Id); // level-3
        
        Enrollment_Component_Relationship__c questionGroupECR = Peak_TestUtils.createEnrollmentComponentRelationship(questionGroupComponent.Id, sectionComponent.Id); // level-4
        Enrollment_Component_Relationship__c questionToSectionECR1 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForSection1.Id, sectionComponent.Id); // level-4
        Enrollment_Component_Relationship__c questionToSectionECR2 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForSection2.Id, sectionComponent.Id); // level-4
        Enrollment_Component_Relationship__c messageToSectionECR2 = Peak_TestUtils.createEnrollmentComponentRelationship(messageComponentForSection.Id, sectionComponent.Id); // level-4


        Enrollment_Component_Relationship__c questionGroupECR1 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForQG1.Id, questionGroupComponent.Id); // level-5
        Enrollment_Component_Relationship__c questionGroupECR2 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForQG2.Id, questionGroupComponent.Id); // level-5
        Enrollment_Component_Relationship__c questionGroupECR3 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForQG3.Id, questionGroupComponent.Id); // level-5
        
    }

    static testMethod void processExport_Positive() {

        // fetch the processID
        Enrollment_Component__c processEC = [SELECT Id, 
                                                    Name, 
                                                    Description__c, 
                                                    Process_Academic_Program__c, 
                                                    RecordTypeId
                                            FROM    Enrollment_Component__c 
                                            WHERE   Process_Academic_Program__c != null
                                            ORDER BY CreatedDate DESC][0];

        
        Test.startTest(); // Export the process
            NES_EnrollmentCompentBuilder.enrollmentComponentData ecData = new NES_EnrollmentCompentBuilder.enrollmentComponentData(processEC.Id);
            Id exportRecID = NES_ECDataImportExport.ExportData(ecData);
        Test.stopTest();
        
        // check if export was successful
        System.assertNotEquals(null, exportRecID, 'test export failed, ecrTree export returned null ID.');

        // compare the ecrTree record with processEC
        ecrTree__c exportRec = NES_ECDataImportExport.getECRTreeByParentIDs(processEC.Id, NES_ECDataImportExport.EC_DATA_CLASS_TYPE);
        System.assertNotEquals(null, exportRec, 'process export failed, no ecrTree__c record found.');

    }

    static testMethod void processExport_Negative() {

        Test.startTest(); // Export the process
            String processId ='a2921000001pR9wAZZ'; // some random ID
            NES_EnrollmentCompentBuilder.enrollmentComponentData ecData = new NES_EnrollmentCompentBuilder.enrollmentComponentData(processId);
            Id exportRecID = NES_ECDataImportExport.ExportData(ecData);
        Test.stopTest();

        System.assertNotEquals(null, exportRecID); // should be null for -ve scenarios

    }

    static testMethod void processImport_Positive() {

        // fetch the processID
        Enrollment_Component__c processEC = [SELECT Id, 
                                                    Name, 
                                                    Description__c, 
                                                    Process_Academic_Program__c, 
                                                    RecordTypeId
                                            FROM    Enrollment_Component__c 
                                            WHERE   Process_Academic_Program__c != null
                                            ORDER BY CreatedDate DESC][0];

        // Export the process
        NES_EnrollmentCompentBuilder.enrollmentComponentData ecData = new NES_EnrollmentCompentBuilder.enrollmentComponentData(processEC.Id);
        Id exportRecID = NES_ECDataImportExport.ExportData(ecData);

        // check if export was successful
        System.assertNotEquals(null, exportRecID, 'test export failed, ecrTree export returned null ID.');

        Test.startTest(); // Import the process
			NES_EnrollmentCompentBuilder.enrollmentComponentData thisProcessData = new NES_EnrollmentCompentBuilder.enrollmentComponentData(processEC.Id);
        Test.stopTest();

        // assert to check if data actually got queried
        System.assertNotEquals(0, thisProcessData.allIds.size(), 'thisProcessData.allIds not found');
        System.assertNotEquals(0, thisProcessData.componentOrderMap.size(), 'thisProcessData.componentOrderMap not found');
        System.assertNotEquals(0, thisProcessData.questionParentIds.size(), 'thisProcessData.questionParentIds not found');
        System.assertNotEquals(0, thisProcessData.stageRelationships.size(), 'thisProcessData.stageRelationships not found');
        System.assertNotEquals(0, thisProcessData.formRelationships.size(), 'thisProcessData.formRelationships not found');
        System.assertNotEquals(0, thisProcessData.sectionRelationships.size(), 'thisProcessData.sectionRelationships not found');
        System.assertNotEquals(0, thisProcessData.questionGroupRelationships.size(), 'thisProcessData.questionGroupRelationships not found');
        System.assertNotEquals(0, thisProcessData.questionRelationships.size(), 'thisProcessData.questionRelationships not found');
        

    }

    static testMethod void processImport_Negative() {

        // fetch the processID
        Enrollment_Component__c processEC = [SELECT Id, 
                                                    Name, 
                                                    Description__c, 
                                                    Process_Academic_Program__c, 
                                                    RecordTypeId
                                            FROM    Enrollment_Component__c 
                                            WHERE   Process_Academic_Program__c != null
                                            ORDER BY CreatedDate DESC][0];

        Test.startTest(); // Import the process
            // Export the process w/out importing it. So basically there is no ecrTree_c record for this process.
            NES_EnrollmentCompentBuilder allECData = NES_EnrollmentCompentBuilder.getInstance();
            NES_EnrollmentCompentBuilder.enrollmentComponentData thisProcessData = allECData.getSpecificProcessECData(processEC.Id);
            // NES_EnrollmentCompentBuilder.enrollmentComponentData thisProcessData = new NES_EnrollmentCompentBuilder.enrollmentComponentData(processEC.Id);
        Test.stopTest();
        
        // compare the ecrTree record with processEC, shouldn't be the case.
        try {
            ecrTree__c exportRec = NES_ECDataImportExport.getECRTreeByParentIDs(processEC.Id, NES_ECDataImportExport.EC_DATA_CLASS_TYPE);
        } catch (ListException ex) {
            
            System.assertEquals('List index out of bounds: 0', ex.getMessage(), 'should have failed');
        }

        // assert to check if data actually got queried
        System.assertNotEquals(0, thisProcessData.allIds.size(), 'thisProcessData.allIds not found');
        System.assertNotEquals(0, thisProcessData.componentOrderMap.size(), 'thisProcessData.componentOrderMap not found');
        System.assertNotEquals(0, thisProcessData.questionParentIds.size(), 'thisProcessData.questionParentIds not found');
        System.assertNotEquals(0, thisProcessData.stageRelationships.size(), 'thisProcessData.stageRelationships not found');
        System.assertNotEquals(0, thisProcessData.formRelationships.size(), 'thisProcessData.formRelationships not found');
        System.assertNotEquals(0, thisProcessData.sectionRelationships.size(), 'thisProcessData.sectionRelationships not found');
        System.assertNotEquals(0, thisProcessData.questionGroupRelationships.size(), 'thisProcessData.questionGroupRelationships not found');
        System.assertNotEquals(0, thisProcessData.questionRelationships.size(), 'thisProcessData.questionRelationships not found');

    }

}