force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Alternative_Address_Request__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Address_Request__c</fullName>
    <label>Alternative Address Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AutomatedPlacementMaxCutoff__c.field-meta.xml
<CustomField>
    <fullName>AutomatedPlacementMaxCutoff__c</fullName>
    <description>The maximum Automated Placement Score a student can have and still be eligible for the Auto-Placement process. This value is set for Academic Program Accounts.</description>
    <label>Automated Placement Max Cutoff</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Annual_Student_Information__c.object
<CustomObject>
    <description>Student data that is specific to a school year is stored on the Annual Student Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Student Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment record for the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The School Year record for the year the data is relevant to.</description>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Student Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Student Information</pluralLabel>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program Enrollment</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>hed__Program_Enrollment__c.hed__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>hed__Program_Enrollment__c.hed__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <formula>&apos;&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ticket_Sub_Type__c</fullName>
        <description>ADO #164365 - Ticket Sub - Type Values to be associated for the respective case - for case visibility.</description>
        <label>Ticket Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Ticket_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Ticket_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/CohortEligibility__c.field-meta.xml
<CustomField>
    <fullName>CohortEligibility__c</fullName>
    <label>Cohort Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allowed to Enroll</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Cohort 2016-2017 or earlier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/EntranceAgeEligibilityFinal__c.field-meta.xml
<CustomField>
    <fullName>EntranceAgeEligibilityFinal__c</fullName>
    <description>This is the final value for the entrance age eligibility.</description>
    <formula>IF(NOT(ISBLANK(TEXT(EntranceAgeEligibilityOverride__c))), TEXT(EntranceAgeEligibilityOverride__c),
IF(ISPICKVAL(Enrollment_Type__c,&apos;Returning Student&apos;),&apos;&apos;,
IF(TEXT(EntranceAgeEligibilitySystem__c)=&apos;Eligible&apos;, &apos;Eligible&apos;,
IF(TEXT(EntranceAgeEligibilitySystem__c)=&apos;Too young&apos; || TEXT(EntranceAgeEligibilitySystem__c)=&apos;Too old&apos;, &apos;Ineligible&apos;,
IF(TEXT(EntranceAgeEligibilitySystem__c)=&apos;Too young - other options&apos; || TEXT(EntranceAgeEligibilitySystem__c)=&apos;Too old - other options&apos;, &apos;Ineligible - Other options&apos;,
IF(TEXT(EntranceAgeEligibilitySystem__c)=&apos;Pending - More Information Needed&apos;, &apos;Pending - More Information Needed&apos;,
&apos;Pending Review&apos;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entrance Age Eligibility (Final)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/OrderingHoldDate__c.field-meta.xml
<CustomField>
    <fullName>OrderingHoldDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ordering Hold Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/OrderingHoldFlag__c.field-meta.xml
<CustomField>
    <fullName>OrderingHoldFlag__c</fullName>
    <description>Hold equipment orders until a specified date</description>
    <label>Ordering Hold Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold Equipment Orders</fullName>
            </value>
            <value>
                <fullName>Withdrawal Process</fullName>
            </value>
            <value>
                <fullName>Alternate Shipping</fullName>
            </value>
            <value>
                <fullName>Not Default Household</fullName>
            </value>
            <value>
                <fullName>POR</fullName>
            </value>
            <value>
                <fullName>Summer School</fullName>
            </value>
            <value>
                <fullName>Private Address</fullName>
            </value>
            <value>
                <fullName>Tech Invoice</fullName>
            </value>
            <value>
                <fullName>Materials Flag</fullName>
            </value>
            <value>
                <fullName>Vacation/Delay Shipment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Start Year (calculated)</description>
    <label>Start Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Special_Education__c.object
<CustomObject>
    <description>The Special Education Data object stores data related to IEPs, 504 plans, gifted education, and other student services</description>
    <fields>
        <fullName>IEPHistory__c</fullName>
        <description>Has the student ever had an Individualized Education Program (IEP)?</description>
        <label>IEPHistory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Decline to Disclose</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Special Educations</relationshipLabel>
        <relationshipName>Special_Educations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Special Education</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Educations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_ProgramEnrollmentBusinessLogic_Test.cls
/**
 * Created updateASIForCompletedPEsTest Method by Maddileti Boya for #194222 User Story on 2020-06-15 

 * Revision :
 * 09-04-2020 Added updateASIForCompletedPEsNegativeTest to cover negative scenarios(Jagadish Babu)
 */
@istest
Private class NES_ProgramEnrollmentBusinessLogic_Test
{
    @TestSetup
    static void setup() {
        // generate test-data
        Id Academic = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019',System.today());
        Account Objacc = Peak_TestUtils.createTestAccount();
        objacc.recordtypeid=Academic;
        Objacc.Alternative_Address_Request__c='Yes';
        Objacc.School_Year__c=currentSchoolYear.id;
        update Objacc;
        
        Contact contact = Peak_TestUtils.createTestContact('Students', Objacc.Id);
        hed__Program_Enrollment__c HousePE= Peak_TestUtils.createProgramEnrollment(objacc.id,contact.id,currentSchoolYear.id,true);
        hed__Program_Enrollment__c Hpe= Peak_TestUtils.createProgramEnrollment(objacc.id,contact.id,currentSchoolYear.id,true);
        Hpe.Household_Program_Enrollment__c=HousePE.id;
        update Hpe;
        Account account = Peak_TestUtils.createTestAccount();
        
        School_Year__c currentSchoolYear2 = Peak_TestUtils.createSchoolYears('2018-2019',date.parse('11/17/2018'));
        
        School_Year__c currentSchoolYearTest = Peak_TestUtils.createSchoolYears('2019-2020',date.parse('11/17/2020'));
        School_Year__c currentSchoolYear2020 = Peak_TestUtils.createSchoolYears('2021-2022',date.parse('11/17/2018'));
        
        School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018',date.parse('11/17/2017'));
        
        Contact contact2 = Peak_TestUtils.createTestContact('Students', account.Id);
        
        Account academicProgramAccount = Peak_TestUtils.createAccountForNewStudentData(account.Id,currentSchoolYear2.Id);
        academicProgramAccount.AutomatedPlacementMaxCutoff__c = 90;
        update academicProgramAccount;
        hed__Program_Enrollment__c progEnrollment5 = Peak_TestUtils.createProgramEnrollment(academicProgramAccount.Id, contact2.Id,currentSchoolYear2020.Id, false);
        insert progEnrollment5;
        Annual_Student_Information__c prevASI1 = Peak_TestUtils.createAnnualStudentInformation('Previous ASI1', progEnrollment5.Id, currentSchoolYear2020.Id, false);
        insert prevASI1;
        System.debug('the asi school year:'+prevASI1.School_Year__c);
        Special_Education__c specialEducations = Peak_TestUtils.createSpecialEducation(progEnrollment5.Id,false);
        specialEducations.IEPHistory__c ='Decline to Disclose';
        insert specialEducations;
        //
        
    }
    
    static testMethod void ProgramEnrollmentBusinessLogictest() 
    {
        Test.startTest();
        hed__Program_Enrollment__c Hpe= [ SELECT id,Status__c,Household_Program_Enrollment__c,OrderingHoldFlag__c,OrderingHoldDate__c,hed__Contact__c FROM hed__Program_Enrollment__c  where Household_Program_Enrollment__c != null limit 1 ];        
        HPe.Status__c = 'Complete';
        update Hpe;
        
        NES_ProgramEnrollmentBusinessLogic.updateHHPEOrderHold(new set<id>{Hpe.id});
        hed__Program_Enrollment__c Hpe1= [ SELECT id,Status__c,OrderingHoldFlag__c,OrderingHoldDate__c FROM hed__Program_Enrollment__c  where id =:Hpe.Household_Program_Enrollment__c limit 1 ];        
        List<case> objcase = new List<case>();
        objCase = [SELECT Id FROM Case WHERE Type='Fulfillment' AND Ticket_Sub_Type__c='Alternate Shipping' AND ContactId = :Hpe.hed__Contact__c AND Contact.account.Alternative_Address_Request__c = 'Yes'];
        
        test.stopTest();
        
        System.assertEquals('Alternate Shipping', Hpe1.OrderingHoldFlag__c);
        System.assertEquals(System.now().date(), Hpe1.OrderingHoldDate__c);
        System.assertNotEquals(objCase,null);
        
    } 
    static testMethod void updateASIForCompletedPEsTest() {
        
        Test.startTest();
        Set<Id> peIdList = new Set<Id>();
        School_Year__c currentYear = [SELECT Id FROM School_Year__c WHERE Name = '2021-2022' LIMIT 1];
        hed__Program_Enrollment__c currentProgramEnrollment = [SELECT Id,Status__c,Start_Year__c FROM hed__Program_Enrollment__c WHERE Start_Year__c =: currentYear.Id];
        currentProgramEnrollment.Status__c='Complete';
        update currentProgramEnrollment;
        hed__Program_Enrollment__c currentProgramEnrollment1 = [SELECT Id,EntranceAgeEligibilityFinal__c,CohortEligibility__c FROM hed__Program_Enrollment__c WHERE Id=: currentProgramEnrollment.Id];
        Special_Education__c speid =[SELECT Id, Program_Enrollment__c FROM Special_Education__c WHERE Program_Enrollment__c = :currentProgramEnrollment1.Id];
        peIdList.add(currentProgramEnrollment.Id);
        NES_ProgramEnrollmentBusinessLogic.updateASIForCompletedPEs(peIdList);
        Annual_Student_Information__c Asi = [SELECT Id,Potential_Child_Find__c,Potential_Child_Find_Detailed_Log__c FROM Annual_Student_Information__c WHERE Program_Enrollment__c = :currentProgramEnrollment1.Id];
        test.stopTest(); 
        System.assertEquals('Yes', Asi.Potential_Child_Find__c);
        System.assertEquals('Caretaker reports student has been evaluated in the last year, but did not indicate that the student has an IEP or Section 504 Plan or the caretaker declined to disclose.', Asi.Potential_Child_Find_Detailed_Log__c);
        
    } 
    

    //Created for US228767 (Jagadish Babu) to make sure to work if the special education and asi records are not exist
    static testMethod void updateASIForCompletedPEsNegativeTest() {        
        Test.startTest();
        Set<Id> peIdList = new Set<Id>();
        School_Year__c currentYear = [SELECT Id FROM School_Year__c WHERE Name = '2021-2022' LIMIT 1];
        hed__Program_Enrollment__c currentProgramEnrollment = [SELECT Id,Status__c,Start_Year__c FROM hed__Program_Enrollment__c WHERE Start_Year__c =: currentYear.Id];
        Annual_Student_Information__c Asi = [SELECT Id,Potential_Child_Find__c,Potential_Child_Find_Detailed_Log__c FROM Annual_Student_Information__c WHERE Program_Enrollment__c = :currentProgramEnrollment.Id];
        Special_Education__c speid =[SELECT Id, Program_Enrollment__c FROM Special_Education__c WHERE Program_Enrollment__c = :currentProgramEnrollment.Id];
        delete Asi;
        delete speId;        
        hed__Program_Enrollment__c currentProgramEnrollment1 = [SELECT Id,EntranceAgeEligibilityFinal__c,CohortEligibility__c FROM hed__Program_Enrollment__c WHERE Id=: currentProgramEnrollment.Id];
        currentProgramEnrollment1.Status__c='Complete';
        System.assertEquals(0, [SELECT Id,Potential_Child_Find__c,Potential_Child_Find_Detailed_Log__c FROM Annual_Student_Information__c WHERE Program_Enrollment__c = :currentProgramEnrollment1.Id].size());
        System.assertEquals(0, [SELECT Id, Program_Enrollment__c FROM Special_Education__c WHERE Program_Enrollment__c = :currentProgramEnrollment1.Id].size());
        update currentProgramEnrollment1;
        peIdList.add(currentProgramEnrollment1.Id);
        NES_ProgramEnrollmentBusinessLogic.updateASIForCompletedPEs(peIdList);        
        test.stopTest();               
    } 
    
}