force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Address_Search_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Address Search Settings</label>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>API_Mapping__c</fullName>
        <description>This tells us how the mapping occurs from API</description>
        <encryptionScheme>None</encryptionScheme>
        <label>API Mapping</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_ExperianIntegrationTest.cls
/*
*   Class Name: NES_ExperianIntegrationTest
*   Description: Test class for NES_ExperianIntegration
*
*   Date          New/Modified     User
*   11/22/2018    New        	  Akhilesh Kumar
*   12/5/208      Modified       S.Anand
*
*/
@isTest
private class NES_ExperianIntegrationTest {

	/*@TestSetup
	static void setup() {
		Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();

		Contact TestContact = Peak_TestUtils.createTestContact();
		School_Year__c schlYear = Peak_TestUtils.createSchoolYears('2018-2019', System.today());
		Account academicAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id, schlYear.Id);

		School_Year__c pSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018',date.parse('11/17/2017'));

		hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicAccount.Id,TestContact.Id,pSchoolYear.Id, false);
		insert progEnrollment;


		// Create a Enrollment Components with different record type
		List<Enrollment_Component__c> componentList = new List<Enrollment_Component__c>();
		Enrollment_Component__c questionComponent = Peak_TestUtils.createEnrollmentComponent(academicAccount.Id, 'Question', false);
		questionComponent.API_Mapping__c = 'country';
		Enrollment_Component__c sectionComponent = Peak_TestUtils.createEnrollmentComponent(academicAccount.Id, 'Section', false);
		componentList.add(sectionComponent);
		componentList.add(questionComponent);
		insert componentList;

		// create Enrollment Component Relationships
		Enrollment_Component_Relationship__c enrollCompRelationship = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponent.Id, sectionComponent.Id);

		// create Enrollment Component Affiliations with different parent Enrollment Components.
		List<Enrollment_Component_Affiliation__c> enrollmentComponentAffiliations = new List<Enrollment_Component_Affiliation__c>();
		Enrollment_Component_Affiliation__c affiliationQuestion = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, questionComponent.Id, false);
		affiliationQuestion.Status__c = 'In Progress';
		enrollmentComponentAffiliations.add(affiliationQuestion);

		insert enrollmentComponentAffiliations;


	}*/

	static testMethod void searchAddressTest() {

		Test.setMock(HttpCalloutMock.class, new Peak_MockHttpResponseGenerator());

		String response = NES_ExperianIntegration.searchAddress('1600 Pennsylvania Ave');
        System.debug('response>>>>>>>>>>>'+response);
		System.assert(true,response != null); 
		// create custom setting record
		Address_Search_Settings__c addressSearchRec=Peak_TestUtils.createAddressSearchSettings(123,456);
		// calling getSearchSettings function
		Address_Search_Settings__c customSettingRec = NES_ExperianIntegration.getSearchSettings();
		system.assert(true, customSettingRec!= null);
	}

    static testMethod void getFormattedAddressTest() {
        String sampleId ='d29eee21-95c5-46be-b5bd-4e0e48a1de7b_U40_24_0_0_0%3D103%24QL3%24GEO0';
		Test.setMock(HttpCalloutMock.class, new Peak_MockHttpResponseGenerator());

		String response = NES_ExperianIntegration.getFormattedAddress(sampleId);
		System.assert(true,response != null);
		// create custom setting record
		Address_Search_Settings__c addressSearchRec=Peak_TestUtils.createAddressSearchSettings(123,456);
		// calling getSearchSettings function
		Address_Search_Settings__c customSettingRec = NES_ExperianIntegration.getSearchSettings();
		system.assert(true, customSettingRec!= null);
	}

	static testMethod void saveAddressFieldsTest(){
        
        Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();

		Contact TestContact = Peak_TestUtils.createTestContact();
		School_Year__c schlYear = Peak_TestUtils.createSchoolYears('2018-2019', System.today());
		Account academicAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id, schlYear.Id);

		School_Year__c pSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018',date.parse('11/17/2017'));

		hed__Program_Enrollment__c programEnrollment = Peak_TestUtils.createProgramEnrollment(academicAccount.Id,TestContact.Id,pSchoolYear.Id, false);
		insert programEnrollment;
        
        Enrollment_Component__c groupId = Peak_TestUtils.createEnrollmentComponent(academicAccount.Id, 'Section', false);
        
		
		List<NES_ExperianIntegration.AddressData> addressData = new List<NES_ExperianIntegration.AddressData>();
		NES_ExperianIntegration.AddressData wrapData = new NES_ExperianIntegration.AddressData();
		wrapData.addressLine1 = 'Test Address One';
		wrapData.addressLine2 = 'Test Addr Two';
		wrapData.addressLine3 = 'Test Addr Three';
		wrapData.postalCode = '123456';
		wrapData.locality = 'Test';
		wrapData.province = 'Province Test';
		wrapData.country = 'USA';
		addressData.add(wrapData);
		String JSONString = JSON.serialize(addressData);
		Test.startTest();
		NES_ExperianIntegration.getQuestions(groupId.Id, programEnrollment.Id);
		NES_ExperianIntegration.saveAddressFields(groupId.Id, programEnrollment.Id, JSONString, true);
		Test.stopTest();
	}
}