force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Provides a way to systematically export and load Enrollment Components.  Unique.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/EC_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>EC_Record_Type__c</fullName>
    <description>Initially added to calculate the % complete on the PR</description>
    <label>EC Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Question Group</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Form</fullName>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Flag</fullName>
            </value>
            <value>
                <fullName>Message</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Enrollment</fullName>
                <default>true</default>
                <label>Initial Enrollment</label>
            </value>
            <value>
                <fullName>Re-enrolling student</fullName>
            </value>
            <value>
                <fullName>Returning Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>This field used to display in Student program enrollment object, in student program enrollment pagelayout.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Tell Us About Your Student</fullName>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
            <value>
                <fullName>Confirmation Of Enrollment</fullName>
            </value>
            <value>
                <fullName>Intent To Attend</fullName>
            </value>
            <value>
                <fullName>Offer Of Enrollment</fullName>
            </value>
            <value>
                <fullName>Open Application Period</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NES_ECAManualAddition.cls
global class NES_ECAManualAddition implements Database.Batchable<sObject> {
   
    string academicprogram1;   
    String peId1;
    global NES_ECAManualAddition(String academicprogram, String peId){
        academicprogram1=academicprogram;
        peId1 = peId;
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
       // Get the Student PEs of the Academic Program being passed
       // return  Database.getQueryLocator('SELECT ID, Name, hed__Account__r.Name, Household_Program_Enrollment__c,Enrollment_Type__c FROM hed__program_enrollment__c where hed__Account__r.Name =:academicprogram1 AND Status__c = \'In Progress\' AND RecordType.Name = \'Student\' AND Enrollment_Type__c in (\'Initial Enrollment\', \'Re-enrolling Student\') AND CreatedDate <: PECreatedDate AND Stage__c NOT IN (\'Intent to Attend\', \'Waitlist\') ');
       //return  Database.getQueryLocator('SELECT ID, Name, hed__Account__r.Name, Household_Program_Enrollment__c,Enrollment_Type__c FROM hed__program_enrollment__c where hed__Account__r.Name =:academicprogram1 AND Status__c = \'In Progress\' AND RecordType.Name = \'Student\' AND Enrollment_Type__c in (\'Initial Enrollment\', \'Re-enrolling Student\') AND Stage__c IN (\'Open Application\') ');
       if(string.isNotBlank(peId1))
       {
            return  Database.getQueryLocator('SELECT ID, Name, hed__Account__r.Name, Household_Program_Enrollment__c,Enrollment_Type__c FROM hed__program_enrollment__c where hed__Account__r.Name =:academicprogram1 AND RecordType.Name = \'Student\' and Id =: peId1 and enrollment_type__c != \'Returning Student\' ');
       }
        else{
            // Final Query
            return  Database.getQueryLocator('SELECT ID, Name, hed__Account__r.Name, Household_Program_Enrollment__c,Enrollment_Type__c FROM hed__program_enrollment__c where hed__Account__r.Name =:academicprogram1 AND RecordType.Name = \'Student\' and enrollment_type__c != \'Returning Student\' ');
        }
    }
    global void execute(Database.BatchableContext bc, List<hed__program_enrollment__c> scope){
        hed__program_enrollment__c pe = new hed__program_enrollment__c ();
        pe = scope[0];
        
        // Get the State CA
        String str = academicprogram1;
        List<String> res = str.split(' ', 2);
        String State = res[0].toUppercase();
        System.debug('STATE :::' + State);
        String StateStr = '%'+State+'2122%';
        System.debug('NDEBUG :: STATESTR :::' + StateStr);
        
        
        // Get the Ids of new ECs being added
        List <String> newEcsList = new List <String> ();
        // Common for All States
        newEcsList.add('Schooling Information');
        newEcsList.add('Re-Enrollment Parent/Legal Guardian (Caretaker) Acknowledgement');
        newEcsList.add('Re-Enrollment RC Contextual Help');
        newEcsList.add('Re-Enrollment PAH Contextual Help');
        
        // Unique for Non-Calca States  
        if(State != 'CALCA'){      
            newEcsList.add('Re-Enrollment Homeschool Prior Academic History Form (Document)');        
            newEcsList.add('Re-Enrollment Report Card (Document)');
        }
        
        // Unique for Calca States 
        if(State == 'CALCA'){      
            newEcsList.add('Re-Enrollment Report Card (Optional Document)');        
            newEcsList.add('Re-Enrollment Homeschool Prior Academic History Form (Optional Document)');
        }       
        
        // Get the List of new ECs
        List <Enrollment_Component__c> ecList = [Select Id from Enrollment_Component__c 
                                                 where Name in: newEcsList 
                                                 and External_Id__c like : StateStr];
        
        System.debug('NDEBUG::: EC Count' + ecList.size());
        
        List <Id> newEcsIdList = new List <Id> ();
        List <Id> finalEcsIdList = new List <Id> ();
        Map <Id, Boolean> ecExistMap =  new Map <Id, Boolean> ();
        for(Enrollment_Component__c ec: ecList){
            newEcsIdList.add(ec.Id);
            ecExistMap.put(ec.Id, false);
        }
        
        System.debug('NDEBUG Existing ECA MAP:::' + ecExistMap);
        
        // Get the List of ECRs related to above ECs
        List <Enrollment_Component_Relationship__c> ecrList = [Select Id, Order__c, Child_Enrollment_Component__c 
                                                               from  Enrollment_Component_Relationship__c where Child_Enrollment_Component__c in : newEcsIdList];
        
        // Create the EC to Order Map
        Map <String, Decimal> ecToOrderMap = new Map <String, Decimal> ();
        for(Enrollment_Component_Relationship__c ecr : ecrList){
            ecToOrderMap.put(ecr.Child_Enrollment_Component__c, ecr.Order__c);
            System.debug('NDEBUG :::::: ' + ecr.Order__c);  
        }
        
        // Check if any new ECAs already exists for this PE
        List <Enrollment_Component_Affiliation__c> existEcaList = [Select Id, Program_Enrollment__c, Enrollment_Component__c 
                                                                   from Enrollment_Component_Affiliation__c 
                                                                  where Program_Enrollment__c =: pe.Id
                                                                  and Enrollment_Component__c in: newEcsIdList];
        List <Id> dupEcsIdList = new List <Id> ();
        
        if(existEcaList != null && existEcaList.size() > 0){
            for(Enrollment_Component_Affiliation__c eca : existEcaList){
                if(eca != null)
                    ecExistMap.put(eca.Enrollment_Component__c, true);
            }            
        }
        System.debug('NDEBUG Existing ECA MAP:::' + ecExistMap);
        
        for(Id ecid: ecExistMap.keyset()){
            if(!ecExistMap.get(ecid))
               finalEcsIdList.add(ecid);            
        }      
        
        
        // Insert the final ECAs
        List <Enrollment_Component_Affiliation__c> ecaList = new List <Enrollment_Component_Affiliation__c> ();
        Enrollment_Component_Affiliation__c e;
        
        for(String ecId : finalEcsIdList){
            e = new Enrollment_Component_Affiliation__c ();
            e.EC_Record_Type__c = 'Document';
            e.Status__c = 'Not Applicable';
            e.Program_Enrollment__c = pe.Id;
            e.Enrollment_Component__c = ecId;
            e.Order__c = ecToOrderMap.get(ecId);
            ecaList.add(e);
        }

        System.debug('ECAs being inserted are:::::' + ecaList);
        Insert ecaList;
    }
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
    
    public static void testCoveragePaddingMethod(){
        integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}