force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <displayFormat>S-{00000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Document_Submission_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Submission Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Enrollment_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrollment Document</label>
        <referenceTo>Enrollment_Document__c</referenceTo>
        <relationshipLabel>Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flag</fullName>
        <active>true</active>
        <label>Flag</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <recordTypes>
        <fullName>Text</fullName>
        <active>true</active>
        <label>Text</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Picklist_Option__c.object
<CustomObject>
    <label>Enrollment Component Picklist Option</label>
    <nameField>
        <displayFormat>PO-{0}</displayFormat>
        <label>Enrollment Component Picklist Option Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Picklist Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Picklist_Option__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <inlineHelpText>Parent Question Record Type, Picklist Type Enrollment Component.</inlineHelpText>
    <label>Enrollment Component</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Enrollment_Component__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Question</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Picklist Options</relationshipLabel>
    <relationshipName>Enrollment_Component_Picklist_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Enrollment_Component_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Component Affiliation</label>
    <referenceTo>Enrollment_Component_Affiliation__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Enrollment</fullName>
                <default>true</default>
                <label>Initial Enrollment</label>
            </value>
            <value>
                <fullName>Re-enrolling student</fullName>
            </value>
            <value>
                <fullName>Returning Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Student_ID__c.field-meta.xml
<CustomField>
    <fullName>Student_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Student ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Full_Reactivation_Date__c</fullName>
        <description>Full Reactivation Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Reactivation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reactivation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Reactivation Date</description>
        <label>Reactivation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Student Id)</relationshipLabel>
        <relationshipName>Opportunities_Stdnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NES_EnrollmentControllerTest.cls
/**
 * Created by triciaigoe on 12/27/18.
 */
@IsTest
public with sharing class NES_EnrollmentControllerTest {
 
    @TestSetup 
    static void setup() {
        Account account = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019', Date.parse('11/17/2018'));
        School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018', Date.parse('11/17/2017'));

        // Create a contact with 'Students' record type
        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);

        // Create a account with 'Academic Program' record type
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(account.Id, currentSchoolYear.Id);
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, currentSchoolYear.Id, true);
		
		User u = [SELECT Id,ContactId FROM User WHERE ContactId != NULL AND IsActive = TRUE LIMIT 1];
        hed__Relationship__c  relationship = Peak_TestUtils.createRelationship(u.ContactId, contact.Id, true);

        // Create a Enrollment Components with different record type
        List < Enrollment_Component__c > componentList = new List < Enrollment_Component__c > ();
        Enrollment_Component__c stageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Stage', false);
        Enrollment_Component__c processComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Process', false);
        Enrollment_Component__c questionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        Enrollment_Component__c sectionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Section', false);
        Enrollment_Component__c formComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Form', false);
        Enrollment_Component__c messageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Message', false);
        Enrollment_Component__c documentComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Document', false);

        componentList.add(stageComponent);
        componentList.add(processComponent);
        componentList.add(questionComponent);
        componentList.add(sectionComponent);
        componentList.add(formComponent);
        componentList.add(messageComponent);
        componentList.add(documentComponent);
        insert componentList;

        // create Enrollment Component Relationships with different parent Enrollment Components.
        Enrollment_Component_Relationship__c enrollCompRelationship = Peak_TestUtils.createEnrollmentComponentRelationship(stageComponent.Id, processComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship2 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponent.Id, sectionComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship3 = Peak_TestUtils.createEnrollmentComponentRelationship(formComponent.Id, stageComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship4 = Peak_TestUtils.createEnrollmentComponentRelationship(messageComponent.Id, formComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship5 = Peak_TestUtils.createEnrollmentComponentRelationship(sectionComponent.Id, formComponent.Id);

        // create Enrollment Component Affiliations with different parent Enrollment Components.
        Enrollment_Component_Affiliation__c affiliation = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, formComponent.Id);
        Enrollment_Component_Affiliation__c affiliationStage = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, stageComponent.Id);
       
        Enrollment_Component_Affiliation__c  affiliationSection = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, sectionComponent.Id);
        affiliationSection.Status__c='In Progress';
        update affiliationSection;
        Enrollment_Component_Affiliation__c  affiliationSection2 = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, sectionComponent.Id);
        Enrollment_Component_Affiliation__c affiliationDocument = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, documentComponent.Id);

         Enrollment_Component_Affiliation__c affiliationDocument2 = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, documentComponent.Id);
        Enrollment_Component_Affiliation__c affiliationProcess = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, processComponent.Id);
        
        Enrollment_Component_Picklist_Option__c picklistOption = Peak_TestUtils.createEnrollmentComponentPicklistOption(questionComponent.Id, true);
 
        Enrollment_Document__c enrollmentDocument1 = Peak_TestUtils.createEnrollmentDocumentRecord(progEnrollment.id);
        enrollmentDocument1.Enrollment_Component_Affiliation__c = affiliationSection.Id;
        update enrollmentDocument1;

        //

        Grade_Level__c gradeLevel = Peak_TestUtils.createGradeLevel('Test',true);
        Program_Grade_Level__c programGradeLevel = Peak_TestUtils.createProgramGradeLevel('Test', academicProgram.Id, gradeLevel.Id,Datetime.now(), true);

        // Create a Standard User

        User  portalUser= Peak_TestUtils.CreatePortalCaretTakerUser(contact.Id);
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('SchoolTest', System.today());
        hed__Program_Enrollment__c ProgramEnrollmentTest = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, schlYear.Id, false);
        insert ProgramEnrollmentTest;

    }

    /**
   * Created by Anushka on 20/11/18.
   * Purpose : This method is a Test method for getRelatedFormContent method of NES_DashboardUtilities class.
*/
 static testMethod void testGetRelatedFormContent() {
  Enrollment_Component__c formComponent = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Form' LIMIT 1];
  hed__Program_Enrollment__c programEnrollment = [SELECT Id FROM hed__Program_Enrollment__c LIMIT 1];
     
  List<NES_DashboardUtilities.RelatedFormContent> relatedForm = NES_EnrollmentController.getRelatedFormContent(formComponent.Id, programEnrollment.Id);
  System.assertNotEquals(null,relatedForm );
  relatedForm = NES_EnrollmentController.getRelatedFormContent(null,null);
  System.assertEquals(null,relatedForm );

     update new Enrollment_Component__c(Id = formComponent.Id, Document_Submission_Start_Date__c = Date.today().addMonths(2));
     relatedForm = NES_EnrollmentController.getRelatedFormContent(formComponent.Id, null);
     System.assertNotEquals(null,relatedForm );
 }

    /**
      * Created by Anushka on 20/11/18.
      * Purpose : This method is a Test method for getRelatedStages method of NES_DashboardController class.
   */
    static testMethod void testGetRelatedStages() {
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,Status__c FROM hed__Program_Enrollment__c LIMIT 1];
        List<Enrollment_Component_Affiliation__c> affiliations  = NES_EnrollmentController.getRelatedStages(progEnrollment.Id);
        System.assertNotEquals(null,affiliations );
        affiliations = NES_EnrollmentController.getRelatedStages(null);
        System.assertEquals(null,affiliations );
        
    }

    /**
      * Created by Anushka on 20/11/18.
      * Purpose : This method is a Test method for getRelatedMessages method of NES_DashboardController class.
   */
    static testMethod void testGetRelatedMessages() {
        hed__Program_Enrollment__c progEnrollment = [SELECT Id FROM hed__Program_Enrollment__c LIMIT 1];
        Enrollment_Component__c stageComponent = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Form' 
        LIMIT 1];
        List<Enrollment_Component__c> enrollmentComponents =  NES_EnrollmentController.getRelatedMessages(stageComponent.Id, progEnrollment.Id);
        System.assertNotEquals(null,enrollmentComponents );
        enrollmentComponents = NES_EnrollmentController.getRelatedMessages(null, progEnrollment.Id);
        System.assertEquals(0,enrollmentComponents.size() );
    }

    /**
      * Created by Anushka on 20/11/18.
      * Purpose : This method is a Test method for getProcessInformation method of NES_DashboardController class.
     **/
    static testMethod void testGetProcessInformation() {
        Enrollment_Component__c processComponent = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Process' LIMIT 1];
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c FROM hed__Program_Enrollment__c LIMIT 1];

        NES_DashboardUtilities.Process process = NES_EnrollmentController.getProcessInformation(processComponent.Id, progEnrollment.Id);
        System.assertNotEquals(null,process );
        process = NES_EnrollmentController.getProcessInformation(null, progEnrollment.Id);
        System.assertEquals(null,process );
    }

    /**
      * Created by Anushka on 20/11/18 .
      * Purpose : This method is a Test method for getRelatedForms method of NES_DashboardController class.
     **/
    static testMethod void testGetRelatedForms() {
     Enrollment_Component__c stageComponent = [Select id from Enrollment_Component__c where RecordType.DeveloperName = 'Stage' limit 1];
     hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c FROM hed__Program_Enrollment__c LIMIT 1];

     List<NES_DashboardUtilities.Form> form = NES_EnrollmentController.getRelatedForms(stageComponent.Id, progEnrollment.Id);
     System.assertNotEquals(null,form );
     form = NES_EnrollmentController.getRelatedForms(null,null);
     System.assertEquals(null,form );
        update new Enrollment_Component__c(Id = stageComponent.Id, Document_Submission_Start_Date__c = Date.today().addMonths(2));
        form = NES_EnrollmentController.getRelatedForms(stageComponent.Id, progEnrollment.Id);
        System.assertNotEquals(null,form );
    }


    /**
     * Created by Raju on 30/11/18.
     * Purpose : This method is a Test method for both getTerminationReasons and terminateApplication methods of NES_DashboardController class.
     */
    static testMethod void testTerminateApplication() {
        hed__Program_Enrollment__c hpe = [SELECT Id, Status__c FROM hed__Program_Enrollment__c WHERE CreatedDate = TODAY LIMIT 1];
        Opportunity opty=Peak_TestUtils.createOpportunity(hpe.Id);
        Test.startTest();
        Peak_Response response = NES_EnrollmentController.terminateApplication(hpe.Id, 'Not a good fit');
        NES_EnrollmentController.getTerminationReasons();
        Test.stopTest();
    }
    
    static testMethod void testTerminate() {
        hed__Program_Enrollment__c hpe = [SELECT Id,Status__c,Enrollment_Type__c FROM hed__Program_Enrollment__c LIMIT 1];
        hpe.Enrollment_Type__c='Re-enrolling student';
        update hpe;
        Opportunity opty=Peak_TestUtils.createOpportunity(hpe.Id);
        Test.startTest();
       	Peak_Response response = NES_EnrollmentController.terminateApplication(hpe.Id, 'Not a good fit');
       
        Test.stopTest();
        hed__Program_Enrollment__c hpe1 = [SELECT Id,Status__c,Enrollment_Type__c FROM hed__Program_Enrollment__c where id=:hpe.id];
        System.assertEquals('Withdrawn', hpe1.Status__c);
        System.assertNotEquals('Inactive',hpe1.Status__c);
    }
    /**
     * Created by Gourav on 3/3/19.
     * Purpose : This method is a Test method for negative testing of terminateApplication methods of NES_DashboardController class.
     */
    static testMethod void testTerminateApplicationNegative() {
        hed__Program_Enrollment__c hpe = [SELECT Id, Status__c FROM hed__Program_Enrollment__c WHERE CreatedDate = TODAY LIMIT 1];
        //Opportunity opty=Peak_TestUtils.createOpportunity(hpe.Id);
        Test.startTest();
        Peak_Response response = NES_EnrollmentController.terminateApplication(hpe.Id, 'Not a good fit');
        NES_EnrollmentController.getTerminationReasons();
        Test.stopTest();
    }
    /**
     * Created by Gourav on 3/3/19.
     * Purpose : This method is a Test method grabNameOfStudent of NES_DashboardController class.
     */
    static testMethod void testgrabNameOfStudent() {
        Contact student = [SELECT Id FROM Contact LIMIT 1];
        User portalUser = [SELECT Id FROM User WHERE ContactId != null AND IsActive=TRUE LIMIT 1];
        Test.startTest();
            system.runAs(portalUser) {
                NES_EnrollmentController.grabNameOfStudent(student.Id, null);
            }
        Test.stopTest();
    }

    static testMethod void testGetCaretakers() {
        Contact student = [SELECT Id FROM Contact LIMIT 1];
        Peak_Response response =  NES_EnrollmentController.getCaretakers(student.Id);
        System.assertNotEquals(null,response);
    }

    /*static testMethod void testSubmitQuestions(){
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c FROM hed__Program_Enrollment__c LIMIT 1];
        Enrollment_Component__c processComponent = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Process' LIMIT 1];
        Enrollment_Component__c sectionComponent = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Section' LIMIT 1];
        Enrollment_Component__c questionComponent = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Question' LIMIT 1];

        List<NES_EvaluateUtil.Question> questionsList = new List<NES_EvaluateUtil.Question>();
        NES_EvaluateUtil.Question questionWrap = new NES_EvaluateUtil.Question();
        questionWrap.questionPrompt = 'questionPromptTest';
        questionWrap.tooltipText = 'tooltipTextTest';
        questionWrap.componentMessage = 'componentMessageTest';
        questionWrap.questionType = 'Text';
        questionWrap.questionId = questionComponent.Id;
        questionWrap.parentId = sectionComponent.Id;
        questionWrap.targetField = 'Contact.Name';
        questionWrap.componentType = 'Student';
        questionWrap.questionTarget = '';
        questionWrap.required = false;
        questionsList.add(questionWrap);

        String questionJSON = JSON.serialize(questionsList);
        Test.startTest();
        NES_EnrollmentController.submitQuestions(progEnrollment.Id, questionJSON, processComponent.Id, sectionComponent.Id);
        Test.stopTest();
    }*/
    
    /**
     * Created by Chinnamanaidu Neerasa on 29/11/2019 for US#119347
     * Purpose : This method is used to display popup window when the  Program Enrollment's related
     *           Opportunity Application End Reason (Internal) field starts with "Regulation" 
     */
    static testMethod void testdisplayPopupReg() {

     Contact student = [SELECT Id FROM Contact LIMIT 1];
            Opportunity opty = new Opportunity();
                opty.Name = 'test 1';
                opty.StageName = 'Closed Lost';
                opty.Reactivation__c = true;
                opty.CloseDate = Date.today().addMonths(1);
               
                opty.Student_Id__c=student.Id;
               opty.Full_Reactivation_Date__c = system.today();
                                    
                
        insert opty;
        Test.startTest();
       
        opty.Application_End_Reason_internal__c ='Regulation';
        update opty;
       boolean res =  NES_EnrollmentController.displayPopupReg(student.Id);
       
       
        Test.stopTest();
        System.assertEquals( true,res);
    }
    
    /*Created By : Jagadish Babu
     *Purpose : this method is use to cover getIsEnrollmentReady method and reactivateStudent Method
	 */
    static testMethod void testEnrollmentsReady() {
        hed__Program_Enrollment__c hpe = [SELECT Id, Initial_ECA_Creation_Complete__c FROM hed__Program_Enrollment__c where Initial_ECA_Creation_Complete__c = false  LIMIT 1 ];
        test.startTest();
        Boolean response = NES_EnrollmentController.getIsEnrollmentReady(hpe.Id);
        Peak_Response pResponse = NES_EnrollmentController.reactivateStudent(hpe.Id);
        system.assertEquals(false, response);
        test.stopTest();
    }
	
    
    /*Created By : Jagadish Babu
     *Purpose : this method is use to cover getSchoolId
	 */
    static testMethod void testGetSchoolId() {
        hed__Program_Enrollment__c hpe = [SELECT Id,hed__Account__r.ParentId FROM hed__Program_Enrollment__c LIMIT 1 ];
        test.startTest();       
        Id schoolRecId = NES_EnrollmentController.getSchoolId(hpe.Id);
        system.assertEquals(hpe.hed__Account__r.ParentId, schoolRecId);
        test.stopTest();
    }
    
    static testMethod void gradeLevelsTest() {
        Account academicProgram = [SELECT Id,name, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1];
        School_Year__c schoolYears = [Select id,Name FROM School_Year__c WHERE Name ='2018-2019' LIMIT 1]; 
        test.startTest();       
        List<Grade_Level__c> gradeLevelId = NES_EnrollmentController.getGradeLevels(academicProgram.Name,schoolYears.Name);
        Boolean flag = NES_EnrollmentController.getNextYearAvailability(academicProgram.Name,schoolYears.Name);
        test.stopTest();
    }
       static testMethod void schoolYearsTest() {
        Account academicProgram = [SELECT Id,name, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1];
        //School_Year__c schoolYears = [Select id,Name FROM School_Year__c WHERE Name ='2018-2019' LIMIT 1]; 
        test.startTest();       
        List<School_Year__c> schoolIds = NES_EnrollmentController.getSchoolYears(academicProgram.Name);
        test.stopTest();
    }
    
    static testMethod void updatedOpenAppReleasedTest() {
        hed__Program_Enrollment__c hpe = [SELECT Id,Open_Application__c FROM hed__Program_Enrollment__c LIMIT 1 ];
        hpe.Open_Application__c = 'Released';
        update hpe;
        test.startTest();       
        	NES_EnrollmentController.updatedOpenAppReleased(hpe.Id);
        test.stopTest();
    }
    
}