force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/PushToSecondSemester__c.field-meta.xml
<CustomField>
    <fullName>PushToSecondSemester__c</fullName>
    <description>This is when the second semester becomes the only option</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Push To Second Semester</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to the Contact records with the Caretaker Record type.It is being used by the student Record Types of Contact</description>
        <label>Caretaker Id</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Caretaker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade_Level__c.object
<CustomObject>
    <description>The grade level object stores grade level information for connection to Academic Programs and Caps.</description>
    <label>Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caretaker Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Semester_Indicator__c</fullName>
        <label>Final Semester Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Semester_Indicator__c</fullName>
        <label>Semester Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                    <default>true</default>
                    <label>First</label>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/PushToSecondSemester__c.field-meta.xml
<CustomField>
    <fullName>PushToSecondSemester__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Push To Second Semester</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_Batch_SecondSemesterTest.cls
/**
 * Created by Ashish Sharma on 12/04/18
 * Class Name: NES_Batch_SecondSemesterTest
 * Purpose : Test class for NES_Batch_SecondSemester
*/
@isTest
public class NES_Batch_SecondSemesterTest {
    //Constants
    static final String ACCOUNT_OBJECT = 'Account';
    static final String PROGRAM_GRADE_LEVEL_OBJECT = 'Program_Grade_Level__c';
    static final String FIRST_SEMESTER_INDICATOR = 'First';
    static final String SECOND_SEMESTER_INDICATOR = 'Second';
    static final String SCHEDULER_NAME = 'NES_Batch_SecondSemester';
    static final String HOURLY_SCHEDULE_CRON = '0 00 00 * * ?';

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Method to setup the test data
    */
    @TestSetup
    static void setup() {
        Account account = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019', date.parse('11/17/2018'));
        Contact contact = Peak_TestUtils.createTestContact('Caretaker', account.Id);
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(account.Id, currentSchoolYear.Id);
        academicProgram.PushToSecondSemester__c = Datetime.now().addDays(-5);
        update academicProgram;

        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, currentSchoolYear.Id, true);

        Opportunity opportunity = Peak_TestUtils.createOpportunity(UserInfo.getUserId(), null);
        opportunity.Program_Enrollment__c = progEnrollment.Id;
        opportunity.Semester_Indicator__c = FIRST_SEMESTER_INDICATOR;
        opportunity.Caretaker_Id__c = contact.Id;
        opportunity.StageName = 'Open';
        insert opportunity;

        Grade_Level__c gradeLevel = Peak_TestUtils.createGradeLevel('Test Grade Level', true);
        Program_Grade_Level__c programGradeLevel = Peak_TestUtils.createProgramGradeLevel('Test Program Grade Level', academicProgram.Id,
                                                                                          gradeLevel.Id, Datetime.now().addDays(-5), true);
    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test the functionality if batch is running for Account object
    */
    static testMethod void testAccountRelatedOpportunities() {
        //execute the NES_Batch_SecondSemester batch for Account object
        Test.startTest();
        Database.executeBatch(new NES_Batch_SecondSemester(ACCOUNT_OBJECT, Datetime.now()));
        Test.stopTest();

        //Assert test if Final_Semester_Indicator__c for related opportunity is set to Second Semester or not
        System.assertNotEquals(FIRST_SEMESTER_INDICATOR, [SELECT Final_Semester_Indicator__c FROM Opportunity][0].Final_Semester_Indicator__c);
    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test the functionality if batch is running for Program_Grade_Level__c object
    */
    static testMethod void testPGLRelatedOpportunities() {
        //execute the NES_Batch_SecondSemester batch for Program Grade Level object
        Test.startTest();
        Database.executeBatch(new NES_Batch_SecondSemester(PROGRAM_GRADE_LEVEL_OBJECT, Datetime.now()));
        Test.stopTest();

        //Assert test if Final_Semester_Indicator__c for related opportunity is set to Second Semester or not
        System.assertNotEquals(FIRST_SEMESTER_INDICATOR, [SELECT Final_Semester_Indicator__c FROM Opportunity][0].Final_Semester_Indicator__c);
    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test scheduler for NES_Batch_SecondSemester
    */
    static testMethod void testSchedule() {
        //Assert test if scheduler is scheduled or not
        System.assertNotEquals(null, System.schedule(SCHEDULER_NAME, HOURLY_SCHEDULE_CRON, new NES_Batch_SecondSemester()));
    }
}