force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Calculated_ID__c.field-meta.xml
<CustomField>
    <fullName>Calculated_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Calculated ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Computer_in_Home__c.field-meta.xml
<CustomField>
    <fullName>Computer_in_Home__c</fullName>
    <description>Indicator of whether or not the family has a computer in their home.</description>
    <label>Do you have a computer in your home</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Internet_Connection_Type__c.field-meta.xml
<CustomField>
    <fullName>Internet_Connection_Type__c</fullName>
    <description>Internet connection type for the household.</description>
    <label>Internet Connection Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cable</fullName>
            </value>
            <value>
                <fullName>Dial-up</fullName>
            </value>
            <value>
                <fullName>DSL</fullName>
            </value>
            <value>
                <fullName>Mobile hotspot</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Other - High Speed</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LC_HighestLevelofEducation__c.field-meta.xml
<CustomField>
    <fullName>LC_HighestLevelofEducation__c</fullName>
    <description>The highest level of education recieved by the learning coach</description>
    <label>LC Highest Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>College graduate (Bachelor&apos;s degree)</fullName>
            </value>
            <value>
                <fullName>Graduate school / Post-graduate training</fullName>
            </value>
            <value>
                <fullName>High school graduate</fullName>
            </value>
            <value>
                <fullName>I decline to state</fullName>
            </value>
            <value>
                <fullName>Not a high school graduate</fullName>
            </value>
            <value>
                <fullName>Some college or associate&apos;s degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mktg_Customer_Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Mktg_Customer_Loyalty__c</fullName>
    <description>Returning family with an application for the new school year</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Mktg Customer Loyalty</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Id__c.field-meta.xml
<CustomField>
    <fullName>School_Id__c</fullName>
    <description>This field holds school unique Id values</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>School Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Living_Accommodations__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Living_Accommodations__c</fullName>
    <description>The type of living situation the student(s) has at the primary nighttime residence.</description>
    <label>Type of Living Accommodations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In a shelter</fullName>
            </value>
            <value>
                <fullName>Awaiting foster care placement</fullName>
            </value>
            <value>
                <fullName>In a hotel or motel</fullName>
            </value>
            <value>
                <fullName>In a temporary trailer, campground, car, or park due to the lack of alternative accommodations</fullName>
            </value>
            <value>
                <fullName>None of the above</fullName>
            </value>
            <value>
                <fullName>With more than one family in a house or an apartment NOT due to loss of housing or economic hardship</fullName>
            </value>
            <value>
                <fullName>With More Than One Family In A House, An Apartment Or Other Transitional Housing Due To Loss Of Housing Or Economic Hardship</fullName>
            </value>
            <value>
                <fullName>In a shelter or transitional housing</fullName>
            </value>
            <value>
                <fullName>With more than one family in a house or an apartment due to loss of housing or economic hardship</fullName>
            </value>
            <value>
                <fullName>2+ Families In A Shared Living Situation Due To Loss Of Housing Or Economic Hardship</fullName>
            </value>
            <value>
                <fullName>House, apartment, or mobile home</fullName>
            </value>
            <value>
                <fullName>Motel, car, or campsite</fullName>
            </value>
            <value>
                <fullName>Travel/Live in motor home</fullName>
            </value>
            <value>
                <fullName>A Primary Nighttime Residence Not Designed For Regular Sleeping Accommodations</fullName>
            </value>
            <value>
                <fullName>A primary nighttime residence that is a public or private place not designed for or ordinarily used</fullName>
                <isActive>false</isActive>
                <label>A primary nighttime residence that is a public or private place not designed for or ordinarily used</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/HomelessRiskFlag__c.field-meta.xml
<CustomField>
    <fullName>HomelessRiskFlag__c</fullName>
    <description>Homeless Risk Flag</description>
    <label>Homeless Risk Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homeless</fullName>
            </value>
            <value>
                <fullName>Potential Homeless</fullName>
            </value>
            <value>
                <fullName>Not Homeless</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/LC_HighestLevelofEducation__c.field-meta.xml
<CustomField>
    <fullName>LC_HighestLevelofEducation__c</fullName>
    <description>The highest level of education recieved by the learning coach.</description>
    <label>LC Highest Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>College graduate (Bachelor&apos;s degree)</fullName>
            </value>
            <value>
                <fullName>Graduate school / Post-graduate training</fullName>
            </value>
            <value>
                <fullName>High school graduate</fullName>
            </value>
            <value>
                <fullName>I decline to state</fullName>
            </value>
            <value>
                <fullName>Not a high school graduate</fullName>
            </value>
            <value>
                <fullName>Some college or associate&apos;s degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/School_Id__c.field-meta.xml
<CustomField>
    <fullName>School_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for criteria based sharing rule calculations.</inlineHelpText>
    <label>School Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NES_AccountBusinessLogic.cls
/**
 * Created by Ritvik on 25-10-2018.
 * Purpose : BusinessLogic class for AccountTrigger called by AccountHandler class.
 */


//Generating 20 characters unique Calculated Id on creating or updating a account & populating it into School Id if this field is blank.
public without sharing class NES_AccountBusinessLogic {
    private static Peak_ApexLog logger = new Peak_ApexLog('AccountBusinessLogic');

/**
 * Created by Ritvik on 25-10-2018.
 * Purpose : Generating 20 characters unique Calculated Id on creating or updating a account & populating it into School Id if this field is blank.
 * Parameter : List<Account> record to be inserted.
 */
    //Method depricated
   /* public static void createUniqueID(List<Account> newMap) {
        try {
            for (Account record : newMap) {
                //Logic to generate random Id
                Integer len = 20;
                String chars = '0123456789';
                String randomString = '';
                while (randomString.length() < len) {
                    Integer count = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
                    randomString += chars.substring(count, count + 1);
                }


                record.Calculated_ID__c = randomString;
                if (String.isBlank(record.School_Id__c)) {
                    record.School_Id__c = record.Calculated_ID__c;
                }
            }
        } catch (Exception e) {
            logger.logException('createUniqueId', e);
            logger.saveLogs();
            throw e ;
        }
    } */

    /**
 * Created by Ritvik on 25-10-2018.
 * Purpose : Generating 20 characters unique Calculated Id on creating or updating a account & populating it into School Id if this field is blank.
 * Parameter : @Map<Id, Account> -  Account record to updated with updated values.
 *             @Map<Id, Account> -  Account record to updated with values before updation i.e. old.
 */
  //Method depricated
  /*
    public static void populateSchoolID(Map<Id, Account> oldMap, Map<Id, Account> newMap) {
        try {

            for (Account record : newMap.values()) {
                if (String.isBlank(record.School_Id__c)) {
                    record.School_Id__c = record.Calculated_ID__c;
                }
            }
        } catch (Exception e) {
            logger.logException('populateSchoolID', e);
            logger.saveLogs();
            throw e ;
        }
    }
*/
    /**
    * Created by Raju on 12/13/18.
    * Purpose : Method is used to Set set Program_Enrollment__c.HomelessRiskFlag__c to “Potential Homeless”
    */
    public static void calculateHomelessRiskFlag(Map<Id, Account> newMap, Map<Id, Account> oldMap) {
        Id householdRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        Set<Id> accountIdSet = new Set<Id>();
        for (Account account : (List<Account>) newMap.values() ) {
            if (account.RecordTypeId == householdRecordTypeId && String.isNotBlank(account.Type_of_Living_Accommodations__c)) {
                if (account.Type_of_Living_Accommodations__c.contains('With more than one family in a house or an apartment due to loss') ||
                                account.Type_of_Living_Accommodations__c.contains('In a shelter') ||
                                account.Type_of_Living_Accommodations__c.contains('In a temporary trailer') ||
                                account.Type_of_Living_Accommodations__c.contains('Awaiting') ||
                                account.Type_of_Living_Accommodations__c.contains('In a hotel or motel') ||
                                account.Type_of_Living_Accommodations__c.contains('A Primary Nighttime Residence')) {
                    accountIdSet.add(account.id);
                }
            }
        }

        if (accountIdSet.size() > 0) {
            NES_BusinessLogicUtils.calculateHomelessRiskFlag(accountIdSet);
        }
    }

    /**
     * Created By Anushka on 12/18/2018
     * purpose is to call the calculateLTS method in the NES_BusinessLogicUtils class after Update/Insert.
     */
    public static void calculateLTS(List<Account> newList, Map<Id, Account> oldMap) {
        Set<Id> accountIds = new Set<Id>();
        for (Account account : newList) {
            if (oldMap != null && !oldMap.isEmpty()) {
                if (account.LC_HighestLevelofEducation__c != oldMap.get(account.Id).LC_HighestLevelofEducation__c
                        || account.Mktg_Customer_Loyalty__c != oldMap.get(account.Id).Mktg_Customer_Loyalty__c
                        || account.Computer_in_Home__c != oldMap.get(account.Id).Computer_in_Home__c
                        || account.Internet_Connection_Type__c != oldMap.get(account.Id).Internet_Connection_Type__c)
                    accountIds.add(account.Id);
            } else {
                if (!String.isBlank(account.LC_HighestLevelofEducation__c) || !String.isBlank(account.Mktg_Customer_Loyalty__c)
                        || account.Computer_in_Home__c != null || !String.isBlank(account.Internet_Connection_Type__c))

                    accountIds.add(account.Id);
            }
        }
        if (accountIds.size() > 0) {
            Map<Id, hed__Program_Enrollment__c> programEnrollmentMap = new Map<Id, hed__Program_Enrollment__c>([
                    Select id from hed__Program_Enrollment__c
                    where hed__Contact__r.AccountId IN :accountIds and status__c = 'In Progress'
            ]);
            List<hed__Program_Enrollment__c> programEnrollments = NES_LTSUtility.calculateLTS(programEnrollmentMap.keySet());
            try {
                update programEnrollments;
            } catch (Exception ex) {logger.logException('calculateLTS', ex);logger.saveLogs();}
        }
    }
    /**
     * Created By Mark Membrino on 10/24/2019  Story 113910
     * If an account postal or state is updated, we need to recalc the address eligibility.
     * // Added  shippingstreet code for the User Story #154114 on 06/04/2020
     * If an account postal or state or shippingstreet is updated, we need to recalc the address eligibility.
     */
    public static void recalcAddrEligIfRequired(List<Account> newList, Map<Id, Account> oldMap) {
        Set<Id> accountIds = new Set<Id>();
        for (Account account : newList) {
            if (oldMap != null && !oldMap.isEmpty()) {
                if (account.shippingstate != oldMap.get(account.Id).shippingstate
                        || account.ShippingPostalCode != oldMap.get(account.Id).ShippingPostalCode || account.shippingstreet != oldMap.get(account.Id).shippingstreet)
                    accountIds.add(account.Id);
            }
        }

        if (accountIds.size() > 0) {
           list <hed__Program_Enrollment__c> PEsToCheck = new list <hed__Program_Enrollment__c>
             ([ Select id, hed__Account__c, hed__Contact__c
                from hed__Program_Enrollment__c
                where hed__Contact__r.AccountId IN :accountIds and status__c = 'In Progress']);

            if (PEsToCheck.size() > 0) {
                list <hed__Program_Enrollment__c> PEsToUpdate = NES_BusinessLogicUtils.calculateAddressEligibility(PEsToCheck);
                update PEsToUpdate;
            }
        }
    }


    /**
     * Created By Mark Membrino on 10/30/2019  Story 114150
     * If computer in home is updated, we need to recalc the technology flag for all related PEs.
     */
    public static void recalcTechnologyFlag(List<Account> newList, Map<Id, Account> oldMap) {
        Set<Id> accountIds = new Set<Id>();
        for (Account account : newList) {
            if (oldMap != null && !oldMap.isEmpty()) {
               if ( ( String.isBlank(oldMap.get(account.Id).Computer_in_Home__c) || oldMap.get(account.Id).Computer_in_Home__c =='Yes') && account.Computer_in_Home__c == 'No')
                     accountIds.add(account.Id);
            }
        }

        System.debug('recalcTechnologyFlag accountIds' + accountIds);
        if (accountIds.size() > 0) {
           /*list <hed__Program_Enrollment__c> PEsToCheck = new list <hed__Program_Enrollment__c>
             ([ Select id, hed__Account__c, hed__Contact__c
                from hed__Program_Enrollment__c
                where hed__Contact__r.AccountId IN :accountIds and status__c = 'In Progress']);*/
           //added for bug 121557
            list <hed__Program_Enrollment__c> PEsToCheck =[ Select id, hed__Account__c, hed__Contact__c
                from hed__Program_Enrollment__c
                where hed__Contact__r.AccountId IN :accountIds ]; //and status__c = 'In Progress'
          //added for bug 121557

                System.debug('recalcTechnologyFlag PEsToCheck' + PEsToCheck);

            if (PEsToCheck.size() > 0) {
                list <hed__Program_Enrollment__c> PEsToUpdate = NES_BusinessLogicUtils.flagTechnologyAction(PEsToCheck);
                update PEsToUpdate;
            }
        }
    }
}