force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Enrollment_Stop_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Stop_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Enrollment Cutoff Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/PushToSecondSemester__c.field-meta.xml
<CustomField>
    <fullName>PushToSecondSemester__c</fullName>
    <description>This is when the second semester becomes the only option</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Push To Second Semester</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Announcement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Academic_Program</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Educational_Institution</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Announcements</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <label>Alert Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Alert</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Body</label>
        <length>1000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Date_Off__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Off</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_On__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dismissable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dismissable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Grade_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Grade Level the Announcement should be displayed for.</description>
        <inlineHelpText>The Program Grade Level the Announcement should be displayed for.</inlineHelpText>
        <label>Program Grade Level</label>
        <referenceTo>Program_Grade_Level__c</referenceTo>
        <relationshipLabel>Announcements</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Announcement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to the Contact records with the Caretaker Record type.It is being used by the student Record Types of Contact</description>
        <label>Caretaker Id</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Caretaker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <displayFormat>S-{00000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Announcement__c.object
<CustomObject>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Contact Announcements</relationshipLabel>
        <relationshipName>Contact_Announcements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Caretaker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Announcements</relationshipLabel>
        <relationshipName>Contact_Announcements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Off__c</fullName>
        <description>The date this announcement will be turned off for this contact</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Off</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_On__c</fullName>
        <description>The date this announcement will be turned on for this contact</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dismissed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dismissed</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Announcement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Announcements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Student_ID__c.field-meta.xml
<CustomField>
    <fullName>Student_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Student ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caretaker Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Semester_Indicator__c</fullName>
        <label>Final Semester Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Semester_Indicator__c</fullName>
        <label>Semester Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                    <default>true</default>
                    <label>First</label>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Student Id)</relationshipLabel>
        <relationshipName>Opportunities_Stdnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Academic_Program__c</fullName>
    <label>Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/PushToSecondSemester__c.field-meta.xml
<CustomField>
    <fullName>PushToSecondSemester__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Push To Second Semester</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/NES_Batch_SecondSemester.cls
/**
 * Created by Ashish Sharma on 12/03/18
 * Class Name: NES_Batch_SecondSemester
 * Test Class Name: NES_Batch_SecondSemesterTest
 * Purpose : This batch/scheduler class is used to set Final_Semester_Indicator__c on opportunities to second semester
*/
global class NES_Batch_SecondSemester implements DataBase.Batchable<sObject>, Schedulable {
    private static Peak_ApexLog logger = new Peak_ApexLog('SecondSemester');

    //Constants
    static final String ACCOUNT_OBJECT = 'Account';
    static final String PROGRAM_GRADE_LEVEL_OBJECT = 'Program_Grade_Level__c';
    static final String FIRST_SEMESTER_INDICATOR = 'First';
    static final String SECOND_SEMESTER_INDICATOR = 'Second';
    static final String CRITICAL_ALERT_TYPE = 'Critical';

    //Variables to store the object's Name and push date for second semester after which records need to be processed
    String objectName;
    Datetime secondSemesterPushDate;

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: N/A
     * Return Type: N/A
     * Purpose : Constructor method
    */
    global NES_Batch_SecondSemester() {

    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: String, Datetime
     * Return Type: N/A
     * Purpose : Constructor method that accept object name and second semester push date for filter in query
    */
    global NES_Batch_SecondSemester(String objectName, Datetime secondSemesterPushDate) {
        this.objectName = objectName;
        this.secondSemesterPushDate = secondSemesterPushDate;
    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: Database.BatchableContext
     * Return Type: Database.QueryLocator
     * Purpose : Batch class start method to query the Account or related account on Program_Grade_Level__c
     *           based on the objectName passed in the constructor
    */
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query;
        Set<Id> accountIds = new Set<Id>();
        //build query based on the parameters passed in the constructor
        if (objectName == ACCOUNT_OBJECT) {
            for (Account acct : [SELECT Id FROM Account WHERE PushToSecondSemester__c <: secondSemesterPushDate]) {
                accountIds.add(acct.Id);
            }
        } else if (objectName == PROGRAM_GRADE_LEVEL_OBJECT) {
            for (Program_Grade_Level__c pgl : [SELECT Academic_Program__c FROM Program_Grade_Level__c WHERE PushToSecondSemester__c <: secondSemesterPushDate]) {
                accountIds.add(pgl.Academic_Program__c);
            }
        }

        return Database.getQueryLocator([
                SELECT Id, Student_Id__r.Name, Caretaker_Id__c, Program_Enrollment__r.hed__Account__c, Program_Enrollment__r.hed__Account__r.Name, Program_Enrollment__r.hed__Account__r.Enrollment_Stop_Date__c
                FROM Opportunity
                WHERE Program_Enrollment__r.hed__Account__c IN :accountIds AND Semester_Indicator__c = : FIRST_SEMESTER_INDICATOR AND StageName =: 'Open'
        ]);
    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: Database.BatchableContext, List<sObject>
     * Return Type: void
     * Purpose : Batch class execute method to process the collect the account Ids and process
     *           further in pushSecondSemester method
    */
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        pushSecondSemester(scope);
    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: Set<Id>
     * Return Type: void
     * Purpose : Method to process the Opportunities related to accountIds and set Final_Semester_Indicator__c
     *           to Second semester
    */
    void pushSecondSemester(List<Opportunity> opportunities) {

        System.debug('Opportunities returned: ' + opportunities);

        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();

        //collections to store notification related records
        // The code related to the announcement is commented for the Defect 312723 on 10/14/2020  
       /* List<Announcement__c> announcements = new List<Announcement__c>();
        List<Contact_Announcement__c> contactAnnouncements = new List<Contact_Announcement__c>(); */

        for (Opportunity opportunity : opportunities) {

           /* String bodyMessage = 'We have moved ' + opportunity.Student_Id__r.Name +
                    '\'s enrollment in ' +
                    (opportunity.Program_Enrollment__r.hed__Account__r != null && String.isNotBlank(opportunity.Program_Enrollment__r.hed__Account__r.Name) ?
                            opportunity.Program_Enrollment__r.hed__Account__r.Name : '') + ' to the second semester'; */

            System.debug('Creating an op');
            opportunitiesToUpdate.add(new Opportunity(Id = opportunity.Id,
                    Semester_Indicator__c = SECOND_SEMESTER_INDICATOR));

          /*  if (opportunity.Caretaker_Id__c != null) {
                announcements.add(new Announcement__c(Dismissable__c = true, Alert_Type__c = CRITICAL_ALERT_TYPE,
                        Name = 'Moved to Second Semester',
                        Account__c = opportunity.Program_Enrollment__r.hed__Account__c,
                        Body__c = 'We have moved ' + opportunity.Student_Id__r.Name +
                                '\'s enrollment in ' +
                                (opportunity.Program_Enrollment__r.hed__Account__r != null && String.isNotBlank(opportunity.Program_Enrollment__r.hed__Account__r.Name) ?
                                        opportunity.Program_Enrollment__r.hed__Account__r.Name : '') + ' to the second semester',
                        Date_On__c = Datetime.now(),
                        Date_Off__c = (opportunity.Program_Enrollment__r.hed__Account__r != null ?
                                opportunity.Program_Enrollment__r.hed__Account__r.Enrollment_Stop_Date__c : null)));

                contactAnnouncements.add(new Contact_Announcement__c(Contact__c = opportunity.Caretaker_Id__c, Dismissed__c = false,
                        Name = 'Moved to Second Semester'));
            } */


        }

        NES_Constants.runAssignment = false;

        //update opportunitiesToUpdate if not empty
        if (opportunitiesToUpdate.size() > 0) {
            Database.update(opportunitiesToUpdate, false);
        }

        //insert announcements and related contact announcements records
     /*   if (announcements.size() > 0) {
            try {
                insert announcements;

                for (Integer i = 0; i < announcements.size(); i++) {
                    contactAnnouncements[i].Announcement__c = announcements[i].Id;
                }

                insert contactAnnouncements;
            } catch (Exception e) {
                System.debug('Exception in NES_Batch_SecondSemester>> ' + e.getMessage());
                logger.logException('pushSecondSemester', e);
                logger.saveLogs();
            }
        } */
    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: Database.BatchableContext
     * Return Type: void
     * Purpose : Batch class finish method
    */
    global void finish(Database.BatchableContext BC) {

    }

    /**
     * Created by Ashish Sharma on 12/03/18
     * Parameters: SchedulableContext
     * Return Type: void
     * Purpose : Method to schedule the batch apex job
    */
    global void execute(SchedulableContext sc) {
        database.executebatch(new NES_Batch_SecondSemester(ACCOUNT_OBJECT, Datetime.now()));
        database.executebatch(new NES_Batch_SecondSemester(PROGRAM_GRADE_LEVEL_OBJECT, Datetime.now()));
    }
}