force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Confirmation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_End_Date__c</fullName>
    <description>The date/time that final confirmation stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Annual_Student_Information__c.object
<CustomObject>
    <description>Student data that is specific to a school year is stored on the Annual Student Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Student Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment record for the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The School Year record for the year the data is relevant to.</description>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Student Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Student Information</pluralLabel>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Reactivation_Status__c</fullName>
        <description>Part of [US 119348] Full Reactivation.</description>
        <label>Reactivation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question_Group</fullName>
        <active>true</active>
        <label>Question Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Special_Education__c.object
<CustomObject>
    <description>The Special Education Data object stores data related to IEPs, 504 plans, gifted education, and other student services</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Special Educations</relationshipLabel>
        <relationshipName>Special_Educations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Special Education</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Educations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_EnrollmentReactivationTest.cls
/** 

@author: Ali KM (Ness Tech)
* Created this test class on 12/03/2019 for [US 119348]
* Test coverage for 
// => NES_EnrollmentReactivation.cls  (DEPRECATED - NO LONGER USED)
=> NES_EnrollmentReactivationBase.cls
=> NES_StudentReenrollment.cls
=> NES_StudentReactivation.cls
=> NES_EnrollmentReactivationHandler.cls

*/
@isTest(SeeAllData=false isParallel=true)
public with sharing class NES_EnrollmentReactivationTest { 
    public enum Reactivation {SOFT, FULL, RE_ENROLLMENT } 
    
    
    public static final String EC_DEFAULT_REACTIVATION_STATUS = 'Not Started'; // OR => In Progress // EC.Reactivation_Status__c
    public static final String OPP_DEFAULT_OPP_STAGE = 'Closed Lost';
    public static final String REACTIVATION_FULL = 'FULL';
    public static final String REACTIVATION_SOFT = 'SOFT';
    public static final String STUDENT_RE_ENROLLMENT = 'RE_ENROLLMENT';
    
    
    @TestSetup 
    static void setup() {
        
        Account account = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019', Date.parse('11/17/2018'));
        School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018', Date.parse('11/17/2017'));
        
        
        // Create a contact with 'Students' record type
        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);
        
        
        // Create a account with 'Academic Program' record type
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(account.Id, currentSchoolYear.Id);
        academicProgram.Registration_End_Date__c=Date.today().addMonths(1);
        academicProgram.Registration_Start_Date__c=Date.newInstance(2017,11,11);
        academicProgram.Confirmation_End_Date__c = Date.today().addMonths(1);
        update academicProgram;
        
        
        // Create STUDENT PE
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, currentSchoolYear.Id, false);
        progEnrollment.Status__c='Inactive';
        insert progEnrollment;
        
        
        // NOT SURE WHY WE NEED Relationship
        User u = [SELECT Id,ContactId FROM User WHERE ContactId != NULL AND IsActive = TRUE LIMIT 1];
        hed__Relationship__c  relationship = Peak_TestUtils.createRelationship(u.ContactId, contact.Id, true);
        
        
        // Create ECs with different record type
        List < Enrollment_Component__c > componentList = new List < Enrollment_Component__c > ();
        Enrollment_Component__c stageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Stage', false);
        stageComponent.Reactivation_Status__c = EC_DEFAULT_REACTIVATION_STATUS;
        Enrollment_Component__c processComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Process', false);
        Enrollment_Component__c questionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        questionComponent.Reactivation_Status__c = EC_DEFAULT_REACTIVATION_STATUS;
        Enrollment_Component__c questionGroupComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question_Group', false);
        questionGroupComponent.Reactivation_Status__c = EC_DEFAULT_REACTIVATION_STATUS;
        Enrollment_Component__c sectionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Section', false);
        Enrollment_Component__c formComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Form', false);
        formComponent.Reactivation_Status__c = EC_DEFAULT_REACTIVATION_STATUS;
        Enrollment_Component__c messageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Message', false);
        Enrollment_Component__c documentComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Document', false);
        documentComponent.Reactivation_Status__c = EC_DEFAULT_REACTIVATION_STATUS;
        
        componentList.add(stageComponent);
        componentList.add(processComponent);
        componentList.add(questionComponent);
        componentList.add(questionGroupComponent);
        componentList.add(sectionComponent);
        componentList.add(formComponent);
        componentList.add(messageComponent);
        componentList.add(documentComponent);
        insert componentList;
        
        
        // Not sure why we need this
        // create Enrollment Component Relationships with different parent Enrollment Components.
        Enrollment_Component_Relationship__c enrollCompRelationship = Peak_TestUtils.createEnrollmentComponentRelationship(stageComponent.Id, processComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship2 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponent.Id, questionGroupComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship3 = Peak_TestUtils.createEnrollmentComponentRelationship(questionGroupComponent.Id, sectionComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship4 = Peak_TestUtils.createEnrollmentComponentRelationship(formComponent.Id, stageComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship5 = Peak_TestUtils.createEnrollmentComponentRelationship(messageComponent.Id, formComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship6 = Peak_TestUtils.createEnrollmentComponentRelationship(sectionComponent.Id, formComponent.Id);
        
        
        // create Enrollment Component Affiliations with different parent Enrollment Components.
        Enrollment_Component_Affiliation__c affiliation = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, formComponent.Id);
        Enrollment_Component_Affiliation__c affiliationStage = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, stageComponent.Id);
        Enrollment_Component_Affiliation__c affiliationSection = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, sectionComponent.Id);
        Enrollment_Component_Affiliation__c affiliationDocument = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, documentComponent.Id);
        Enrollment_Component_Affiliation__c affiliationProcess = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, processComponent.Id);
        Enrollment_Component_Affiliation__c affiliationQuestionGroup = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, questionGroupComponent.Id);
        Enrollment_Component_Picklist_Option__c picklistOption = Peak_TestUtils.createEnrollmentComponentPicklistOption(questionComponent.Id, true);
        
        
        // create EDs
        Enrollment_Document__c enrollmentDocument1 = Peak_TestUtils.createEnrollmentDocumentRecord(progEnrollment.Id,'IEP Exit Documentation','Requested',false);
        // enrollmentDocument1.Type__c = 'IEP Exit Documentation';
        // enrollmentDocument1.Status_Reason__c = 'Requested';
        enrollmentDocument1.Enrollment_Component_Affiliation__c = affiliation.Id;
        insert enrollmentDocument1;
        
        Grade_Level__c gradeLevel = Peak_TestUtils.createGradeLevel('Test',true);
        Program_Grade_Level__c programGradeLevel = Peak_TestUtils.createProgramGradeLevel('Test', academicProgram.Id, gradeLevel.Id,Datetime.now(), true);
        
        // Create a Standard User
        User  portalUser= Peak_TestUtils.CreatePortalCaretTakerUser(contact.Id);
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('SchoolTest', System.today());
        // hed__Program_Enrollment__c ProgramEnrollmentTest = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, schlYear.Id, false);
        // insert ProgramEnrollmentTest;
        
        // create ASIs
        Annual_Student_Information__c annualStudentInformation 
            = Peak_TestUtils.createAnnualStudentInformation('Test ASI',progEnrollment.Id,currentSchoolYear.Id,true);
        
        // create SE
        Special_Education__c specialEducation = Peak_TestUtils.createSpecialEducation(progEnrollment.Id,false);
        specialEducation.IEP__c = 'Documenting';
        specialEducation.Plan504__c = 'Received';
        insert specialEducation;
        
        // create Opportunity
        Opportunity newOpp = createOpportunity(progEnrollment.Id, progEnrollment.hed__Account__c, OPP_DEFAULT_OPP_STAGE, true);
        
        
    }
    
    
    static testMethod void studReenrollment_Positive() {
        
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];
        progEnrollment.Status__c = NES_EnrollmentReactivationBase.PE_WITHDRAWAL_STATUS;
        update progEnrollment;
        List<Enrollment_Component__c> lstECs = new List<Enrollment_Component__c>();
        for(Enrollment_Component__c EC : [Select Id,RecordType.Name, Needed_For_Re_Enrollment__c from Enrollment_Component__c]){
            lstECs.add(new Enrollment_Component__c(Id=EC.Id, Needed_For_Re_Enrollment__c = true));
        }
        update lstECs;
        List<Enrollment_Component_Affiliation__c> lstECAs = new List<Enrollment_Component_Affiliation__c>();
        for(Enrollment_Component_Affiliation__c ECA : [Select Id, Status__c, Program_Enrollment__c, Enrollment_Component__r.RecordType.Name from Enrollment_Component_Affiliation__c where Program_enrollment__c =:progEnrollment.Id]){
            lstECAs.add(new Enrollment_Component_Affiliation__c(Id=ECA.Id, Status__c ='Complete'));
        }
        update lstECAs;
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, STUDENT_RE_ENROLLMENT);
        Test.stopTest();
        System.assertEquals(true,response.success);
        
    }
    
    
    static testMethod void studEnrollmentReactivationFull_Positive() {
        
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];
        
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, REACTIVATION_FULL);
        Test.stopTest();
        System.assertEquals(true,response.success);
        
        
    }
    
    
    static testMethod void studEnrollmentReactivationSoft_Positive() {
        
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];
        
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, REACTIVATION_SOFT);
        Test.stopTest();
        System.assertEquals(true,response.success);
        
    }
    
    
    static testMethod void studEnrollmentReactivation_Negative() {
        
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];
        
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, 'UNLISTED');
        Test.stopTest();
        System.assertEquals(false,response.success);
        
        
    }
    
    
    // Test Data creation methods
    public static Opportunity createOpportunity(Id programEnrollmentId, Id accID, String stageName, Boolean isInsert) {
        
        Opportunity newOpportunity = new Opportunity(
            Program_Enrollment__c = programEnrollmentId,
            Name = Peak_TestConstants.OPP_NAME,
            StageName = stageName,
            AccountId = accID,
            CloseDate = Date.today().addMonths(1)
        );
        
        if(isInsert) {
            Insert newOpportunity;
        }
        
        return newOpportunity;
        
        
    }
    static testMethod void studentsMigratedTest() {
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,V2_External_ID__c,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];
        progEnrollment.V2_External_ID__c  = 'Test Migrated';
        progEnrollment.Status__c = NES_EnrollmentReactivationBase.PE_WITHDRAWAL_STATUS;
        update progEnrollment;
        List<Enrollment_Component_Affiliation__c> ecaList = [Select Id,Program_Enrollment__c from Enrollment_Component_Affiliation__c where Program_Enrollment__c =: progEnrollment.Id];
        delete ecaList;
        List<Enrollment_Component__c> ecList = new List<Enrollment_Component__c>();
        for(Enrollment_Component__c EC : [Select Id, Assignment_Logic__c,Needed_for_Re_enrollment__c from Enrollment_Component__c]){
            ecList.add(new Enrollment_Component__c(Id=Ec.Id, Needed_for_Re_enrollment__c = true,Assignment_Logic__c=''));
        }
        update ecList;
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, STUDENT_RE_ENROLLMENT);
        Test.stopTest();
        System.assertEquals(true,response.success);
    }
    
    static testMethod void studReenrollment_NegativeRec() {
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];
        progEnrollment.RecordTypeId = Schema.SObjectType.hed__Program_Enrollment__c.getRecordTypeInfosByDeveloperName().get('Caretaker').getRecordTypeId();
        update progEnrollment;       
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, STUDENT_RE_ENROLLMENT);
        try{
            NES_StudentReactivation obj = new NES_StudentReactivation(progEnrollment.Id, NES_EnrollmentReactivationBase.Reactivation.RE_ENROLLMENT);
        }
        catch(Exception e1){}
        Test.stopTest();
    }
    static testMethod void studReenrollment_NegativeRec1() {
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];   
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, STUDENT_RE_ENROLLMENT);
        try{
            NES_StudentReactivation obj = new NES_StudentReactivation(progEnrollment.Id, NES_EnrollmentReactivationBase.Reactivation.RE_ENROLLMENT);        
            obj.validateStudPEID(null);
        }
        catch(Exception e1){}
        Test.stopTest();
    }
    static testMethod void studReenrollment_NegativeRec2() {
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];   
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, STUDENT_RE_ENROLLMENT);
        try{
            NES_StudentReactivation obj = new NES_StudentReactivation(progEnrollment.Id, NES_EnrollmentReactivationBase.Reactivation.RE_ENROLLMENT);        
            id recId = [Select id from Account limit 1].Id;
            obj.validateStudPEID(recId);
        }
        catch(Exception e1){}
        Test.stopTest();
    }
    
    static testMethod void studEnrollmentReactivationFull_Positive2() {
        
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];     
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, STUDENT_RE_ENROLLMENT);
        Test.stopTest();
    }
    
    
    static testMethod void studEnrollmentReactivationSoft_Positive1() {
        
        hed__Program_Enrollment__c progEnrollment = [SELECT Id,hed__Account__c, Status__c,RecordType.Name FROM hed__Program_Enrollment__c  LIMIT 1];      
        Test.startTest();
        Peak_Response response = NES_EnrollmentReactivationHandler.reactivateStudent(progEnrollment.Id, STUDENT_RE_ENROLLMENT);
        NES_StudentReactivation obj = new NES_StudentReactivation(progEnrollment.Id, NES_EnrollmentReactivationBase.Reactivation.RE_ENROLLMENT);
        obj.processECAs(STUDENT_RE_ENROLLMENT);
        Test.stopTest();
    }    
}