force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Educational_Institution_SSTF_Mapping__mdt.object
<CustomObject>
    <description>This custom metadata is used to Assign Permission Set to School staff Community User (US#123101 - Task# 160180, 159334 &amp; 158397).</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <description>US #123101 - This field is set with the Public Group Name belonging to the Internal Staff users. This field gets set when the Batch Job named CS_SSTFPublicGroupUserPermissionBatch is executed.</description>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <description>US #123101 - This field is used to capture the associated permission set name belonging to the Internal Staff users. This field gets set when the Batch Job named CS_SSTFPublicGroupUserPermissionBatch is executed.</description>
        <label>Permission Set Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Profile__c</fullName>
        <description>US #123101 - This field captures the community user profile names. This field gets set when the Batch Job named CS_SSTFpermissionBatch is executed.</description>
        <label>User Profile</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Educational Institution_SSTF_Mapping</label>
    <pluralLabel>Educational Institution_SSTF_Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mapping_Profiles__mdt.object
<CustomObject>
    <description>This Metadata represents information regarding the profile names of School Counselor, School Principal, School Special Education Director, School Staff Administrator.</description>
    <label>Mapping Profile</label>
    <pluralLabel>Mapping Profiles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mapping_Profiles__mdt/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <description>US # 123101 - This field holds the value of Non-Community profile names like School Counselor, School Principal, School Special Education Director, School Staff Administrator. This field is set when the batch CS_SSTFPublicGroupUserPermissionBatch is executed.</description>
    <label>Profile Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Records_Processing_Intervals__mdt.object
<CustomObject>
    <description>This is created for User Story No. 164369 (Pls don&apos;t delete). This MDT is for determining how earlier the records should be taken into consideration based on the days, hours, mins for processing. This is being used in determining the timestamp of the Program Enrollment/Relationship object records for the LC Community Access to School relevant Knowledge Articles based on Topics.</description>
    <fields>
        <fullName>Days__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Days that we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions.The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter a negative value say &quot;-1&quot; to pick records updated in the last 1 day&apos;s time. &quot;-2&quot; will imply records that were updated in the last 2 days time interval.</inlineHelpText>
        <label>Days</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Hours by which we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions. The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter the hours in negative values like &quot;-3&quot; to consider records that were updated in the last 3 hours accordingly. &quot;-6&quot; will imply records that were updated in the last 6 hours time interval.</inlineHelpText>
        <label>Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Mins by which we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions. The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter the Minutes in negative values like &quot;-30&quot; to consider records that were updated in the last 30 minutes accordingly. &quot;-40&quot; will imply records that were updated in the last 40 minutes time interval.</inlineHelpText>
        <label>Minutes</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Records Processing Intervals</label>
    <pluralLabel>Records Processing Intervals</pluralLabel>
</CustomObject>

force-app/main/default/classes/CS_SSTFPublicGroupUserPermissionBatch.cls
/*
  Author:Guravaiah Gunturi
  ****************************
  User Story: #123101 (Task: #158397,160126)
  *******************************************
  Date:23/03/2020
  ********************************************
  Apex Classes: CS_SSTFPublicGroupUserPermissionBatch
  *****************************************************************************
  Description:This class is controller for Assigning permission set to Public Group Members 
			    - Query all the Group Members of the Particular Group,identify whether the perimission set is already been assigned for each Member
				- If the User is already having the permission set ->Ignore
				- The group member doesn't have permission set assigned to them -> New Member to the Group -> Assign the Permisison Set
				- Users who has Permission set but not part of the Group -> Remove the Permisison Set from that User
*/

global class CS_SSTFPublicGroupUserPermissionBatch implements Schedulable,Database.Batchable <sObject> {
    Global List<Educational_Institution_SSTF_Mapping__mdt> EISSTFMappingList = new List<Educational_Institution_SSTF_Mapping__mdt>();
    
    //Assign all custom metadata records to declared metadata list variable in constructor
    global CS_SSTFPublicGroupUserPermissionBatch(){
        this.EISSTFMappingList = getAllEISSTFmappingList();
    }
    //  While running the batch class this method will start and fetching all the Groups from the custom metadata.
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Set<String> groupNameList = new Set<String>();
        for(Educational_Institution_SSTF_Mapping__mdt cutMdt :EISSTFMappingList ){
            groupNameList.add(cutMdt.Group_Name__c);
        }
        Records_Processing_Intervals__mdt recordProcessInterval = [SELECT Id, Days__c, Hours__c, Minutes__c FROM Records_Processing_Intervals__mdt WHERE DeveloperName = :CS_Constants.SSTF_PUBLIC_GROUP_USER_PERMISSION_ACCESS_PROCESS];
        DateTime dateTimeInterval = system.now().addDays(Integer.valueOf(recordProcessInterval.Days__c)).addHours(Integer.valueOf(recordProcessInterval.Hours__c)).addMinutes(Integer.valueOf(recordProcessInterval.Minutes__c));    
        
        //Running Batch for Each Group from the Custom Metadata
        String query = 'SELECT Id,Name FROM Group WHERE Name in:groupNameList and SystemModstamp >=:dateTimeInterval';
        if(Test.isRunningTest()){
            query = 'SELECT Id,Name FROM Group WHERE Name in:groupNameList limit 1';
        }
        //system.debug('query====='+query);
        return Database.getQueryLocator(query);
    }
    //This method divided the number of Group records into batches and execte the one by one batch.
    global void execute(Database.BatchableContext bc, List<Group> groupRecords){
        //Query All the GroupMembers under the Group
        List<GroupMember> records=[SELECT UserOrGroupId,Group.Name FROM GroupMember WHERE Group.Id=:groupRecords];
        set<Id> userIdSet = new set<Id>();
        set<String> groupNameSet = new set<String>();
        for (GroupMember gm :records)
        { 
            userIdSet.add(gm.UserOrGroupId);  
            groupNameSet.add(gm.Group.Name);
        }
        Set<String> profileName = new set<String>();
        for(Mapping_Profiles__mdt	mp:[Select Profile_Name__c from Mapping_Profiles__mdt]){
            profileName.add(mp.Profile_Name__c);
        }
        Map<Id,User> userMap = new Map<Id,User>([Select Id,profile.Name from user where Id in:userIdSet AND profile.name IN:profileName]);
        
        List<PermissionSetAssignment> permissionSetList = new List<PermissionSetAssignment>();
        List<PermissionSetAssignment> deletePermissionSetList = new List<PermissionSetAssignment>();
        Map<String,String> GroupPermissionsetMap = new Map<String,String>();
        
        //Identify the Corresponsing permission set name for that Group
        for(Educational_Institution_SSTF_Mapping__mdt cutMdt :EISSTFMappingList ){
            if(groupNameSet.contains(cutMdt.Group_Name__c)){
                GroupPermissionsetMap.put(cutMdt.Group_Name__c,cutMdt.Permission_Set_Name__c);                   
            }
        }
        
        
        //Query the Permission Set where name in custom metadata
        Map<String,Id> permissionSetMap = new Map<String,Id>();
        for(permissionset ps:[Select id,Name from PermissionSet Where Name in:GroupPermissionsetMap.values()])
        {
            permissionSetMap.put(ps.Name,ps.Id);
        }
        
        
        
        if(!permissionSetMap.isEmpty())
        {
            Map<String,Id> existingPAUsers = new Map<String,Id>();
            //Query all the Users who are having the Existing Permission Set assigned to them
            List<PermissionSetAssignment> psaList = [Select Id,AssigneeId,Assignee.Contact.Account.RecordType.Name,PermissionSetId from PermissionSetAssignment where PermissionSetId=:permissionSetMap.values()];
            for(PermissionSetAssignment psa : psaList){                
                if(psa.Assignee.Contact.Account.RecordType.Name !='Educational Institution' ){
                    existingPAUsers.put(psa.PermissionSetId+'_'+psa.AssigneeId,psa.Id);
                }
            }  
            for (GroupMember gm :records)
            {
                System.debug('Printing usermap'+userMap.get(gm.UserOrGroupId));
                if(userMap.get(gm.UserOrGroupId)!=null && profileName.contains(userMap.get(gm.UserOrGroupId).profile.Name)){ //Assign Permission setto the Corresponding Profile Users only
                    Id permissionSetId = permissionSetMap.get(GroupPermissionsetMap.get(gm.Group.Name));
                    if(existingPAUsers.containsKey(PermissionSetId+'_'+gm.UserOrGroupId)){ //If the User is already having the permission set ->Ignore
                        existingPAUsers.remove(PermissionSetId+'_'+gm.UserOrGroupId);
                        //usersToremove.add(gm.UserOrGroupId);
                    }else{ //The group member doesn't have permission set assigned to them -> New Member to the Group -> Assign the Permisison Set
                        PermissionSetAssignment psa = new PermissionSetAssignment (PermissionSetId =permissionSetId , AssigneeId = gm.UserOrGroupId);
                        permissionSetList.add(psa);       
                    }
                }
            }
            if(!existingPAUsers.isEmpty()){ // Users who has Permission set but not part of the Group -> Remove the Permisison Set from that User
                for(Id psaId:existingPAUsers.values()){
                    deletePermissionSetList.add(new PermissionSetAssignment(Id=psaId));
                }                
            }
            //system.debug('permissionSetList====='+permissionSetList);
            //system.debug('deletePermissionSetList====='+deletePermissionSetList);
            try{
                Database.insert(permissionSetList,false);
                delete deletePermissionSetList;
            }Catch(Exception ex){
                system.debug('Exception---'+ex);
            }
            
        }
        
    }  
    //This metod will be stop the process once execute method completed.
    global void finish(Database.BatchableContext bc){
        
    }  //Scheduled batch class
    global void execute(SchedulableContext scon) {
        Database.executeBatch(new CS_SSTFPublicGroupUserPermissionBatch());
    }
    
    //This metod returning all the Permissionsets,Groups and Profiles from the Custom Meatadata.
    Public List<Educational_Institution_SSTF_Mapping__mdt> getAllEISSTFmappingList(){
        return [SELECT MasterLabel,
                Permission_Set_Name__c,
                User_Profile__c,
                Group_Name__c
                FROM Educational_Institution_SSTF_Mapping__mdt];
    }
}