force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Record_Type_Text__c</fullName>
        <defaultValue>$RecordType.Name</defaultValue>
        <description>Contact Record Type in text format to allow it to be referenced in Duplicate Matching Rules because the standard Record Type field is not available for Matching Rules.

User Story #111315</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Current record Contact Record Type value.</inlineHelpText>
        <label>Contact Record Type (Text)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c.object
<CustomObject>
    <description>&quot;The Enrollment object stores the dates and status codes that define a student’s enrollment with the Academic Program. A student may have multiple Enrollment records for a single Program Enrollment. Each withdrawal and re-enrollment within the same Academic Program will generate a new Enrollment associated with the Program Enrollment.

All Enrollment records are coded with a specific school year. Enrollment records are  updated with a withdrawal date and code sent from the SIS when students withdraw from the academic program.&quot;</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>Child records can be reparented to other parent records after they are created</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The School Year record for the year the data is relevant for.</description>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Withdrawal_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Withdrawal Category</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade_Level__c.object
<CustomObject>
    <description>The grade level object stores grade level information for connection to Academic Programs and Caps.</description>
    <label>Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Start Year (calculated)</description>
    <label>Start Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Academic_Program__c</fullName>
    <label>Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The current school year</description>
        <label>Current School Year</label>
        <type>Checkbox</type>
    </fields>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_ReactivationNewSYHelper.cls
/**
* Created by Sravani Pendyala on 12/01/2020.
* Created for the task #335376.
* Test Class : NES_ReactivationNewSYHelperTEST
* Description : This class acts as controller for the lightning component "NES_ReactivationNewSY" 
* which is used for "Reactivation - New SY" quick action on PE record detail page.
*                        
*/




public class NES_ReactivationNewSYHelper {
    
/**
* Created by Sravani Pendyala on 12/01/2020.
* Return Type: List<Grade_Level__c>
* Purpose : This method is used to get the related Grade levels for selected year and institute name.
*/
    @AuraEnabled
    public static List<Grade_Level__c> getGradeLevels(string selectedYr,String instituteName) {
        List<Grade_Level__c> gradeLevels = NES_EnrollmentController.getGradeLevels(instituteName,selectedYr);
        /*
        hed__Program_Enrollment__c programEnrollment =[Select id,hed__Account__r.ParentId,Start_Year__c from hed__Program_Enrollment__c where id=:programEnrollmentId];
        List<Grade_Level__c> gradeLevels = [SELECT Id, Name FROM Grade_Level__c where Id in (Select Grade_Level__c from Program_Grade_Level__c where Academic_Program__r.ParentId=:programEnrollment.hed__Account__r.ParentId) order by Name];
        */
        return gradeLevels;
    }
    
/**
* Created by Sravani Pendyala on 12/01/2020.
* Return Type: Peak_Response
* Purpose : This method is used to Reactive the PE for new School year.
*/
    @AuraEnabled
    public static Peak_Response newYearReactivate(Id studentId,String instituteNam,String schoolYear,String gradeLevels, String callType, boolean enrollFlag, Id programEnrollmentId) {
        Peak_Response pr = NES_EnrollmentController.nextYearEnrollment(studentId,instituteNam,schoolYear,gradeLevels,callType,enrollFlag,programEnrollmentId);
        return pr;
    }
    
/**
* Created by Sravani Pendyala on 12/01/2020.
* Purpose : Wrapper class used for validatePE method
*/
    public class validatePEwrapper{
        @AuraEnabled
        public hed__Program_Enrollment__c programEnrollment{get;set;}
        @AuraEnabled
        public string isValid{get;set;}
        public validatePEwrapper(hed__Program_Enrollment__c pe, string isvalid){
            this.programEnrollment = pe;
            this.isvalid = isvalid;
        }
    }
    
/**
* Created by Sravani Pendyala on 12/01/2020.
* Return Type: validatePEwrapper
* Purpose : This method is used to validate given PE for New Year Reactivation  
*/
    @AuraEnabled
    public static validatePEwrapper validatePE(ID programEnrollmentId) {
        String PE_status_Inactive = 'Inactive';

        String PE_status_Withdrawn = 'Withdrawn';// Updated by sravani #361444
        String PE_status_Complete = 'Complete';
        string isValid = 'valid';
        hed__Program_Enrollment__c programEnrollment = [SELECT id, Start_Year__c,Start_Year__r.Name,hed__Contact__c,hed__Contact__r.Contact_Record_Type_Text__c,hed__Account__r.Parent.Name,Status__c,
                                                        (select id,Withdrawal_Category__c from Enrollments__r order by createddate desc) FROM hed__Program_Enrollment__c WHERE Id = :programEnrollmentId];
        
       
        if(!(PE_status_Inactive.containsIgnoreCase(programEnrollment.Status__c) 
             || PE_status_Withdrawn.containsIgnoreCase(programEnrollment.Status__c)
            || (PE_status_Complete.containsIgnoreCase(programEnrollment.Status__c) && (!programEnrollment.Enrollments__r.isEmpty()) && (programEnrollment.Enrollments__r[0].Withdrawal_Category__c == 'Not Returning' ) ) )){           
               isValid = 'PE Status is not valid for the process.';} 
     
        validatePEwrapper  vPEw = new validatePEwrapper(programEnrollment,isValid);
        return vPEw;
    }
    
/**
* Created by Sravani Pendyala on 12/01/2020.
* Return Type: List<School_Year__c>
* Purpose : This method is used to get list of valid School years for given Institute   
*/
    @AuraEnabled
    public static List<School_Year__c> getSchoolYears(String instituteName, String omitPEYearId) {
        List<School_Year__c> schoolYears = NES_EnrollmentController.getSchoolYears(instituteName);
        List<School_Year__c> validSchoolYears = New List<School_Year__c>();
        for(School_Year__c SY : schoolYears){
            
            if(SY.Id!=omitPEYearId){
                validSchoolYears.add(SY);
           	}
          
            
        }
        /*
        List<String> schoolYearIds = new List<String>();
        new List<School_Year__c>();
        hed__Program_Enrollment__c programEnrollment =[Select id,hed__Account__r.ParentId,Start_Year__c from hed__Program_Enrollment__c where id=:programEnrollmentId];
        List<School_Year__c> schoolYears = [Select id,name,Current_Year__c from School_Year__c where Id in (Select School_Year__c from Account where parentid=:programEnrollment.hed__Account__r.ParentId) and Current_Year__c!=true and id!=:programEnrollment.Start_Year__c ];
        */        
        return validSchoolYears;
    }
}