force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Family_Enrollment_Counselor__c.field-meta.xml
<CustomField>
    <fullName>Family_Enrollment_Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US: 120471
Name of the FEC assisting this Household</description>
    <label>Family Enrollment Counselor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to the Contact records with the Caretaker Record type.It is being used by the student Record Types of Contact</description>
        <label>Caretaker Id</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Caretaker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Assignment_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component is relevant to the program enrollment the evaluation was completed for and it would then be assigned to the PE through a Enrollment Component Affiliation. If there is no assignment logic defined on a component, it inherits it&apos;s assigment from its parent.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Assignment Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Indicator of whether the component relates to student or caretaker (household) program enrollments. This field is used for components of the following types: Flag, Form. All child components of a form should implicitly inherit the type of the form when used in the context of that form.</description>
        <label>Component Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Caretaker</fullName>
                    <isActive>false</isActive>
                    <label>Caretaker</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic program associated with the component. This is exclusively used by components with a record type of Process to create a relationship between the account entity and it&apos;s required components. As the child components of the process could be used by multiple processes, there is not a direct relationship between them and a specific academic program and those relationships are inferred from their parent process.</description>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enrollment Components (Academic Program)</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <description>The enrollment component that is the parent in the relationship being defined.</description>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The current school year</description>
        <label>Current School Year</label>
        <type>Checkbox</type>
    </fields>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_ReactivateStdUtils.cls
// Created By Maddileti for New SY Reactivation

public class NES_ReactivateStdUtils {
    
    public static user getCTUserFromStudentId(String studentId){
        User ctUser;
        Contact stdUser;
        if(studentId != null){
            stdUser= [SELECT Id, Caretaker_Id__c from Contact where Id=:studentId limit 1];
            ctUser = [SELECT Id, AccountId, ContactId, Contact.RecordType.Name,Contact.Account.Family_Enrollment_Counselor__c, Contact.AccountId FROM User WHERE ContactId = :stdUser.Caretaker_Id__c limit 1];
        }
        else
            ctUser = null;
        
        return ctUser; 
    }
    public static user getCTUser(String userId){
        
        User ctUser;
        if(userId != null){
            ctUser = [SELECT Id, AccountId, ContactId, Contact.RecordType.Name,Contact.Account.Family_Enrollment_Counselor__c, Contact.AccountId FROM User WHERE Id = :userId];
        }
        else
            ctUser = null;
        
        return ctUser; 
    }
    
    public static Id getStudentRTId(){		
        return Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Students').getRecordTypeId();
    }
    
    public static Contact getStudentContact(Id studentId, Id studentRTId){
        Contact student;
        if(studentId != null){
            student =[select id,AccountId,firstName,middleName,lastName,Birthdate__c from Contact WHERE id = :studentId  AND RecordTypeId = :studentRTId limit 1];
        }
        else
            student = null;
        return student;
    }
    
    
    public static School_year__c getSchoolYears(String schoolYearName){
        School_Year__c schoolYear;
        if(schoolYearName != null){
            schoolYear = [SELECT Current_Year__c,Id,name FROM School_Year__c where name =:schoolYearName limit 1];
        }
        else
            schoolYear = null;
        return schoolYear;
    }
    
    public static account getInstitute(String instituationName){
        
        return [SELECT Id, name FROM Account where name =:instituationName limit 1];
    }
    
    public static Id getAcademicRTProgramId(){
        
        return Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
    }
    
    
    
    public static List<Enrollment_Component__c> getProcessEC(Id academicProgramId){
        return [SELECT Id, Assignment_Logic__c
                FROM Enrollment_Component__c
                WHERE Process_Academic_Program__c = :academicProgramId
                AND RecordType.Name = :NES_DashboardUtilities.PROCESS_RT
                LIMIT 1
               ];
    }
    
    
    public Static List<Enrollment_Component_Relationship__c> getAllStages(Id processComponent){
        return [
            SELECT Child_Enrollment_Component__c, Id, Order__c, Parent_Enrollment_Component__c,
            Child_Enrollment_Component__r.Assignment_Logic__c, Child_Enrollment_Component__r.Component_Type__c
            FROM Enrollment_Component_Relationship__c
            WHERE Parent_Enrollment_Component__c = :processComponent
            AND Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.STAGE_RT
            ORDER BY Order__c ASC
        ];
    }
    
    
    public static List<Enrollment_Component_Affiliation__c> insertAffiliations(Id processId, Id studentPEId, List<Enrollment_Component_Relationship__c> stageAffiliations){
        
        List<Enrollment_Component_Affiliation__c> ecAffiliationsToInsert = new List<Enrollment_Component_Affiliation__c>();
        // Add process affiliation
        Enrollment_Component_Affiliation__c affiliationRecord1 = new Enrollment_Component_Affiliation__c();
        affiliationRecord1.Enrollment_Component__c = processId;
        affiliationRecord1.Program_Enrollment__c = studentPEId;
        affiliationRecord1.Status__c = 'In Progress';
        ecAffiliationsToInsert.add(affiliationRecord1);
        
        // add stage 1 affiliation
        Enrollment_Component_Affiliation__c affiliationRecord2 = new Enrollment_Component_Affiliation__c();
        affiliationRecord2.Enrollment_Component__c = stageAffiliations[0].Child_Enrollment_Component__c;
        affiliationRecord2.Program_Enrollment__c = studentPEId;
        affiliationRecord2.Status__c = 'Complete';
        affiliationRecord2.Order__c = stageAffiliations[0].Order__c;
        ecAffiliationsToInsert.add(affiliationRecord2);
        
        //Add the rest of the stages that have no assignment logic.
        for (Integer i = 1; i < stageAffiliations.size(); i++) {
            if (String.isBlank(stageAffiliations[i].Child_Enrollment_Component__r.Assignment_Logic__c)) {                
                Enrollment_Component_Affiliation__c affiliationRecord = new Enrollment_Component_Affiliation__c();
                affiliationRecord.Enrollment_Component__c = stageAffiliations[i].Child_Enrollment_Component__c;
                affiliationRecord.Program_Enrollment__c = studentPEId;
                affiliationRecord.Order__c = stageAffiliations[i].Order__c;
                //The second stage should be in progress all others not started.
                if (i == 1)
                    affiliationRecord.Status__c = 'In Progress';
                else
                    affiliationRecord.Status__c = 'Not Started';
                ecAffiliationsToInsert.add(affiliationRecord);
            }
        } 
        
        //add forms affiliation for the forms under stage 1 that have no assignment logic
        List<Enrollment_Component_Relationship__c> formRelationships = [
            SELECT Child_Enrollment_Component__c, Id, Order__c, Parent_Enrollment_Component__c, Child_Enrollment_Component__r.Assignment_Logic__c
            FROM Enrollment_Component_Relationship__c
            WHERE Parent_Enrollment_Component__c = :stageAffiliations[0].Child_Enrollment_Component__c
            AND Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.FORM_RT
            ORDER BY Order__c
        ];
        System.debug(formRelationships);
        List<Id> formRelationshipIds = new List<Id>();
        for (Enrollment_Component_Relationship__c formRelationship : formRelationships) {
            if (String.isBlank(formRelationship.Child_Enrollment_Component__r.Assignment_Logic__c)) {
                Enrollment_Component_Affiliation__c affiliationRecord3 = new Enrollment_Component_Affiliation__c();
                affiliationRecord3.Enrollment_Component__c = formRelationship.Child_Enrollment_Component__c;
                affiliationRecord3.Program_Enrollment__c = studentPEId;
                affiliationRecord3.Status__c = 'Complete';
                affiliationRecord3.Order__c = formRelationship.Order__c;
                ecAffiliationsToInsert.add(affiliationRecord3);
                formRelationshipIds.add(formRelationship.Child_Enrollment_Component__c);
            }
        }
        
        //add section affiliations that have assignment criteria that were added in the previous section.
        List<Enrollment_Component_Relationship__c> sectionRelationships = [
            SELECT Child_Enrollment_Component__c, Id, Order__c, Parent_Enrollment_Component__c, Child_Enrollment_Component__r.Assignment_Logic__c
            FROM Enrollment_Component_Relationship__c
            WHERE Parent_Enrollment_Component__c IN :formRelationshipIds
            AND Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.SECTION_RT
        ];
        System.debug(sectionRelationships);
        for (Enrollment_Component_Relationship__c sectionRelationship : sectionRelationships) {
            if (String.isBlank(sectionRelationship.Child_Enrollment_Component__r.Assignment_Logic__c)) {
                Enrollment_Component_Affiliation__c affiliationRecord3 = new Enrollment_Component_Affiliation__c();
                affiliationRecord3.Enrollment_Component__c = sectionRelationship.Child_Enrollment_Component__c;
                affiliationRecord3.Program_Enrollment__c = studentPEId;
                affiliationRecord3.Status__c = 'Complete';
                affiliationRecord3.Order__c = sectionRelationship.Order__c;
                ecAffiliationsToInsert.add(affiliationRecord3);
            }
        }
        
        List<Enrollment_Component_Affiliation__c> nonNullInsertingAffiliations = new List<Enrollment_Component_Affiliation__c>();
        for (Enrollment_Component_Affiliation__c eca : ecAffiliationsToInsert) {
            if (eca <> null && eca.Enrollment_Component__c <> null && eca.Program_Enrollment__c <> null)
                nonNullInsertingAffiliations.add(eca);
        }
        
        return nonNullInsertingAffiliations;
    }
    
    
    
    
}