force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Annual_Student_Information__c.object
<CustomObject>
    <description>Student data that is specific to a school year is stored on the Annual Student Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Student Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>Grade_Level_Completed__c</fullName>
        <description>The grade level completed during the school year.</description>
        <label>Grade Level Completed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>Kindergarten</fullName>
                </value>
                <value>
                    <fullName>None- entering kindergarten for the first time.</fullName>
                </value>
                <value>
                    <fullName>None- student was not enrolled during the school year.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grade_Level_Requested__c</fullName>
        <description>The grade level the student is requesting for the school year.</description>
        <label>Grade Level Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>Kindergarten</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment record for the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Annual Student Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Student Information</pluralLabel>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Field__c</fullName>
        <description>The API name of the object-field combination being used on the right side of the criteria comparison. This field should be populated if you are comparing the left side field to the value of another field. Example. Account.Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Field (Left)</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Criteria__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The criteria being associated to the Enrollment Component.</description>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Enrollment Component Criteria</relationshipLabel>
        <relationshipName>Enrollment_Component_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_or_Household__c</fullName>
        <label>Student or Household</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component Criteria</label>
    <nameField>
        <displayFormat>ECC-{000}</displayFormat>
        <label>Enrollment Component Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Date_Today__c.field-meta.xml
<CustomField>
    <fullName>Date_Today__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Today</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/DisciplinaryFlagOverride__c.field-meta.xml
<CustomField>
    <fullName>DisciplinaryFlagOverride__c</fullName>
    <description>Disciplinary Flag</description>
    <label>Disciplinary Flag Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/HomelessRiskFlag__c.field-meta.xml
<CustomField>
    <fullName>HomelessRiskFlag__c</fullName>
    <description>Homeless Risk Flag</description>
    <label>Homeless Risk Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homeless</fullName>
            </value>
            <value>
                <fullName>Potential Homeless</fullName>
            </value>
            <value>
                <fullName>Not Homeless</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/LastSchoolType__c.field-meta.xml
<CustomField>
    <fullName>LastSchoolType__c</fullName>
    <label>Last School Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homeschool</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>BIE School / Federal Grant / BIE Contract</fullName>
            </value>
            <value>
                <fullName>Charter School (Public)</fullName>
            </value>
            <value>
                <fullName>Correctional Facility</fullName>
            </value>
            <value>
                <fullName>Home School</fullName>
            </value>
            <value>
                <fullName>Online (Virtual) Public School</fullName>
            </value>
            <value>
                <fullName>Out of school more than 1 year</fullName>
            </value>
            <value>
                <fullName>Out of state</fullName>
            </value>
            <value>
                <fullName>Private/Parochial School</fullName>
            </value>
            <value>
                <fullName>Public School</fullName>
            </value>
            <value>
                <fullName>State Supported</fullName>
            </value>
            <value>
                <fullName>Virtual School (Public)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/WaitlistFlag__c.field-meta.xml
<CustomField>
    <fullName>WaitlistFlag__c</fullName>
    <description>Waitlist Flag</description>
    <label>Waitlist Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active-Reset</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Disciplinary History</fullName>
            </value>
            <value>
                <fullName>Special Education</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PECEvaluation.cls
public class PECEvaluation {

    // MM 12/8/2020 | capturing all criteriaFields
    public static void evaluatePECs(List<Enrollment_Component_Criteria__c> eccs, id programEnrollment) {
        //Household or Student,  Object, Field list
        Map<String, Map<String, Set<String>>> criteriaObjectFieldsMapByPEType = new Map<String, Map<String, Set<String>>>();
        for (Enrollment_Component_Criteria__c ecc : eccs) 
        {
            if (String.isBlank(ecc.Criteria__r.Criteria_Field__c))
                continue;

            String[] fieldParts = ecc.Criteria__r.Criteria_Field__c.toLowerCase().split('\\.', 2); 
            if (fieldParts.size()!=2) {
                System.debug('>>>Invalid field parts for ECC>>>' + JSON.serialize(ecc));    
                continue;
            }

            Map<String, Set<String>> tmpCriteriaObjectFieldsMap = criteriaObjectFieldsMapByPEType.get(ecc.Student_or_Household__c);
            if (tmpCriteriaObjectFieldsMap==null) {
                tmpCriteriaObjectFieldsMap = new Map<String, Set<String>>();
                criteriaObjectFieldsMapByPEType.put(ecc.Student_or_Household__c, tmpCriteriaObjectFieldsMap);
            }
            
            Set<String> tmpObjectFields = tmpCriteriaObjectFieldsMap.get(fieldParts[0]);
            if (tmpObjectFields==null)
                tmpObjectFields = new Set<String>();
            tmpObjectFields.add(fieldParts[1]);
            tmpCriteriaObjectFieldsMap.put(fieldParts[0], tmpObjectFields);
        }
        System.debug('>>>criteriaObjectFieldsMapByPEType>>>' + JSON.serialize(criteriaObjectFieldsMapByPEType));        

        if(criteriaObjectFieldsMapByPEType.size()==0)
            return;

        // query studPE & HH details...
        hed__Program_Enrollment__c studPE = getStudPEById(programEnrollment);
        id caretakerEnrollmentId = studPE.Household_Program_Enrollment__c;
        Id caretakerContactId = studPE.Household_Program_Enrollment__r.hed__Contact__c;
        Id studentContactId = studPE.hed__Contact__c;
        Id accountId = studPE.hed__Contact__r.AccountId;

        // // query the records...
        //Household or Student, Object, list of records for that object.
        Map<String, Map<String, List<sObject>>> criteriaObjectRecordsMapByPEType = new Map<String, Map<String, List<sObject>>>();
        for (String k : criteriaObjectFieldsMapByPEType.keySet()) {
            Id enrollmentId = ( (k.endsWithIgnoreCase('Household'))? caretakerEnrollmentId : programEnrollment);
            Id contactId = ( (k.endsWithIgnoreCase('Household')) ? caretakerContactId : studentContactId );

            //  caretakerMap = getObjectDataList(objectMap, caretakerEnrollmentId, accountId, caretakerContactId);
            criteriaObjectRecordsMapByPEType.put(k, 
                queryRelatedRecords(criteriaObjectFieldsMapByPEType.get(k), enrollmentId, accountId, contactId));
        }
        System.debug('>>>criteriaObjectRecordsMapByPEType>>>' + JSON.serialize(criteriaObjectRecordsMapByPEType));

        // List of fieldUpdate...
        List<EvaluationUtils.fieldUpdate> fldUpdates = new List<EvaluationUtils.fieldUpdate>();
        for ( String k : criteriaObjectRecordsMapByPEType.keySet()) // Ex: Household / Student
        {
            for (String objName : criteriaObjectRecordsMapByPEType.get(k).keySet()) // Ex: ASI / EmergencyContact / PE / PriorSchool / SpecialEducation / ... 
            {
                for (sObject rec : criteriaObjectRecordsMapByPEType.get(k).get(objName)) // Ex: {annual_student_information__c=(Annual_Student_Information__c:{Id=a1t3C000000RWLYQA4, Grade_Level_Requested__c=7}, Annual_Student_Information__c:{Id=a1t3C000000RWLiQAO, Grade_Level_Completed__c=6}
                {
                    for (String field : criteriaObjectFieldsMapByPEType.get(k).get(objName)) // Ex: "waitlistflag__c","date_today__c","LastSchoolType__c","DisciplinaryFlagOverride__c","HomelessRiskFlag__c"
                    {
                        EvaluationUtils.fieldUpdate fldUpdate = new EvaluationUtils.fieldUpdate();
                        fldUpdate.programEnrollmentId = programEnrollment;
                        fldUpdate.objectAndFieldName = objName + '.' + field; 
                        fldUpdate.newValue = rec.get(field);
                        fldUpdates.add(fldUpdate);
                    }
                }
            }
        }

        if (fldUpdates.size()>0) {
            System.debug ('>>>fldUpdates>>> size>>> ' + fldUpdates.size() + '>>>' + fldUpdates);
            EvaluationUtils.evaluateChangedFields(fldUpdates);
        }
    }

    public static hed__Program_Enrollment__c getStudPEById(Id studPEID)
    {
        return [
            SELECT  Id, Name, hed__Contact__c, hed__Contact__r.Name, hed__Contact__r.AccountId, 
                    Household_Program_Enrollment__c, Household_Program_Enrollment__r.hed__Contact__c,
                    Household_Program_Enrollment__r.Name, Household_Program_Enrollment__r.hed__Contact__r.Name
            FROM    hed__Program_Enrollment__c
            WHERE   Id = :studPEID
        ];
    }

    public static Map<String, List<SObject>> queryRelatedRecords(Map <String, Set<String>> queryMap, Id enrollmentId, Id accountId, Id contactId) {
        Map<String, List<SObject>> newQueryMap = new Map<String, List<SObject>>();
        for (String mapKey : queryMap.keySet()) 
        {
            String objectName = mapKey;
            String fieldStrings;
            List<SObject> childRecords = new List<SObject>();
            List<String> fieldNames = new List<String>(queryMap.get(mapKey));
            
            String query;
            if (objectName == 'account') {
                query = 'SELECT Id, ' +  String.join(fieldNames, ',') + ' FROM Account WHERE Id = \'' + accountId + '\' ';
            } else if (objectName == 'contact') {
                query = 'SELECT id, ' + String.join(fieldNames, ',') + ' FROM Contact WHERE Id = \'' + contactId + '\' ';
            } else if (objectName == 'hed__program_enrollment__c' && String.isNotBlank(enrollmentId)) {
                query = 'SELECT id, ' + String.join(fieldNames, ',') + ' FROM hed__program_enrollment__c WHERE id = \'' + enrollmentId + '\' ';
            } else if (String.isNotBlank(enrollmentId)) {
                query = 'SELECT id, ' + String.join(fieldNames, ',') + ' FROM ' + objectName + ' WHERE program_enrollment__c = \'' + enrollmentId + '\' ';
            } 
            System.debug('>>>query>>>' + JSON.serialize(query));
            if (String.isNotBlank(query)) {
                query.remove('(');
                query.remove(')');
                childRecords = Database.query(query);
            }

            if (childRecords.size() > 0) {
                newQueryMap.put(mapKey.toLowerCase(), childRecords);
            } else {
                newQueryMap.put(mapKey.toLowerCase(), new List<SObject>());
            }
            System.debug(newQueryMap);
        }
        return newQueryMap;
    }
}