force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Confirmation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_End_Date__c</fullName>
    <description>The date/time that final confirmation stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program Enrollment</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>hed__Program_Enrollment__c.hed__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>hed__Program_Enrollment__c.hed__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <formula>&apos;&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Year</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Picklist_Option__c.object
<CustomObject>
    <label>Enrollment Component Picklist Option</label>
    <nameField>
        <displayFormat>PO-{0}</displayFormat>
        <label>Enrollment Component Picklist Option Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Picklist Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Picklist_Option__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <inlineHelpText>Parent Question Record Type, Picklist Type Enrollment Component.</inlineHelpText>
    <label>Enrollment Component</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Enrollment_Component__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Question</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Picklist Options</relationshipLabel>
    <relationshipName>Enrollment_Component_Picklist_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FEC_Task_Creation_Rule__mdt.object
<CustomObject>
    <description>FEC Task Creation Rules US 169194</description>
    <label>FEC Task Creation Rule</label>
    <pluralLabel>FEC Task Creation Rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/FEC_Task_Creation_Rule__mdt/fields/lowerLimitInDays__c.field-meta.xml
<CustomField>
    <fullName>lowerLimitInDays__c</fullName>
    <label>lowerLimitInDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FEC_Task_Creation_Rule__mdt/fields/taskSubTypeDefault__c.field-meta.xml
<CustomField>
    <fullName>taskSubTypeDefault__c</fullName>
    <label>taskSubTypeDefault</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Less than 10% within 3 days</fullName>
                <default>true</default>
                <label>Less than 10% within 3 days</label>
            </value>
            <value>
                <fullName>Less than 33% within 5 days</fullName>
            </value>
            <value>
                <fullName>Less than 45% within 7 days</fullName>
            </value>
            <value>
                <fullName>Less than 75% within 10 days</fullName>
            </value>
            <value>
                <fullName>Less than 90% within 21 days</fullName>
            </value>
            <value>
                <fullName>Initial Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FEC_Task_Creation_Rule__mdt/fields/taskTypeDefault__c.field-meta.xml
<CustomField>
    <fullName>taskTypeDefault__c</fullName>
    <label>taskTypeDefault</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student Progress</fullName>
                <default>true</default>
                <label>Student Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_FECTaskCreationTest.cls
/**
 * 2020-05-29 added test class for #US169194  (Mark Membrino)
 * Code coverage: Batch_FECTaskCreation (100%)
 */
@isTest(SeeAllData=false)
public class Batch_FECTaskCreationTest {

    public static final String MISSING_RULES_ERROR_MESSAGE = 'Missing required FEC Task Creation Setting: Found zero records for FEC_Task_Creation_Rule__mdt';

    @TestSetup 
    static void setup() {

        // Create institution Account
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());

        // Create a account with 'Academic Program' record type
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, currentSchoolYear.Id);
        academicProgram.Registration_End_Date__c=Date.today().addMonths(1);
        academicProgram.Registration_Start_Date__c=Date.newInstance(2017,11,11);
        academicProgram.Confirmation_End_Date__c = Date.today().addMonths(1);
        update academicProgram;

        // Create a Contact with 'Caretaker' record type
        Contact careTakerContact = Peak_TestUtils.createTestContact('Caretaker', institutionAccount.Id);
        User careTaker = Peak_TestUtils.CreatePortalCaretTakerUser(careTakerContact.Id);
        Id careTakerEnrollmentType = Schema.SObjectType.hed__Program_Enrollment__c.getRecordTypeInfosByName().get('Caretaker').getRecordTypeId();
        hed__Program_Enrollment__c careTakerEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, careTaker.ContactId, currentSchoolYear.Id, false);
        careTakerEnrollment.RecordTypeId = careTakerEnrollmentType;
        insert careTakerEnrollment;

        // Create a contact with 'Students' record type
        Contact contact = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);

        // Create STUDENT PE
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, currentSchoolYear.Id, false);
        progEnrollment.Status__c=Batch_FECTaskCreation.PE_STATUS;
        insert progEnrollment;

        // Create EnrollmentSupport Case for the student PE
        Case esCase = createCase(progEnrollment.Id, institutionAccount.Id, careTakerContact.Id, true);

        // MISC...
        User u = [SELECT Id,ContactId FROM User WHERE ContactId != NULL AND IsActive = TRUE LIMIT 1];
        hed__Relationship__c  relationship = Peak_TestUtils.createRelationship(u.ContactId, contact.Id, true);


        // Create ECs with different record type
        List < Enrollment_Component__c > componentList = new List < Enrollment_Component__c > ();
        Enrollment_Component__c stageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Stage', false);
        Enrollment_Component__c processComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Process', false);
        Enrollment_Component__c questionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        Enrollment_Component__c sectionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Section', false);
        Enrollment_Component__c formComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Form', false);
        Enrollment_Component__c messageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Message', false);
        Enrollment_Component__c documentComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Document', false);
        componentList.add(stageComponent);
        componentList.add(processComponent);
        componentList.add(questionComponent);
        componentList.add(sectionComponent);
        componentList.add(formComponent);
        componentList.add(messageComponent);
        componentList.add(documentComponent);
        insert componentList;
        
        // create Enrollment Component Relationships with different parent Enrollment Components.
        Enrollment_Component_Relationship__c enrollCompRelationship = Peak_TestUtils.createEnrollmentComponentRelationship(stageComponent.Id, processComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship2 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponent.Id, sectionComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship3 = Peak_TestUtils.createEnrollmentComponentRelationship(formComponent.Id, stageComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship4 = Peak_TestUtils.createEnrollmentComponentRelationship(messageComponent.Id, formComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship5 = Peak_TestUtils.createEnrollmentComponentRelationship(sectionComponent.Id, formComponent.Id);

        // create Enrollment Component Affiliations with different parent Enrollment Components.
        Enrollment_Component_Affiliation__c affiliationForm = createEnrollmentComponentAffiliation(progEnrollment.Id, formComponent.Id);
        Enrollment_Component_Affiliation__c affiliationForm2 = createEnrollmentComponentAffiliation(progEnrollment.Id, formComponent.Id);
        Enrollment_Component_Affiliation__c affiliationForm3 = createEnrollmentComponentAffiliation(progEnrollment.Id, formComponent.Id);
        Enrollment_Component_Affiliation__c affiliationStage = createEnrollmentComponentAffiliation(progEnrollment.Id, stageComponent.Id);
        Enrollment_Component_Affiliation__c affiliationSection = createEnrollmentComponentAffiliation(progEnrollment.Id, sectionComponent.Id);
        Enrollment_Component_Affiliation__c affiliationDocument = createEnrollmentComponentAffiliation(progEnrollment.Id, documentComponent.Id);
        Enrollment_Component_Affiliation__c affiliationProcess = createEnrollmentComponentAffiliation(progEnrollment.Id, processComponent.Id);
        Enrollment_Component_Picklist_Option__c picklistOption = Peak_TestUtils.createEnrollmentComponentPicklistOption(questionComponent.Id, true);
        List<Enrollment_Component_Affiliation__c> ecas = new List<Enrollment_Component_Affiliation__c>();
        ecas.add(affiliationForm);
        ecas.add(affiliationForm2);
        ecas.add(affiliationForm3);
        ecas.add(affiliationStage);
        ecas.add(affiliationSection);
        ecas.add(affiliationDocument);
        ecas.add(affiliationProcess);
        insert ecas;
    }

    /**
     *  test to verify creation of Task for rule qualifiying PE/Cases
     * */    
    static testMethod void Batch_FECTaskCreationPositiveTest() {

        // get the FEC Task Creation Rules
        List<FEC_Task_Creation_Rule__mdt> fecTaskCreationRules = Batch_FECTaskCreation.getTaskCreationRules();
        FEC_Task_Creation_Rule__mdt currentRule = fecTaskCreationRules[0];

        if (fecTaskCreationRules.size()==0)
            throw new Batch_FECTaskCreation.FECTaskCreationException(MISSING_RULES_ERROR_MESSAGE);

        // get PE
        hed__Program_Enrollment__c progEnrollment = 
            [SELECT Id FROM hed__Program_Enrollment__c WHERE RecordTypeId 
                = :Batch_FECTaskCreation.STUD_PE_RECORD_TYPE_ID ORDER BY CreatedDate DESC LIMIT 1];
        
        // get case
        Case c = [SELECT Id from Case LIMIT 1];
                
        // Move the createdDate back as per current rule
        Datetime newCreatedDate = datetime.now().addDays((Integer)(-1 * currentRule.lowerLimitInDays__c));
        Test.setCreatedDate(progEnrollment.Id, newCreatedDate);

        // verify CreatedDate is set as expected
        progEnrollment = refreshPE(progEnrollment.Id);
        System.assertEquals(newCreatedDate, progEnrollment.CreatedDate);
    
        Test.startTest();
            Batch_FECTaskCreation taskCreationBatch = new Batch_FECTaskCreation();
            Database.executeBatch(taskCreationBatch);
        Test.stopTest();

        // get Task for the given Case
        c = refreshCase(c.Id);
        Task tsk = [Select Id, CreatedDate, Subject, RecordTypeId, Type, SubType__c, OwnerId from Task where whatId = :c.Id LIMIT 1];

        // assertions/verification
        System.assertEquals(label.Household_Pool_Queue_ID, tsk.OwnerId);
        System.assertEquals(Batch_FECTaskCreation.NEW_TASK_RECORD_ID, tsk.RecordTypeId);
        System.assertEquals(currentRule.taskTypeDefault__c, tsk.Type);
        System.assertEquals(currentRule.taskSubTypeDefault__c, tsk.SubType__c);
    }

    /**
    *  test to verify NO NEW task get created for existing task for the same rule.
    * */    
    static testMethod void Batch_FECTaskCreationPositiveTest2() {

        // get the FEC Task Creation Rules
        List<FEC_Task_Creation_Rule__mdt> fecTaskCreationRules = Batch_FECTaskCreation.getTaskCreationRules();
        FEC_Task_Creation_Rule__mdt currentRule = fecTaskCreationRules[2];

        if (fecTaskCreationRules.size()==0)
            throw new Batch_FECTaskCreation.FECTaskCreationException(MISSING_RULES_ERROR_MESSAGE);

        // get PE
        hed__Program_Enrollment__c progEnrollment = 
            [SELECT Id FROM hed__Program_Enrollment__c WHERE RecordTypeId 
                = :Batch_FECTaskCreation.STUD_PE_RECORD_TYPE_ID ORDER BY CreatedDate DESC LIMIT 1];
        
        // get case
        Case c = [SELECT Id from Case LIMIT 1];
                
        // Move the createdDate back as per current rule
        // Integer moveInDays = (Integer)(-1 * currentRule.lowerLimitInDays__c); 
        Datetime newCreatedDate = datetime.now().addDays((Integer)(-1 * currentRule.lowerLimitInDays__c));
        Test.setCreatedDate(progEnrollment.Id, newCreatedDate);

        // verify CreatedDate is set as expected
        progEnrollment = refreshPE(progEnrollment.Id);
        System.assertEquals(newCreatedDate, progEnrollment.CreatedDate);

        Test.startTest();
            // run the batch 1st time: 
            Batch_FECTaskCreation taskCreationBatch = new Batch_FECTaskCreation();
            Database.executeBatch(taskCreationBatch);

            // run the batch 2nd time: 
            Batch_FECTaskCreation taskCreationBatch2 = new Batch_FECTaskCreation();
            Database.executeBatch(taskCreationBatch2);
        Test.stopTest();

        // get Task for the given Case
        c = refreshCase(c.Id);
        List<Task> tsks = [Select Id, CreatedDate, Subject, RecordTypeId, Type, SubType__c, OwnerId from Task where whatId = :c.Id];

        // assertions/verification
        System.assertEquals(1, tsks.size());

    }

    /**
    *  test to verify NO task is created for Case/PE that does not meet any rule criteria.
    * */    
    static testMethod void Batch_FECTaskCreationNegativeTest() {

        // get the FEC Task Creation Rules
        List<FEC_Task_Creation_Rule__mdt> fecTaskCreationRules = Batch_FECTaskCreation.getTaskCreationRules();
        FEC_Task_Creation_Rule__mdt currentRule = fecTaskCreationRules[0];

        if (fecTaskCreationRules.size()==0)
            throw new Batch_FECTaskCreation.FECTaskCreationException(MISSING_RULES_ERROR_MESSAGE);

        // get PE
        hed__Program_Enrollment__c progEnrollment = 
            [SELECT Id FROM hed__Program_Enrollment__c WHERE RecordTypeId 
                = :Batch_FECTaskCreation.STUD_PE_RECORD_TYPE_ID ORDER BY CreatedDate DESC LIMIT 1];
        
        // get case
        Case c = [SELECT Id from Case LIMIT 1];
                
        // Move the createdDate back as per current rule
        // Integer moveInDays = (Integer)(-1 * currentRule.lowerLimitInDays__c);
        Datetime newCreatedDate = datetime.now();
        Test.setCreatedDate(progEnrollment.Id, newCreatedDate);

        // verify CreatedDate is set as expected
        progEnrollment = refreshPE(progEnrollment.Id);
        System.assertEquals(newCreatedDate, progEnrollment.CreatedDate);
    
        Test.startTest();
            Batch_FECTaskCreation taskCreationBatch = new Batch_FECTaskCreation();
            Database.executeBatch(taskCreationBatch);
        Test.stopTest();

        // get Task for the given Case
        c = refreshCase(c.Id);
        List<Task> tsks = [Select Id, CreatedDate, Subject, RecordTypeId, Type, SubType__c, OwnerId from Task where whatId = :c.Id];

        // assertions/verification
        System.assertEquals(0, tsks.size());
    }

    /**
    *  test for scheduled run.
    * */    
    static testMethod void testSchedule() {
        Test.StartTest();
            Batch_FECTaskCreation schClass = new Batch_FECTaskCreation();
            String sch = '0 0 23 * * ?'; 
            system.schedule('Test FEC Task Creation Scheduled run', sch, schClass); 
        Test.stopTest(); 
    }

    public static Case createCase(Id peId, Id accID, Id conId, Boolean isInsert) {
        Case c = new Case();
        c.AccountId = accID; //caretaker.Contact.AccountId;
        c.ContactId = conId; //caretaker.ContactId; 
        c.Origin = 'Enrollment Community';
        c.Type = 'Enrollment Assistance';
        c.Ticket_Type__c='New Applicant Call';
        c.Platform__c = 'Pearson Connexus';
        c.Description = 'New Applicant Call';
        c.Program_Enrollment__c = peId; //newStudentEnrollment.Id;
        c.Subject = 'Initial Call';
        c.RecordTypeId = Batch_FECTaskCreation.CASE_RECORD_ID;

        if(isInsert) insert c;
        return c;
    }

    public static Enrollment_Component_Affiliation__c createEnrollmentComponentAffiliation(String programEnrollmentId, String componentId) {

        Enrollment_Component_Affiliation__c compAffiliation = new Enrollment_Component_Affiliation__c();
        compAffiliation.Status__c = 'Not Started';
        compAffiliation.Program_Enrollment__c = programEnrollmentId;
        compAffiliation.Enrollment_Component__c = componentId;
        return compAffiliation;
    }

    public static hed__Program_Enrollment__c refreshPE(Id peId) {
        return [SELECT Id, Name, Status__c, Total_Forms__c, Total_Forms_Completed__c, Percent_Complete__c, CreatedDate, Date_Today__c
                FROM hed__Program_Enrollment__c
                WHERE Id = :peID];
    }

    public static Case refreshCase(Id caseId) {
        return [SELECT  Id, OwnerId, Owner.Type, RecordTypeId, Program_Enrollment__c
                FROM Case 
                WHERE Id = :caseId];
    }
    
}