force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Electives_Exclude_from_Auto_Course_Sel__c.field-meta.xml
<CustomField>
    <fullName>Electives_Exclude_from_Auto_Course_Sel__c</fullName>
    <description>Electives Exclude from Auto Course Selection</description>
    <label>Electives Exclude from Auto Course Sel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Art</fullName>
            </value>
            <value>
                <fullName>Educational Technology</fullName>
            </value>
            <value>
                <fullName>Health and Physical Education 8</fullName>
            </value>
            <value>
                <fullName>Home Life</fullName>
            </value>
            <value>
                <fullName>Middle School Career Exploration I</fullName>
            </value>
            <value>
                <fullName>Middle School Digital Art and Design</fullName>
            </value>
            <value>
                <fullName>Middle School Journalism</fullName>
            </value>
            <value>
                <fullName>Middle Sign Language</fullName>
            </value>
            <value>
                <fullName>Middle Spanish</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Theater</fullName>
            </value>
            <value>
                <fullName>WebQuest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Student_Information__c.object
<CustomObject>
    <description>Student data that is specific to a school year is stored on the Annual Student Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Student Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>Exclude_AutoCourse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude from Automatic Course Selection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment record for the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Annual Student Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Student Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement_and_Elective__c.object
<CustomObject>
    <description>The Placement and Elective Request object stored course requests made  by the caretaker during the enrollment process.</description>
    <fields>
        <fullName>Course_Requested__c</fullName>
        <description>Select the elective choice your student is interested in taking</description>
        <label>Course Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Educational Technology and Online Learning</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Business Keyboarding</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Digital Arts</fullName>
                </value>
                <value>
                    <fullName>Sign Language</fullName>
                </value>
                <value>
                    <fullName>Webquest</fullName>
                </value>
                <value>
                    <fullName>Discovering Music I (3-5)</fullName>
                </value>
                <value>
                    <fullName>Discovering Music II (3-5)</fullName>
                </value>
                <value>
                    <fullName>Discovering Music III (3-5)</fullName>
                </value>
                <value>
                    <fullName>Experiencing Music I (K-2)</fullName>
                </value>
                <value>
                    <fullName>Experiencing Music II (K-2)</fullName>
                </value>
                <value>
                    <fullName>Experiencing Music III (K-2)</fullName>
                </value>
                <value>
                    <fullName>Exploring Music I (6-8)</fullName>
                </value>
                <value>
                    <fullName>Exploring Music II (6-8)</fullName>
                </value>
                <value>
                    <fullName>Exploring Music III (6-8)</fullName>
                </value>
                <value>
                    <fullName>No music course required</fullName>
                </value>
                <value>
                    <fullName>Art History A</fullName>
                </value>
                <value>
                    <fullName>Concepts of Engineering and Technology</fullName>
                </value>
                <value>
                    <fullName>Digital Photography I A</fullName>
                </value>
                <value>
                    <fullName>Emergent Computer Technology</fullName>
                </value>
                <value>
                    <fullName>French I A</fullName>
                </value>
                <value>
                    <fullName>French II A</fullName>
                </value>
                <value>
                    <fullName>French IV A</fullName>
                </value>
                <value>
                    <fullName>Game Design I A</fullName>
                </value>
                <value>
                    <fullName>German I A</fullName>
                </value>
                <value>
                    <fullName>German II A</fullName>
                </value>
                <value>
                    <fullName>Introduction to Graphic Design A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_Requested__c</fullName>
        <description>English level</description>
        <label>Course Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Advanced Placement</fullName>
                </value>
                <value>
                    <fullName>Honors</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Dual Diploma</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment Record of the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipName>Placement_and_Elective_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course History and Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Placement and Elective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course History and Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_PlacementAndElectiveBusinessLogic.cls
/**
* Created by Anushka on 19-12-2018.
* Purpose : BusinessLogic class for PlacementAndElectiveTrigger called by PlacementAndElectiveHandler.
*/

public class NES_PlacementAndElectiveBusinessLogic {
    private static Peak_ApexLog logger = new Peak_ApexLog('PlacementAndElectiveBusinessLogic');
    
    /**
* Created By Anushka on 12/18/2018
* purpose is to call the calculateLTS method in the NES_BusinessLogicUtils class after Update.
*/
    
    public static void calculateLTS_Update(Map<Id, Placement_and_Elective__c> oldMap, Map<Id, Placement_and_Elective__c> newMap) {
        Set<Id> programEnrollmentIds = new Set<Id>();
        for (Placement_and_Elective__c pne : newMap.values()) {
            if (pne.Level_Requested__c != oldMap.get(pne.Id).Level_Requested__c ||
                pne.Course_Requested__c != oldMap.get(pne.Id).Course_Requested__c)
                programEnrollmentIds.add(pne.Program_Enrollment__c);
        }
        
        List<hed__Program_Enrollment__c> programEnrollments = NES_LTSUtility.calculateLTS(programEnrollmentIds);
        try {
            update programEnrollments;
        } catch(Exception e) {
            logger.logException('calculateLTS_Update', e);
            logger.saveLogs();
            throw e;
        }
    }
    
    /**
* Created By Anushka on 12/18/2018
* purpose is to call the calculateLTS method in the NES_BusinessLogicUtils class after Insert.
*/
    
    public static void calculateLTS_Insert(List<Placement_and_Elective__c> newList) {
        Set<Id> programEnrollmentIds = new Set<Id>();
        for (Placement_and_Elective__c pne : newList) {
            if (pne.Level_Requested__c != null || pne.Course_Requested__c != null) {
                programEnrollmentIds.add(pne.Program_Enrollment__c);
            }
        }
        
        List<hed__Program_Enrollment__c> programEnrollments = NES_LTSUtility.calculateLTS(programEnrollmentIds);
        try {
            update programEnrollments;
        } catch(Exception e) {
            logger.logException('calculateLTS_Insert', e);
            logger.saveLogs();
            throw e;
        }
    }
  /* commented as this is commented in handler too by Alex   
    public static void shouldRunPlacement(List<Placement_and_Elective__c> newList, Map<Id, Placement_and_Elective__c> oldMap) {
        
        List<Id> programEnrollmentIds = new List<Id>();
        for(Placement_and_Elective__c pe : newList) {
            Placement_and_Elective__c oldPe = oldMap.get(pe.Id);
            if(pe.Level_Requested__c != oldPe.Level_Requested__c) {
                programEnrollmentIds.add(pe.Program_Enrollment__c);
            }
        }
        
        if(programEnrollmentIds.size() > 0) {
            
            List<Annual_Student_Information__c> asis = [SELECT Id, Program_Enrollment__c FROM Annual_Student_Information__c WHERE Program_Enrollment__c IN : programEnrollmentIds];
            NES_AnnualStudentInfoBusinessLogic.verifyAffiliationsComplete(asis);
        }
    }*/
    
/* Start -Added by anitha p for US 117571 (Task # 118636) on 15/11/2019
* Purpose : Added exclude auto course logic for ASI record for US 117571 (Task # 118636)
*/
    public static void excludeAutoCourseFromASI(List<Placement_and_Elective__c> newList) {
        Set<Id> programEnrollmentIds = new Set<Id>();
        map<id,string> placementandElec = new map<id,string>();
        map<id,id> placmenttope = new map<id,id>();
        //get Placement and Elective ID's
        for (Placement_and_Elective__c pne : newList) {
            if (pne.Course_Requested__c != null) {
                programEnrollmentIds.add(pne.Program_Enrollment__c);
                placementandElec.put(pne.id, pne.Course_Requested__c );
                placmenttope.put( pne.Program_Enrollment__c,pne.id);
            }
        }

        
        //Update ASI records Exclude_AutoCourse__c comparing Account's Electives_Exclude_from_Auto_Course_Sel__c values with Placement and electives's Course_Requested__c
        List<Annual_Student_Information__c> asiList = new List<Annual_Student_Information__c>();
        
        list<string> pickValues = new list<string> ();
        for (Annual_Student_Information__c asi:[select ID ,Program_Enrollment__c,Exclude_AutoCourse__c,Program_Enrollment__r.hed__Account__r.Electives_Exclude_from_Auto_Course_Sel__c from Annual_Student_Information__c
                                                where Program_Enrollment__c in :programEnrollmentIds ]){
                                                    if ( asi.Exclude_AutoCourse__c!= true){
                                                        if(!placementandElec.isEmpty()&&!placmenttope.isEmpty()){
                                                            if(placmenttope.containskey(asi.Program_Enrollment__c) && asi.Program_Enrollment__r.hed__Account__r.Electives_Exclude_from_Auto_Course_Sel__c != null)		{
                                                                pickValues = asi.Program_Enrollment__r.hed__Account__r.Electives_Exclude_from_Auto_Course_Sel__c.split(';');
                                                                if(pickValues.size()>0 && pickValues.contains(placementandElec.get(placmenttope.get(asi.Program_Enrollment__c)))){ 
                                                                    asi.Exclude_AutoCourse__c = true;
                                                                    asiList.add(asi);
                                                                    pickValues.clear();
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
        
        try {
            update asiList;
        } catch(Exception e) {
            logger.logException('exclude_AutoCourse_Insert', e);
            logger.saveLogs();
            throw e;
        }
    }           
    // End -added by anitha p for US 117571 (Task # 118636)
}