force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Confirmation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_End_Date__c</fullName>
    <description>The date/time that final confirmation stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to the Contact records with the Caretaker Record type.It is being used by the student Record Types of Contact</description>
        <label>Caretaker Id</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Caretaker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <displayFormat>S-{00000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade_Level__c.object
<CustomObject>
    <description>The grade level object stores grade level information for connection to Academic Programs and Caps.</description>
    <label>Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Student_ID__c.field-meta.xml
<CustomField>
    <fullName>Student_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Student ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caretaker Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Reactivation_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who executed the last full reactivation</description>
        <label>Full Reactivation User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Student Id)</relationshipLabel>
        <relationshipName>Opportunities_Stdnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_OtherSchoolEnrollmentHelperTest.cls
@IsTest
public class NES_OtherSchoolEnrollmentHelperTest {
@TestSetup
    static void setup(){
        //Create Educational Institutional Account i.e.., Parent Account
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        
        //Insert the School Year record
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());
        
        // Create a Contact with 'Caretaker' record type
        Contact careTakerContact = Peak_TestUtils.createTestContact('Caretaker', institutionAccount.Id);
        
        //Create a care taker user for community
        User careTaker = Peak_TestUtils.CreatePortalCaretTakerUser(careTakerContact.Id);
        
        
        //Create Academic Program Account i.e.., Child Account
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
        academicProgram.Registration_Start_Date__c = System.today().addDays(-10);
        academicProgram.Registration_End_Date__c = System.today().addDays(10);
        // academicProgram.OwnerId=institutionAccount.OwnerId;
        update academicProgram;
        
        
        
        
        
        
        //Create a enrollment for the CareTaker Contact i.e..,House Hold Enrollment
        Id careTakerEnrollmentType = Schema.SObjectType.hed__Program_Enrollment__c.getRecordTypeInfosByName().get('Caretaker').getRecordTypeId();
        hed__Program_Enrollment__c careTakerEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, careTaker.ContactId, schoolYear.Id, false);
        careTakerEnrollment.RecordTypeId = careTakerEnrollmentType;
        insert careTakerEnrollment;
        
        
        // Create a Contact with 'Students' record type
        Contact student = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);
        student.Caretaker_Id__c = careTakerContact.Id;
        update student;
        //Create a relationship between the User Contact and Student Contact
        hed__Relationship__c  relationship = Peak_TestUtils.createRelationship(careTaker.ContactId, student.Id, true);
        
        //Create a student enrollment with House Hold Enrollment
        Id studentEnrollmentType = Schema.SObjectType.hed__Program_Enrollment__c.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        hed__Program_Enrollment__c studentEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, student.Id, schoolYear.Id, false);
        studentEnrollment.RecordTypeId = studentEnrollmentType;
        studentEnrollment.Program_Enrollment__c = careTakerEnrollment.Id; 
        //studentEnrollment.hed__Contact__r.Caretaker_Id__c = careTakerContact.Id;
        insert studentEnrollment;
        
        Grade_Level__c gradeLevel = Peak_TestUtils.createGradeLevel('Test',true);
        Program_Grade_Level__c programGradeLevel = Peak_TestUtils.createProgramGradeLevel('Test', academicProgram.Id, gradeLevel.Id,Datetime.now(), true);
        Opportunity oppToInsert = new Opportunity();
        oppToInsert.Name = 'test opportunity';
        oppToInsert.OwnerId = careTaker.Id;
        oppToInsert.Caretaker_Id__c = careTaker.ContactId;
        oppToInsert.Student_Id__c = student.Id;
        oppToInsert.AccountId = student.AccountId;
        oppToInsert.Program_Enrollment__c = studentEnrollment.Id;
        oppToInsert.StageName = 'Closed Lost';
        oppToInsert.CloseDate = academicProgram.Confirmation_End_Date__c == null ? Date.today() : academicProgram.Confirmation_End_Date__c.date();
        insert oppToInsert;
    }

    static testMethod void unitTesting() {
        User careTaker = [SELECT Id, ContactId FROM User WHERE Username = 'portalUser@gmail.com'];
        Contact studentid=[select id,AccountId,firstName,middleName,lastName from Contact WHERE RecordType.name='Students' limit 1];
        Account institutionalAccount = [SELECT Id,Name FROM Account WHERE RecordType.Name = 'Educational Institution' LIMIT 1];
        Account academicProgram = [SELECT Id,name, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c FROM Account
                                   WHERE RecordType.Name = 'Academic Program' LIMIT 1];
        
        
        Grade_Level__c gradeLevel=[select id,name from Grade_Level__c where name ='test' limit 1];
        
        System.debug('academicProgram++'+academicProgram);
        List<School_Year__c> schoolYears = [SELECT Id,name FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        
        //Create a student enrollment for the CareTaker Contact
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, careTaker.ContactId, schoolYears[0].Id, true);
        hed__Program_Enrollment__c progEnrollment2 = [SELECT id,(SELECT Id,StageName FROM Opportunities__r)
                                                        FROM hed__Program_Enrollment__c WHERE Id = :progEnrollment.Id];
        List<Opportunity> oppo = progEnrollment2.Opportunities__r;
        //////////////
        //
        Test.startTest(); 
        NES_OtherSchoolEnrollmentHelper.getSchoolsToAttend(studentid.Id);  
        NES_OtherSchoolEnrollmentHelper.getSchoolYears(institutionalAccount.Name);  
        NES_OtherSchoolEnrollmentHelper.getGradeLevels(institutionalAccount.Name,  schoolYears[0].Name);
        NES_OtherSchoolEnrollmentHelper.otherSchoolEnrollment(studentid.Id,institutionalAccount.Name,  schoolYears[0].Name,gradeLevel.Name,'application',true);  
        Test.stopTest();
        
        
    }
}