force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <displayFormat>C-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Document_Status_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Document type identifier</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/DocumentsUpdateService_Test.cls
//Swapna:Test class for Documents Update service
@isTest
public class DocumentsUpdateService_Test{
       
    @isTest
    Public static void DocumentsUpdateRequestTest()
    {
        DocumentsUpdateService.DocumentsUpdateRequest Docreq = new DocumentsUpdateService.DocumentsUpdateRequest();
        Docreq.contactId ='0030n00000i6VQQAA2';
        Docreq.docType = '504 Plan';
        Docreq.schoolId = '0010n000010QglXAAS';
        Docreq.schoolYearId = '2019-2020';
        Docreq.filePaths = new List<String>();
        Docreq.filePaths.add('123.jpg');
        Docreq.filePaths.add('456.jpg');
    }
    
   @isTest
    Public static void updateDocRefTest()
    {
         Test.startTest();
        Account houseHoldAccount = Peak_TestUtils.createAccountRecord('Testy5', 'Household'); 
        Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        Contact TestContact = Peak_TestUtils.createTestContact();
      //  Contact c = [select contact_Id__c from Contact where Id =:TestContact.Id];
        String conId = TestContact.Id;
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('2018-2019', System.today());
        Account academicAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id, schlYear.Id);
        hed__Program_Enrollment__c ProgramEnrollmentTest = Peak_TestUtils.createProgramEnrollment(academicAccount.Id, TestContact.Id, schlYear.Id, true);
        Enrollment_Document__c enrollmentDocument1 = Peak_TestUtils.createEnrollmentDocumentRecord(ProgramEnrollmentTest.id);
        enrollmentDocument1.Type__c = '504 Plan';
        enrollmentDocument1.Status_Reason__c = 'Submitted';
        update enrollmentDocument1;
        DocumentsUpdateService.DocumentsUpdateRequest Docreq = new DocumentsUpdateService.DocumentsUpdateRequest();
        Docreq.contactId =TestContact.Id;
        Docreq.docType = '504 Plan';
        Docreq.schoolId = parentAccount.Id;
        Docreq.schoolYearId = '2018-2019';
        Docreq.filePaths = new List<String>();
        Docreq.filePaths.add('123.jpg');
        Docreq.filePaths.add('456.jpg');
        String jsonBody = JSON.serialize(Docreq);
       // String JsonBody = '{"contactId":"C-00040","schoolYearId":"2018-2019","schoolId":"0550","docType":"504 Plan","filePaths":["123.jpg","456.jpg"]}';
       
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI ='/services/apexrest/DocsInfo/';
        req.requestBody = Blob.valueOf(jsonBody);
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;
        DocumentsUpdateService.updateDocRef();
               Test.stopTest();
    }    
    
    @isTest
    Public static void updateDocRefTest2()
    {
         Test.startTest();
        Account houseHoldAccount = Peak_TestUtils.createAccountRecord('Testy5', 'Household'); 
        Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        Contact TestContact = Peak_TestUtils.createTestContact();
       // Contact c = [select contact_Id__c from Contact where Id =:TestContact.Id];
      //  String conId = TestContact.Id;
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('2018-2019', System.today());
        Account academicAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id, schlYear.Id);
        hed__Program_Enrollment__c ProgramEnrollmentTest = Peak_TestUtils.createProgramEnrollment(academicAccount.Id, TestContact.Id, schlYear.Id, true);
        Enrollment_Document__c enrollmentDocument1 = Peak_TestUtils.createEnrollmentDocumentRecord(ProgramEnrollmentTest.id);
        enrollmentDocument1.Type__c = '504 Plan';
        enrollmentDocument1.Status_Reason__c = 'Submitted';
        update enrollmentDocument1;
        DocumentsUpdateService.DocumentsUpdateRequest Docreq = new DocumentsUpdateService.DocumentsUpdateRequest();
        Docreq.contactId =TestContact.Id;
        Docreq.docType = 'Choice Transfer Form';
        Docreq.schoolId = parentAccount.Id;
        Docreq.schoolYearId = '2018-2019';
        Docreq.filePaths = new List<String>();
        Docreq.filePaths.add('123.jpg');
        Docreq.filePaths.add('456.jpg');
        String jsonBody = JSON.serialize(Docreq);
       // String JsonBody = '{"contactId":"C-00040","schoolYearId":"2018-2019","schoolId":"0550","docType":"504 Plan","filePaths":["123.jpg","456.jpg"]}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI ='/services/apexrest/DocsInfo/';
        req.requestBody = Blob.valueOf(jsonBody);
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;
        DocumentsUpdateService.updateDocRef();
        Test.stopTest();
    }    
    
      
      

}