force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Use_Updated_ECA_Process__c.field-meta.xml
<CustomField>
    <fullName>Use_Updated_ECA_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created by Mark Membrino while rewriting the ECA processing.</description>
    <label>Use Updated ECA Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/V2_External_ID__c.field-meta.xml
<CustomField>
    <fullName>V2_External_ID__c</fullName>
    <description>external account id for the pcx environment. to prevent data issues and facilitate indexing, setting to Unique.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>V2 External ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>V2_External_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>V2 External ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Field__c</fullName>
        <description>The API name of the object-field combination being used on the right side of the criteria comparison. This field should be populated if you are comparing the left side field to the value of another field. Example. Account.Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Field (Left)</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic program associated with the component. This is exclusively used by components with a record type of Process to create a relationship between the account entity and it&apos;s required components. As the child components of the process could be used by multiple processes, there is not a direct relationship between them and a specific academic program and those relationships are inferred from their parent process.</description>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enrollment Components (Academic Program)</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Type__c</fullName>
        <description>Indicator of whether or not the criteria is used as part of eligibility screening.</description>
        <label>Criteria Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ineligibility</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Completion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The criteria being associated to the Enrollment Component.</description>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Enrollment Component Criteria</relationshipLabel>
        <relationshipName>Enrollment_Component_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Component__c</fullName>
        <description>The parent enrollment component for the component criteria.</description>
        <label>Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Enrollment Component Criteria</relationshipLabel>
        <relationshipName>Enrollment_Component_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Criteria</label>
    <nameField>
        <displayFormat>ECC-{000}</displayFormat>
        <label>Enrollment Component Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Date_Today__c.field-meta.xml
<CustomField>
    <fullName>Date_Today__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Today</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Enrollment</fullName>
                <default>true</default>
                <label>Initial Enrollment</label>
            </value>
            <value>
                <fullName>Re-enrolling student</fullName>
            </value>
            <value>
                <fullName>Returning Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Initial_ECA_Creation_Complete__c.field-meta.xml
<CustomField>
    <fullName>Initial_ECA_Creation_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by the new student creation process to allow the creation of all the ECAs to be async.  When the Caretaker creates the student this will be false.  An async job that creates the ECAs will mark check this when it completes.</description>
    <label>Initial ECA Creation Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NES_Batch_TimeCriteria.cls
/**
 * Created by triciaigoe on 1/16/19.
 *  Revision History
 *  Added V2_External_ID__c in query line 66 as the runAssignment method needs V2_External_ID__c field in logic DEF255843(Jagadish Babu)
 */

global with sharing class NES_Batch_TimeCriteria implements DataBase.Batchable<SObject>, Schedulable {

    global NES_Batch_TimeCriteria() {

    }

    // Find all the current in progress program enrollments for evaluation
    // MM 9/23/2020  Added an additional check to the query to only retrieve PEs that have had all their ECAs created. (using Initial_ECA_Creation_Complete__c)
    global List<SObject> start(Database.BatchableContext BC){
        List<hed__Program_Enrollment__c> programEnrollments = [SELECT Id, hed__Account__r.Use_Updated_ECA_Process__c FROM hed__Program_Enrollment__c WHERE Status__c = 'In Progress' AND RecordType.Name = 'Student'  and Initial_ECA_Creation_Complete__c = true ];
        return programEnrollments;

        // List<hed__Program_Enrollment__c> programEnrollments = [
        //     SELECT Id, hed__Account__r.Use_Updated_ECA_Process__c 
        //     FROM    hed__Program_Enrollment__c 
        //     WHERE   Status__c = 'In Progress' AND 
        //             RecordType.Name = 'Student'  and Initial_ECA_Creation_Complete__c = true AND
        //             hed__Account__r.Use_Updated_ECA_Process__c = true
        // ];
        // return programEnrollments;
    }


    // Evaluate whether to run completion and then run it
    global void execute(Database.BatchableContext BC, List<SObject> scope) {

        Set<Id> programEnrollmentIds = new Set<Id>();  //Old ECA model PEs
        Set<Id> programEnrollmentIdsNewECAModel = new Set<Id>();  //New ECA model PEs
        for(SObject programEnrollment : scope) {
            if ( ((hed__Program_Enrollment__c) programEnrollment).hed__Account__r.Use_Updated_ECA_Process__c == true)
                programEnrollmentIdsNewECAModel.add(programEnrollment.Id);
            else 
                programEnrollmentIds.add(programEnrollment.Id);
        }
        
        if (programEnrollmentIdsNewECAModel.size() > 0) {
            List<EvaluationUtils.fieldUpdate> fieldUpdateList = new List<EvaluationUtils.fieldUpdate> ();

            for (id peID: programEnrollmentIdsNewECAModel ) {
                //Add a record for to force the calculation of fields that are based on today's date.
                EvaluationUtils.fieldUpdate newFieldUpdate = new EvaluationUtils.fieldUpdate ();
                newFieldUpdate.programEnrollmentId = peID;
                newFieldUpdate.objectAndFieldName = 'hed__program_enrollment__c.date_today__c';
                newFieldUpdate.newValue = System.today();
                fieldUpdateList.add(newFieldUpdate);
            }

            EvaluationUtils.evaluateChangedFields  (fieldUpdateList);
        }

        if (programEnrollmentIds.size() > 0) {   //Must be some PEs in the batch using the old ECA model.

            //Collect the data you need.
            Map<Id,List<Enrollment_Component_Affiliation__c>> progEnrollECAListMap = new Map<Id,List<Enrollment_Component_Affiliation__c>> ();
            for ( Enrollment_Component_Affiliation__c affiliation : [SELECT Id, Enrollment_Component__c, Program_Enrollment__c, Status__c, Enrollment_Component__r.RecordType.Name
                                                                        FROM Enrollment_Component_Affiliation__c
                                                                        WHERE Program_Enrollment__c in :programEnrollmentIds]) {
                if (!progEnrollECAListMap.containsKey(affiliation.Program_Enrollment__c)){
                    list <Enrollment_Component_Affiliation__c> ecas = new List<Enrollment_Component_Affiliation__c> ();
                    ecas.add(affiliation);
                    progEnrollECAListMap.put(affiliation.Program_Enrollment__c, ecas);
                } else
                    progEnrollECAListMap.get(affiliation.Program_Enrollment__c).add(affiliation);
            }
        
            map<Id,hed__Program_Enrollment__c> EnrollmentsMap = new map<Id,hed__Program_Enrollment__c>();
            Set<Id> acedemicProgramsReferenced = new Set<Id> ();

            for (hed__Program_Enrollment__c pe : [SELECT Id, hed__Account__c, hed__Contact__c, hed__Contact__r.RecordType.Name, Enrollment_Type__c,
                            Household_Program_Enrollment__c,V2_External_ID__c,Household_Program_Enrollment__r.hed__Contact__c, hed__Contact__r.AccountId
                            FROM hed__Program_Enrollment__c WHERE Id IN :programEnrollmentIds] ) {
                EnrollmentsMap.put(pe.Id, pe);
                acedemicProgramsReferenced.add(pe.hed__Account__c);
            }

            //Build a map between Academic Programs and Process ids.
            map <Id, Id> academicProgramProcessIdMap = new Map<Id,Id>();
            Set<Id> processIdSet = new Set<Id>();
            for (Enrollment_Component__c e : [SELECT Id, Process_Academic_Program__c FROM Enrollment_Component__c WHERE Process_Academic_Program__c = :acedemicProgramsReferenced  AND RecordType.Name = :NES_DashboardUtilities.PROCESS_RT])
            {
                academicProgramProcessIdMap.put(e.Process_Academic_Program__c, e.id);
                processIdSet.add(e.id);
            }

            //Build a list of all the enrollment components that have time based criteria and pass
            //those to runAssignment as a list of all the ids of the possibly impacted components.
            map<Id, List<Id>> processIdTimeBasedComponentsMap = new Map<Id, List<Id>> ();
            NES_EnrollmentCompentBuilder allECData = NES_EnrollmentCompentBuilder.getInstance();

            for (id pId : processIdSet) {
                NES_EnrollmentCompentBuilder.enrollmentComponentData thisProcessData = allECData.getSpecificProcessECData(pId);

            
                for (Enrollment_Component_Criteria__c ECC : [ SELECT Enrollment_Component__c, enrollment_component__r.name
                                                FROM Enrollment_Component_Criteria__c
                                                WHERE Enrollment_Component__c IN :thisProcessData.allIds
                                                AND Criteria_Type__c = 'Assignment'
                                                AND Criteria__r.criteria_field__c = 'hed__program_enrollment__c.date_today__c' ] ) {

                    List<Id> componentList;
                    if (processIdTimeBasedComponentsMap.containsKey(pid))
                        componentList = processIdTimeBasedComponentsMap.get(pid);
                    else 
                        componentList = new List<Id> ();

                    system.debug ('enrollment_component__r.name' + ECC.enrollment_component__r.name);
                                                
                    componentList.add(ECC.Enrollment_Component__c);
                    processIdTimeBasedComponentsMap.put(pId, componentList);
                    
                }
            }

        
            //for(SObject programEnrollment : scope) {
            for (id peID: programEnrollmentIds){
                hed__Program_Enrollment__c thisEnrollment = EnrollmentsMap.get(peID);
                id processId = academicProgramProcessIdMap.get(thisEnrollment.hed__Account__c);
                List<Id> thisProcessTimeBasedComponents = processIdTimeBasedComponentsMap.get(processId);
                system.debug ('thisProcessTimeBasedComponents' + thisProcessTimeBasedComponents);
                NES_ECAEvaluation.runAssignment(peID, thisProcessTimeBasedComponents, thisEnrollment, progEnrollECAListMap.get(peID), processId );
            }

            List<Enrollment_Component_Affiliation__c> affiliations = [
                    SELECT Id, Enrollment_Component__c, Program_Enrollment__c, Enrollment_Component__r.RecordType.Name, Status__c, Order__c,
                        Enrollment_Component__r.Assignment_Logic__c, Enrollment_Component__r.Completion_Logic__c, Enrollment_Component__r.Is_Required__c
                    FROM Enrollment_Component_Affiliation__c
                    WHERE Program_Enrollment__c IN : programEnrollmentIds];

            Map<Id,List<Enrollment_Component_Affiliation__c>> progEnrollECAAfterAssignmentListMap = new Map<Id,List<Enrollment_Component_Affiliation__c>> ();
            for ( Enrollment_Component_Affiliation__c affiliation : affiliations) {
                if (!progEnrollECAAfterAssignmentListMap.containsKey(affiliation.Program_Enrollment__c)){
                    list <Enrollment_Component_Affiliation__c> ecas = new List<Enrollment_Component_Affiliation__c> ();
                    ecas.add(affiliation);
                    progEnrollECAAfterAssignmentListMap.put(affiliation.Program_Enrollment__c, ecas);
                } else
                    progEnrollECAAfterAssignmentListMap.get(affiliation.Program_Enrollment__c).add(affiliation);
            }

            Map<Id, Map<Id, Enrollment_Component_Affiliation__c>> enrollmentAffiliationMap = new Map<Id, Map<Id, Enrollment_Component_Affiliation__c>>();

            //Loop through affiliations and grab EC Ids and create map of PE Id to map of EC Id to Affiliation

            for(Id enrollmentId : programEnrollmentIds) {

                Map<Id, Enrollment_Component_Affiliation__c> tempAffiliationMap = new Map<Id, Enrollment_Component_Affiliation__c>();

                for(Enrollment_Component_Affiliation__c affiliation : affiliations) {

                    if(enrollmentId == affiliation.Program_Enrollment__c) {

                        if(enrollmentAffiliationMap.keySet().contains(enrollmentId)) {
                            tempAffiliationMap = enrollmentAffiliationMap.get(enrollmentId);
                        }

                        tempAffiliationMap.put(affiliation.Enrollment_Component__c, affiliation);
                        System.debug(tempAffiliationMap);
                    }

                }
                enrollmentAffiliationMap.put(enrollmentId, tempAffiliationMap);
            }

            for(Id enrollmentId : programEnrollmentIds) {

                Map<Id, Enrollment_Component_Affiliation__c> tempAffiliationMap = enrollmentAffiliationMap.get(enrollmentId);
                if(tempAffiliationMap.size() > 0) {
                    hed__Program_Enrollment__c thisEnrollment = EnrollmentsMap.get(enrollmentId);
                    id processId = academicProgramProcessIdMap.get(thisEnrollment.hed__Account__c);
                    List<Enrollment_Component_Affiliation__c> thisPEECAs = progEnrollECAAfterAssignmentListMap.get(enrollmentId);
                    if (thisPEECAs <> null && thisPEECAs.size() > 0)
                        NES_ECACompletion.evaluateCompletion(enrollmentId, processId, null, tempAffiliationMap, thisPEECAs, thisEnrollment);
                }

            }
        }
    }


    global void finish(Database.BatchableContext BC) {

    }


    global void execute(SchedulableContext sc) {
        Database.executeBatch(new NES_Batch_TimeCriteria(), 2);
    }

}