force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_and_Immunization__c.object
<CustomObject>
    <fields>
        <fullName>Immunization_Status_FollowUp__c</fullName>
        <label>Immunization Status FollowUp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exemption</fullName>
                </value>
                <value>
                    <fullName>Extension Approved by Principal</fullName>
                </value>
                <value>
                    <fullName>Incomplete - Allow</fullName>
                </value>
                <value>
                    <fullName>Incomplete - Hold</fullName>
                </value>
                <value>
                    <fullName>Incomplete Exemption</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Medical Exemption</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>ORCA Exempt - VEC Required</fullName>
                </value>
                <value>
                    <fullName>ORCA Exempt - VEC Verified</fullName>
                </value>
                <value>
                    <fullName>Pending- IA Review</fullName>
                </value>
                <value>
                    <fullName>Personal Exemption</fullName>
                </value>
                <value>
                    <fullName>Religious Exemption</fullName>
                </value>
                <value>
                    <fullName>Review - Allow</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verified-In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Immunization_Status__c</fullName>
        <description>Enrollment Immunization Status</description>
        <label>Immunization Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exemption</fullName>
                </value>
                <value>
                    <fullName>Extension Approved by Principal</fullName>
                </value>
                <value>
                    <fullName>Incomplete - Allow</fullName>
                </value>
                <value>
                    <fullName>Incomplete - Hold</fullName>
                </value>
                <value>
                    <fullName>Incomplete Exemption</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Invalid Form</fullName>
                </value>
                <value>
                    <fullName>Medical Exemption</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Non-compliant Allow</fullName>
                </value>
                <value>
                    <fullName>ORCA Exempt - VEC Required</fullName>
                </value>
                <value>
                    <fullName>ORCA Exempt - VEC Verified</fullName>
                </value>
                <value>
                    <fullName>Pending- IA Review</fullName>
                </value>
                <value>
                    <fullName>Personal Exemption</fullName>
                </value>
                <value>
                    <fullName>Provisional Certificate Required</fullName>
                </value>
                <value>
                    <fullName>Religious Exemption</fullName>
                </value>
                <value>
                    <fullName>Review - Allow</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verified-In Progress</fullName>
                </value>
                <value>
                    <fullName>MCK Liaison Waiver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Health and Immunizations</relationshipLabel>
        <relationshipName>Health_and_Immunizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Health and Immunization</label>
    <nameField>
        <displayFormat>HI-{0000}</displayFormat>
        <label>Health and Immunization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health and Immunizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_HealthAndImmunizationTriggerTest.cls
/**
 * Created by Anushka Bansal on 12-12-2018.
 */

 @istest
 public class NES_HealthAndImmunizationTriggerTest {

     @TestSetup
     static void setup(){

         Peak_TestUtils.createNESBusinessLogicSwitch('Immunization Status Current', true);
         Account account = Peak_TestUtils.createTestAccount();
         School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019', date.parse('11/17/2018'));
         School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018', date.parse('11/17/2017'));
         Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);
         Account academicProgramAccount = Peak_TestUtils.createAccountForNewStudentData(account.Id, currentSchoolYear.Id);
         hed__Program_Enrollment__c programEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgramAccount.Id, contact.Id, currentSchoolYear.Id, true);
         Health_and_Immunization__c hni = new Health_and_Immunization__c(Program_Enrollment__c = programEnrollment.Id, Immunization_Status_FollowUp__c = 'Verified', Immunization_Status__c = 'Verified');
         insert hni;
     }


     static testMethod void afterInsertTest() {

         hed__Program_Enrollment__c programEnrollment = [SELECT Id FROM hed__Program_Enrollment__c LIMIT 1];
         Health_and_Immunization__c hni = new Health_and_Immunization__c(Program_Enrollment__c = programEnrollment.Id, Immunization_Status_FollowUp__c = 'Verified', Immunization_Status__c = 'Verified');
         insert hni;
     }

     static testMethod void afterUpdateTest() {

         hed__Program_Enrollment__c programEnrollment = [SELECT Id FROM hed__Program_Enrollment__c LIMIT 1];
         Health_and_Immunization__c hni = new Health_and_Immunization__c(Program_Enrollment__c = programEnrollment.Id, Immunization_Status_FollowUp__c = 'Verified', Immunization_Status__c = 'Verified');
         insert hni;
         Health_and_Immunization__c hni2 = [SELECT Id FROM Health_and_Immunization__c LIMIT 1];
         List<Health_and_Immunization__c> listOfHealthAndImmunizations = new List<Health_and_Immunization__c>();
         listOfHealthAndImmunizations.add(hni);
         listOfHealthAndImmunizations.add(hni2);

         listOfHealthAndImmunizations[0].Immunization_Status__c = 'Missing';
         listOfHealthAndImmunizations[0].Immunization_Status_FollowUp__c = 'Verified';
         listOfHealthAndImmunizations[1].Immunization_Status__c = 'Verified';
         listOfHealthAndImmunizations[1].Immunization_Status_FollowUp__c = 'Missing';
         update hni;
     }
 }