force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Annual_Household_Information__c.object
<CustomObject>
    <description>Household data that is specific to a school year is stored on the Annual Household Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Household Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Annual Household Information</relationshipLabel>
        <relationshipName>Annual_Household_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Annual Household Information</relationshipLabel>
        <relationshipName>Annual_Household_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Household Information</label>
    <nameField>
        <displayFormat>AHI-{0000}</displayFormat>
        <label>Annual Household Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Household Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Household_Enrollment_Information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Household Enrollment Information</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Enrollment_Information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Student Enrollment Information</label>
        <type>Checkbox</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/DisciplinaryPastActions__c.field-meta.xml
<CustomField>
    <fullName>DisciplinaryPastActions__c</fullName>
    <description>Has this student ever been suspended or expelled from any school?</description>
    <label>Disciplinary Past Actions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes, expelled</fullName>
            </value>
            <value>
                <fullName>Yes, in the process of being expelled</fullName>
            </value>
            <value>
                <fullName>Yes, suspended</fullName>
            </value>
            <value>
                <fullName>Yes, suspended and expelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/LastSchoolType__c.field-meta.xml
<CustomField>
    <fullName>LastSchoolType__c</fullName>
    <label>Last School Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homeschool</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>BIE School / Federal Grant / BIE Contract</fullName>
            </value>
            <value>
                <fullName>Charter School (Public)</fullName>
            </value>
            <value>
                <fullName>Correctional Facility</fullName>
            </value>
            <value>
                <fullName>Home School</fullName>
            </value>
            <value>
                <fullName>Online (Virtual) Public School</fullName>
            </value>
            <value>
                <fullName>Out of school more than 1 year</fullName>
            </value>
            <value>
                <fullName>Out of state</fullName>
            </value>
            <value>
                <fullName>Private/Parochial School</fullName>
            </value>
            <value>
                <fullName>Public School</fullName>
            </value>
            <value>
                <fullName>State Supported</fullName>
            </value>
            <value>
                <fullName>Virtual School (Public)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Stress_Factors__c.field-meta.xml
<CustomField>
    <fullName>Stress_Factors__c</fullName>
    <description>Are there any family stress factors that may impede your student’s success</description>
    <label>Stress Factors</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Decline to disclose</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement_and_Elective__c.object
<CustomObject>
    <description>The Placement and Elective Request object stored course requests made  by the caretaker during the enrollment process.</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment Record of the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipName>Placement_and_Elective_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipName>Placement_and_Elective_Requests_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course History and Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Placement and Elective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course History and Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Education__c.object
<CustomObject>
    <description>The Special Education Data object stores data related to IEPs, 504 plans, gifted education, and other student services</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Special Educations</relationshipLabel>
        <relationshipName>Special_Educations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Special Education</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Educations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_LTSUtilityTest.cls
/**
 * Created by Anushka Bansal on 19-12-2018.
 */

@IsTest
public with sharing class NES_LTSUtilityTest {

    @TestSetup static void setup() {
        Peak_TestUtils.createNESBusinessLogicSwitch('Likelihood to Transition Score', true);
        Account account = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019',date.parse('11/17/2018')); 

        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);
        Account academicProgramAccount = Peak_TestUtils.createAccountForNewStudentData(account.Id,currentSchoolYear.Id);
        hed__Program_Enrollment__c progEnrollmentHH = Peak_TestUtils.createProgramEnrollment(academicProgramAccount.Id, contact.Id,currentSchoolYear.Id, true); 

        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgramAccount.Id, contact.Id,currentSchoolYear.Id, false);
        progEnrollment.Stress_Factors__c = 'Yes';
        progEnrollment.DisciplinaryPastActions__c = 'Yes, expelled';
        progEnrollment.LastSchoolType__c = 'Private/Parochial School';
        insert progEnrollment;
        
        Enrollment_Component__c formComponent = Peak_TestUtils.createEnrollmentComponent(academicProgramAccount.Id, 'Form', false);
        formComponent.Household_Enrollment_Information__c = True;
        formComponent.Student_Enrollment_Information__c = True;
        insert formComponent;
        Enrollment_Component_Affiliation__c affiliation = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, formComponent.Id);
        affiliation.Status__c = 'In Progress';
        update affiliation;
        Annual_Household_Information__c ahi = Peak_TestUtils.createAnnualHouseholdInformation( progEnrollment.Id, currentSchoolYear.Id, false);
        ahi.Income_Opt_Out_Options__c ='Yes';
        ahi.Total_Gross_HH_Income__c=1;
        ahi.Number_HH_Children__c=10;
        ahi.Number_HH_Adults__c=10;
        insert ahi;

        Opportunity opp = Peak_TestUtils.createOpportunity('oldOpty',account.Id,System.Today(),'closed won',False);
        opp.Program_Enrollment__c = progEnrollment.Id;
        opp.SFDC_Informed__c = 'Uninformed';
        opp.SFDC_Engaged_Grassroots_User__c = 'True';
        Insert  opp;
       // Opportunity opportunity = Peak_TestUtils.createOpportunity(progEnrollment.Id);



    }
    /**
     * Created By Anushka 19/12/2018
     * Purpose : To test CalculateLTS method on Insert and update of Placement And Elective record
     */
    static testMethod void testCalculateLTSPlacementAndElective(){
        hed__Program_Enrollment__c progEnrollment = [select Id from hed__Program_Enrollment__c limit 1];
        system.debug('pro test' + progEnrollment);

       // Enrollment_Component_Affiliation__c aff = [Select id,Program_Enrollment__c, Status__c, Enrollment_Component__c, Enrollment_Component__r.Student_Enrollment_Information__c, Enrollment_Component__r.RecordType.DeveloperNamefrom Enrollment_Component_Affiliation__c limit 1];
        Test.startTest();
        Placement_and_Elective__c pne = Peak_TestUtils.createPlacementAndElective(progEnrollment.Id,false);
        pne.Course_Requested__c = 'World History';
        pne.Level_Requested__c = 'Honors';
        
        insert pne;
        Contact con = [Select id, Why_Is_Your_Child_Attending_CA__c from Contact limit 1];
        con.Why_Is_Your_Child_Attending_CA__c = 'Student was struggling academically';
        update con;
        Test.stopTest();
    }

    /**
     * Created By Anushka 19/12/2018
     * Purpose : To test CalculateLTS method on Insert and update of Special Education record
     */
    static testMethod void testCalculateLTSSpecialEductaion(){
        hed__Program_Enrollment__c progEnrollment = [select Id from hed__Program_Enrollment__c limit 1];
        Test.startTest();
        Special_Education__c specialEducation = Peak_TestUtils.createSpecialEducation(progEnrollment.Id, false);
        specialEducation.Gifted__c = 'Gifted IEP';
        insert specialEducation;
        specialEducation.Gifted__c = 'Gifted Allow';
        update  specialEducation;
        Test.stopTest();
    }
    
      /**
     * Created By Anushka 19/12/2018
     * Purpose : To test CalculateLTS method on Insert and update of Contact record
     */
    static testMethod void testCalculateLTSContact(){
        Account  account = [Select id from Account limit 1];
        hed__Program_Enrollment__c progEnrollment = [select Id from hed__Program_Enrollment__c limit 1];
        Test.startTest();
        Contact con = Peak_TestUtils.createContact('Test', account.Id,'Students',false);
        con.Why_Is_Your_Child_Attending_CA__c = 'Student has or had mental health concerns';
        insert con;

        account.LC_HighestLevelofEducation__c = 'College graduate (Bachelor\'s degree)';
        update account;
        
        con.Why_Is_Your_Child_Attending_CA__c = 'Student was struggling academically';
        update con;

        account.LC_HighestLevelofEducation__c = 'Not a high school graduate';
        account.Internet_Connection_Type__c = 'None';
        update account;

        con.Why_Is_Your_Child_Attending_CA__c = 'Student was ahead academically';
        update con;

        progEnrollment.LastSchoolType__c = 'Online (Virtual) Public School';
        update progEnrollment;

        account.LC_HighestLevelofEducation__c = 'High school graduate';
        account.Mktg_Customer_Loyalty__c = 'Customer Loyalty';
        account.Computer_in_Home__c = 'No';
        account.Internet_Connection_Type__c = 'Dial-up';
        update account;

        con.Why_Is_Your_Child_Attending_CA__c = 'Student was ahead academically';
        update con;

        Test.stopTest();
    }

}