force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Confirmation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_End_Date__c</fullName>
    <description>The date/time that final confirmation stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flag</fullName>
        <active>true</active>
        <label>Flag</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Enrollment_Component_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component_Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment Component Affiliation</label>
    <referenceTo>Enrollment_Component_Affiliation__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/AcademicPerformanceEligibility__c.field-meta.xml
<CustomField>
    <fullName>AcademicPerformanceEligibility__c</fullName>
    <label>Academic Performance Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allowed to Enroll</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Need additional information</fullName>
                <isActive>false</isActive>
                <label>Need additional information</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Start Year (calculated)</description>
    <label>Start Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NES_Enrollment_Process_Settings__mdt.object
<CustomObject>
    <description>Holds all settings related to NES Enrollment process, including Soft/Full Reactivation</description>
    <fields>
        <fullName>Reactivation_Whitelist__c</fullName>
        <description>Holds comma separated list of Profile Names having access to Full/Soft Reactivation button.</description>
        <inlineHelpText>Comma separated list of Profile Names having access to Full/Soft Reactivation button.</inlineHelpText>
        <label>Reactivation Whitelist</label>
        <type>TextArea</type>
    </fields>
    <label>NES_Enrollment_Process_Settings</label>
    <pluralLabel>NES_Enrollment_Process_Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caretaker Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Reactivation_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who executed the last full reactivation</description>
        <label>Full Reactivation User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>How_Student_Was_Reactivated__c</fullName>
        <description>How was this student reactivated</description>
        <label>How Student Was Reactivated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Caretaker</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The current school year</description>
        <label>Current School Year</label>
        <type>Checkbox</type>
    </fields>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_EnrollmentReactivationBase.cls
/**
 * 
 * Created by ali km on May/06/2020 for [US 168070]
 *      - This class is the base call for following User/Button Actions
 *          -> PE.Soft Reactivation
 *          -> PE.FULL Reactivation
 *          -> PE.Re-enrollment
 *      
 */
public abstract class NES_EnrollmentReactivationBase {
    
    public enum Reactivation {SOFT, FULL, RE_ENROLLMENT } 
    public enum ReactivatedBy {Caretaker, Staff} 

    public static final String COMMUNITY_USER_PROFILE_PREFIX = 'Caretaker';  
    public static final String PE_WITHDRAWAL_STATUS = 'Withdrawn';
    public static final String PE_REACTIVATION_STATUS = 'In Progress';
    public static final String STUD_PE_RECORD_TYPE_ID 
        = Schema.SObjectType.hed__Program_Enrollment__c.getRecordTypeInfosByDeveloperName().get('Student').getRecordTypeId();

    public Reactivation type {get; protected set;} 
    public Profile currentUserProfile {get; private set;}
    public hed__Program_Enrollment__c studPE {get; private set;}
    public List<Enrollment_Component_Affiliation__c> ecaList {get; protected set;}

    public NES_EnrollmentReactivationBase(String stud_PEID, Reactivation type) { 

        this.type = type;
        init(stud_PEID);    

    }

    // does bulk of the process for each reactivation type (ex: FULL, SOFT, RE_ENROLLMENT)
    // to be implemented by child class
    public abstract void execute();


    @TestVisible protected void init(String stud_PEID) {

        setCurrentUserProfile();
        setStudPE(stud_PEID);

    }


    private void setCurrentUserProfile() {
        
        currentUserProfile = [Select Id, Name from Profile where id = : UserInfo.getProfileId()];    
        validateUserProfile();

    }


    private void setStudPE(String stud_PEID) {

        validateStudPEID(stud_PEID); // validate stud_PEID
        
        // Added Start_Year__r.Current_Year__c for 335376 by Shravani Pendyala
        // fetch PE rec 
        studPE =
            [SELECT Id, Start_Year__r.Current_Year__c,hed__Account__r.ParentId, Name, hed__Contact__r.Name,hed__Account__r.Registration_Start_Date__c, hed__Account__r.OwnerId,
                hed__Account__r.Registration_End_Date__c, hed__Account__r.Confirmation_End_Date__c,hed__Contact__r.AccountId, 
                AcademicPerformanceEligibility__c, RecordTypeId, RecordType.Name, Status__c, Household_Program_Enrollment__c,
                (SELECT Id,StageName FROM Opportunities__r)
              FROM hed__Program_Enrollment__c WHERE Id = :stud_PEID];

        preValidatePE(); // validate the stud_PE rec

    }
    

    @TestVisible protected void validateUserProfile() {
        
        NES_Enrollment_Process_Settings__mdt enrollmentSettings = 
            [SELECT Id, DeveloperName, MasterLabel, Reactivation_Whitelist__c 
                FROM NES_Enrollment_Process_Settings__mdt WHERE DeveloperName = :type.name() ];
        System.debug(JSON.serialize(enrollmentSettings));

        if (!enrollmentSettings.Reactivation_Whitelist__c.toLowerCase().Contains(currentUserProfile.Name.toLowerCase())) {
            throw new NoAccess_Exception('You do not have access to perform this action, please reach out to your Salesforce Admin for help.');
        }

    }


    @TestVisible protected void validateStudPEID(String stud_PEID) {

        // Validate stud_PEID is not blank/null
        if (String.isBlank(stud_PEID)) {
            throw new InvalidParameterValue_Exception('BLANK OR Null Program Enrollment Id:' + stud_PEID);
        }

        // Validate stud_PEID is of type ProgramEnrollment
        Schema.sObjectType paramEntityType = Id.valueOf(stud_PEID).getSObjectType();
        // System.assert(entityType == hed__Program_Enrollment__c.sObjectType);
        if (paramEntityType !=hed__Program_Enrollment__c.sObjectType) { // ensure we have PD ID
            throw new InvalidParameterValue_Exception('Not a Program Enrollment Record Id:' + stud_PEID);
        }

    }


    @TestVisible protected void preValidatePE() { 

        // Validate stud_PEID if right RecordType
        if (studPE.RecordTypeId != STUD_PE_RECORD_TYPE_ID) {
            throw new InvalidParameterValue_Exception(
                'This Program Enrollment is not eligible for Student ' +  type + ', Id:' 
                    + studPE.Id + '; RecordType:' + studPE.RecordType.Name + ', Expected: Student');
        } 
        
        // Added for 335376 by Shravani Pendyala
        if (studPE.Start_Year__r.Current_Year__c != true) {
            throw new InvalidParameterValue_Exception(
                'This Program Enrollment is not eligible; Start Year is Current Year:' + studPE.Start_Year__r.Current_Year__c + ', Expected: true');
        }

        // // move to implementing child class...
        // if (!PE_WITHDRAWAL_STATUS.equalsIgnoreCase(this.studPE.Status__c)) {
        //     throw new InvalidParameterValue_Exception(
        //         'This Program Enrollment is not eligible for Student ' +  this.type 
        //             + ', Id:' + this.studPE.Id + '; Status:' + this.studPE.Status__c + ', Expected: ' + PE_WITHDRAWAL_STATUS);
        // }

    }

    // move to implementing child class...
    @TestVisible protected Opportunity getNewOpportunity() { // template to initialize the Oppty & return

        hed__Program_Enrollment__c progEnrollment = studPE;
        ReactivatedBy userType =  
            (currentUserProfile.Name.Contains(COMMUNITY_USER_PROFILE_PREFIX)) ? ReactivatedBy.Caretaker : ReactivatedBy.Staff;

        return (
            new Opportunity(
                Name = progEnrollment.hed__Contact__r.Name+'Opportunity',
                AccountId = progEnrollment.hed__Contact__r.AccountId,
                Program_Enrollment__c = progEnrollment.Id,
                StageName ='Open',
                CloseDate = progEnrollment.hed__Account__r.Confirmation_End_Date__c.date(),
                OwnerId = progEnrollment.hed__Account__r.OwnerId,
                How_Student_Was_Reactivated__c = userType.name()             
            )
        );

    }


    @TestVisible protected void processECAs(String enrollmentType) {
        
        List<Enrollment_Component_Affiliation__c> ecaToUpdate = new List<Enrollment_Component_Affiliation__c>();

        //Fix for Bug #195463 on 2020-06-25 (Krishna Peddanagammol)
        //Added Else If condition for defect #210102

        Set<Id> ECAsOfTypeDocument = new Set<Id>();
        Set<Id> ECsOfTypeDocument = new Set<Id>();
        for (Enrollment_Component_Affiliation__c eca : ecaList) {
            if((eca.Enrollment_Component__r.RecordType.Name != 'Stage') && (eca.Status__c == 'In Progress' || eca.Status__c == 'Complete')) {
                eca.Status__c = 'Not Started';
            }else if((eca.Enrollment_Component__r.RecordType.Name == 'Stage')  && (eca.Status__c == 'In Progress' || eca.Status__c == 'Complete')){
                if(eca.Order__c == 2){
                    eca.Status__c = 'In Progress';
                }else if(eca.Order__c > 2){
                    eca.Status__c = 'Not Started';
                }
            }
            system.debug('Enrollment Type*********'+eca.Program_Enrollment__r.Enrollment_Type__c);
            //Added for making Form status as In Progress, This will run only for Re-Enrolling Students for Defect 244255
            if((eca.Enrollment_Component__r.RecordType.Name == 'Form') && enrollmentType == 'RE-ENROLLMENT') 
                eca.Status__c = 'In Progress';
            
            //store the ECAs of document because during a reenrollment, we have to update the Enrollment docs tied to these ECAs
            if (eca.Enrollment_Component__r.RecordType.Name == 'Document') {
                ECAsOfTypeDocument.add(eca.id);       
                ECsOfTypeDocument.add(eca.Enrollment_Component__c);

                //For Reenrollments, all ECAs should have been completed once and for documents, they should be marked as In Progress.
                if(type==Reactivation.RE_ENROLLMENT) 
                    eca.Status__c = 'In Progress';
            }
 
            ecaToUpdate.add(eca);     
        }
        
        if (ecaToUpdate.size()>0) {
           // Added code for the defect 228339 by Maddileti on 28-08-2020   
           // To bypass the auto-completion logic , passing Flag value from  NES_EnrollmentReactivationBase class to NES_AddStudentCBLQueueable class
           if(type==Reactivation.RE_ENROLLMENT) {
               //Mark any Enrollment document that is tied to any ECA we are opening as invalid.
               Set<id> EDsAlreadyAdded = new Set<Id> ();
               List<Enrollment_Document__c> allEDsToUpdate = new List<Enrollment_Document__c> ([select id, Status_Reason__c from Enrollment_Document__c where Enrollment_Component_Affiliation__c in :ECAsOfTypeDocument]);
               for (Enrollment_Document__c ed : allEDsToUpdate) {
                   ed.Status_Reason__c = 'Invalid-Reenrollment';
                   EDsAlreadyAdded.add(ed.id);
               }

               //MM 10/5/2020 We need to find the house docs that might be tied to a different ECA.
               List<Enrollment_Document__c> allHouseholdEDsToUpdate = new List<Enrollment_Document__c> ([select id, Status_Reason__c 
                                                                                from Enrollment_Document__c 
                                                                                where Program_Enrollment__c = :studPE.Household_Program_Enrollment__c
                                                                                and Enrollment_Component_Affiliation__r.Enrollment_Component__c in :ECsOfTypeDocument ]);
               for (Enrollment_Document__c ed : allHouseholdEDsToUpdate) {
                   ed.Status_Reason__c = 'Invalid-Reenrollment';
                   if (!EDsAlreadyAdded.contains(ed.id))
                       allEDsToUpdate.add(ed);
               }

               if (allEDsToUpdate.size() > 0)
                   update allEDsToUpdate;
           }
           
           update ecaToUpdate;
        }
    }


    // exception classes
    public class EnrollmentReactivation_Exception extends Exception {}
    public class InvalidParameterValue_Exception extends Exception {}
    public class NoAccess_Exception extends Exception {}
}