force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Confirmation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_End_Date__c</fullName>
    <description>The date/time that final confirmation stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Confirmation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Start_Date__c</fullName>
    <description>The date/time that final confirmation will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enrollment_Stop_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Stop_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Enrollment Cutoff Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Confirmation_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmation Form</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic program associated with the component. This is exclusively used by components with a record type of Process to create a relationship between the account entity and it&apos;s required components. As the child components of the process could be used by multiple processes, there is not a direct relationship between them and a specific academic program and those relationships are inferred from their parent process.</description>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enrollment Components (Academic Program)</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_Batch_UpdateHardStopTimeConsTest.cls
@isTest
/**
 * Created By Anand
 * purpose : To Test The NES_Batch_UpdateHardStopTimeCons
 */
private class NES_Batch_UpdateHardStopTimeConsTest {
    @testSetup static void setup() {
        DateTime DateTimeTest = System.Now();
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        Id RecordTypeIdEnrollment = Schema.SObjectType.Enrollment_Component__c.getRecordTypeInfosByName().get('Process').getRecordTypeId();
        Id RecordTypeIdContact = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Caretaker').getRecordTypeId();
        Account account = Peak_TestUtils.createTestAccount();
        Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        Account parentAccount1 = [Select id,Name FROM Account WHERE Id = :parentAccount.Id];
        parentAccount1.Name = 'TestAccount1';
        update parentAccount1;
        Account accTest = [Select id,Name FROM Account WHERE Id = :parentAccount1.Id];
        Contact testContact = Peak_TestUtils.createTestContact();
        TestContact.LastName = 'TestCon';
        update TestContact;
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('SchoolTest', System.today());
        School_Year__c schlYearTest = Peak_TestUtils.createSchoolYears('SchoolTest1', System.today());


        Account academicAccount = Peak_TestUtils.createAcademicAccount('TestAcc1', parentAccount.Id, schlYear.Id, false);
        academicAccount.Enrollment_stop_date__c = datetime.newInstance(2014, 9, 15, 12, 30, 0);
        academicAccount.Confirmation_End_Date__c = datetime.newInstance(2014, 9, 15, 12, 30, 0);
        academicAccount.Confirmation_Start_Date__c = datetime.newInstance(2017, 9, 15, 12, 30, 0);
        insert academicAccount;
        Account academicAccountTest = Peak_TestUtils.createAcademicAccount('TestAcc2', accTest.Id, schlYearTest.Id, false);

        academicAccountTest.Enrollment_stop_date__c = datetime.newInstance(2014, 9, 15, 12, 30, 0);
        insert academicAccountTest;
        Account accountTest1 = [select Id,Enrollment_stop_date__c from Account WHERE Name = 'TestAcc1' LIMIT 1];
        Account accountTest2 = [select Id from Account WHERE Name = 'TestAcc2' LIMIT 1];
        List<Enrollment_Component__c> componentList = new List<Enrollment_Component__c>();
        for (Integer i = 0; i < 20; i++) {
            Enrollment_Component__c enrollmentComponent1 = Peak_TestUtils.createEnrollmentComponent(schlYear.Id, 'Process', false);
            enrollmentComponent1.Name = 'PE' + i;
            if (i <= 5) {
                Enrollment_Component__c enrollmentComponent2 = Peak_TestUtils.createEnrollmentComponent(schlYear.Id, 'form', false);
                enrollmentComponent2.Name = 'PE' + i;
                enrollmentComponent2.Process_Academic_Program__c = academicAccount.Id;
                enrollmentComponent2.Confirmation_Form__c = True;
                componentList.add(enrollmentComponent2);
            } if(i  >5 && i < 10){
                Enrollment_Component__c enrollmentComponent2 = Peak_TestUtils.createEnrollmentComponent(schlYear.Id, 'form', false);
                enrollmentComponent2.Name = 'PE' + i;
                enrollmentComponent2.Process_Academic_Program__c = academicAccount.Id;
                enrollmentComponent2.Confirmation_Form__c = false;
                componentList.add(enrollmentComponent2);
            }
            else {
                enrollmentComponent1.Process_Academic_Program__c = academicAccountTest.Id;
                componentList.add(enrollmentComponent1);
            }

        }
        Insert componentList;
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicAccount.Id, testContact.Id, schlYear.Id, True);
        hed__Program_Enrollment__c progEnrollment1 = Peak_TestUtils.createProgramEnrollment(academicAccountTest.Id, testContact.Id, schlYear.Id, True);
        List<Opportunity> optyList = new List<Opportunity>();
        for (Integer i = 0; i < 20; i++) {
            Opportunity optyTest1 = Peak_TestUtils.createOpportunity('oldOpty' + i, accountTest1.Id, System.Today(), 'closed Lost', False);
            optyTest1.Program_Enrollment__c = progEnrollment.Id;
            optyList.add(optyTest1);
        }
        Insert optyList;


    }
    /**
     * Created By Anand
     * Purpose : To  Test  the  NES_Batch_UpdateHardStopTimeCons Batch Class
     */
    static testMethod void testBatchUpdateHardStopTimeContraint() {
        Account accountTest1 = [select Id,Enrollment_stop_date__c from Account WHERE Name = 'TestAcc1' LIMIT 1];
        Account accountTest2 = [select Id from Account WHERE Name = 'TestAcc2' LIMIT 1];
        List<Enrollment_Component_Affiliation__c> affiliationList = new List<Enrollment_Component_Affiliation__c>();

        hed__Program_Enrollment__c progEnrollmentTest1 = [Select Id FROM hed__Program_Enrollment__c WHERE hed__Account__c = :accountTest1.Id LIMIT 1];
        hed__Program_Enrollment__c progEnrollmentTest = [Select Id FROM hed__Program_Enrollment__c WHERE hed__Account__c = :accountTest2.Id LIMIT 1];
        Integer i = 0;
        for (Enrollment_Component__c component : [select Id,Confirmation_Form__c FROM Enrollment_Component__c]) {
            Enrollment_Component_Affiliation__c affiliationTest;
            if (component.Confirmation_Form__c) {
                affiliationTest  = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollmentTest1.Id, component.Id, false);

            } else {
                affiliationTest = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollmentTest.Id, component.Id, false);
            }
            affiliationTest.status__c = 'Exempt';
            affiliationList.add(affiliationTest);

        }
        Insert affiliationList;
        Test.startTest();

        NES_Batch_UpdateHardStopTimeConstraint obj = new NES_Batch_UpdateHardStopTimeConstraint();
        DataBase.executeBatch(obj);


        Test.stopTest();
        List<Enrollment_Component_Affiliation__c> affiliationsTest1 = [Select Id from Enrollment_Component_Affiliation__c Where Status__c = 'Time Expired'];
        System.assertEquals(26, affiliationsTest1.Size());

        for (Opportunity opp : [select Id,StageName From Opportunity Where Program_Enrollment__c IN (Select Id from hed__Program_Enrollment__c)]) {
            System.assertEquals('Closed Lost', opp.StageName);
        }


    }



}