force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <description>Within the enrollment model, some objects are a one to many off of the Program Enrollment. For example, ASI (Annual Student Information). In those cases, we need to know which Criteria record need recalculating. This field will store the school year that this criteria is related to.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Criteria_Group__c.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Component__c</fullName>
        <description>The parent enrollment component for the criteria group.</description>
        <label>Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Criteria Groups</relationshipLabel>
        <relationshipName>Criteria_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Criteria Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Assignment_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component is relevant to the program enrollment the evaluation was completed for and it would then be assigned to the PE through a Enrollment Component Affiliation. If there is no assignment logic defined on a component, it inherits it&apos;s assigment from its parent.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Assignment Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Indicator of whether the component relates to student or caretaker (household) program enrollments. This field is used for components of the following types: Flag, Form. All child components of a form should implicitly inherit the type of the form when used in the context of that form.</description>
        <label>Component Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Caretaker</fullName>
                    <isActive>false</isActive>
                    <label>Caretaker</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question_Group</fullName>
        <active>true</active>
        <label>Question Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Component__c</fullName>
        <description>The parent enrollment component for the component criteria.</description>
        <label>Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Enrollment Component Criteria</relationshipLabel>
        <relationshipName>Enrollment_Component_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <description>Within the enrollment model, some objects are a one to many off of the Program Enrollment. For example, ASI (Annual Student Information). In those cases, we need to know which Criteria record need recalculating. This field will store the school year that this criteria is related to.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Enrollment Component Criteria</label>
    <nameField>
        <displayFormat>ECC-{000}</displayFormat>
        <label>Enrollment Component Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Initial_ECA_Creation_Complete__c.field-meta.xml
<CustomField>
    <fullName>Initial_ECA_Creation_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by the new student creation process to allow the creation of all the ECAs to be async.  When the Caretaker creates the student this will be false.  An async job that creates the ECAs will mark check this when it completes.</description>
    <label>Initial ECA Creation Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NES_Batch_TimeCriteria_Test.cls
/**
 * Created by ajith on 05/02/19.
 * purpose : To Test The NES_Batch_TimeCriteria
 */

@isTest 

private class NES_Batch_TimeCriteria_Test {

    @testSetup static void setup(){
    
        Account account = Peak_TestUtils.createEducationalInstitutionAccount();

        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());

        User  portalUser= Peak_TestUtils.CreatePortalCaretTakerUser();

        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);

        // Create a account with 'Academic Program' record type
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(account.Id, schoolYear.Id);
        academicProgram.Registration_Start_Date__c = System.today().addDays(-10);
        academicProgram.Registration_End_Date__c = System.today().addDays(10);
        update academicProgram;

        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, portalUser.ContactId, schoolYear.Id, false);
        progEnrollment.Status__c = 'In Progress';
        progEnrollment.Initial_ECA_Creation_Complete__c = true;
        insert progEnrollment;


        // Create a Enrollment Components with different record type
        List < Enrollment_Component__c > componentList = new List < Enrollment_Component__c > ();
        Enrollment_Component__c stageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Stage', false);
        Enrollment_Component__c processComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Process', false);
        Enrollment_Component__c questionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        //questionComponent.Component_Type__c = 'Student';
        questionComponent.Component_Type__c = 'Household';
        questionComponent.Assignment_Logic__c = null;
        Enrollment_Component__c sectionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Section', false);
        sectionComponent.Assignment_Logic__c = null;
        Enrollment_Component__c formComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Form', false);
        formComponent.Assignment_Logic__c = null;
        Enrollment_Component__c messageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Message', false);
        Enrollment_Component__c documentComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Document', false);
        Enrollment_Component__c questionGroupComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question_Group', false);
        questionGroupComponent.Assignment_Logic__c = null;

        componentList.add(questionGroupComponent);
        componentList.add(stageComponent);
        componentList.add(processComponent);
        componentList.add(questionComponent);
        componentList.add(sectionComponent);
        componentList.add(formComponent);
        componentList.add(messageComponent);
        componentList.add(documentComponent);
        insert componentList;

        Criteria_Group__c criteriaGroup1= Peak_TestUtils.createCriteriaGroup('Test CG1',questionComponent.Id,false);
        criteriaGroup1.Group_Number__c = 1;
        criteriaGroup1.Group_Logic__c = '((1 OR 2) AND 3)';
        insert criteriaGroup1;

        Criteria__c criteria1 = Peak_TestUtils.createCriteriaRecord('Test Criteria1','hed__Program_Enrollment__c.LTS__c','>=',false);
        criteria1.Comparison_Field__c = 'hed__Program_Enrollment__c.hed__Credits_Earned__c';
        criteria1.Comparison_Data_Type__c = 'Date';
        insert criteria1;
        Criteria__c criteria2 = Peak_TestUtils.createCriteriaRecord('Test Criteria2','hed__Program_Enrollment__c.LTS__c','>=',false);
        criteria2.Comparison_Field__c = 'hed__Program_Enrollment__c.hed__Credits_Earned__c';
        criteria2.Comparison_Data_Type__c = 'Date';
        insert criteria2;

        Criteria_Refinement__c criteriaRefinement1 = new Criteria_Refinement__c(Criteria__c = criteria1.Id, Refinement_Type__c = 'Left side', Refinement_Value__c = '10',
                Operator__c = '>=',Refinement_Field_Left__c = 'hed__Program_Enrollment__c.LTS__c');
        insert criteriaRefinement1;

        Enrollment_Component_Criteria__c enrollmentComponentCriteria1 = Peak_TestUtils.createEnrollCompCriteria('Test ECC1',questionComponent.Id,false);
        enrollmentComponentCriteria1.Criteria__c = criteria1.Id;
        enrollmentComponentCriteria1.Student_or_Household__c = 'Student';
        enrollmentComponentCriteria1.Criteria_Number__c = 1;
        insert enrollmentComponentCriteria1;

        Enrollment_Component_Criteria__c enrollmentComponentCriteria2 = Peak_TestUtils.createEnrollCompCriteria('Test ECC2',questionComponent.Id,false);
        enrollmentComponentCriteria2.Criteria__c = criteria2.Id;
        enrollmentComponentCriteria2.Student_or_Household__c = 'Household';
        enrollmentComponentCriteria2.Criteria_Number__c = 2;
        insert enrollmentComponentCriteria2;

        // create Enrollment Component Relationships with different parent Enrollment Components.
        Enrollment_Component_Relationship__c enrollCompRelationship = Peak_TestUtils.createEnrollmentComponentRelationship(stageComponent.Id, processComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship2 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponent.Id, sectionComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship3 = Peak_TestUtils.createEnrollmentComponentRelationship(formComponent.Id, stageComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship4 = Peak_TestUtils.createEnrollmentComponentRelationship(messageComponent.Id, formComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship5 = Peak_TestUtils.createEnrollmentComponentRelationship(sectionComponent.Id, formComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship6 = Peak_TestUtils.createEnrollmentComponentRelationship(questionGroupComponent.Id,sectionComponent.Id);
        Enrollment_Component_Relationship__c enrollCompRelationship7 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponent.Id,questionGroupComponent.Id);

        // create Enrollment Component Affiliations with different parent Enrollment Components.
        List<Enrollment_Component_Affiliation__c> enrollmentComponentAffiliations = new List<Enrollment_Component_Affiliation__c>();
        Enrollment_Component_Affiliation__c affiliation = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, formComponent.Id, false);
        affiliation.Status__c = 'In Progress';
        Enrollment_Component_Affiliation__c affiliationStage = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, stageComponent.Id, false);
        affiliationStage.Status__c = 'In Progress';
        Enrollment_Component_Affiliation__c affiliationSection = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, sectionComponent.Id, false);
        affiliationSection.Status__c = 'In Progress';
        Enrollment_Component_Affiliation__c affiliationQuestion = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, questionComponent.Id, false);
        affiliationQuestion.Status__c = 'In Progress';
        Enrollment_Component_Affiliation__c affiliationDocument = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, documentComponent.Id, false);
        Enrollment_Component_Affiliation__c affiliationProcess = Peak_TestUtils.createEnrollmentComponentAffiliation(progEnrollment.Id, processComponent.Id, false);


        enrollmentComponentAffiliations.add(affiliation);
        enrollmentComponentAffiliations.add(affiliationStage);
        enrollmentComponentAffiliations.add(affiliationSection);
        enrollmentComponentAffiliations.add(affiliationDocument);
        enrollmentComponentAffiliations.add(affiliationProcess);
        enrollmentComponentAffiliations.add(affiliationQuestion);

        insert enrollmentComponentAffiliations;  
    } 

    static testMethod void unitTestPositiveTests(){

        Test.startTest();
        hed__Program_Enrollment__c progEnrollment = [SELECT Id FROM hed__Program_Enrollment__c WHERE Status__c = 'In Progress'];
        List<Enrollment_Component_Affiliation__c> affiliations = [SELECT Id, Status__c, Enrollment_Component__c, Program_Enrollment__c
                                                                        FROM Enrollment_Component_Affiliation__c
                                                                        WHERE Status__c != 'Complete'];
        System.debug('affiliations++++++'+affiliations);

        List<Enrollment_Component_Criteria__c> enrollmentComponentCriteria = new List<Enrollment_Component_Criteria__c>([SELECT Id, Criteria__r.Comparison_Data_Type__c, Enrollment_Component__c FROM Enrollment_Component_Criteria__c]);
        System.debug('enrollmentComponentCriteria++++'+enrollmentComponentCriteria);

        NES_Batch_TimeCriteria obj = new NES_Batch_TimeCriteria();
        DataBase.executeBatch(obj);
        Test.stopTest();
    }


}