force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Answer_Target__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Defines the system location to store the answer to this question. e.g. Household_Income__c.Value__c</inlineHelpText>
        <label>Answer Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NES_ECUtilities.cls
/**
 * Created by Ritvik on 01-11-2018.
 */

public with sharing class NES_ECUtilities {    

    /**
    * Created By Ajith on 31-12-2018.
    * purpose : Wrapper Class for sending the request to the Experian Marketing Services
    */
    public class phoneValidatorWrap{

        public Long NumberKey;
        public String DefaultCountryCode;

        public phoneValidatorWrap(Long NumberKey, String DefaultCountryCode){
            this.NumberKey = NumberKey;
            this.DefaultCountryCode = DefaultCountryCode;
        }
    }

    /**
    * Created By Ajith on 31-12-2018.
    * purpose : Wrapper Class to hold the data from the request response from Experian Marketing Services
    */
    public class GlobalPhoneInfo{

        public Long phoneKey {get; set;}
        public String PhoneType {get; set;}
        public String Certainty {get; set;}

        public GlobalPhoneInfo(Long phoneKey, String phoneType, String certainty){

            this.phoneKey = phoneKey;
            this.PhoneType = phoneType;
            this.Certainty = certainty;
        }
    }

    /**
    * Created By Ajith on 31-12-2018.
    * purpose : Method to construct the query for the ECAs EC of type Question and Phone
    *           and query the records based on the PE on the ECA record
    * params : List of ECA records
    */

    public static Map<Long, Enrollment_Component_Affiliation__c> configureQuery(List<Enrollment_Component_Affiliation__c> enrollmentComponentAffiliations) {
        Map<Enrollment_Component_Affiliation__c, String> ecaToQueryMap = new Map <Enrollment_Component_Affiliation__c, String>();
        //Map to hold the phone number and related ECA 
        Map<Long, Enrollment_Component_Affiliation__c> phoneToECAMap = new Map<Long, Enrollment_Component_Affiliation__c>();

        for(Enrollment_Component_Affiliation__c eca : enrollmentComponentAffiliations){

            String data = eca.Enrollment_Component__r.Answer_Target__c;
            //Split the Target field to get the Object and Field API Names
            String fieldApiName = data.substring(data.indexOf('.') + 1, data.length());
            String objectApiName = data.substring(0, data.indexOf('.'));

            String query;
            if(objectApiName == 'Account') {
                query = 'SELECT Id, ' + fieldApiName + ' FROM Account WHERE Id = \'' + eca.Program_Enrollment__r.hed__Contact__r.AccountId + '\' ';
            } else if(objectApiName == 'Contact') {
                query = 'SELECT Id, ' + fieldApiName + ' FROM Contact WHERE Id = \'' + eca.Program_Enrollment__r.hed__Contact__c + '\' ';
            } else if(objectApiName == 'hed__Program_Enrollment__c') {
                query = 'SELECT Id, ' + fieldApiName + ' FROM hed__Program_Enrollment__c WHERE Id = \'' + eca.Program_Enrollment__c + '\' ';
            } else {
                query = 'SELECT Id, ' + fieldApiName + ' FROM ' + objectApiName + ' WHERE Program_Enrollment__c = \'' + eca.Program_Enrollment__c + '\' ';
            }
            if(String.isNotBlank(query)){
                query += ' LIMIT 1 ';
                ecaToQueryMap.put(eca, query);
                List<SObject> childRecords = new List<SObject>();
                System.debug(query);
                query.remove('(');
                query.remove(')');
                //Query the Records
                childRecords = Database.query(query);
                if(!childRecords.isEmpty()){
                    SObject childRecord = childRecords[0];
                    System.debug('NES_ECUtilities:: configureQuery:: childRecord:: '+childRecord);
                    System.debug('NES_ECUtilities:: configureQuery:: field name:: '+childRecord.get(fieldApiName));
                    String phoneNumber = (String)childRecord.get(fieldApiName);
                    String trimPhoneNumber = phoneNumber.replaceAll('[^0-9]', '');
                    System.debug('NES_ECUtilities:: configureQuery:: field name::: '+ trimPhoneNumber);
                    phoneToECAMap.put(Long.valueOf(trimPhoneNumber), eca);
                }
            }
        }

        return phoneToECAMap;
    }

    /**
    * Created By Ajith on 31-12-2018.
    * purpose : Method to construct Http request and return response of the request

    */
    public static HttpCalloutMock mock = null;
    public static HttpResponse createHttpRequestForPhoneData(String method, String endpoint, String authToken, String body) {
        HttpRequest request = new HttpRequest();
        request.setMethod(method);
        request.setEndpoint(endpoint);

        if(method == 'POST') {
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('auth-token', authToken);
            request.setHeader('authorization', 'Bearer '+ authToken);
            request.setBody(body);
        }

       HttpResponse response = null;
       // if--else condition added by raju 
        if (Test.isRunningTest() && (mock!=null)) {
            return mock.respond(request);
        } else {
           //Send the request
           Http http = new Http();
           response = http.send(request);
        }
        
        return response;
    }
     

}