force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Final_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Final_Grade_Level__c</fullName>
    <label>Final Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transitional K</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentEnrollment.cls
public class StudentEnrollment {
    private static Peak_ApexLog logger = new Peak_ApexLog('DashboardHelper');

     @AuraEnabled
    
    public static list<NES_DashboardUtilities.StudentInformation> getStudentinfo(ID currentstudentID){
         try {
             Id careTakerContactId;
            
             // studentIds.add(currentstudentID);
             system.debug('currentstudentID'+currentstudentID);
                          careTakerContactId=currentstudentID;
             
                 if (careTakerContactId != null) {
                //Retrieve the related student Ids of the careTakerContactId
                Set<Id> studentIds = new Set<Id>();
                Id studentRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(NES_DashboardUtilities.STUDENT_RT).getRecordTypeId();

                for (hed__Relationship__c con : [
                        SELECT hed__RelatedContact__c
                        FROM hed__Relationship__c
                        WHERE hed__Contact__c = :careTakerContactId
                        AND hed__RelatedContact__r.RecordTypeId = :studentRecordTypeId
                ]) {
                    studentIds.add(con.hed__RelatedContact__c);
                }

                if (studentIds.size() > 0) {
             
         List<NES_DashboardUtilities.StudentInformation> students = new List<NES_DashboardUtilities.StudentInformation>();
            // NES_DashboardUtilities.StudentInformation student_enroll = new NES_DashboardUtilities.StudentInformation();  

                    List<hed__Program_Enrollment__c> programEnrollments = [
                            SELECT Id, hed__Contact__c, hed__Contact__r.Name,hed__Contact__r.AccountId, Status__c, Final_Grade_Level__c,
                                    hed__Account__r.Registration_Start_Date__c, hed__Account__r.Registration_End_Date__c, hed__Account__r.ParentId,
                            (SELECT Order__c, Enrollment_Component__r.Name, Status__c,Enrollment_Component__r.Order__c,
                                    Program_Enrollment__r.Final_Grade_Level__c, Enrollment_Component__r.RecordType.Name
                                FROM Enrollment_Component_Affiliation__r
                                WHERE Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.PROCESS_RT
                                OR Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.STAGE_RT)
                            FROM hed__Program_Enrollment__c
                            WHERE hed__Contact__c IN:studentIds
                    ];

                    for (hed__Program_Enrollment__c temp : programEnrollments) {

                        System.debug(temp.Id);
                        if (temp.Enrollment_Component_Affiliation__r != null && temp.Enrollment_Component_Affiliation__r.size() > 0) {
                            List<Enrollment_Component_Affiliation__c> stages = new List<Enrollment_Component_Affiliation__c>();

                            for (Enrollment_Component_Affiliation__c eca : temp.Enrollment_Component_Affiliation__r) {
                                if (eca.Enrollment_Component__r.RecordType.Name == NES_DashboardUtilities.STAGE_RT) {
                                    stages.add(eca);
                                }

                            }

                            for (Enrollment_Component_Affiliation__c eca : temp.Enrollment_Component_Affiliation__r) {
                                if (eca.Enrollment_Component__r.RecordType.Name == NES_DashboardUtilities.PROCESS_RT) {
                                    String statusString;
                                    if (String.isNotBlank(temp.Status__c)) {
                                        statusString = temp.Status__c;
                                    } else {
                                        statusString = eca.Status__c;
                                    }
                                    students.add(new NES_DashboardUtilities.StudentInformation(temp.Id, temp.hed__Contact__c, statusString, temp.hed__Contact__r.Name, temp.hed__Account__r.ParentId, stages, eca.Enrollment_Component__c, temp.Final_Grade_Level__c, temp.hed__Account__r.Registration_Start_Date__c, temp.hed__Account__r.Registration_End_Date__c));
                                }
                            }
                        }
                    }
                    system.debug('students'+students);
                 return students;
                }
            }

            return null;
        } catch (Exception e) {
            logger.logException('getRelatedStudentsWithId', e);
            logger.saveLogs();
            return null;
        }
    }
}
     //private static Peak_ApexLog logger = new Peak_ApexLog('DashboardHelper');

    /**
     * Created by Ashish Sharma on 12/05/18
     * Parameters: Id
     * Return Type: List<NES_DashboardUtilities.StudentInformation>
     * Purpose : This method is used to retrieve all program enrollments related to the students (based on care taker user's Id passed in the method parameter)
                 and then get all PROCESS_RT
                 type Enrollment components and related ECAs. Return this information after adding
                 in List<NES_DashboardUtilities.StudentInformation>
    */
   /* public static List<NES_DashboardUtilities.StudentInformation> getRelatedStudentsWithId(Id ctUserId) {
        try {
            Id careTakerContactId;

            //Retrieve the care taker contact Id of the current logged in user
            for (User tempUser : [SELECT ContactId FROM User WHERE Id = :ctUserId]) {
                careTakerContactId = tempUser.ContactId;
            }


            if (careTakerContactId != null) {
                //Retrieve the related student Ids of the careTakerContactId
                Set<Id> studentIds = new Set<Id>();
                Id studentRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(NES_DashboardUtilities.STUDENT_RT).getRecordTypeId();

                for (hed__Relationship__c con : [
                        SELECT hed__RelatedContact__c
                        FROM hed__Relationship__c
                        WHERE hed__Contact__c = :careTakerContactId
                        AND hed__RelatedContact__r.RecordTypeId = :studentRecordTypeId
                ]) {
                    studentIds.add(con.hed__RelatedContact__c);
                }

                if (studentIds.size() > 0) {
                    /*
                      Retrieve all program enrollments related to the students and then get all PROCESS_RT
                      type Enrollment components and related ECAs. Return this information after adding
                      in List<NES_DashboardUtilities.StudentInformation>
                    */
                   /* List<NES_DashboardUtilities.StudentInformation> students = new List<NES_DashboardUtilities.StudentInformation>();

                    List<hed__Program_Enrollment__c> programEnrollments = [
                            SELECT Id, hed__Contact__c, hed__Contact__r.Name,hed__Contact__r.AccountId, Status__c, Final_Grade_Level__c,
                                    hed__Account__r.Registration_Start_Date__c, hed__Account__r.Registration_End_Date__c, hed__Account__r.ParentId,
                            (SELECT Order__c, Enrollment_Component__r.Name, Status__c,Enrollment_Component__r.Order__c,
                                    Program_Enrollment__r.Final_Grade_Level__c, Enrollment_Component__r.RecordType.Name
                                FROM Enrollment_Component_Affiliation__r
                                WHERE Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.PROCESS_RT
                                OR Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.STAGE_RT)
                            FROM hed__Program_Enrollment__c
                            WHERE hed__Contact__c IN:studentIds
                    ];

                    for (hed__Program_Enrollment__c temp : programEnrollments) {

                        System.debug(temp.Id);
                        if (temp.Enrollment_Component_Affiliation__r != null && temp.Enrollment_Component_Affiliation__r.size() > 0) {
                            List<Enrollment_Component_Affiliation__c> stages = new List<Enrollment_Component_Affiliation__c>();

                            for (Enrollment_Component_Affiliation__c eca : temp.Enrollment_Component_Affiliation__r) {
                                if (eca.Enrollment_Component__r.RecordType.Name == NES_DashboardUtilities.STAGE_RT) {
                                    stages.add(eca);
                                }

                            }

                            for (Enrollment_Component_Affiliation__c eca : temp.Enrollment_Component_Affiliation__r) {
                                if (eca.Enrollment_Component__r.RecordType.Name == NES_DashboardUtilities.PROCESS_RT) {
                                    String statusString;
                                    if (String.isNotBlank(temp.Status__c)) {
                                        statusString = temp.Status__c;
                                    } else {
                                        statusString = eca.Status__c;
                                    }
                                    students.add(new NES_DashboardUtilities.StudentInformation(temp.Id, temp.hed__Contact__c, statusString, temp.hed__Contact__r.Name, temp.hed__Account__r.ParentId, stages, eca.Enrollment_Component__c, temp.Final_Grade_Level__c, temp.hed__Account__r.Registration_Start_Date__c, temp.hed__Account__r.Registration_End_Date__c));
                                }
                            }
                        }
                    }
                    return students;
                }
            }
}

            return null;
        } catch (Exception e) {
            logger.logException('getRelatedStudentsWithId', e);
            logger.saveLogs();
            return null;
        }
    }*/