force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Alternative_Address_Request__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Address_Request__c</fullName>
    <label>Alternative Address Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Annual_Student_Information__c.object
<CustomObject>
    <description>Student data that is specific to a school year is stored on the Annual Student Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Student Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment record for the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The School Year record for the year the data is relevant to.</description>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Student Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Student Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/CounselingFlag__c.field-meta.xml
<CustomField>
    <fullName>CounselingFlag__c</fullName>
    <description>Program Fit Flag</description>
    <label>Program Fit Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stop</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/EligibilityFlag__c.field-meta.xml
<CustomField>
    <fullName>EligibilityFlag__c</fullName>
    <description>Eligibility Flag</description>
    <label>Eligibility Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/PlacementFlag__c.field-meta.xml
<CustomField>
    <fullName>PlacementFlag__c</fullName>
    <label>Placement Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Communication- More Info</fullName>
            </value>
            <value>
                <fullName>Awaiting Communication- Retain</fullName>
            </value>
            <value>
                <fullName>Awaiting Communication- School Counselor</fullName>
            </value>
            <value>
                <fullName>Awaiting Communication- WYCA</fullName>
            </value>
            <value>
                <fullName>Counselor Review</fullName>
            </value>
            <value>
                <fullName>Pending Assessment</fullName>
            </value>
            <value>
                <fullName>Pending Secondary Documentation</fullName>
            </value>
            <value>
                <fullName>Principal Review</fullName>
            </value>
            <value>
                <fullName>Principal Review- Awaiting Feedback</fullName>
            </value>
            <value>
                <fullName>Principal Review- Complete</fullName>
            </value>
            <value>
                <fullName>Principal Review- Gifted</fullName>
            </value>
            <value>
                <fullName>Principal Review- Need Information</fullName>
            </value>
            <value>
                <fullName>RC/PAH Not Uploaded</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Academic Placement Advisor</fullName>
            </value>
            <value>
                <fullName>Special Education Director</fullName>
            </value>
            <value>
                <fullName>11th Grade Counselor Review</fullName>
                <isActive>false</isActive>
                <label>11th Grade Counselor Review</label>
            </value>
            <value>
                <fullName>Principal Review- Gifted Request</fullName>
                <isActive>false</isActive>
                <label>Principal Review- Gifted Request</label>
            </value>
            <value>
                <fullName>Special Education Director Review (FLVSFT Only)</fullName>
                <isActive>false</isActive>
                <label>Special Education Director Review (FLVSFT Only)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/PriorWithdrawalFlag__c.field-meta.xml
<CustomField>
    <fullName>PriorWithdrawalFlag__c</fullName>
    <description>Student Withdrawn Previously</description>
    <label>Prior Withdrawal Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Start Year (calculated)</description>
    <label>Start Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Academic_Program__c</fullName>
    <label>Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/AutoPlacement_Special_EdExclude__c.field-meta.xml
<CustomField>
    <fullName>AutoPlacement_Special_EdExclude__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AutoPlacement Special EdExclude</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Education__c.object
<CustomObject>
    <description>The Special Education Data object stores data related to IEPs, 504 plans, gifted education, and other student services</description>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Special Educations</relationshipLabel>
        <relationshipName>Special_Educations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Special Education</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Educations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_BusinessLogicUtilswhyflagTest.cls
@istest
private class NES_BusinessLogicUtilswhyflagTest
{
    @TestSetup
    static void setup() {
        // generate test-data
        
        Id Academic = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        School_Year__c previousSchoolYears = Peak_TestUtils.createSchoolYears('2018-2019',System.today());
        Account objacc = Peak_TestUtils.createEducationalInstitutionAccount();
        
        objacc.recordtypeid=Academic;
        Objacc.Alternative_Address_Request__c='Yes';
        Objacc.School_Year__c=previousSchoolYears.id;
        update Objacc;
        Contact contact = Peak_TestUtils.createTestContact('Students', Objacc.Id);
        hed__Program_Enrollment__c HousePE= Peak_TestUtils.createProgramEnrollment(objacc.id,contact.id,previousSchoolYears.id,true);
        hed__Program_Enrollment__c Hpe= Peak_TestUtils.createProgramEnrollment(objacc.id,contact.id,previousSchoolYears.id,true);
        Hpe.Household_Program_Enrollment__c=HousePE.id;
        update Hpe;
    }
    
    static testMethod void calculateWhyFlaggedtest (){
        
        date mydate = date.parse('04/12/2020');
        School_Year__c previousSchoolYears=new School_Year__c();
        previousSchoolYears.Name='testing';
        previousSchoolYears.Start_Date__c=mydate;
        previousSchoolYears.End_Date__c=mydate;
        insert previousSchoolYears;
        System.debug('syear:'+previousSchoolYears);
        
        Grade_Level__c glsRecords=new Grade_Level__c();
        glsRecords.Name='testing';
        insert glsRecords;
        
       	Account objacc = Peak_TestUtils.createEducationalInstitutionAccount(); 
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(objacc.Id, previousSchoolYears.Id);
        Program_Grade_Level__c pglRecords=new Program_Grade_Level__c();
        pglRecords.Academic_Program__c=academicProgram.Id;
        pglRecords.Grade_Level__c=glsRecords.Id;
        pglRecords.AutoPlacement_Special_EdExclude__c=FALSE;
        insert pglRecords;
        
        hed__Program_Enrollment__c progEnrollment1 = new hed__Program_Enrollment__c();
        progEnrollment1.Start_Year__c=previousSchoolYears.Id;
        progEnrollment1.Program_Grade_Level__c=pglRecords.Id;
        progEnrollment1.PlacementFlag__c='Principal Review';
        progEnrollment1.CounselingFlag__c='Stop';
        progEnrollment1.EligibilityFlag__c='Pending';
        progEnrollment1.PriorWithdrawalFlag__c='Hold';
        progEnrollment1.WaitlistFlag__c='Active';
        //progEnrollment1.UserTechnologyFlag__c='Technology Flag';
        progEnrollment1.DisciplinaryFlagOverride__c='Withdraw';
        progEnrollment1.HomelessRiskFlag__c='Potential Homeless';
        progEnrollment1.PrincipalGeneralFlag__c='Released';
        progEnrollment1.GradeLevelEligibility__c='Need additional information';
        progEnrollment1.EntranceAgeEligibility__c='Too old';
        insert progEnrollment1;
        
        Enrollment_Document__c eds=new Enrollment_Document__c();
        eds.Program_Enrollment__c=progEnrollment1.Id;
        eds.Type__c='IEP Exit Documentation';
        eds.Status_Reason__c='Awaiting IEP';
        insert eds;
       
        
        Special_Education__c speciEds=new Special_Education__c();
        speciEds.Program_Enrollment__c=progEnrollment1.Id;
        speciEds.IEP__c='Documenting';
        speciEds.Plan504__c='504 Missing';
       	speciEds.FormallyExitedIEP__c='Yes';
        
        insert speciEds;
        Annual_Student_Information__c asRecords = new Annual_Student_Information__c();
        asRecords.Program_Enrollment__c = progEnrollment1.id;
        asRecords.School_Year__c=previousSchoolYears.Id;
        insert asRecords;
    }
}