force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/MaxSpecialEdBirthdate__c.field-meta.xml
<CustomField>
    <fullName>MaxSpecialEdBirthdate__c</fullName>
    <description>Birth date when a student becomes too old to be eligible for Academic Program&apos;s Special Education programs</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Special Education Birthdate Max Cutoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Too_Young_Cutoff__c.field-meta.xml
<CustomField>
    <fullName>Too_Young_Cutoff__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Too Young Cutoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <formula>&apos;&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_Name__c</fullName>
        <description>The person the privacy request is for, if that person is not the requester (generally, this will be the student&apos;s name).</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Subject Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_of_Origin__c</fullName>
        <description>ADO #146813 - Support Agent to designate a case as Pre or Post Enrollment</description>
        <label>System of Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Enrollment</fullName>
                </value>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ticket_Sub_Type__c</fullName>
        <description>ADO #164365 - Ticket Sub - Type Values to be associated for the respective case - for case visibility.</description>
        <label>Ticket Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Ticket_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Ticket_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ticket_Type__c</fullName>
        <description>ADO #164365 - Ticket Type Values to be associated for the respective case - for case visibility.</description>
        <label>Ticket Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Extension/Exception Requests</fullName>
                </value>
                <value>
                    <fullName>File/Access Permissions</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Formative Assessments</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Google Apps</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Homeless</fullName>
                </value>
                <value>
                    <fullName>Household Account Assistance</fullName>
                </value>
                <value>
                    <fullName>Human Resources Inquiry</fullName>
                </value>
                <value>
                    <fullName>IEP</fullName>
                    <label>IEP Software</label>
                </value>
                <value>
                    <fullName>Internal Only-Issue Document Creation</fullName>
                </value>
                <value>
                    <fullName>Internet Filtering/Security</fullName>
                </value>
                <value>
                    <fullName>Jive</fullName>
                </value>
                <value>
                    <fullName>LEAP</fullName>
                </value>
                <value>
                    <fullName>LiveLesson</fullName>
                </value>
                <value>
                    <fullName>Login</fullName>
                </value>
                <value>
                    <fullName>Materials and Technology</fullName>
                </value>
                <value>
                    <fullName>Message Boards</fullName>
                </value>
                <value>
                    <fullName>Network &amp; Connectivity</fullName>
                </value>
                <value>
                    <fullName>New Computer Setup</fullName>
                </value>
                <value>
                    <fullName>Training/Orientation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Phone Call-Left Message</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Phone Hardware/Application Support</fullName>
                </value>
                <value>
                    <fullName>Placement Changes</fullName>
                </value>
                <value>
                    <fullName>Placement Recommendation Needed</fullName>
                </value>
                <value>
                    <fullName>Post-Enrollment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Learning_Coach</fullName>
        <active>true</active>
        <description>To capture Learning Coach details</description>
        <label>Learning Coach</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_AddHHMemApexControllerTest.cls
@isTest
public class NES_AddHHMemApexControllerTest {
    
   @TestSetup
    static void setup(){
        //Create Educational Institutional Account i.e.., Parent Account
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        
        //Insert the School Year record
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School', System.today());
        
        //Create Academic Program Account i.e.., Child Account
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
        academicProgram.Registration_Start_Date__c = System.today().addDays(-10);
        academicProgram.Registration_End_Date__c = System.today().addDays(10);
        academicProgram.MaxSpecialEdBirthdate__c = Date.today().addMonths(-2);
        update academicProgram;
        
        // Create a Contact with 'Caretaker' record type
        Contact careTakerContact = Peak_TestUtils.createTestContact('Caretaker', institutionAccount.Id);
        
        //Create a care taker user for community
        //User careTaker = Peak_TestUtils.CreatePortalCaretTakerUser(careTakerContact.Id);
        Profile profile_1 = [SELECT Id FROM Profile WHERE Name = 'Caretaker Community User' LIMIT 1];        
        User careTaker;        
        Account account_1 = new Account( Name = 'Community', Too_Young_Cutoff__c = System.today());
        insert account_1;
        Id caretakerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Caretaker').getRecordTypeId();
        
        Contact contact_1 = new Contact(AccountId = account_1.Id, LastName = 'xgeek',RecordTypeId=caretakerRecordTypeId);
        insert contact_1;
        System.debug('Student Id'+ contact_1.Id);
        careTaker = new User (
            Email = 'userTest@test.com',
            ProfileId = profile_1.Id,
            Username = 'addlHHMemUS@test.com',
            Alias = 'Test',
            TimeZoneSidKey = 'America/New_York',
            EmailEncodingKey = 'ISO-8859-1',
            LocaleSidKey = 'en_US',
            IsActive = true,
            LanguageLocaleKey = 'en_US',
            ContactId = contact_1.Id,
            PortalRole = 'Manager',
            FirstName = 'Testing',
            LastName = 'Portal User'
        );
        insert careTaker;
        
        Id studentRecordTypeId =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Students').getRecordTypeId();
        // Create a Contact with 'Students' record type
        Contact student = Peak_TestUtils.createTestContact();
        student.LastName='TestCon';
        student.Phone='8143098909';
        student.Birthdate__c=Date.newInstance(2014, 2, 17);
        student.AccountId=institutionAccount.Id;  
        student.RecordTypeId=studentRecordTypeId;
        update student;        
        
        //Create a relationship between the User Contact and Student Contact
        hed__Relationship__c  relationship = Peak_TestUtils.createRelationship(careTaker.ContactId, student.Id, true);  
    }
    static testMethod void LCTest(){
        User careTaker = [SELECT Id, ContactId FROM User WHERE Username = 'addlHHMemUS@test.com'];	
        Account institutionAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Educational Institution' LIMIT 1];
        Contact careTakerContact=[select id, RecordTypeId from Contact where RecordType.Name='Caretaker' Limit 1];
        
        System.runAs(careTaker) { 
            Test.startTest();
            NES_AddHHMemApexController.AdditionalHouseHoldMembers a = new NES_AddHHMemApexController.AdditionalHouseHoldMembers();
            a.fname = 'fname';
            a.lname = 'lname';
            a.mname = 'M';
            a.email = 'fname@test.com';
            a.phoneType = 'Mobile';
            a.phoneNumber = '1234512345';
            a.accountId = institutionAccount.Id;
            a.suffix = '';
            a.memberRTDeveloperName = 'Learning_Coach:Test';
            
            String cntct = JSON.serialize(a);
            System.debug('NDEBUG:: Final String:::' + cntct);
            
            Boolean StudentExists = NES_AddHHMemApexController.STExistsforCT();
            system.assertEquals(StudentExists, true);
            //System.debug('NDEBUG::: StudentExists' + StudentExists);
            NES_AddHHMemApexController.chkExistCnts(cntct);
            String response = NES_AddHHMemApexController.createAddlHHMemContact(cntct);
            //System.assertEquals('New Contact Created', response);
            Test.stopTest();   
            
            
        }
        /*
        //Check whether Case has been created with correct parameters
            List<Case> tickets=[select id,Description,Origin,Status,Subject,Subject_Name__c,System_of_Origin__c,Ticket_Sub_Type__c,Ticket_Type__c,Type
                                 from Case where ContactId=: careTakerContact.Id limit 1];
            System.assertEquals(1,tickets.size());
*/
        // Check the record type of the contact which has been created
            Id caretakerRecordTypeId =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Learning Coach').getRecordTypeId(); 
            List<Contact> contacts=[select id, RecordTypeId from Contact where firstName =: 'fname' and lastName =: 'lname' and email =: 'fname@test.com' limit 1];
            //System.assertEquals(1,contacts.size());
            //System.assertEquals(caretakerRecordTypeId, contacts[0].RecordTypeId);
    } 
    
    static testMethod void CTGaurdianest(){
        User careTaker = [SELECT Id, ContactId FROM User WHERE Username = 'addlHHMemUS@test.com'];	
        Account institutionAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Educational Institution' LIMIT 1];
        Contact careTakerContact=[select id, RecordTypeId from Contact where RecordType.Name='Caretaker' Limit 1];
        
        System.runAs(careTaker) {  
            Test.startTest();
            NES_AddHHMemApexController.AdditionalHouseHoldMembers a = new NES_AddHHMemApexController.AdditionalHouseHoldMembers();
            a.fname = 'fname';
            a.lname = 'lname';
            a.mname = 'M';
            a.email = 'fname@test.com';
            a.phoneType = 'Work';
            a.phoneNumber = '1234512345';
            a.accountId = institutionAccount.Id;
            a.suffix = '';
            a.memberRTDeveloperName = 'Caretaker_Designated:Test';
            
            String cntct = JSON.serialize(a);
            System.debug('NDEBUG:: Final String:::' + cntct);
            
            Boolean StudentExists = NES_AddHHMemApexController.STExistsforCT();
            system.assertEquals(StudentExists, true);
            NES_AddHHMemApexController.chkExistCnts(cntct);
            String response = NES_AddHHMemApexController.createAddlHHMemContact(cntct);
            System.assertEquals('New Contact Created', response);
            Test.stopTest();
            /*
            //Check whether Case has been created with correct parameters
            List<Case> tickets=[select id,Description,Origin,Status,Subject,Subject_Name__c,System_of_Origin__c,Ticket_Sub_Type__c,Ticket_Type__c,Type
                                 from Case where ContactId=: careTakerContact.Id limit 1];
            System.assertEquals(1,tickets.size());
			*/
            
        }
        // Check the record type of the contact which has been created
            Id caretakerRecordTypeId =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Caretaker').getRecordTypeId(); 
            List<Contact> contacts=[select id, RecordTypeId from Contact where firstName =: 'fname' and lastName =: 'lname' and email =: 'fname@test.com' limit 1];
            System.assertEquals(1,contacts.size());
            System.assertEquals(caretakerRecordTypeId, contacts[0].RecordTypeId);
    }
    
    static testMethod void CTParentest(){
        User careTaker = [SELECT Id, ContactId FROM User WHERE Username = 'addlHHMemUS@test.com'];	
        Account institutionAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Educational Institution' LIMIT 1];
        Contact careTakerContact=[select id, RecordTypeId from Contact where RecordType.Name='Caretaker' Limit 1];
        
        System.runAs(careTaker) {
            Test.startTest();
            NES_AddHHMemApexController.AdditionalHouseHoldMembers a = new NES_AddHHMemApexController.AdditionalHouseHoldMembers();
            a.fname = 'fname';
            a.lname = 'lname';
            a.mname = 'M';
            a.email = 'fname@test.com';
            a.phoneType = 'Home';
            a.phoneNumber = '1234512345';
            a.accountId = institutionAccount.Id;
            a.suffix = '';
            a.memberRTDeveloperName = 'Caretaker_Parent:Test';
            
            String cntct = JSON.serialize(a);
            System.debug('NDEBUG:: Final String:::' + cntct);
            
            Boolean StudentExists = NES_AddHHMemApexController.STExistsforCT();
            system.assertEquals(StudentExists, true);
            NES_AddHHMemApexController.chkExistCnts(cntct);
            String response = NES_AddHHMemApexController.createAddlHHMemContact(cntct);
            //System.assertEquals('New Contact Created', response);
            
            Test.stopTest();
            /*
            //Check whether Case has been created with correct parameters
            List<Case> tickets=[select id,Description,Origin,Status,Subject,Subject_Name__c,System_of_Origin__c,Ticket_Sub_Type__c,Ticket_Type__c,Type
                                 from Case where ContactId=: careTakerContact.Id limit 1];
            System.assertEquals(1,tickets.size());
*/
            
        }
        // Check the record type of the contact which has been created
            Id caretakerRecordTypeId =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Caretaker').getRecordTypeId(); 
            List<Contact> contacts=[select id, RecordTypeId from Contact where firstName =: 'fname' and lastName =: 'lname' and email =: 'fname@test.com' limit 1];
            //System.assertEquals(1,contacts.size());
            //System.assertEquals(caretakerRecordTypeId, contacts[0].RecordTypeId);
    }

    
}