force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Educational_Institution_SSTF_Mapping__mdt.object
<CustomObject>
    <description>This custom metadata is used to Assign Permission Set to School staff Community User (US#123101 - Task# 160180, 159334 &amp; 158397).</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <description>US #123101 - This field is set with the Public Group Name belonging to the Internal Staff users. This field gets set when the Batch Job named CS_SSTFPublicGroupUserPermissionBatch is executed.</description>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <description>US #123101 - This field is used to capture the associated permission set name belonging to the Internal Staff users. This field gets set when the Batch Job named CS_SSTFPublicGroupUserPermissionBatch is executed.</description>
        <label>Permission Set Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Profile__c</fullName>
        <description>US #123101 - This field captures the community user profile names. This field gets set when the Batch Job named CS_SSTFpermissionBatch is executed.</description>
        <label>User Profile</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Educational Institution_SSTF_Mapping</label>
    <pluralLabel>Educational Institution_SSTF_Mappings</pluralLabel>
</CustomObject>

force-app/main/default/classes/SSTFUserPermissionBatch_TEST.cls
/***************************************************************************************************************************************
* Name: SSTFUserPermissionBatch_TEST
****************************************************************************************************************************************
* Author: Ranjit Chaganti
* Purpose: This is a Test class for SSTFUserPermissionBatch (US#123101, Task # 159001).
* Created Date: 03/24/2020
****************************************************************************************************************************************
* <Modification History>
* <initials> - <date> - <reason for update>
*                     - <what was changed/added>
***************************************************************************************************************************************/

@isTest
public class SSTFUserPermissionBatch_TEST {
    
    @TestSetup
    public static void createTestData(){
        UserRole r=[Select Id from UserRole where PortalType ='none' limit 1];
        User u=new User(username='teste123@pearson.com.admin',
                        UserRoleId=r.Id,
                        alias = 'adminn',
                        timezonesidkey='America/Los_Angeles',
                        languagelocalekey='en_US',
                        localesidkey='en_US',emailencodingkey='UTF-8',country='United States',
                        profileId=UserInfo.getProfileId(),lastname='admin',email='test123@pearson.com.admin');
        insert u;
        System.runAs(u) {
            Id p = [select id from profile where name='School Staff Community User'].id;
            Id recordTypeIdEI  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Educational Institution').getRecordTypeId();
            Account ac = new Account(name ='TNCA',recordtypeId = recordTypeIdEI) ;
            insert ac; 
            
            Contact con = new Contact(LastName ='testCon',AccountId = ac.Id);
            insert con;  
            
            
            
            User user = new User(alias = 'SSFT', email='test123@pearson.com',
                                 emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                                 localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                                 ContactId = con.Id,
                                 timezonesidkey='America/Los_Angeles', username='teste123@pearson.com');       
           insert user;        
        }
    }
    
    private static TestMethod void runBatch(){
        
        User u=new User(Id=UserInfo.getUserId());
        Group groupRecord = [Select Id from Group where Name='TNCA'];
        insert new groupmember(groupId=groupRecord.Id,UserOrGroupId=u.Id);
        System.runAs(u) {            
            test.starttest();
            Database.executeBatch(new SSTFUserPermissionBatch());
            /*SSTFPublicGroupUserPermissionBatch groupUserPermission = new SSTFPublicGroupUserPermissionBatch();
            groupUserPermission.EISSTFMappingList=[SELECT MasterLabel,Permission_Set_Name__c,User_Profile__c,Group_Name__c
                                                   FROM Educational_Institution_SSTF_Mapping__mdt where Group_Name__c='TNCA'];
           
            Database.executeBatch(groupUserPermission,1);*/
            String chron = '0 0 23 * * ?';        
            //system.schedule('Assign PermissionSet 1', chron, groupUserPermission);
            SSTFUserPermissionBatch sch = new SSTFUserPermissionBatch ();   
            system.schedule('Assign PermissionSet 2', chron, sch);
            test.stopTest();
        }
    }
}