force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Computer_in_Home__c.field-meta.xml
<CustomField>
    <fullName>Computer_in_Home__c</fullName>
    <description>Indicator of whether or not the family has a computer in their home.</description>
    <label>Do you have a computer in your home</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Internet_Connection_Type__c.field-meta.xml
<CustomField>
    <fullName>Internet_Connection_Type__c</fullName>
    <description>Internet connection type for the household.</description>
    <label>Internet Connection Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cable</fullName>
            </value>
            <value>
                <fullName>Dial-up</fullName>
            </value>
            <value>
                <fullName>DSL</fullName>
            </value>
            <value>
                <fullName>Mobile hotspot</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Other - High Speed</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LC_HighestLevelofEducation__c.field-meta.xml
<CustomField>
    <fullName>LC_HighestLevelofEducation__c</fullName>
    <description>The highest level of education recieved by the learning coach</description>
    <label>LC Highest Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>College graduate (Bachelor&apos;s degree)</fullName>
            </value>
            <value>
                <fullName>Graduate school / Post-graduate training</fullName>
            </value>
            <value>
                <fullName>High school graduate</fullName>
            </value>
            <value>
                <fullName>I decline to state</fullName>
            </value>
            <value>
                <fullName>Not a high school graduate</fullName>
            </value>
            <value>
                <fullName>Some college or associate&apos;s degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mktg_Customer_Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Mktg_Customer_Loyalty__c</fullName>
    <description>Returning family with an application for the new school year</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Mktg Customer Loyalty</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Id__c.field-meta.xml
<CustomField>
    <fullName>School_Id__c</fullName>
    <description>This field holds school unique Id values</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>School Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Living_Accommodations__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Living_Accommodations__c</fullName>
    <description>The type of living situation the student(s) has at the primary nighttime residence.</description>
    <label>Type of Living Accommodations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In a shelter</fullName>
            </value>
            <value>
                <fullName>Awaiting foster care placement</fullName>
            </value>
            <value>
                <fullName>In a hotel or motel</fullName>
            </value>
            <value>
                <fullName>In a temporary trailer, campground, car, or park due to the lack of alternative accommodations</fullName>
            </value>
            <value>
                <fullName>None of the above</fullName>
            </value>
            <value>
                <fullName>With more than one family in a house or an apartment NOT due to loss of housing or economic hardship</fullName>
            </value>
            <value>
                <fullName>With More Than One Family In A House, An Apartment Or Other Transitional Housing Due To Loss Of Housing Or Economic Hardship</fullName>
            </value>
            <value>
                <fullName>In a shelter or transitional housing</fullName>
            </value>
            <value>
                <fullName>With more than one family in a house or an apartment due to loss of housing or economic hardship</fullName>
            </value>
            <value>
                <fullName>2+ Families In A Shared Living Situation Due To Loss Of Housing Or Economic Hardship</fullName>
            </value>
            <value>
                <fullName>House, apartment, or mobile home</fullName>
            </value>
            <value>
                <fullName>Motel, car, or campsite</fullName>
            </value>
            <value>
                <fullName>Travel/Live in motor home</fullName>
            </value>
            <value>
                <fullName>A Primary Nighttime Residence Not Designed For Regular Sleeping Accommodations</fullName>
            </value>
            <value>
                <fullName>A primary nighttime residence that is a public or private place not designed for or ordinarily used</fullName>
                <isActive>false</isActive>
                <label>A primary nighttime residence that is a public or private place not designed for or ordinarily used</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_AccountBusinessLogicTest.cls
/**
 * Created by Ajith on 17-04-2019.
 */

@isTest
public with sharing class NES_AccountBusinessLogicTest {
    @TestSetup
    static void setup(){
        Peak_TestUtils.createNESBusinessLogicSwitch('AccountTrigger', true);
        Peak_TestUtils.createNESBusinessLogicSwitch('Likelihood to Transition Score', true);
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
        Id AccountHouseholdRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        Account householdAccount = new Account();
        householdAccount.Name = 'Household Account';
        householdAccount.RecordTypeId = AccountHouseholdRecordTypeId;
        householdAccount.LC_HighestLevelofEducation__c = 'High school graduate';
        insert householdAccount;
        
    }
    static testMethod void createUniqueIDTest(){
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
    }
    static testMethod void populateSchoolIDTest(){
        Account account1 = [SELECT Id, Name, RecordType.Name FROM Account WHERE RecordType.Name = 'Educational Institution' limit 1];
        account1.Name = 'New name';
        account1.School_Id__c = '';
        update account1;
    }
    static testMethod void calculateHomelessRiskFlagTest(){
        Account account1 = [SELECT Id, Name, RecordType.Name FROM Account WHERE RecordType.Name = 'Household'];
        account1.Name = 'New name';
        account1.School_Id__c = '';
        account1.Type_of_Living_Accommodations__c = 'A Primary Nighttime Residence Not Designed For Regular Sleeping Accommodations';
        update account1;
    }
    static testMethod void calculateLTSTest1(){
        Account account1 = [SELECT Id, Name, RecordType.Name FROM Account WHERE RecordType.Name = 'Household'];
        account1.Name = 'New name';
        account1.School_Id__c = '';
        account1.Type_of_Living_Accommodations__c = 'A Primary Nighttime Residence Not Designed For Regular Sleeping Accommodations';
        account1.Internet_Connection_Type__c = 'DSL';
        update account1;
    }
    static testMethod void calculateLTSTest2(){
        Account account1 = [SELECT Id, Name, RecordType.Name FROM Account WHERE RecordType.Name = 'Household'];
        account1.Internet_Connection_Type__c = 'Cable';
        account1.LC_HighestLevelofEducation__c = 'High school graduate';
        account1.Mktg_Customer_Loyalty__c = 'Test Customer Loyalty';
        account1.Computer_in_Home__c = 'Yes';
        update account1;
    }
    
}