force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Process_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic program associated with the component. This is exclusively used by components with a record type of Process to create a relationship between the account entity and it&apos;s required components. As the child components of the process could be used by multiple processes, there is not a direct relationship between them and a specific academic program and those relationships are inferred from their parent process.</description>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enrollment Components (Academic Program)</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/PicklistSelectorController.cls
/**
 *  
 *  code from: https://medium.com/@aneudupi/custom-picklist-component-using-lwc-e6014a0de9c5
 * 
 *  @Usage: 
        List<Map<String, String>> options = PicklistSelectorController.getAllProcessOptions();
        System.debug(JSON.serialize(options));
 *
 *        
 */
public with sharing class PicklistSelectorController {

    @AuraEnabled
    public static List<Map<String, String>> getAllProcessOptions(){

        List<Map<String, String>> options = new List<Map<String, String>>();
        Map<String, String> tempValues; 

        for (Enrollment_Component__c processEC : [
            SELECT      Id, Process_Academic_Program__r.Name 
            FROM        Enrollment_Component__c 
            WHERE       Process_Academic_Program__c != null 
            ORDER BY    CreatedDate DESC 
            LIMIT       50
        ]) 
        {
            options.add( 
                new Map<String, String>{
                    'label' => processEC.Process_Academic_Program__r.Name,
                    'value' => processEC.Id
                } 
            );
        }

        return options;        
        
    }


    /**
        >>> BELOW NOT NEEDED FOR OUR PURPOSE >>>
            @AuraEnabled
            public static List < Map < String, String >> getPickListValues(String objApiName, String fieldName) {
                List < Map < String, String >> options = new List < Map < String, String >> ();
                Map < String, Schema.SObjectType > objGlobalMap = Schema.getGlobalDescribe();
                Schema.SObjectType objType = Schema.getGlobalDescribe().get(objApiName);
                if (objType == null) {
                    return options;
                }
                Schema.DescribeSObjectResult sobjectDescribe = objType.getDescribe();
                Map < String, Schema.SObjectField > fieldMap = sobjectDescribe.fields.getMap();
                if (fieldMap.get(fieldName) == null) {
                    return options;
                }
                List < Schema.PicklistEntry > pickListValues = fieldMap.get(fieldName).getDescribe().getPickListValues();
                for (Schema.PicklistEntry f: pickListValues) {
                    Map < String, String > values = new Map < String, String > {
                        'label' => f.getLabel(),
                        'value' => f.getValue()
                    };
                    options.add(values);
                }
                return options;
            }
            @AuraEnabled
            public static Map < Object, List < Map < String, String >>> getDependentOptions(String objApiName, String fieldName, String contrFieldApiName) {
                return FieldUtilityClass.getFieldDependenciesMaps(objApiName, contrFieldApiName, fieldName);
            }
            @AuraEnabled
            public static String getFieldLabel(String objName, String fieldName) {
                return FieldUtilityClass.getFieldLabel(objName, fieldName);
            }
        >>> END >>>
    */

}