force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Alt_Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Alt_Shipping_City__c</fullName>
    <description>Shipping City for Alternative Shipping Address.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Alternative Shipping City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Alt_Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>Alt_Shipping_State__c</fullName>
    <description>Start date for Alternative Shipping Address.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Alternative Shipping State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Alt_Shipping_Street_1__c.field-meta.xml
<CustomField>
    <fullName>Alt_Shipping_Street_1__c</fullName>
    <description>Shipping Street 1 for Alternative Shipping Address.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Alternative Shipping Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Family_Enrollment_Counselor__c.field-meta.xml
<CustomField>
    <fullName>Family_Enrollment_Counselor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US: 120471
Name of the FEC assisting this Household</description>
    <label>Family Enrollment Counselor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Use_Updated_ECA_Process__c.field-meta.xml
<CustomField>
    <fullName>Use_Updated_ECA_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created by Mark Membrino while rewriting the ECA processing.</description>
    <label>Use Updated ECA Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Family_Enrollment_Counselor__c.field-meta.xml
<CustomField>
    <fullName>Family_Enrollment_Counselor__c</fullName>
    <description>Allows a user to see on the PE who the FEC is for this family.</description>
    <formula>hed__Contact__r.Account.Family_Enrollment_Counselor__r.FirstName + &apos; &apos; + hed__Contact__r.Account.Family_Enrollment_Counselor__r.LastName</formula>
    <label>Family Enrollment Counselor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Old_Status__c.field-meta.xml
<CustomField>
    <fullName>Old_Status__c</fullName>
    <description>Added to capture Old Status value of the PE Record as per US # 186957 (Task# 195460, 195459)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Old Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/OrderingHoldDate__c.field-meta.xml
<CustomField>
    <fullName>OrderingHoldDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ordering Hold Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/OrderingHoldFlag__c.field-meta.xml
<CustomField>
    <fullName>OrderingHoldFlag__c</fullName>
    <description>Hold equipment orders until a specified date</description>
    <label>Ordering Hold Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold Equipment Orders</fullName>
            </value>
            <value>
                <fullName>Withdrawal Process</fullName>
            </value>
            <value>
                <fullName>Alternate Shipping</fullName>
            </value>
            <value>
                <fullName>Not Default Household</fullName>
            </value>
            <value>
                <fullName>POR</fullName>
            </value>
            <value>
                <fullName>Summer School</fullName>
            </value>
            <value>
                <fullName>Private Address</fullName>
            </value>
            <value>
                <fullName>Tech Invoice</fullName>
            </value>
            <value>
                <fullName>Materials Flag</fullName>
            </value>
            <value>
                <fullName>Vacation/Delay Shipment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NES_AccountHandler.cls
/**
* Created by Ritvik on 25-10-2018.
* Purpose : Handler Class for AccountTrigger.
*/
public without sharing class NES_AccountHandler {
   
    static final Boolean logicSwitch = NES_TriggerUtility.BusinessLogicSwitch('AccountTrigger');
    static final Boolean likelihoodToTransitionScore = NES_TriggerUtility.BusinessLogicSwitch('Likelihood to Transition Score');
    //Swapna:Functionality depricated
    /*  public static void handleBeforeUpdate(Map<Id, Account> oldMap, Map<Id, Account> newMap) {
if (!logicSwitch) return;
NES_AccountBusinessLogic.populateSchoolID(oldMap, newMap);
}*/
   
    // public static void handleAfterUpdate(Map<Id, Account> oldMap, Map<Id, Account> newMap) { //Swapna:Changed method signature
    public static void handleAfterUpdate(Map<Id, Account> oldMap, Map<Id, Account> newMap,Map<Id, Account> actlstoldMap, Map<Id, Account> actlstnewMap) {
        
        //Find the changed fields and pass to the program enrollments that are using the new ECA process.
        //Create a map between each changed account and a map of the changed fields with their new values.
        Map<Id, Map<String, object>> AcctsToChangedFieldNewValMap = new Map<Id, Map<String, Object>> ();
        List<EvaluationUtils.fieldUpdate> fieldUpdateList = new List<EvaluationUtils.fieldUpdate> (); //How we track field changes in the new ECA model.
        Map<String, Schema.SObjectField> mapFields = Schema.SObjectType.account.fields.getMap();
        Map<Id, Account> FECupdatedAccounts = new Map<Id, Account>(); // used to track FEC field updated Accounts;Added for US #247791

        for (account a : actlstnewMap.values()) {  //Iterate over all accounts
            account oldAcct = actlstoldMap.get(a.Id); 
            for (String str : mapFields.keySet()) {  //Iterate over all fields
                if (a.get(str) != oldAcct.get(str)) {  //Any field that has been updated should go in the map.
                    Map<String, object> thisAccountsChangedFields;
                    if (!AcctsToChangedFieldNewValMap.containsKey(a.id)) {  //instantiate the new inner map if we don't have this account yet.
                        thisAccountsChangedFields = new Map<String, object> ();
                        AcctsToChangedFieldNewValMap.put(a.Id, thisAccountsChangedFields);
                    }
                    else
                        thisAccountsChangedFields = AcctsToChangedFieldNewValMap.get(a.id);

                    thisAccountsChangedFields.put(str, a.get(str) );  //add the column and the new Value for later use.
                    
                    if(str == 'family_enrollment_counselor__c'){  // Checking if updated field is 'Family_Enrollment_Counselor__c'; Added for US #247791
                        FECupdatedAccounts.put(a.Id,a);             // adding account to the tracking map variable 'FECupdatedAccounts' ; Added for US #247791
                    }
                }
            }
        }

        System.debug ('AcctsToChangedFieldNewValMap:' + AcctsToChangedFieldNewValMap);
        System.debug ('AcctsToChangedFieldNewValMap.keySet():' + AcctsToChangedFieldNewValMap.keySet());

        System.debug ('FECupdatedAccounts:' + FECupdatedAccounts); // Added for US #247791
        
        //Find the Program Enrollments that are tied to any of the changed accounts that are using the new ECA process.
        if (AcctsToChangedFieldNewValMap.size() > 0) {
            list <hed__Program_Enrollment__c> PEsToCheck = new list <hed__Program_Enrollment__c>
                    ([ Select id, hed__Contact__r.AccountId from hed__Program_Enrollment__c  where hed__Contact__r.AccountId IN :AcctsToChangedFieldNewValMap.keySet() and hed__Account__r.Use_Updated_ECA_Process__c = true and status__c = 'In Progress']);
            for (hed__Program_Enrollment__c pe : PEsToCheck)  {
                //Get the changed fields for this account.
                Map<String, object> thisAccountsChangedFields = AcctsToChangedFieldNewValMap.get(pe.hed__Contact__r.AccountId);

                //Iterate over the changed fields for the account that is tied to this PE
                for (String fieldName : thisAccountsChangedFields.keySet()){
                    EvaluationUtils.fieldUpdate newFieldUpdate = new EvaluationUtils.fieldUpdate ();
                    newFieldUpdate.programEnrollmentId = pe.Id;
                    newFieldUpdate.objectAndFieldName = 'account.' + fieldName;
                    newFieldUpdate.newValue = thisAccountsChangedFields.get(fieldName);
                    fieldUpdateList.add(newFieldUpdate);
                }
            }
            
            System.debug ('fieldUpdateList:' + fieldUpdateList);

            if (fieldUpdateList.size() > 0)  //Must be at least one PE in the NEW ECA model that has a changed field so call the new ECA stuff.
                EvaluationUtils.evaluateChangedFields  (fieldUpdateList);
        }


        
        // NES_AccountBusinessLogic.calculateHomelessRiskFlag(newMap, oldMap);
        NES_AccountBusinessLogic.calculateHomelessRiskFlag(actlstnewMap, actlstoldMap);//Swapna:Changed to active list
       
        if (likelihoodToTransitionScore) {
            //    NES_AccountBusinessLogic.calculateLTS(newMap.values(), oldMap);
            NES_AccountBusinessLogic.calculateLTS(actlstnewMap.values(), actlstoldMap);//Swapna:Changed to active list
           
        }
        /*NES_AccountBusinessLogic.recalcAddrEligIfRequired(newMap.values(), oldMap);
NES_AccountBusinessLogic.recalcTechnologyFlag(newMap.values(), oldMap); */
        //Swapna:Changed to active list
        NES_AccountBusinessLogic.recalcAddrEligIfRequired(actlstnewMap.values(), actlstoldMap);
        
        //Commented Deprecate Technology flag logic for US 476956
        //NES_AccountBusinessLogic.recalcTechnologyFlag(actlstnewMap.values(), actlstoldMap);
       
        //Added/changed by Chinna on 8 , 9th and 10 april 2020
        //Map<Id, Account> accountsMap = new Map<Id, Account>();
        //for(Account acc : newMap.values()){
        //    Account oldAcc = oldMap.get(acc.Id);
        //    if(acc.Alt_Shipping_City__c <> oldAcc.Alt_Shipping_City__c ||
        //       acc.Alt_Shipping_State__c <> oldAcc.Alt_Shipping_State__c ||
        //       acc.Alt_Shipping_Street_1__c <> oldAcc.Alt_Shipping_Street_1__c){
        //           accountsMap.put(acc.Id, acc);
        //       }
        //}
        //if(!accountsMap.isEmpty()){
        //    updatePEOrderingFlag(accountsMap);
        //}

    }
    //Swapna:Functionality depricated
    /*  public static void handleBeforeInsert(List<Account> newMap) {
if (!logicSwitch) return;
NES_AccountBusinessLogic.createUniqueID(newMap);
}*/
   
    // public static void handleAfterInsert(List<Account> newList, Map<Id, Account> oldMap) {
    //Swapna:Changed method signature
    public static void handleAfterInsert(List<Account> newList, Map<Id, Account> oldMap,List<Account> actList) {
        if (likelihoodToTransitionScore) {
            // NES_AccountBusinessLogic.calculateLTS(newList, null);
            NES_AccountBusinessLogic.calculateLTS(actList, null); //Swapna:CHanged to active list
        }
    }
   
    //Added by chinna on 8 april 2020
    //public static void updatePEOrderingFlag(Map<Id, Account> accountsMap){
    //    List<hed__Program_Enrollment__c> PEList = [Select Id, OrderingHoldDate__c, OrderingHoldFlag__c from hed__Program_Enrollment__c where hed__Account__c IN: accountsMap.keyset() AND RecordType.Name = 'Caretaker'AND Status__c = 'Complete' AND Old_Status__c = 'In Progress' limit 5];
    //    for(hed__Program_Enrollment__c PE : PEList){
    //        PE.OrderingHoldDate__c = System.Date.Today();
    //        PE.OrderingHoldFlag__c = 'Alternate Shipping';
    //    }
    //    update PEList;
    //}
}