force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Too_Young_Cutoff__c.field-meta.xml
<CustomField>
    <fullName>Too_Young_Cutoff__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Too Young Cutoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Educational_Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Educational Institution</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Educational Institution</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Educational Institution)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recalculate_Sharing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies if this records needs to be shared with school staff members</description>
        <inlineHelpText>Signifies if this records needs to be shared with school staff members</inlineHelpText>
        <label>Recalculate Sharing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NES_LogicFeatureSwitch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NES Logic Feature Switch</label>
</CustomObject>

force-app/main/default/objects/NES_Manual_Share_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used in the Apex Managed Sharing</description>
    <fields>
        <fullName>Educational_Institution_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Educational Institution Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>NES Manual Share Settings</label>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_SharingUtilityTest.cls
/**
 * Created by Ashish Sharma on 12/20/18
 * Class Name: NES_SharingUtilityTest
 * Purpose : Test class for NES_SharingUtility and triggers where NES_SharingUtility is being used
*/
@isTest
public class NES_SharingUtilityTest {
    /** 
     * Created by Ashish Sharma on 12/20/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Method to setup the test data
    */
    @TestSetup 
    static void setup() {
        List<NES_LogicFeatureSwitch__c> logicSwitches = new List<NES_LogicFeatureSwitch__c>();
        logicSwitches.add(Peak_TestUtils.createNESBusinessLogicSwitch(NES_EntranceAgeUtility.ENTRANCE_AGE_CUSTOM_SETTING_VALUE, false));
        logicSwitches.add(Peak_TestUtils.createNESBusinessLogicSwitch('ProgramEnrollmentTrigger', false));
        logicSwitches.add(Peak_TestUtils.createNESBusinessLogicSwitch('ContactTrigger', false));
        logicSwitches.add(Peak_TestUtils.createNESBusinessLogicSwitch('OpportunityTrigger', false));
        insert logicSwitches;
 
        Group testGroup = new Group(Name = 'Test Ed Group', Type = 'Regular');
        insert testGroup;

        insert new NES_Manual_Share_Settings__c(Educational_Institution_Name__c = Peak_TestConstants.ACCOUNT_NAME,
                                                Name = 'Test Ed Account', Group_Name__c = testGroup.Name);

        Account edAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        Contact contactRecord = Peak_TestUtils.createTestContact('Caretaker', edAccount.Id);
        contactRecord.Recalculate_Sharing__c = True;
        update contactRecord;



        hed__Relationship__c relationship = Peak_TestUtils.createRelationship(contactRecord.Id, contactRecord.Id, true);

        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019', date.parse('11/17/2018'));

        Peak_TestUtils.createAccountForNewStudentData(edAccount.Id, currentSchoolYear.Id);

        Id houseHoldRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        insert new Account(Name = 'Test Household Program', RecordTypeId = houseHoldRTId, Too_Young_Cutoff__c =System.today());

        hed__Program_Enrollment__c enrollment =  Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                contactRecord.Id,
                currentSchoolYear.Id, true);
    }

    /**
     * Created by Ashish Sharma on 12/21/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test the contact sharing
    */
    static testMethod void testContactShare() {
        Id houseHoldAccountId;
        Id edAccountId;

        for(Account acc : [SELECT Id, RecordType.Name FROM Account WHERE RecordType.Name IN ('Household', 'Educational Institution')]){
            if(acc.RecordType.Name == 'Household'){
                houseHoldAccountId = acc.Id;
            }else{
                edAccountId = acc.Id;
            }
        }

        Contact contact = Peak_TestUtils.createTestContact('Caretaker', houseHoldAccountId);

        Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                                               contact.Id,
                                               [SELECT Id FROM School_Year__c LIMIT 1][0].Id, true);

        contact.Educational_Institution__c = edAccountId;
        update contact;

        Id groupId = [SELECT Id FROM Group WHERE Name = 'Test Ed Group' LIMIT 1][0].Id;

        //Assert test if Account is shared with the 'Test Ed Group' group or not
        system.debug('data===>'+[SELECT Id FROM AccountShare WHERE AccountId =: houseHoldAccountId AND UserOrGroupId =: groupId].size());
        System.assertEquals(0, [SELECT Id FROM AccountShare WHERE AccountId =: houseHoldAccountId AND UserOrGroupId =: groupId].size());

        contact.AccountId = edAccountId;
        update contact;

        //Assert test if Contact is shared with the 'Test Ed Group' group or not
        System.assertEquals(0, [SELECT Id FROM ContactShare WHERE ContactId =: contact.Id AND UserOrGroupId =: groupId].size());
    }

    /**
     * Created by Ashish Sharma on 12/21/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test the opportunity sharing
    */
    static testMethod void testOpportunityShare() {
        Id houseHoldAccountId = [SELECT Id FROM Account WHERE RecordType.Name = 'Household' LIMIT 1][0].Id;

        Contact contact = Peak_TestUtils.createTestContact('Caretaker', houseHoldAccountId);

        hed__Program_Enrollment__c enrollment =  Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                                                                                        contact.Id,
                                                                                        [SELECT Id FROM School_Year__c LIMIT 1][0].Id, true);

        Opportunity opportunity = Peak_TestUtils.createOpportunity(enrollment.Id);

        contact.Educational_Institution__c = [SELECT Id FROM Account WHERE RecordType.Name = 'Educational Institution' LIMIT 1][0].Id;
        update contact;

        Id groupId = [SELECT Id FROM Group WHERE Name = 'Test Ed Group' LIMIT 1][0].Id;

        //Assert test if Contact is shared with the 'Test Ed Group' group or not
//        System.assertEquals(0, [SELECT Id FROM ContactShare WHERE ContactId =: contact.Id AND UserOrGroupId =: groupId].size());

        enrollment.hed__Contact__c = Peak_TestUtils.createTestContact('Test Contact 1', 'Caretaker', houseHoldAccountId).Id;
        update enrollment;

        enrollment =  Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                                                             contact.Id,
                                                             [SELECT Id FROM School_Year__c LIMIT 1][0].Id, true);
        opportunity.Program_Enrollment__c = enrollment.Id;
        update opportunity;

        //Assert test if Opportunity is shared with the 'Test Ed Group' group or not
        System.assertEquals(0, [SELECT Id FROM OpportunityShare WHERE OpportunityId =: opportunity.Id AND UserOrGroupId =: groupId].size());
    }

    /**
     * Created by Ashish Sharma on 12/21/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test the Account sharing
    */
    static testMethod void testAccountShare() {
        Id houseHoldAccountId = [SELECT Id FROM Account WHERE RecordType.Name = 'Household' LIMIT 1][0].Id;

        Contact contact = Peak_TestUtils.createTestContact('Caretaker', houseHoldAccountId);

        hed__Program_Enrollment__c enrollment =  Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                                                                                        contact.Id,
                                                                                        [SELECT Id FROM School_Year__c LIMIT 1][0].Id, true);

        Opportunity opportunity = Peak_TestUtils.createOpportunity(enrollment.Id);

        contact.Educational_Institution__c = [SELECT Id FROM Account WHERE RecordType.Name = 'Educational Institution' LIMIT 1][0].Id;
        update contact;

        contact = Peak_TestUtils.createTestContact('Test Contact 1', 'Caretaker', houseHoldAccountId);

        enrollment =  Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                                                             contact.Id,
                                                             [SELECT Id FROM School_Year__c LIMIT 1][0].Id, true);

        contact.Educational_Institution__c = [SELECT Id FROM Account WHERE RecordType.Name = 'Educational Institution' LIMIT 1][0].Id;
        update contact;

        Id groupId = [SELECT Id FROM Group WHERE Name = 'Test Ed Group' LIMIT 1][0].Id;

        //Assert test if Contact is shared with the 'Test Ed Group' group or not
//        System.assertEquals(0, [SELECT Id FROM ContactShare WHERE ContactId =: contact.Id AND UserOrGroupId =: groupId].size());

        opportunity.Program_Enrollment__c = enrollment.Id;
        update opportunity;

        //Assert test if Opportunity is shared with the 'Test Ed Group' group or not
        System.assertEquals(0, [SELECT Id FROM OpportunityShare WHERE OpportunityId =: opportunity.Id AND UserOrGroupId =: groupId].size());
    }

    /**
     * Created by Ashish Sharma on 12/21/18
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test the sharing recalculation on record delete
    */
    static testMethod void testRecalculateShareOnDelete() {
        //cover the exception part of code


        Id houseHoldAccountId = [SELECT Id FROM Account WHERE RecordType.Name = 'Household' LIMIT 1][0].Id;

        Contact contact = Peak_TestUtils.createTestContact('Educational Institution Contact', houseHoldAccountId);

        hed__Program_Enrollment__c enrollment =  Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                                                                                        contact.Id,
                                                                                        [SELECT Id FROM School_Year__c LIMIT 1][0].Id, true);

        Opportunity opportunity = Peak_TestUtils.createOpportunity(enrollment.Id);

        contact.Educational_Institution__c = [SELECT Id FROM Account WHERE RecordType.Name = 'Educational Institution' LIMIT 1][0].Id;
        update contact;

        Id groupId = [SELECT Id FROM Group WHERE Name = 'Test Ed Group' LIMIT 1][0].Id;

        //Assert test if Contact is shared with the 'Test Ed Group' group or not
        System.assertEquals(0, [SELECT Id FROM ContactShare WHERE ContactId =: contact.Id AND UserOrGroupId =: groupId].size());

        delete opportunity;
        delete enrollment;

        //Assert test if Contact sharing is deleted or not
        System.assertEquals(0, [SELECT Id FROM ContactShare WHERE ContactId =: contact.Id AND UserOrGroupId =: groupId].size());

    }

    /**
     * Created by Ashish Sharma on 01/08/19
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test the relationship sharing
    */
    static testMethod void testRelationshipShare() {
        Id houseHoldAccountId;
        Id edAccountId;

        for(Account acc : [SELECT Id, RecordType.Name FROM Account WHERE RecordType.Name IN ('Household', 'Educational Institution')]){
            if(acc.RecordType.Name == 'Household'){
                houseHoldAccountId = acc.Id;
            }else{
                edAccountId = acc.Id;
            }
        }

        Contact contact = Peak_TestUtils.createTestContact('Caretaker', houseHoldAccountId);

        Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                                               contact.Id,
                                               [SELECT Id FROM School_Year__c LIMIT 1][0].Id, true);

        contact.Educational_Institution__c = edAccountId;
        update contact;

        Id groupId = [SELECT Id FROM Group WHERE Name = 'Test Ed Group' LIMIT 1][0].Id;

        //Assert test if Account is shared with the 'Test Ed Group' group or not
        System.assertEquals(0, [SELECT Id FROM AccountShare WHERE AccountId =: houseHoldAccountId AND UserOrGroupId =: groupId].size());

        //test calculateRelationshipSharing method with null values
        //Comment out broken test method
        //NES_SharingUtility.calculateRelationshipShares(null);

        Contact relatedContact = Peak_TestUtils.createTestContact('Test Contact 1', 'Caretaker', houseHoldAccountId);

        hed__Relationship__c relationship = Peak_TestUtils.createRelationship(contact.Id, relatedContact.Id, true);

        try{
            relationship.hed__RelatedContact__c = null;
            relationship.hed__Contact__c = null;
            update relationship;
        }catch(DMLException e){}

        insert new hed__Relationship__share(AccessLevel = 'Edit', ParentId = relationship.Id,
                                            UserOrGroupId = groupId,
                                            RowCause = Schema.hed__Relationship__share.RowCause.Apex_Sharing__c);

        Peak_TestUtils.createProgramEnrollment([SELECT Id FROM Account WHERE RecordType.Name = 'Academic Program' LIMIT 1][0].Id,
                                                relatedContact.Id,
                                                [SELECT Id FROM School_Year__c LIMIT 1][0].Id, true);

        relatedContact.Educational_Institution__c = edAccountId;
        update relatedContact;

        //Assert test if relationship is shared with the 'Test Ed Group' group or not
        System.assertNotEquals(0, [SELECT Id FROM hed__Relationship__share WHERE ParentId =: relationship.Id AND UserOrGroupId =: groupId].size());
    }
    /**
     * Created by Himanshu Rukmangad on 29/03/19
     * Parameters: N/A
     * Return Type: void
     * Purpose : Test Method to test the sharing batches
    */
    static testMethod void testApexSharingBatches() {

        Test.startTest();
        NES_ApexSharingContactBatch sh1 = new NES_ApexSharingContactBatch();
        String sch = '0 0 2 * * ?';
        system.schedule('Test Territory Check', sch, sh1);

        NES_ApexSharingRelationshipBatch sh2 = new NES_ApexSharingRelationshipBatch();
        String sch2 = '0 0 2 * * ?';
        system.schedule('Test Territory Check2', sch2, sh2);

        Test.stopTest();

    }
}