force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Start Year (calculated)</description>
    <label>Start Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_CreateTestStudent.cls
/**
 * Created by: Alex Chisholm on 05/06/2019
 * Class Name: NES_CreateTestStudent
 * Purpose : Service class for creating enrolled student test records
*/
@RestResource(urlMapping='/CreateTestStudent/*')
global with sharing class NES_CreateTestStudent {
 @httppost
    global static void doPost() {
        //instantiate rest response and request
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        //get parameters from the request
        String firstName = req.params.get('firstName');
        String lastName = req.params.get('lastName');
        String schoolID = req.params.get('schoolID');
        String schoolYear = req.params.get('schoolYear');
        String gradeLevel = req.params.get('gradeLevel');
        String householdID = req.params.get('householdID');
        String caretakerID = req.params.get('caretakerID');

        if (!String.isBlank(firstName)&& !String.isBlank(lastName) && !String.isblank(schoolID) && !String.isblank(schoolYear) && !String.isblank(gradeLevel)
        && !String.isblank(householdID)) {
        
            /* Create Student Contact and add them to the household account */
            Account[] HH = new List<Account>([SELECT ID FROM Account WHERE ID =: householdID]);
            Contact student = new Contact(
                firstName = firstName,
                lastName = lastName,
                Account = HH[0]);
            
            /* Determine the caretaker */
            Contact[] caretaker = new List<Contact>([SELECT ID FROM CONTACT WHERE ID =: caretakerID]);
            
            /* Create relationship record */
            hed__relationship__c rel = new hed__relationship__c(
                hed__Contact__r = student,
                hed__RelatedContact__r = caretaker[0],
                hed__type__c = 'Parent'
            );
                
            /* Determine the Academic Program */
            Account[] AP = new List<Account>([SELECT ID, School_Year__c FROM Account WHERE ParentID =: schoolID AND School_Year__r.External_ID__c =: schoolYear]);
            
            /* Create the caretaker program enrollment */
            hed__program_enrollment__c caretakerPE = new hed__program_enrollment__c(
                Start_Year__c = AP[0].School_Year__c,
                hed__Account__r = AP[0],
                hed__Contact__r = caretaker[0]
            );
                        
            /* Create the student program enrollment */
            hed__program_enrollment__c studentPE = new hed__program_enrollment__c(
                Start_Year__c = AP[0].School_Year__c,
                hed__Account__r = AP[0],
                hed__Contact__r = student,
                Household_Program_Enrollment__r = caretakerPE
            );
            
            /* Create ASI */
            
            /* Create Enrollment */
        }
    }
}