force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>API_Mapping__c</fullName>
        <description>This tells us how the mapping occurs from API</description>
        <encryptionScheme>None</encryptionScheme>
        <label>API Mapping</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer_Target__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Defines the system location to store the answer to this question. e.g. Household_Income__c.Value__c</inlineHelpText>
        <label>Answer Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>The data type of the question. Used exclusively for components of type Document.</description>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Date/Time</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Checkbox Group</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Address</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>School Search</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question_Group</fullName>
        <active>true</active>
        <label>Question Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/API_Validated__c.field-meta.xml
<CustomField>
    <fullName>API_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes when user input has been validated by an API</description>
    <label>Input Validated by API</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/School_Search_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>School Search Settings</label>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State__mdt.object
<CustomObject>
    <description>A list of States used for school select</description>
    <label>State</label>
    <pluralLabel>States</pluralLabel>
</CustomObject>

force-app/main/default/classes/NES_MDRIntegrationTest.cls
/**
 * Created by Anand on 1/9/2019.
 */
@IsTest
private class NES_MDRIntegrationTest {
    @TestSetup
    static void setup() {
        Account account = Peak_TestUtils.createTestAccount(); 
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('CSY', System.today());
        // Create a contact with 'Students' record type
        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);

        // Create a account with 'Academic Program' record type
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(account.Id, currentSchoolYear.Id);
        List<Enrollment_Component__c> enrollmentCompList = new List<Enrollment_Component__c>();
        Enrollment_Component__c questionComponentTest1 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        questionComponentTest1.Answer_Target__c = 'Account.Name';
        questionComponentTest1.API_Mapping__c = 'schoolName' ;
        questionComponentTest1.Question_Type__c = 'Picklist';
        Enrollment_Component__c questionComponentTest2 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        questionComponentTest2.Answer_Target__c = 'Account.Department';
        questionComponentTest2.API_Mapping__c = 'streetAddress';
        questionComponentTest2.Question_Type__c = 'Radio';
        Enrollment_Component__c questionComponentTest3 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        questionComponentTest3.Answer_Target__c = 'contact.AssistantName';
        questionComponentTest3.API_Mapping__c = 'city';
        questionComponentTest3.Question_Type__c = 'Checkbox Group';

        Enrollment_Component__c sectionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Section', false);

        enrollmentCompList.add(questionComponentTest1);
        enrollmentCompList.add(questionComponentTest2);
        enrollmentCompList.add(questionComponentTest3);
        enrollmentCompList.add(sectionComponent);

        insert enrollmentCompList;
        Enrollment_Component__c questionGroupComp = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question_Group', false);
        questionGroupComp.Status__c = 'Inactive';
        insert questionGroupComp;
        Enrollment_Component_Relationship__c enrollCompRelationshipTest1 = Peak_TestUtils.createEnrollmentComponentRelationship(enrollmentCompList[0].Id, questionGroupComp.Id);
        Enrollment_Component_Relationship__c enrollCompRelationshipTest2 = Peak_TestUtils.createEnrollmentComponentRelationship(enrollmentCompList[1].Id, questionGroupComp.Id);
        Enrollment_Component_Relationship__c enrollCompRelationshipTest3 = Peak_TestUtils.createEnrollmentComponentRelationship(enrollmentCompList[2].Id, questionGroupComp.Id);

        hed__Program_Enrollment__c ProgramEnrollmentTest = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, currentSchoolYear.Id, True);
        Enrollment_Component_Affiliation__c ecaAffiliation=Peak_TestUtils.createEnrollmentComponentAffiliation(ProgramEnrollmentTest.Id,enrollmentCompList[0].Id);
        ecaAffiliation.status__c = 'Exempt';
        update ecaAffiliation;

        Enrollment_Component_Affiliation__c ecaSectionAffiliation = Peak_TestUtils.createEnrollmentComponentAffiliation(ProgramEnrollmentTest.Id, sectionComponent.Id);
    }

    static testMethod void searchSchoolTest() {
        Test.startTest();
        Peak_MockHttpResponseGenerator mockGenerator = new Peak_MockHttpResponseGenerator();
        Test.setMock(HttpCalloutMock.class, new Peak_MockHttpResponseGenerator());

        String response = NES_MDRIntegration.searchSchool('Hebron High School', 'Hebron', 'IN');
        System.debug('response==>>' + response);
        test.stopTest();
    }
    static testMethod void searchSchoolCustomSettingsTest() {
        School_Search_Settings__c schoolSearchRec = Peak_TestUtils.createSchoolSearchSettings(123, 456);
        School_Search_Settings__c customSettingRec = NES_MDRIntegration.getSchoolSearchSettings();
        system.assert(true, customSettingRec != null);
    }
    Static testMethod void updateEnrollments() {
        test.startTest();
        hed__Program_Enrollment__c programEnrollment = [SELECT Id FROM hed__Program_Enrollment__c LIMIT 1];
        Id questionGroupRecordTypeId = Schema.SObjectType.Enrollment_Component__c.getRecordTypeInfosByName().get('Question Group').getRecordTypeId();
        Enrollment_Component__c enrollmentComp = [
                SELECT Id,Answer_Target__c,API_Mapping__c
                FROM Enrollment_Component__c
                WHERE recordTypeId = :questionGroupRecordTypeId
                LIMIT 1
        ];
        String json = '{\"streetAddress\":\"9604 Illinois St\",' +
                '\"stateAbbr\":\"IL\",\"searchScore\":3.5380974,' +
                '\"schoolName\":\"Alden-Hebron Middle High Sch\",' +
                '\"postalCode\":\"60034\",' +
                '\"districtName\":\"Alden-Hebron School Dist 19\",' +
                '\"countryAbbr\":\"USA\",\"city\":\"Hebron\"}';

        //Peak_Response response = NES_MDRIntegration.updateEnrollmentAnswerTarget(json, enrollmentComp.Id, programEnrollment.Id);
        //System.assertEquals(response.success, True);
        //System.assertNotEquals(response.results, Null);
        test.stopTest();

    }


    static testMethod void test_markQuestionAPIValidated(){
        Enrollment_Component_Affiliation__c ecaRecord = [SELECT ID,API_Validated__c FROM Enrollment_Component_Affiliation__c WHERE Status__c = 'Exempt' Limit 1];
        test.startTest();
        //Peak_Response peakResponse = NES_MDRIntegration.markQuestionAPIValidated(ecaRecord.Id);
        Enrollment_Component_Affiliation__c ecaRecord1 = [SELECT ID,API_Validated__c FROM Enrollment_Component_Affiliation__c WHERE Status__c = 'Exempt' Limit 1];
        //System.assertEquals(True, ecaRecord1.API_Validated__c);
        //System.assert(peakResponse.success);
        test.stopTest();
    }

    @isTest static void testGetStates(){
        List<State__mdt> listOfStates = NES_MDRIntegration.getStates();
        System.debug('This is my list of state ==' + listOfStates);
        System.assert(true, listOfStates.size() > 1);
    }
    @isTest static void updateEnrollmentAnswerTarget(){
        String schoolAddress = '{"schoolName": "harbor","searchScore": "3.3","streetAddress": "harbor","city": "harbor","postalCode": "22222","stateAbbr": "ABR","countryAbbr": "OH","districtName": "OH"}';
        
        hed__Program_Enrollment__c ProgramEnrollmentTest = [SELECT Id FROM hed__Program_Enrollment__c LIMIT 1];
        Enrollment_Component__c questionGroupComp2 = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Question_Group' LIMIT 1];

        Peak_Response response =NES_MDRIntegration.updateEnrollmentAnswerTarget(schoolAddress,questionGroupComp2.Id,ProgramEnrollmentTest.Id,true);
        System.assert(response.messages != null);
       

    }
    @isTest static void evaluateQuestions() {
        User usr = Peak_TestUtils.CreatePortalCaretTakerUser([SELECT Id FROM Contact LIMIT 1].Id);
        System.runAs(usr){
            Test.startTest();
            hed__Program_Enrollment__c ProgramEnrollmentTest = [SELECT Id FROM hed__Program_Enrollment__c LIMIT 1];
            Enrollment_Component__c questionGroupComp = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Question' LIMIT 1];
            Enrollment_Component__c questionGroupComp2 = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Question_Group' LIMIT 1];
            Enrollment_Component__c sectionComponent = [SELECT Id FROM Enrollment_Component__c WHERE RecordType.DeveloperName = 'Section' LIMIT 1];

            List<NES_EvaluateUtil.Question> relatedquestions = NES_MDRIntegration.getRelatedQuestions(questionGroupComp.Id, ProgramEnrollmentTest.Id);
            List<NES_EvaluateUtil.Question> questions = NES_MDRIntegration.getQuestions(questionGroupComp2.Id, ProgramEnrollmentTest.Id);
            List<NES_EvaluateUtil.Question> response =NES_MDRIntegration.evaluateQuestions(ProgramEnrollmentTest.Id,JSON.serialize(questions),sectionComponent.Id);
            System.assert(questions != null);
            Test.stopTest();
        }
    }

}