force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Confirmation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_End_Date__c</fullName>
    <description>The date/time that final confirmation stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstDayforStudents__c.field-meta.xml
<CustomField>
    <fullName>FirstDayforStudents__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Day of School for Students</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstDaySecondSemester__c.field-meta.xml
<CustomField>
    <fullName>FirstDaySecondSemester__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Day of the Second Semester</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PushToSecondSemester__c.field-meta.xml
<CustomField>
    <fullName>PushToSecondSemester__c</fullName>
    <description>This is when the second semester becomes the only option</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Push To Second Semester</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Second_Semester_Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Semester_Confirmation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Second Semester Confirmation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <description>To store the Household details</description>
    <label>Household</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to the Contact records with the Caretaker Record type.It is being used by the student Record Types of Contact</description>
        <label>Caretaker Id</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Caretaker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c.object
<CustomObject>
    <description>&quot;The Enrollment object stores the dates and status codes that define a student’s enrollment with the Academic Program. A student may have multiple Enrollment records for a single Program Enrollment. Each withdrawal and re-enrollment within the same Academic Program will generate a new Enrollment associated with the Program Enrollment.

All Enrollment records are coded with a specific school year. Enrollment records are  updated with a withdrawal date and code sent from the SIS when students withdraw from the academic program.&quot;</description>
    <fields>
        <fullName>Enrollment_Date__c</fullName>
        <description>Date Enrolled</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Type__c</fullName>
        <description>Add for ITR Events</description>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Enrollment</fullName>
                </value>
                <value>
                    <fullName>Re-enrolling student</fullName>
                </value>
                <value>
                    <fullName>Returning Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>Child records can be reparented to other parent records after they are created</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The School Year record for the year the data is relevant for.</description>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Enrollment</fullName>
                <default>true</default>
                <label>Initial Enrollment</label>
            </value>
            <value>
                <fullName>Re-enrolling student</fullName>
            </value>
            <value>
                <fullName>Returning Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Final_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Final_Grade_Level__c</fullName>
    <label>Final Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transitional K</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/HouseholdEnrollmentDate__c.field-meta.xml
<CustomField>
    <fullName>HouseholdEnrollmentDate__c</fullName>
    <description>Household Enrollment Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Household Enrollment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NES_LogicFeatureSwitch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>NES Logic Feature Switch</label>
</CustomObject>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caretaker Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Earliest_Final_Confirmation_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Earliest Final Confirmation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Final_Semester_Indicator__c</fullName>
        <label>Final Semester Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredStartDate__c</fullName>
        <description>Preferred Start Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferred Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reactivation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Reactivation Date</description>
        <label>Reactivation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SFDC_Informed__c</fullName>
        <description>SFDC Enrolled</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SFDC Informed</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Semester_Indicator__c</fullName>
        <label>Semester Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                    <default>true</default>
                    <label>First</label>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_OpportunityTriggerTest.cls
/**
 * Created by Anand on 12/7/2018.
 */

@isTest

Private class NES_OpportunityTriggerTest {

    @TestSetup
    static void setup() {
        Peak_TestUtils.createNESBusinessLogicSwitch('OpportunityTrigger', true);
        Peak_TestUtils.createNESBusinessLogicSwitch('Likelihood to Transition Score', true);
        Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        Contact TestContact = Peak_TestUtils.createTestContact();
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('SchoolTest', System.today()); 
        Account academicAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id, schlYear.Id);
        academicAccount.Confirmation_End_Date__c=datetime.newInstance(2014, 9, 15, 12, 30, 0);
        academicAccount.Second_Semester_Confirmation_Date__c=datetime.newInstance(2014, 9, 15, 12, 30, 0);
        update academicAccount;
        hed__Program_Enrollment__c ProgramEnrollmentTest = Peak_TestUtils.createProgramEnrollment(academicAccount.Id, TestContact.Id, schlYear.Id, false);
        ProgramEnrollmentTest.Final_Grade_Level__c = '1';
        Insert ProgramEnrollmentTest;
        List<Opportunity> optyList=new List<Opportunity>();
        Opportunity optyTest1 = Peak_TestUtils.createOpportunity('oldOpty',parentAccount.Id,System.Today(),'closed won',False);
        optyTest1.Semester_Indicator__c='First';
        optyTest1.Final_Semester_Indicator__c='Second';
        optyTest1.Earliest_Final_Confirmation_Date__c=System.today();
        optyTest1.Program_Enrollment__c=ProgramEnrollmentTest.Id;
        Insert  optyTest1;

    //Test data setup by Ritvik
        //Account account = Peak_TestUtils.createTestAccount();
        School_Year__c schoolYear1 = Peak_TestUtils.createSchoolYears('2018-2019',date.parse('11/17/2018'));
        //Contact contact = Peak_TestUtils.createTestContact('Students', parentAccount.Id);
        //Account academicProgramAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id,schoolYear1.Id);
        academicAccount.FirstDayforStudents__c = System.today().addDays(-10);
        academicAccount.PushToSecondSemester__c = System.today().addDays(-5);
        academicAccount.FirstDaySecondSemester__c = System.today().addDays(-15);
        update academicAccount;
        hed__Program_Enrollment__c programEnrollmentWithoutEnrollment = Peak_TestUtils.createProgramEnrollment(academicAccount.Id, TestContact.Id,schlYear.Id, true);
        hed__Program_Enrollment__c programEnrollmentWithEnrollment = Peak_TestUtils.createProgramEnrollment(academicAccount.Id, TestContact.Id,schoolYear1.Id, true);
        Enrollment__c enrollment1 = Peak_TestUtils.createEnrollmentRecord(programEnrollmentWithEnrollment.Id,schoolYear1.Id,true);
        //Enrollment__c enrollment2 = Peak_TestUtils.createEnrollmentRecord(programEnrollmentWithEnrollment.Id,schoolYear1.Id,false);
        //enrollment2.Enrollment_Date__c = System.today();
        Opportunity opportunity1 = Peak_TestUtils.createOpportunity('Test Opportunity1',academicAccount.Id,date.today(),'Proposal',false);
        opportunity1.PreferredStartDate__c = System.today().addDays(-7);
        opportunity1.Semester_Indicator__c = 'Second';
        opportunity1.Program_Enrollment__c = programEnrollmentWithoutEnrollment.Id;
        insert opportunity1;

        Opportunity opportunity2 = Peak_TestUtils.createOpportunity('Test Opportunity2',academicAccount.Id,date.today(),'Proposal',false);
        opportunity2.PreferredStartDate__c = System.today().addDays(-7);
        opportunity2.Semester_Indicator__c = 'Second';
        opportunity2.Program_Enrollment__c = programEnrollmentWithEnrollment.Id;
        insert opportunity2;

        Opportunity opportunity3 = Peak_TestUtils.createOpportunity('Test Opportunity3',academicAccount.Id,date.today(),'Proposal',false);
        opportunity3.PreferredStartDate__c = System.today().addDays(-7);
        opportunity3.Semester_Indicator__c = 'Second';
        opportunity3.Program_Enrollment__c = programEnrollmentWithEnrollment.Id;
		opportunity3.Semester_Indicator__c = 'First';
        opportunity3.Final_Semester_Indicator__c = '';
        Insert opportunity3;

        User  portalUser= Peak_TestUtils.CreatePortalCaretTakerUser();
    }
    /**
     * Created By Anand on 11/10/2018
     *
     */
    static testMethod void updateOpportunityConfirmationDate() {
        Opportunity optyTest1 = [
                select id,
                        Semester_Indicator__c,
                        Program_Enrollment__c,
                        Final_Semester_Indicator__c,
                        Earliest_Final_Confirmation_Date__c
                FROM OPPORTUNITY
                WHERE Final_Semester_Indicator__c = 'Second'
                LIMIT 1
        ];
        Test.startTest();
        // Condition for if Final Semester changed to First from Second
        optyTest1.Final_Semester_Indicator__c = 'First';
        update optyTest1;
        hed__Program_Enrollment__c prEnrollment = [
                SELECT Id,hed__Account__r.Second_Semester_Confirmation_Date__c,
                        hed__Account__r.Confirmation_End_Date__c
                FROM hed__Program_Enrollment__c
                WHERE ID = :optyTest1.Program_Enrollment__c
        ];
        Opportunity optyAssert1 = [
                select id,Program_Enrollment__c,Final_Semester_Indicator__c,Earliest_Final_Confirmation_Date__c
                FROM OPPORTUNITY
                WHERE Id = :optyTest1.Id
        ];
        // Assert the final Confirmation Date to Account Coniframtion End Date
        System.assertEquals(optyAssert1.Earliest_Final_Confirmation_Date__c, prEnrollment.hed__Account__r.Confirmation_End_Date__c);
        // update the final semester value to Second From First
        optyAssert1.Final_Semester_Indicator__c = 'Second';
        update optyAssert1;
        Opportunity optyAssert2 = [select id, Earliest_Final_Confirmation_Date__c FROM OPPORTUNITY WHERE Id = :optyTest1.Id];
        // Assert the final confirmation date to Second Confirmation Date
        System.assertEquals(optyAssert2.Earliest_Final_Confirmation_Date__c, prEnrollment.hed__Account__r.Second_Semester_Confirmation_Date__c);
        // checking if final semester value is Null on update
        optyTest1.Semester_Indicator__c = 'Second';
        optyTest1.Final_Semester_Indicator__c = '';
        update optyTest1;
        Opportunity optyTest2 = [select id,Semester_Indicator__c,Final_Semester_Indicator__c FROM OPPORTUNITY WHERE Id = :optyTest1.Id];
        // Assert final semister to semester Indicator__c
        System.assertEquals(optyTest2.Semester_Indicator__c, optyTest2.Final_Semester_Indicator__c);
        optyTest2.Final_Semester_Indicator__c = 'Second';
        update optyTest2;
        Test.stopTest();

    }
    /**
     * Created By Anand 12/10/2018
     */
    static TestMethod void populateFinal_SemesterIndicatorTest() {
        Account parentAccount = [select Id From Account Limit 1];
        // if  semester has value and final semester is Null
        Test.startTest();
        Opportunity optyTest2 = [select id,Semester_Indicator__c,Final_Semester_Indicator__c FROM OPPORTUNITY WHERE name = 'Test Opportunity3'];
        // Assert semesterIndicator to FinalSemesterIndicator
        System.assertEquals(optyTest2.Semester_Indicator__c, optyTest2.Final_Semester_Indicator__c);
        Opportunity optyTest3 = Peak_TestUtils.createOpportunity('Opty2', parentAccount.Id, System.Today(), 'closed won', False);
        optyTest3.Semester_Indicator__c = 'First';
        optyTest3.Final_Semester_Indicator__c = 'Second';
        Insert optyTest3;
        Opportunity optyTest4 = [select id,Semester_Indicator__c,Final_Semester_Indicator__c FROM OPPORTUNITY WHERE Id = :optyTest3.Id];
        // Assert semesterIndicator to FinalSemesterIndicator
        System.assertNotEquals(optyTest4.Semester_Indicator__c, optyTest4.Final_Semester_Indicator__c);

        Test.stopTest();

    }
    //Created by Ritvik
    static testMethod void populateEnrollmentDate_Scenario1() {
        Opportunity opportunityRecord1 = [SELECT Id,Program_Enrollment__c FROM Opportunity WHERE Name = 'Test Opportunity1'];
        opportunityRecord1.StageName = 'Closed Won';
        Test.startTest();
        update opportunityRecord1;
        Enrollment__c enrollmentRecord = [SELECT Enrollment_Date__c FROM Enrollment__c WHERE Program_Enrollment__c = :opportunityRecord1.Program_Enrollment__c];
        System.assertEquals(System.today().addDays(1), enrollmentRecord.Enrollment_Date__c);
        Test.StopTest();
    }

    //Created by Ritvik
    static testMethod void populateEnrollmentDate_Scenario2() {
        Opportunity opportunityRecord2 = [SELECT Id,Program_Enrollment__c FROM Opportunity WHERE Name = 'Test Opportunity2'];
        opportunityRecord2.StageName = 'Closed Won';
        Test.startTest();
        update opportunityRecord2;
        Enrollment__c enrollmentRecord = [SELECT Enrollment_Date__c FROM Enrollment__c WHERE Program_Enrollment__c = :opportunityRecord2.Program_Enrollment__c];
        System.assertEquals(System.today().addDays(1), enrollmentRecord.Enrollment_Date__c);
        Test.StopTest();
    }

    //Created by Ritvik
    static testMethod void populateEnrollmentDate_Scenario3() {
        Id programEnrollmentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        Account academicAccount = [SELECT Id FROM Account WHERE RecordTypeId = :programEnrollmentRecordTypeId AND Name = 'Test Account'];
        academicAccount.FirstDaySecondSemester__c = System.today().addDays(10);
        academicAccount.FirstDayforStudents__c = System.today().addDays(20);
        update academicAccount;
        Opportunity opportunityRecord2 = [SELECT Id,Program_Enrollment__c FROM Opportunity WHERE Name = 'Test Opportunity2'];
        opportunityRecord2.StageName = 'Closed Won';
        Test.startTest();
        update opportunityRecord2;
        Enrollment__c enrollmentRecord = [SELECT Enrollment_Date__c FROM Enrollment__c WHERE Program_Enrollment__c = :opportunityRecord2.Program_Enrollment__c];
        System.assertEquals(academicAccount.FirstDayforStudents__c, enrollmentRecord.Enrollment_Date__c);
        Test.StopTest();
    }

    //Created by Ritvik
    static testMethod void populateEnrollmentDate_Scenario4() {
        Id programEnrollmentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        Account academicAccount = [SELECT Id FROM Account WHERE RecordTypeId = :programEnrollmentRecordTypeId AND Name = 'Test Account'];
        academicAccount.FirstDaySecondSemester__c = System.today().addDays(10);
        academicAccount.FirstDayforStudents__c = System.today().addDays(20);
        academicAccount.PushToSecondSemester__c = System.today().addDays(5);
        update academicAccount;
        Opportunity opportunityRecord1 = [SELECT Id,Program_Enrollment__c FROM Opportunity WHERE Name = 'Test Opportunity1'];
        opportunityRecord1.StageName = 'Closed Won';
        opportunityRecord1.Semester_Indicator__c = 'First';
        Test.startTest();
        update opportunityRecord1;
        Enrollment__c enrollmentRecord = [SELECT Enrollment_Date__c FROM Enrollment__c WHERE Program_Enrollment__c = :opportunityRecord1.Program_Enrollment__c];
        System.assertEquals(academicAccount.FirstDayforStudents__c, enrollmentRecord.Enrollment_Date__c);
        Test.StopTest();
    }


    //Created by Ritvik
    static testMethod void populateEnrollmentDate_Scenario5() {
        Id programEnrollmentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        Account academicAccount = [SELECT Id FROM Account WHERE RecordTypeId = :programEnrollmentRecordTypeId AND Name = 'Test Account'];
        //academicAccount.FirstDaySecondSemester__c = System.today().addDays(10);
        academicAccount.FirstDayforStudents__c = System.today().addDays(-5);
        academicAccount.PushToSecondSemester__c = System.today().addDays(5);
        update academicAccount;
        Opportunity opportunityRecord1 = [SELECT Id,Program_Enrollment__c FROM Opportunity WHERE Name = 'Test Opportunity1'];
        opportunityRecord1.StageName = 'Closed Won';
        opportunityRecord1.Semester_Indicator__c = 'First';
        opportunityRecord1.PreferredStartDate__c = System.today().addDays(10);
        Test.startTest();
        update opportunityRecord1;
        Enrollment__c enrollmentRecord = [SELECT Enrollment_Date__c FROM Enrollment__c WHERE Program_Enrollment__c = :opportunityRecord1.Program_Enrollment__c];
        System.assertEquals(opportunityRecord1.PreferredStartDate__c, enrollmentRecord.Enrollment_Date__c);
        Test.StopTest();
    }

    //Created by Ritvik
    static testMethod void populateEnrollmentDate_Scenario6() {
        Id programEnrollmentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        Account academicAccount = [SELECT Id FROM Account WHERE RecordTypeId = :programEnrollmentRecordTypeId AND Name = 'Test Account'];
        academicAccount.PushToSecondSemester__c = System.today().addDays(5);
        academicAccount.FirstDayforStudents__c = System.today().addDays(-5);
        update academicAccount;
        Opportunity opportunityRecord2 = [SELECT Id,Program_Enrollment__c FROM Opportunity WHERE Name = 'Test Opportunity2'];
        opportunityRecord2.StageName = 'Closed Won';
        opportunityRecord2.Semester_Indicator__c = 'First';
        opportunityRecord2.PreferredStartDate__c = System.today().addDays(10);
        Test.startTest();
        update opportunityRecord2;
        Enrollment__c enrollmentRecord = [SELECT Enrollment_Date__c FROM Enrollment__c WHERE Program_Enrollment__c = :opportunityRecord2.Program_Enrollment__c];
        System.assertEquals(opportunityRecord2.PreferredStartDate__c, enrollmentRecord.Enrollment_Date__c);
        Test.StopTest();
    }
    /**
     * created By Anand
     * Purpose: To test the reactivation Date method
     */
    static testMethod void calculateReactivationDate() {
        Test.StartTest();
        User portuser = [Select Id,ContactId FROM USER Where Username = 'portalUser@gmail.com'];
        Account account = Peak_TestUtils.createTestAccount();
        Contact Student1 = Peak_TestUtils.createContact('Stud1', account.Id, 'Students', True);
        Contact Student2 = Peak_TestUtils.createContact('Stud2', account.Id, 'Students', True);
        List<hed__Relationship__c> relationList = new List<hed__Relationship__c>();
        hed__Relationship__c relationship1 = Peak_TestUtils.createRelationship(portuser.contactId, Student1.Id, false);
        relationship1.hed__Contact__c = portuser.ContactId;
        Insert relationship1;
        hed__Relationship__c relationship2 = Peak_TestUtils.createRelationship(portuser.contactId, Student2.Id, false);
        relationship2.hed__Contact__c = portuser.ContactId;
        Insert relationship2;
        NES_LogicFeatureSwitch__c logicSwitch = new NES_LogicFeatureSwitch__c(Name = 'Reactivation Date', Active__c = true);
        insert logicSwitch ;
        Boolean eVal = NES_LogicFeatureSwitch__c.getValues('Reactivation Date').Active__c;
        System.assertEquals(True, eVal);
        hed__Program_Enrollment__c ProgramEnrollment = [select Id,hed__Contact__c FROM hed__Program_Enrollment__c LIMIT 1];
        ProgramEnrollment.hed__Contact__c = Student1.Id;
        update ProgramEnrollment;

        Id programEnrollmentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        Account academicAccount = [select ID from Account Where RecordTypeId = :programEnrollmentRecordTypeId];

        Opportunity optyTest1 = Peak_TestUtils.createOpportunity('Test Opportunity1', academicAccount.Id, date.today(), 'Proposal', false);
        optyTest1.Program_Enrollment__c = ProgramEnrollment.Id;
        optyTest1.Caretaker_Id__c = Student1.Id;
        Insert optyTest1;
        Opportunity optyTest3 = Peak_TestUtils.createOpportunity('Test Opportunity3', academicAccount.Id, date.today(), 'Proposal', false);
        optyTest3.Program_Enrollment__c = ProgramEnrollment.Id;
        optyTest3.Caretaker_Id__c = Student2.Id;
        Insert optyTest3;
        List<Opportunity> optyList = new LIst<Opportunity>();


        Opportunity optyTest2 = Peak_TestUtils.createOpportunity('Test Opportunity21', academicAccount.Id, date.today(), 'close', false);
        optyTest2.Program_Enrollment__c = ProgramEnrollment.Id;
        optyTest2.Caretaker_Id__c = portuser.ContactId;
        Opportunity optyTest4 = Peak_TestUtils.createOpportunity('Test Opportunity41', academicAccount.Id, date.today(), 'Proposal', false);
        optyTest4.Program_Enrollment__c = ProgramEnrollment.Id;
        optyTest4.Caretaker_Id__c = portuser.ContactId;
        optyList.add(optyTest2);
        optyList.add(optyTest4);
        Insert optyList;
        Test.StopTest();
        //Start : Removed Reactivation_Date__c from query by Ritvik on 01/16/2019 as it is deleted from org.
        Opportunity optyUpdate = [select Id,Reactivation__c From Opportunity Where Name = 'Test Opportunity21'];
        System.assertEquals(optyUpdate.Reactivation__c, false);
        //System.assertEquals(optyUpdate.Reactivation_Date__c, System.today());
        Opportunity optyUpdate1 = [select Id,Reactivation__c From Opportunity Where Name = 'Test Opportunity41'];
        System.assertEquals(optyUpdate1.Reactivation__c, false);
        //System.assertEquals(optyUpdate1.Reactivation_Date__c, System.today());
        //End

    }
/**
 * created By Anand
 * Purpose: To Negative test the reactivation Date method
 */
    static testMethod void calculateReactivationDate_Secenario2() {
        Test.StartTest();
        User portuser = [Select Id,ContactId FROM USER Where Username = 'portalUser@gmail.com'];
        Account account = Peak_TestUtils.createTestAccount();
        Contact Student1 = Peak_TestUtils.createContact('Stud1', account.Id, 'Students', True);
        Contact Student2 = Peak_TestUtils.createContact('Stud2', account.Id, 'Students', True);
        List<hed__Relationship__c> relationList = new List<hed__Relationship__c>();
        hed__Relationship__c relationship1 = Peak_TestUtils.createRelationship(portuser.contactId, Student1.Id, false);
        relationship1.hed__Contact__c = portuser.ContactId;
        Insert relationship1;
        hed__Relationship__c relationship2 = Peak_TestUtils.createRelationship(portuser.contactId, Student2.Id, false);
        relationship2.hed__Contact__c = portuser.ContactId;
        Insert relationship2;
        NES_LogicFeatureSwitch__c logicSwitch = new NES_LogicFeatureSwitch__c(Name = 'Reactivation Date', Active__c = true);
        insert logicSwitch ;
        Boolean eVal = NES_LogicFeatureSwitch__c.getValues('Reactivation Date').Active__c;
        System.assertEquals(True, eVal);
        hed__Program_Enrollment__c ProgramEnrollment = [select Id,hed__Contact__c FROM hed__Program_Enrollment__c LIMIT 1];
        ProgramEnrollment.hed__Contact__c = Student1.Id;
        update ProgramEnrollment;

        Id programEnrollmentRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        Account academicAccount = [select ID from Account Where RecordTypeId = :programEnrollmentRecordTypeId];
        // Negative test data for opportunity stage
        Opportunity optyTest1 = Peak_TestUtils.createOpportunity('Test Opportunity1', academicAccount.Id, date.today(), 'closed won', false);
        optyTest1.Program_Enrollment__c = ProgramEnrollment.Id;
        optyTest1.Caretaker_Id__c = Student1.Id;
        Insert optyTest1;
        // Negative test data for opportunity stage
        Opportunity optyTest3 = Peak_TestUtils.createOpportunity('Test Opportunity3', academicAccount.Id, date.today(), 'closed won', false);
        optyTest3.Program_Enrollment__c = ProgramEnrollment.Id;
        optyTest3.Caretaker_Id__c = Student2.Id;
        Insert optyTest3;
        List<Opportunity> optyList = new List<Opportunity>();


        Opportunity optyTest2 = Peak_TestUtils.createOpportunity('Test Opportunity21', academicAccount.Id, date.today(), 'closed won', false);
        optyTest2.Program_Enrollment__c = ProgramEnrollment.Id;
        optyTest2.Caretaker_Id__c = portuser.ContactId;
        Opportunity optyTest4 = Peak_TestUtils.createOpportunity('Test Opportunity41', academicAccount.Id, date.today(), 'Proposal', false);
        optyTest4.Program_Enrollment__c = ProgramEnrollment.Id;
        optyTest4.Caretaker_Id__c = portuser.ContactId;
        optyList.add(optyTest2);
        optyList.add(optyTest4);
        Insert optyList;
        Test.StopTest();
        //Start : Removed Reactivation_Date__c from query by Ritvik on 01/16/2019 as it is deleted from org.
        Opportunity optyUpdate = [select Id,Reactivation__c From Opportunity Where Name = 'Test Opportunity21'];
        System.assertNotEquals(optyUpdate.Reactivation__c, True);
        //System.assertNotEquals(optyUpdate.Reactivation_Date__c, System.today());
        Opportunity optyUpdate1 = [select Id,Reactivation__c From Opportunity Where Name = 'Test Opportunity41'];
        System.assertNotEquals(optyUpdate1.Reactivation__c, True);
        //System.assertNotEquals(optyUpdate1.Reactivation_Date__c, System.today());
        //End

    }


    Static testMethod void houseHoldEnrollmentDateTest() {
        // Create Test Data for CareTakerId,Students And ProgramEnrollments
        Test.StartTest();
        User portuser = [Select Id,ContactId FROM USER Where Username = 'portalUser@gmail.com'];
        Account account = Peak_TestUtils.createTestAccount();
        Contact Student1 = Peak_TestUtils.createContact('Stud1', account.Id, 'Students', True);
        Contact Student2 = Peak_TestUtils.createContact('Stud2', account.Id, 'Students', True);
        List<hed__Relationship__c> relationList = new List<hed__Relationship__c>();
        hed__Relationship__c relationship1 = Peak_TestUtils.createRelationship(portuser.contactId, Student1.Id, false);
        relationship1.hed__Contact__c = portuser.ContactId;
        Insert relationship1;
        hed__Relationship__c relationship2 = Peak_TestUtils.createRelationship(portuser.contactId, Student2.Id, false);
        relationship2.hed__Contact__c = portuser.ContactId;
        Insert relationship2;
        // Create a record for NES_LogicFeatureSwitch__c with   Household Enrollment Date Value
        NES_LogicFeatureSwitch__c logicSwitch = new NES_LogicFeatureSwitch__c(Name = 'Household Enrollment Date', Active__c = true);
        insert logicSwitch ;
        Boolean eVal = NES_LogicFeatureSwitch__c.getValues('Household Enrollment Date').Active__c;
        // update programEnrollments with StudentId
        hed__Program_Enrollment__c ProgramEnrollment = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c LIMIT 1];
        ProgramEnrollment.hed__Contact__c = Student1.Id;
        ProgramEnrollment.HouseholdEnrollmentDate__c = System.today();
        update ProgramEnrollment;
        School_Year__c schlYear = [select Id FROM School_Year__c LIMIT 1];
        hed__Program_Enrollment__c progEnrollmentUpdated = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :ProgramEnrollment.Id];
        Enrollment__c enrollmentTest = Peak_TestUtils.createEnrollmentRecord(progEnrollmentUpdated.Id, schlYear.Id, false);
        enrollmentTest.Enrollment_Date__c = Date.newInstance(2014, 9, 15);
        Insert enrollmentTest;
        Enrollment__c enrollment1 = [select Id,Enrollment_Date__c FROM Enrollment__c WHERE Id = :enrollmentTest.Id];

        Opportunity oppTest1 = [Select Id,StageName,Program_Enrollment__c FROM Opportunity WHERE StageName <> 'Closed won' LIMIT 1];
        oppTest1.Program_Enrollment__c = progEnrollmentUpdated.Id;
        oppTest1.Caretaker_Id__c = portuser.ContactId;
        update oppTest1;
        //Update opportunity to closed won
        Opportunity opp1 = [select Id,StageName From Opportunity Where Id = :oppTest1.Id];

        opp1.StageName = 'Closed Won';
        update opp1;
        Test.StopTest();
        Opportunity oppUpdated = [select Id,StageName,Program_Enrollment__c From Opportunity Where Id = :opp1.Id];
        hed__Program_Enrollment__c progEnrollment2 = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :oppUpdated.Program_Enrollment__c];
        // Assert the date Enrollment_Date__c to HouseholdEnrollmentDate__c which Needs to be equal
        //System.assertEquals(enrollment1.Enrollment_Date__c, progEnrollment2.HouseholdEnrollmentDate__c);
    }
    Static testMethod void houseHoldEnrollmentDateTestCase2() {
        Test.StartTest();
        User portuser = [Select Id,ContactId FROM USER Where Username = 'portalUser@gmail.com'];
        Account account = Peak_TestUtils.createTestAccount();
        Contact Student1 = Peak_TestUtils.createContact('Stud1', account.Id, 'Students', True);
        Contact Student2 = Peak_TestUtils.createContact('Stud2', account.Id, 'Students', True);
        List<hed__Relationship__c> relationList = new List<hed__Relationship__c>();
        hed__Relationship__c relationship1 = Peak_TestUtils.createRelationship(portuser.contactId, Student1.Id, false);
        relationship1.hed__Contact__c = portuser.ContactId;
        Insert relationship1;
        hed__Relationship__c relationship2 = Peak_TestUtils.createRelationship(portuser.contactId, Student2.Id, false);
        relationship2.hed__Contact__c = portuser.ContactId;
        Insert relationship2;
        NES_LogicFeatureSwitch__c logicSwitch = new NES_LogicFeatureSwitch__c(Name = 'Household Enrollment Date', Active__c = true);
        insert logicSwitch ;
        // Create A record for NES_LogicFeatureSwitch__c with  Household Enrollment Date value
        Boolean eVal = NES_LogicFeatureSwitch__c.getValues('Household Enrollment Date').Active__c;
        hed__Program_Enrollment__c ProgramEnrollment = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c LIMIT 1];
        ProgramEnrollment.hed__Contact__c = Student1.Id;
        ProgramEnrollment.HouseholdEnrollmentDate__c = System.today();
        update ProgramEnrollment;
        School_Year__c schlYear = [select Id FROM School_Year__c LIMIT 1];
        hed__Program_Enrollment__c progEnrollmentUpdated = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :ProgramEnrollment.Id];
        Enrollment__c enrollmentTest = Peak_TestUtils.createEnrollmentRecord(progEnrollmentUpdated.Id, schlYear.Id, false);
        // Negative Testing for Date greater than Program Enrollment Date
        enrollmentTest.Enrollment_Date__c = Date.newInstance(2019, 9, 15);
        Insert enrollmentTest;
        Enrollment__c enrollment1 = [select Id,Enrollment_Date__c FROM Enrollment__c WHERE Id = :enrollmentTest.Id];

        Opportunity oppTest1 = [Select Id,StageName,Program_Enrollment__c FROM Opportunity WHERE StageName <> 'Closed won' LIMIT 1];
        oppTest1.Program_Enrollment__c = progEnrollmentUpdated.Id;
        oppTest1.Caretaker_Id__c = portuser.ContactId;
        update oppTest1;
        // update Stage to closed won
        Opportunity opp1 = [select Id,StageName From Opportunity Where Id = :oppTest1.Id];

        opp1.StageName = 'Closed Won';
        update opp1;
        Test.StopTest();
        hed__Program_Enrollment__c progEnrollment2 = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :progEnrollmentUpdated.Id];
        // HouseholdEnrollmentDate__c of program enrollment shouldnot get updated with Enrollment Date
        System.assertNotEquals(enrollment1.Enrollment_Date__c, progEnrollment2.HouseholdEnrollmentDate__c);

    }
	
    Static testMethod void houseHoldEnrollmentDateTestCase3() {
        Test.StartTest();
        User portuser = [Select Id,ContactId FROM USER Where Username = 'portalUser@gmail.com'];
        Account account = Peak_TestUtils.createTestAccount();
        Contact Student1 = Peak_TestUtils.createContact('Stud1', account.Id, 'Students', True);
        Contact Student2 = Peak_TestUtils.createContact('Stud2', account.Id, 'Students', True);
        List<hed__Relationship__c> relationList = new List<hed__Relationship__c>();
        hed__Relationship__c relationship1 = Peak_TestUtils.createRelationship(portuser.contactId, Student1.Id, false);
        relationship1.hed__Contact__c = portuser.ContactId;
        Insert relationship1;
        hed__Relationship__c relationship2 = Peak_TestUtils.createRelationship(portuser.contactId, Student2.Id, false);
        relationship2.hed__Contact__c = portuser.ContactId;
        Insert relationship2;
        NES_LogicFeatureSwitch__c logicSwitch = new NES_LogicFeatureSwitch__c(Name = 'Household Enrollment Date', Active__c = true);
        insert logicSwitch ;
        // Create A record for NES_LogicFeatureSwitch__c with  Household Enrollment Date value
        Boolean eVal = NES_LogicFeatureSwitch__c.getValues('Household Enrollment Date').Active__c;
        hed__Program_Enrollment__c ProgramEnrollment = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c LIMIT 1];
        ProgramEnrollment.hed__Contact__c = Student1.Id;
        ProgramEnrollment.HouseholdEnrollmentDate__c = System.today();
        update ProgramEnrollment;
        School_Year__c schlYear = [select Id FROM School_Year__c LIMIT 1];
        hed__Program_Enrollment__c progEnrollmentUpdated = [select Id,Enrollment_Type__c,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :ProgramEnrollment.Id];
        Enrollment__c enrollmentTest = Peak_TestUtils.createEnrollmentRecord(progEnrollmentUpdated.Id, schlYear.Id, false);
        // Negative Testing for Date greater than Program Enrollment Date
        enrollmentTest.Enrollment_Date__c = Date.newInstance(2019, 9, 15);
        Insert enrollmentTest;
        Enrollment__c enrollment1 = [select Id,Enrollment_Date__c FROM Enrollment__c WHERE Id = :enrollmentTest.Id];

        Opportunity oppTest1 = [Select Id,StageName,Program_Enrollment__r.Enrollment_Type__c,Program_Enrollment__c FROM Opportunity WHERE StageName <> 'Closed won' LIMIT 1];
        oppTest1.Program_Enrollment__c = progEnrollmentUpdated.Id;
        oppTest1.Caretaker_Id__c = portuser.ContactId;
        update oppTest1;
        // update Stage to closed won
        Opportunity opp1 = [select Id,StageName,Program_Enrollment__c,Program_Enrollment__r.Enrollment_Type__c From Opportunity Where Id = :oppTest1.Id];
        opp1.StageName = 'Closed Won';
        update opp1;
        Test.StopTest();
        hed__Program_Enrollment__c progEnrollment2 = [select Id,HouseholdEnrollmentDate__c,(Select Id, Enrollment_Type__c from enrollments__r),hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :progEnrollmentUpdated.Id];
        // HouseholdEnrollmentDate__c of program enrollment shouldnot get updated with Enrollment Date
        System.assertNotEquals(enrollment1.Enrollment_Date__c, progEnrollment2.HouseholdEnrollmentDate__c);
        hed__Program_Enrollment__c progEnrollment3 = [select Id,HouseholdEnrollmentDate__c,(Select Id, Enrollment_Type__c from enrollments__r),hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :opp1.Program_Enrollment__c];       
    }
     Static testMethod void InitialEnrollmentTestCase4() {
        Test.StartTest();
        User portuser = [Select Id,ContactId FROM USER Where Username = 'portalUser@gmail.com'];
        Account account = Peak_TestUtils.createTestAccount();
        Contact Student1 = Peak_TestUtils.createContact('Stud1', account.Id, 'Students', True);
        Contact Student2 = Peak_TestUtils.createContact('Stud2', account.Id, 'Students', True);
        List<hed__Relationship__c> relationList = new List<hed__Relationship__c>();
        hed__Relationship__c relationship1 = Peak_TestUtils.createRelationship(portuser.contactId, Student1.Id, false);
        relationship1.hed__Contact__c = portuser.ContactId;
        Insert relationship1;
        hed__Relationship__c relationship2 = Peak_TestUtils.createRelationship(portuser.contactId, Student2.Id, false);
        relationship2.hed__Contact__c = portuser.ContactId;
        Insert relationship2;
        NES_LogicFeatureSwitch__c logicSwitch = new NES_LogicFeatureSwitch__c(Name = 'Household Enrollment Date', Active__c = true);
        insert logicSwitch ;
        // Create A record for NES_LogicFeatureSwitch__c with  Household Enrollment Date value
        Boolean eVal = NES_LogicFeatureSwitch__c.getValues('Household Enrollment Date').Active__c;
        hed__Program_Enrollment__c ProgramEnrollment = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c LIMIT 1];
        ProgramEnrollment.hed__Contact__c = Student1.Id;
        ProgramEnrollment.HouseholdEnrollmentDate__c = System.today();
        update ProgramEnrollment;
        School_Year__c schlYear = [select Id FROM School_Year__c LIMIT 1];
        hed__Program_Enrollment__c progEnrollmentUpdated = [select Id,Enrollment_Type__c,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :ProgramEnrollment.Id];              

        Opportunity oppTest1 = [Select Id,StageName,Program_Enrollment__r.Enrollment_Type__c,Program_Enrollment__c FROM Opportunity WHERE StageName <> 'Closed won' LIMIT 1];
        oppTest1.Program_Enrollment__c = progEnrollmentUpdated.Id;
        oppTest1.Caretaker_Id__c = portuser.ContactId;
        update oppTest1;
        // update Stage to closed won
        Opportunity opp1 = [select Id,StageName,Program_Enrollment__c,Program_Enrollment__r.Enrollment_Type__c From Opportunity Where Id = :oppTest1.Id];
        opp1.StageName = 'Closed Won';
         opp1.SFDC_Informed__c = 'Test';         
        update opp1;
        Test.StopTest();
        hed__Program_Enrollment__c progEnrollment2 = [select Id,HouseholdEnrollmentDate__c,(Select Id, Enrollment_Type__c from enrollments__r),hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :progEnrollmentUpdated.Id];
        // HouseholdEnrollmentDate__c of program enrollment shouldnot get updated with Enrollment Date      
        hed__Program_Enrollment__c progEnrollment3 = [select Id,Enrollment_Type__c,HouseholdEnrollmentDate__c,(Select Id, Enrollment_Type__c from enrollments__r),hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :opp1.Program_Enrollment__c];
        System.assertEquals(opp1.Program_Enrollment__r.Enrollment_Type__c, progEnrollment3.enrollments__r[0].Enrollment_Type__c);
    }
     Static testMethod void reenrollingStudentTestCase5() {
        Test.StartTest();
        User portuser = [Select Id,ContactId FROM USER Where Username = 'portalUser@gmail.com'];
        Account account = Peak_TestUtils.createTestAccount();
        Contact Student1 = Peak_TestUtils.createContact('Stud1', account.Id, 'Students', True);
        Contact Student2 = Peak_TestUtils.createContact('Stud2', account.Id, 'Students', True);
        List<hed__Relationship__c> relationList = new List<hed__Relationship__c>();
        hed__Relationship__c relationship1 = Peak_TestUtils.createRelationship(portuser.contactId, Student1.Id, false);
        relationship1.hed__Contact__c = portuser.ContactId;
        Insert relationship1;
        hed__Relationship__c relationship2 = Peak_TestUtils.createRelationship(portuser.contactId, Student2.Id, false);
        relationship2.hed__Contact__c = portuser.ContactId;
        Insert relationship2;
        NES_LogicFeatureSwitch__c logicSwitch = new NES_LogicFeatureSwitch__c(Name = 'Household Enrollment Date', Active__c = true);
        insert logicSwitch ;
        // Create A record for NES_LogicFeatureSwitch__c with  Household Enrollment Date value
        Boolean eVal = NES_LogicFeatureSwitch__c.getValues('Household Enrollment Date').Active__c;
        hed__Program_Enrollment__c ProgramEnrollment = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c LIMIT 1];
        ProgramEnrollment.hed__Contact__c = Student1.Id;
        ProgramEnrollment.Enrollment_Type__c = 'Re-Enrolling Student';
        ProgramEnrollment.HouseholdEnrollmentDate__c = System.today();
        update ProgramEnrollment;
        School_Year__c schlYear = [select Id FROM School_Year__c LIMIT 1];
        hed__Program_Enrollment__c progEnrollmentUpdated = [select Id,Enrollment_Type__c,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :ProgramEnrollment.Id];              

        Opportunity oppTest1 = [Select Id,StageName,Program_Enrollment__r.Enrollment_Type__c,Program_Enrollment__c FROM Opportunity WHERE StageName <> 'Closed won' LIMIT 1];
        oppTest1.Program_Enrollment__c = progEnrollmentUpdated.Id;
        oppTest1.Caretaker_Id__c = portuser.ContactId;
        update oppTest1;
        // update Stage to closed won
        Opportunity opp1 = [select Id,StageName,Program_Enrollment__c,Program_Enrollment__r.Enrollment_Type__c From Opportunity Where Id = :oppTest1.Id];
        opp1.StageName = 'Closed Won';
         opp1.SFDC_Informed__c = 'Test';         
        update opp1;
        Test.StopTest();
        hed__Program_Enrollment__c progEnrollment2 = [select Id,HouseholdEnrollmentDate__c,(Select Id, Enrollment_Type__c from enrollments__r),hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :progEnrollmentUpdated.Id];
        // HouseholdEnrollmentDate__c of program enrollment shouldnot get updated with Enrollment Date      
        hed__Program_Enrollment__c progEnrollment3 = [select Id,Enrollment_Type__c,HouseholdEnrollmentDate__c,(Select Id, Enrollment_Type__c from enrollments__r),hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :opp1.Program_Enrollment__c];
        System.assertEquals(opp1.Program_Enrollment__r.Enrollment_Type__c, progEnrollment3.enrollments__r[0].Enrollment_Type__c);
    }
    Static testMethod void returningStudentTestCase6() {
        Test.StartTest();
        User portuser = [Select Id,ContactId FROM USER Where Username = 'portalUser@gmail.com'];
        Account account = Peak_TestUtils.createTestAccount();
        Contact Student1 = Peak_TestUtils.createContact('Stud1', account.Id, 'Students', True);
        Contact Student2 = Peak_TestUtils.createContact('Stud2', account.Id, 'Students', True);
        List<hed__Relationship__c> relationList = new List<hed__Relationship__c>();
        hed__Relationship__c relationship1 = Peak_TestUtils.createRelationship(portuser.contactId, Student1.Id, false);
        relationship1.hed__Contact__c = portuser.ContactId;
        Insert relationship1;
        hed__Relationship__c relationship2 = Peak_TestUtils.createRelationship(portuser.contactId, Student2.Id, false);
        relationship2.hed__Contact__c = portuser.ContactId;
        Insert relationship2;
        NES_LogicFeatureSwitch__c logicSwitch = new NES_LogicFeatureSwitch__c(Name = 'Household Enrollment Date', Active__c = true);
        insert logicSwitch ;
        // Create A record for NES_LogicFeatureSwitch__c with  Household Enrollment Date value
        Boolean eVal = NES_LogicFeatureSwitch__c.getValues('Household Enrollment Date').Active__c;
        hed__Program_Enrollment__c ProgramEnrollment = [select Id,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c LIMIT 1];
        ProgramEnrollment.hed__Contact__c = Student1.Id;
        ProgramEnrollment.Enrollment_Type__c = 'Returning Student';
        ProgramEnrollment.HouseholdEnrollmentDate__c = System.today();
        update ProgramEnrollment;
        School_Year__c schlYear = [select Id FROM School_Year__c LIMIT 1];
        hed__Program_Enrollment__c progEnrollmentUpdated = [select Id,Enrollment_Type__c,HouseholdEnrollmentDate__c,hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :ProgramEnrollment.Id];              

        Opportunity oppTest1 = [Select Id,StageName,Program_Enrollment__r.Enrollment_Type__c,Program_Enrollment__c FROM Opportunity WHERE StageName <> 'Closed won' LIMIT 1];
        oppTest1.Program_Enrollment__c = progEnrollmentUpdated.Id;
        oppTest1.Caretaker_Id__c = portuser.ContactId;
        update oppTest1;
        // update Stage to closed won
        Opportunity opp1 = [select Id,StageName,Program_Enrollment__c,Program_Enrollment__r.Enrollment_Type__c From Opportunity Where Id = :oppTest1.Id];
        opp1.StageName = 'Closed Won';
         opp1.SFDC_Informed__c = 'Test';         
        update opp1;
        Test.StopTest();
        hed__Program_Enrollment__c progEnrollment2 = [select Id,HouseholdEnrollmentDate__c,(Select Id, Enrollment_Type__c from enrollments__r),hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :progEnrollmentUpdated.Id];
        // HouseholdEnrollmentDate__c of program enrollment shouldnot get updated with Enrollment Date      
        hed__Program_Enrollment__c progEnrollment3 = [select Id,Enrollment_Type__c,HouseholdEnrollmentDate__c,(Select Id, Enrollment_Type__c from enrollments__r),hed__Contact__c FROM hed__Program_Enrollment__c WHERE Id = :opp1.Program_Enrollment__c];
        System.assertEquals(opp1.Program_Enrollment__r.Enrollment_Type__c, progEnrollment3.enrollments__r[0].Enrollment_Type__c);
    }
}