force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_File_References__c.object
<CustomObject>
    <label>Document File References</label>
    <nameField>
        <displayFormat>DFR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document File References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_File_References__c/fields/Document_Link__c.field-meta.xml
<CustomField>
    <fullName>Document_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/Enrollment_Document__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Document__c</fullName>
    <label>Enrollment Document</label>
    <referenceTo>Enrollment_Document__c</referenceTo>
    <relationshipLabel>Document File References</relationshipLabel>
    <relationshipName>Document_File_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/File_Path__c.field-meta.xml
<CustomField>
    <fullName>File_Path__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Review__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Document Reviews (Academic Program)</relationshipLabel>
        <relationshipName>Document_Reviews1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pending_Review_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Pending Review Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Queue_Type__c</fullName>
        <label>Queue Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Non-Academic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <default>true</default>
                    <label>Complete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Review</label>
    <nameField>
        <displayFormat>DR-{0}</displayFormat>
        <label>Document Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Document_Review__c.field-meta.xml
<CustomField>
    <fullName>Document_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Review</label>
    <referenceTo>Document_Review__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grade_Level__c.object
<CustomObject>
    <description>The grade level object stores grade level information for connection to Academic Programs and Caps.</description>
    <label>Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Academic_Program__c</fullName>
    <label>Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_DocumentReviewUtilsTest.cls
/**
* Purpose : Test class for NES_DocumentReviewUtils class.
* Change Log:
*         2019-10-01 initial #US109913 (Andrew Sim)
*/
@isTest(SeeAllData=false)
public class NES_DocumentReviewUtilsTest {
    
    @TestSetup
    static void setup() {
        
        // insert educational institution 
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        
        // insert the school year
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());
        
        // insert academic program
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
        academicProgram.Registration_Start_Date__c = System.today().addDays(-10);
        academicProgram.Registration_End_Date__c = System.today().addDays(10);
        update academicProgram;
        
        // insert grade level(s)
        Grade_Level__c gradeLevelK = new Grade_Level__c(Order__c = 1, External_Id__c = 'GL - K', Name = 'K');
        insert gradeLevelK;
        Grade_Level__c gradeLevel1 = new Grade_Level__c(Order__c = 2, External_Id__c = 'GL - 1', Name = '1');
        insert gradeLevel1;
        
        // insert program grade level(s)
        Program_Grade_Level__c programGradeLevelK = new Program_Grade_Level__c(Name = 'PGL = K', Grade_Level__c = gradeLevelK.id, Academic_Program__c = academicProgram.id);
        insert programGradeLevelK;
        Program_Grade_Level__c programGradeLevel1 = new Program_Grade_Level__c(Name = 'PGL = 1', Grade_Level__c = gradeLevel1.id, Academic_Program__c = academicProgram.id);
        insert programGradeLevel1;
        
        // insert caretaker
        Contact careTakerContact = Peak_TestUtils.createTestContact('Caretaker', institutionAccount.Id);
        
        // insert caretaker user 
        User careTaker = Peak_TestUtils.CreatePortalCaretTakerUser(careTakerContact.Id);
        
        // insert caretaker program enrollment 
        hed__Program_Enrollment__c caretakerEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, careTaker.ContactId, schoolYear.Id, false);
        careTakerEnrollment.RecordTypeId = Schema.SObjectType.hed__Program_Enrollment__c.getRecordTypeInfosByName().get('Caretaker').getRecordTypeId();
        insert careTakerEnrollment;
        
        // insert student
        Contact student = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);
        
        // create relationship between the caretaker and student
        hed__Relationship__c relationship = Peak_TestUtils.createRelationship(careTaker.ContactId, student.Id, true);
        
        // create student program enrollment
        hed__Program_Enrollment__c studentEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, student.Id, schoolYear.Id, false);
        studentEnrollment.RecordTypeId = Schema.SObjectType.hed__Program_Enrollment__c.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        studentEnrollment.Program_Grade_Level__c = programGradeLevelK.Id;
        studentEnrollment.Household_Program_Enrollment__c = caretakerEnrollment.Id;
        studentEnrollment.Program_Enrollment__c = caretakerEnrollment.Id;
        studentEnrollment.hed__Account__c  = academicProgram.Id;
        insert studentEnrollment;
        
        //
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        /*
// insert document reference file 
Document_File_References__c dfr;
dfr = new Document_File_References__c ();
dfr.Document_Link__c = 'text document';
dfr.File_Path__c = 'xxx/file.txt';
dfr.Enrollment_Document__c = enrollmentDoc.id;
insert dfr; 
*/
        
        System.debug('gradeLevelK: ' + gradeLevelK);
        System.debug('programGradeLevelK: ' + programGradeLevelK);
        
        System.debug('academicProgram: ' + academicProgram);
        System.debug('careTakerContact: ' + careTakerContact);
        System.debug('careTaker: ' + careTaker);
        System.debug('student: ' + student);
        System.debug('studentEnrollment: ' + studentEnrollment);
        System.debug('caretakerEnrollment: ' + caretakerEnrollment);
        System.debug('institutionalAccount: ' + institutionAccount);
    }
    
    // matching educational institution no years no grades queue match
    static testMethod void getNextTest1() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = nonacademicGroup.id;
        request.educationalInstitution = institutionAccount.id;
        request.schoolYears = '';
        request.gradeLevels = '';
        requestList.add(request);
        
        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('1-nextId: ' + obj.nextId);
            System.debug('1-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 1);
        }
        Test.stopTest();
    }
    
    // matching educational institution no years no grades no queue match
    static testMethod void getNextTest2() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = academicGroup.id;
        request.educationalInstitution = institutionAccount.id;
        request.schoolYears = '';
        request.gradeLevels = '';
        requestList.add(request);
        
        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('2-nextId: ' + obj.nextId);
            System.debug('2-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 0);
        }
        Test.stopTest();
    }    
    
    // no matching educational institution no years no grades 
    static testMethod void getNextTest3() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = nonacademicGroup.id;
        request.educationalInstitution = academicProgram.id;
        request.schoolYears = '';
        request.gradeLevels = '';
        requestList.add(request);
                
        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('3-nextId: ' + obj.nextId);
            System.debug('3-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 0);
        }
        Test.stopTest();
    }    
    
    // matching educational institution with one or more years 
    static testMethod void getNextTest4() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = nonacademicGroup.id;
        request.educationalInstitution = institutionAccount.id;
        request.schoolYears = schoolYears.id + '; ';
        request.gradeLevels = '';
        requestList.add(request);
        
        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('4-nextId: ' + obj.nextId);
            System.debug('4-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 1);
        }
        Test.stopTest();
    }    
    
    // matching educational institution with no year match
    static testMethod void getNextTest5() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
		Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = nonacademicGroup.id;
        request.educationalInstitution = institutionAccount.id;
        request.schoolYears = '; ';
        request.gradeLevels = '';
        requestList.add(request);
               
        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('5-nextId: ' + obj.nextId);
            System.debug('5-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 0);
        }
        Test.stopTest();
    }    
    
    // matching educational institution with one or more grades
    static testMethod void getNextTest6() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        Grade_Level__c gradeLevelK = [SELECT Id, Name FROM Grade_Level__c WHERE Name = 'K' LIMIT 1];
        Grade_Level__c gradeLevel1 = [SELECT Id, Name FROM Grade_Level__c WHERE Name = '1' LIMIT 1];
        Program_Grade_Level__c programGradeLevelK = [SELECT Id, Name FROM Program_Grade_Level__c WHERE Name = 'PGL = K' LIMIT 1];
        Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = nonacademicGroup.id;
        request.educationalInstitution = institutionAccount.id;
        request.schoolYears = '';
        request.gradeLevels = gradeLevelK.Id + '; ';
        requestList.add(request);
        
        System.debug('6-gradeLevelK: ' + gradeLevelK);
        System.debug('6-programGradeLevelK: ' + programGradeLevelK);

        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('6-nextId: ' + obj.nextId);
            System.debug('6-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 1);
        }
        Test.stopTest();
    }    
    
    // matching educational institution with no grade match
    static testMethod void getNextTest7() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        Grade_Level__c gradeLevelK = [SELECT Id, Name FROM Grade_Level__c WHERE Name = 'K' LIMIT 1];
        Grade_Level__c gradeLevel1 = [SELECT Id, Name FROM Grade_Level__c WHERE Name = '1' LIMIT 1];
        Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = nonacademicGroup.id;
        request.educationalInstitution = institutionAccount.id;
        request.schoolYears = '';
        request.gradeLevels = '; ';
        requestList.add(request);
        
        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('7-nextId: ' + obj.nextId);
            System.debug('7-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 0);
        }
        Test.stopTest();
    }    
    
    // matching educational institution get earliest pending document
    static testMethod void getNextTest8() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        System.debug('8-docReview: ' + docReview.Id);
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        // insert document review
        Document_Review__c docReview2 = new Document_Review__c();
        docReview2.Queue_Type__c = 'Non-Academic';
        docReview2.OwnerId = nonacademicGroup.Id;
        docReview2.Pending_Review_Date__c = Date.parse('11/16/2017');
        docReview2.Status__c = 'In Progress';
        insert docReview2;
        System.debug('8-docReview2: ' + docReview2.Id);
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc2 = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc2.Document_Review__c = docReview2.id;
        insert enrollmentDoc2;

        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = nonacademicGroup.id;
        request.educationalInstitution = institutionAccount.id;
        request.schoolYears = '';
        request.gradeLevels = '';
        requestList.add(request);
        
        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('8-nextId: ' + obj.nextId);
            System.debug('8-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 2);
            System.assertEquals(obj.nextId, docReview2.id);
        }
        Test.stopTest();
    }    
    
    // matching educational institution no program enrollments
    static testMethod void getNextTest9() {
        Account institutionAccount = [SELECT Id, Name, RecordTypeId, CreatedDate FROM Account WHERE RecordType.Name = 'Educational Institution' AND Name = 'Test Account' LIMIT 1];
        School_Year__c schoolYears = [SELECT Id, Name, CreatedDate FROM School_Year__c WHERE Name = 'Test School Year' LIMIT 1];
        Grade_Level__c gradeLevelK = [SELECT Id, Name FROM Grade_Level__c WHERE Name = 'K' LIMIT 1];
        Grade_Level__c gradeLevel1 = [SELECT Id, Name FROM Grade_Level__c WHERE Name = '1' LIMIT 1];
        Account academicProgram = [SELECT Id, Name, RecordTypeId, ParentId, School_Year__c, School_Year__r.Name, Registration_End_Date__c, Registration_Start_Date__c, CreatedDate 
                                   FROM Account WHERE RecordType.Name = 'Academic Program' AND Name = 'Test Account' LIMIT 1];
        hed__Program_Enrollment__c studentEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Student' LIMIT 1];
        hed__Program_Enrollment__c caretakerEnrollment = [SELECT Id, Name, CreatedDate FROM hed__Program_Enrollment__c WHERE RecordType.Name = 'Caretaker' LIMIT 1];
        Group nonacademicGroup = [SELECT Id, Name from GROUP where Name='Non-Academic Documents' AND Type='Queue' LIMIT 1];
        Group academicGroup = [SELECT Id, Name from GROUP where Name='Academic Documents' AND Type='Queue' LIMIT 1];
        
        // insert document review
        Document_Review__c docReview = new Document_Review__c();
        docReview.Queue_Type__c = 'Non-Academic';
        docReview.OwnerId = nonacademicGroup.Id;
        docReview.Pending_Review_Date__c = Date.parse('11/17/2017');
        docReview.Status__c = 'In Progress';
        insert docReview;
        
        // insert enrollment document 
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c(Program_Enrollment__c = studentEnrollment.id);
        enrollmentDoc.Document_Review__c = docReview.id;
        insert enrollmentDoc;
        
        List<NES_DocumentReviewUtils.DocumentReviewRequest> requestList = new List<NES_DocumentReviewUtils.DocumentReviewRequest>();
        NES_DocumentReviewUtils.DocumentReviewRequest request = new NES_DocumentReviewUtils.DocumentReviewRequest();
        request.queue = nonacademicGroup.id;
        request.educationalInstitution = institutionAccount.id;
        request.schoolYears = '';
        request.gradeLevels = gradeLevel1.id + '; ';
        requestList.add(request);
        
        Test.startTest();
        List<NES_DocumentReviewUtils.DocumentReviewResponse> responseList = NES_DocumentReviewUtils.getNextDocumentReviews(requestList);
        for (NES_DocumentReviewUtils.DocumentReviewResponse obj : responseList) {
            System.debug('9-nextId: ' + obj.nextId);
            System.debug('9-statusReason: ' + obj.statusReason);
            System.assertEquals(obj.size, 0);
        }
        Test.stopTest();
    }    
    
}