force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Start Year (calculated)</description>
    <label>Start Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Viewed_Final_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Viewed_Final_Confirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viewed Final Confirmation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_ApplicationSummaryTest.cls
/**
 * Created by Ritvik on 26-12-2018.
 */

@IsTest
private class NES_ApplicationSummaryTest {
    @TestSetup
    static void setup() {
        Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        Contact TestContact = Peak_TestUtils.createTestContact();
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('SchoolTest', System.today());
        Account academicAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id, schlYear.Id);
        hed__Program_Enrollment__c ProgramEnrollmentTest = Peak_TestUtils.createProgramEnrollment(academicAccount.Id, TestContact.Id, schlYear.Id, true);
    }

    static testMethod void setFinalConfirmationViewed_Test(){
        School_Year__c schoolYear = [SELECT Id FROM School_Year__c WHERE Name = 'SchoolTest'];
        hed__Program_Enrollment__c programEnrollment = [SELECT Id,Viewed_Final_Confirmation__c FROM hed__Program_Enrollment__c WHERE Start_Year__c =: schoolYear.Id];
        Test.startTest();
        NES_ApplicationSummary.setFinalConfirmationViewed(programEnrollment);
        hed__Program_Enrollment__c programEnrollmentRecord = [SELECT Id,Viewed_Final_Confirmation__c FROM hed__Program_Enrollment__c WHERE Start_Year__c =: schoolYear.Id];
        Test.stopTest();
        System.assertEquals(true,programEnrollmentRecord.Viewed_Final_Confirmation__c);
    }

    static testMethod void getSuccessfulEnrollmentMessage_Test(){
        School_Year__c schoolYear = [SELECT Id FROM School_Year__c WHERE Name = 'SchoolTest'];
        hed__Program_Enrollment__c programEnrollment = [SELECT Id,Viewed_Final_Confirmation__c FROM hed__Program_Enrollment__c WHERE Start_Year__c =: schoolYear.Id];
        Test.startTest();
        System.assertEquals('Confirmed...',NES_ApplicationSummary.getSuccessfulEnrollmentMessage(programEnrollment));
        Test.stopTest();
    }
}