force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Enrollment</fullName>
                <default>true</default>
                <label>Initial Enrollment</label>
            </value>
            <value>
                <fullName>Re-enrolling student</fullName>
            </value>
            <value>
                <fullName>Returning Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>This field used to display in Student program enrollment object, in student program enrollment pagelayout.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Tell Us About Your Student</fullName>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
            <value>
                <fullName>Confirmation Of Enrollment</fullName>
            </value>
            <value>
                <fullName>Intent To Attend</fullName>
            </value>
            <value>
                <fullName>Offer Of Enrollment</fullName>
            </value>
            <value>
                <fullName>Open Application Period</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/updatePipelinePEsCoeRecs.cls
global class updatePipelinePEsCoeRecs implements Database.Batchable<sObject> {
    id processid;
    string academicprogram1;
    datetime PECreatedDate;
    
    global updatePipelinePEsCoeRecs(String academicprogram,id ecProcessID,datetime createdDate1){
        processid=ecProcessID;
        academicprogram1=academicprogram;
        datetime PECreatedDate=createdDate1;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        return  Database.getQueryLocator('SELECT ID, Name, hed__Account__r.Name, Household_Program_Enrollment__c,Enrollment_Type__c FROM hed__program_enrollment__c where hed__Account__r.Name =:academicprogram1 AND Status__c = \'In Progress\' AND RecordType.Name = \'Student\' AND Enrollment_Type__c in (\'Initial Enrollment\', \'Re-enrolling Student\') AND CreatedDate <: PECreatedDate AND Stage__c = \'Intent to Attend\'');
    }
    global void execute(Database.BatchableContext bc, List<hed__program_enrollment__c> scope){   
    
        /*
        //string academicprogram1 = 'WYCA 2021-2022';
        string academicprogram1 = 'MyCA 2021-2022';
        
        //Id processid = 'a294o000001fC9RAAU';
        Id processid = 'a294o000001fC3jAAE';
        DateTime PECreatedDate = DateTime.newInstance(2021, 6, 2, 0, 0, 00); 
		*/       
        
        // Get the Enrollment Component Form RecordTypeId
        Id formId = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where SobjectType = 'Enrollment_Component__c' and Name = 'Form' limit 1].Id;
        // Get the Enrollment Component Section RecordTypeId
        Id sectionId = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where SobjectType = 'Enrollment_Component__c' and Name = 'Section'].Id;
        // Get the Enrollment Component Stage RecordTypeId
        Id stageId = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where SobjectType = 'Enrollment_Component__c' and Name = 'Stage'].Id;
        
        // Getting the List of PEs
        /*
        List <hed__program_enrollment__c> peList = ['SELECT ID, Name, hed__Account__r.Name, Household_Program_Enrollment__c,Enrollment_Type__c FROM hed__program_enrollment__c where hed__Account__r.Name =: academicprogram1 AND Status__c = 'In Progress' AND RecordType.Name =: 'Student' AND Enrollment_Type__c in ('Initial Enrollment', 'Re-enrolling Student') AND CreatedDate <: PECreatedDate AND Stage__c =: 'Confirmation of Enrollment' order by createddate limit 1];
        */
        
        /*
        String templId = 'a094o000009NEBkAAO';
        List <hed__program_enrollment__c> peList = [SELECT ID, Name, hed__Account__r.Name, 
                                                    Household_Program_Enrollment__c,Enrollment_Type__c 
                                                    FROM hed__program_enrollment__c where Id =: templId limit 1];
		*/
        
        List <Id> peIdList = new List <Id> ();
            
        for(hed__program_enrollment__c pe : scope){
            peIdList.add(pe.Id);
        }


        List <Enrollment_Component_Affiliation__c> updEcaformList = new List <Enrollment_Component_Affiliation__c> ();
        List <Enrollment_Component_Affiliation__c> updEcasectionList = new List <Enrollment_Component_Affiliation__c> ();
        
        // Get the List of COE Form ECAs for the above pes
        List <Enrollment_Component_Affiliation__c> ecaformList = [SELECT Id, Name, Program_Enrollment__c FROM Enrollment_Component_Affiliation__c where Program_Enrollment__c in: peIdList and  Enrollment_Component__r.RecordTypeId =: formId and Enrollment_Component__r.Name =: 'Intent to Attend'];
        
        // Update the Form Status to 'Not Started'
        for(Enrollment_Component_Affiliation__c ecaform: ecaformList){
            ecaform.Status__c = 'Not Started';
            updEcaformList.add(ecaform);
        }
        update updEcaformList;
        
        // Get the List of COE Section ECAs for the above pes
        List <Enrollment_Component_Affiliation__c> ecasectionList = [SELECT Id, Name, Program_Enrollment__c FROM Enrollment_Component_Affiliation__c where Program_Enrollment__c in: peIdList and Enrollment_Component__r.RecordTypeId =: sectionId and Enrollment_Component__r.Name =: 'Intent to Attend Notice'];
        
        // Update the Section Status to 'Not Started'
        for(Enrollment_Component_Affiliation__c ecasection: ecasectionList){
            ecasection.Status__c = 'Not Started';
            updEcasectionList.add(ecasection);
        }
        update updEcasectionList;
        
        for(hed__program_enrollment__c pe: scope){
            System.debug('PE ID being processed is :::::' + pe.Id);
            EvaluationUtils.PerformAsyncNewStudentStepsUpdatePipelinePEs(pe.id,processid,pe.Household_Program_Enrollment__c,
                                                                               pe.Enrollment_Type__c);	
        }
        
        // Get the Tell Us about your Student Stage ECAs and Update the Status to Complete
        List <Enrollment_Component_Affiliation__c> tellusEcaList = [SELECT Id, Name, Program_Enrollment__c FROM Enrollment_Component_Affiliation__c where Program_Enrollment__c in: peIdList and  Enrollment_Component__r.RecordTypeId =: stageId and Enrollment_Component__r.Name =: 'Tell us About your Student'];
        
        List <Enrollment_Component_Affiliation__c> updtellusEcaList = new List <Enrollment_Component_Affiliation__c> ();
        for(Enrollment_Component_Affiliation__c tellustage: tellusEcaList){
        tellustage.Status__c = 'Complete';
        updtellusEcaList.add(tellustage);
        }
        update updtellusEcaList;
        
        // Get the Open Application Stage ECAs and Update the Status to Complete
        List <Enrollment_Component_Affiliation__c> opAppEcaList = [SELECT Id, Name, Program_Enrollment__c FROM Enrollment_Component_Affiliation__c where Program_Enrollment__c in: peIdList and  Enrollment_Component__r.RecordTypeId =: stageId and Enrollment_Component__r.Name =: 'Open Application'];
        
        List <Enrollment_Component_Affiliation__c> updopAppEcaList = new List <Enrollment_Component_Affiliation__c> ();
        for(Enrollment_Component_Affiliation__c tellustage: tellusEcaList){
        tellustage.Status__c = 'Complete';
        updopAppEcaList.add(tellustage);
        }
        update updopAppEcaList;
        
        // Get the List of COE Stage ECAs for the above pes 
        List <Enrollment_Component_Affiliation__c> ecastageList = [SELECT Id, Name, Program_Enrollment__c FROM Enrollment_Component_Affiliation__c where Program_Enrollment__c in: peIdList and  Enrollment_Component__r.RecordTypeId =: stageId and Enrollment_Component__r.Name =: 'Intent to Attend'];
        
        List <Enrollment_Component_Affiliation__c> updEcastageList = new List <Enrollment_Component_Affiliation__c> ();
        
        // Update the Stage Status to 'Not Started'
        for(Enrollment_Component_Affiliation__c ecastage: ecastageList){
            ecastage.Status__c = 'Not Started';
            updEcastageList.add(ecastage);
        }
        update updEcastageList;
        
        // Update the Stage Status to 'In Progress'
        ecastageList = [SELECT Id, Name, Program_Enrollment__c FROM Enrollment_Component_Affiliation__c where Program_Enrollment__c in: peIdList and  Enrollment_Component__r.RecordTypeId =: stageId and Enrollment_Component__r.Name =: 'Intent to Attend'];
        
        updEcastageList = new List <Enrollment_Component_Affiliation__c> ();
        // Update the Stage Status to 'In Progress'
        for(Enrollment_Component_Affiliation__c ecastage: ecastageList){
            ecastage.Status__c = 'In Progress';
            updEcastageList.add(ecastage);
        }
        update updEcastageList;  
    }
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
    
    public static void testCoveragePaddingMethod(){
        integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }

}