force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Commuity_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Educational_Institution_SSTF_Mapping__mdt.object
<CustomObject>
    <description>This custom metadata is used to Assign Permission Set to School staff Community User (US#123101 - Task# 160180, 159334 &amp; 158397).</description>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <description>US #123101 - This field is used to capture the associated permission set name belonging to the Internal Staff users. This field gets set when the Batch Job named CS_SSTFPublicGroupUserPermissionBatch is executed.</description>
        <label>Permission Set Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>US #123101 - This field is used to capture the associated school name(Educational Institutions Account ) belonging to the School Staff Community users. This field gets set when the Batch Job named CS_SSTFpermissionBatch is executed.</description>
        <label>School</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Educational Institution_SSTF_Mapping</label>
    <pluralLabel>Educational Institution_SSTF_Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mapping_Profiles__mdt.object
<CustomObject>
    <description>This Metadata represents information regarding the profile names of School Counselor, School Principal, School Special Education Director, School Staff Administrator.</description>
    <label>Mapping Profile</label>
    <pluralLabel>Mapping Profiles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mapping_Profiles__mdt/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <description>US # 123101 - This field holds the value of Non-Community profile names like School Counselor, School Principal, School Special Education Director, School Staff Administrator. This field is set when the batch CS_SSTFPublicGroupUserPermissionBatch is executed.</description>
    <label>Profile Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Records_Processing_Intervals__mdt.object
<CustomObject>
    <description>This is created for User Story No. 164369 (Pls don&apos;t delete). This MDT is for determining how earlier the records should be taken into consideration based on the days, hours, mins for processing. This is being used in determining the timestamp of the Program Enrollment/Relationship object records for the LC Community Access to School relevant Knowledge Articles based on Topics.</description>
    <fields>
        <fullName>Days__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Days that we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions.The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter a negative value say &quot;-1&quot; to pick records updated in the last 1 day&apos;s time. &quot;-2&quot; will imply records that were updated in the last 2 days time interval.</inlineHelpText>
        <label>Days</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Hours by which we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions. The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter the hours in negative values like &quot;-3&quot; to consider records that were updated in the last 3 hours accordingly. &quot;-6&quot; will imply records that were updated in the last 6 hours time interval.</inlineHelpText>
        <label>Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Mins by which we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions. The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter the Minutes in negative values like &quot;-30&quot; to consider records that were updated in the last 30 minutes accordingly. &quot;-40&quot; will imply records that were updated in the last 40 minutes time interval.</inlineHelpText>
        <label>Minutes</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Records Processing Intervals</label>
    <pluralLabel>Records Processing Intervals</pluralLabel>
</CustomObject>

force-app/main/default/classes/CS_SSTFPermissionBatch.cls
/*
 * Developed By: Sai Rakesh Puli (NESS TECHNOLOGIES)

 * User Story # 176990 
 * Task # 177183 
 * Description - This batch job class used to process School staff records on Contact object.This job will associate or remove permission set for School staff based on the School and its related permission sets
 *               All the School Staff contact records will be pulled that were updated on a specific time frame (Historical records processing)/Last modified date 
 *  TestClass -  Refer CS_SSTFPermissionBatchTest             
*/

global class CS_SSTFPermissionBatch implements  Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext bc) {

        Records_Processing_Intervals__mdt recordProcessInterval = [SELECT Id, Days__c, Hours__c, Minutes__c FROM Records_Processing_Intervals__mdt WHERE DeveloperName = :CS_Constants.SSTF_PERMISSION_ACCESS_PROCESS];
        DateTime dateTimeInterval = system.now().addDays(Integer.valueOf(recordProcessInterval.Days__c)).addHours(Integer.valueOf(recordProcessInterval.Hours__c)).addMinutes(Integer.valueOf(recordProcessInterval.Minutes__c));    
        String schoolstaffRec = CS_Constants.SCHOOL_RECTYPE_STAFF;
        String batchQueryStr = 'SELECT Id, Name, AccountId,Account.Name, Commuity_User__c,Commuity_User__r.Profile.Name FROM Contact WHERE Recordtype.DeveloperName=:schoolstaffRec  AND Commuity_User__c !=null AND LastModifiedDate >= :dateTimeInterval';         



        //System.debug('TEST REC'+batchQueryStr);
        return Database.getQueryLocator(batchQueryStr);
    }
    
    global void execute(Database.BatchableContext bc, List<Contact> ContactList){
        
        List<PermissionSetAssignment> permissionSetList = new List<PermissionSetAssignment>();
        Set<String> permissionSetNames = new Set<String>();


        Set<PermissionSetAssignment> deletepermSet = new Set<PermissionSetAssignment>();
        List<PermissionSetAssignment> deletepermList = new List<PermissionSetAssignment>();
        Map<String,Id> permissionSetMap = new Map<String,Id>();
        Map<String,PermissionSetAssignment> permissionSetAssignetoIdMap = new Map<String,PermissionSetAssignment>();
        Map<String,String> permissionSetAssignmentMap = new Map<String,String>();
        Map<String,Educational_Institution_SSTF_Mapping__mdt> schooltoMdtMap = new Map<String,Educational_Institution_SSTF_Mapping__mdt>();
        Set<String> uniqueCommuserSet = new Set<String>();
        

        Set<String> profileName = new set<String>();  
         //Looping Metadata and capturing Profile Names
        for(Mapping_Profiles__mdt	mp:[Select Profile_Name__c from Mapping_Profiles__mdt]){
            profileName.add(mp.Profile_Name__c);
        }
        
        for(contact cont:ContactList){
            if(profileName.contains(cont.Commuity_User__r.Profile.Name)){
            uniqueCommuserSet.add(cont.Commuity_User__c);
            }
        }
        
        //fetching all Metadata from org
        List<Educational_Institution_SSTF_Mapping__mdt> EISSTFMappingList =  [SELECT MasterLabel,
                                                                        Permission_Set_Name__c,

                                                                        School__c                                                                     
                                                                        FROM Educational_Institution_SSTF_Mapping__mdt];
        //looping metadata and capturing permissionSet names
        
        for(Educational_Institution_SSTF_Mapping__mdt custMdt: EISSTFMappingList)
        {
            permissionSetNames.add(custMdt.Permission_Set_Name__c);
           // system.debug('permissionSetNames====='+permissionSetNames);
            schooltoMdtMap.put(custMdt.School__c,custMdt);
            
          
        } 
        //Preparing map with metadata permissionSet names with permission id
        for(PermissionSet ps: [Select id,Name from PermissionSet WHERE Name IN:permissionSetNames AND IsOwnedByProfile = FALSE])
        {
            permissionSetMap.put(ps.Name,ps.Id);
            //system.debug('permissionSetMap====='+permissionSetMap);
        }
        
        //Query for PermissionSetAssignment 
        for(PermissionSetAssignment psa: [Select id,AssigneeId,PermissionSetId  from PermissionSetAssignment WHERE AssigneeId=:uniqueCommuserSet
                                                  AND PermissionSetId IN (SELECT Id  FROM PermissionSet WHERE IsOwnedByProfile =false)])                                                
        {


            
            permissionSetAssignmentMap.put(psa.AssigneeId,psa.PermissionSetId);
            permissionSetAssignetoIdMap.put(psa.AssigneeId,psa);

        }
        
        //Populate Associate and removal permission sets based on Contact iteration
          for(Contact con: ContactList) 
          {
              //System.debug('Printing SchooltoMdtMap'+schooltoMdtMap.get(con.account.name));

              if(con.AccountId !=null && schooltoMdtMap.get(con.account.name) !=null && uniqueCommuserSet.contains(con.Commuity_User__c))
              {


                      //For the existing School staff if there is a realignment to different School then remove the old permission set
                      if(permissionSetAssignmentMap.get(con.Commuity_User__c)!=null && permissionSetAssignmentMap.get(con.Commuity_User__c)!=permissionSetMap.get(schooltoMdtMap.get(con.account.name).Permission_Set_Name__c)){
                          //System.debug('Lets delete this permission-->'+permissionSetAssignetoIdMap.get(con.Commuity_User__c));


                          deletepermSet.add(permissionSetAssignetoIdMap.get(con.Commuity_User__c));
                      }
                      // 
                       if(permissionSetAssignmentMap.get(con.Commuity_User__c)== permissionSetMap.get(schooltoMdtMap.get(con.account.name).Permission_Set_Name__c)){
                           //If there is no realignment to different school and if there is already existing permissionset for the School staff then do
                           //nothing 


                          // System.debug('Conditions are matched so do nothing-->'+con.Id+'==comm user-->'+con.Commuity_User__c);
                       }else{    
                      PermissionSetAssignment psa = new PermissionSetAssignment (PermissionSetId =permissionSetMap.get(schooltoMdtMap.get(con.account.name).Permission_Set_Name__c) ,
                                                                                           AssigneeId = con.Commuity_User__c);
                      permissionSetList.add(psa);
                       }


                    // }
              }
              
          }
        
        if(permissionSetList !=null && permissionSetList.size() >0)
        {

            Database.insert(permissionSetList,false);
        }
       


        if(deletepermSet !=null && deletepermSet.size() > 0){
            deletepermList.addAll(deletepermSet);
             //System.debug('Printing DELETE PERM LIST'+deletepermList);

             Database.delete(deletepermList,false);
        }
    }
      
    global void finish(Database.BatchableContext bc){
       
    }
}