force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Annual_Student_Information__c.object
<CustomObject>
    <description>Student data that is specific to a school year is stored on the Annual Student Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Student Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The School Year record for the year the data is relevant to.</description>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Student Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Student Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/IEP__c.field-meta.xml
<CustomField>
    <fullName>IEP__c</fullName>
    <description>This field is set via workflow from the related ASI field instead of directly on PE</description>
    <encryptionScheme>None</encryptionScheme>
    <label>IEP</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Special_Education__c.object
<CustomObject>
    <description>The Special Education Data object stores data related to IEPs, 504 plans, gifted education, and other student services</description>
    <fields>
        <fullName>Gifted__c</fullName>
        <description>Identifies gifted students</description>
        <label>Gifted</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Documenting</fullName>
                </value>
                <value>
                    <fullName>Gifted Allow</fullName>
                </value>
                <value>
                    <fullName>Gifted Allow Continue</fullName>
                </value>
                <value>
                    <fullName>Gifted Connections Academy Identification</fullName>
                </value>
                <value>
                    <fullName>Gifted EP - FL</fullName>
                </value>
                <value>
                    <fullName>Gifted IEP</fullName>
                </value>
                <value>
                    <fullName>Gifted Local School Identification</fullName>
                </value>
                <value>
                    <fullName>Gifted No Gifted Courses</fullName>
                </value>
                <value>
                    <fullName>Gifted Potential</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IEPLastUpdated__c</fullName>
        <description>When was the last time the student&apos;s IEP was updated?</description>
        <label>IEP Last Updated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Within the last year</fullName>
                </value>
                <value>
                    <fullName>Within the last two years</fullName>
                </value>
                <value>
                    <fullName>Within the last three years</fullName>
                </value>
                <value>
                    <fullName>More than three years ago</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IEP__c</fullName>
        <description>Students with disabilities with IEPs</description>
        <label>IEP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Documenting</fullName>
                </value>
                <value>
                    <fullName>IEP</fullName>
                </value>
                <value>
                    <fullName>IEP-Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Special Education</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Special Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Educations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_SpecialEdBusinessLogicTest.cls
/**
 * Created by Anushka Bansal on 27-11-2018.
 */

@IsTest
public with sharing class NES_SpecialEdBusinessLogicTest {
    @TestSetup static void setup() {
      Peak_TestUtils.createNESBusinessLogicSwitch('SpecialEdTrigger', true);
        Peak_TestUtils.createNESBusinessLogicSwitch('Likelihood to Transition Score', true);
        Peak_TestUtils.createNESBusinessLogicSwitch(NES_EntranceAgeUtility.ENTRANCE_AGE_CUSTOM_SETTING_VALUE, true);
        Peak_TestUtils.createNESBusinessLogicSwitch('Why Flagged', true);
        Account account = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019',date.parse('11/17/2018'));
        School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018',date.parse('11/17/2017'));
        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);
        Account academicProgramAccount = Peak_TestUtils.createAccountForNewStudentData(account.Id,currentSchoolYear.Id);
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgramAccount.Id, contact.Id,currentSchoolYear.Id, true);
        Annual_Student_Information__c currentASI = Peak_TestUtils.createAnnualStudentInformation('Current ASI', progEnrollment.Id, currentSchoolYear.Id, true);
        
    }


    static testMethod void testInsertSpecialEducation(){
     hed__Program_Enrollment__c progEnrollment = [select Id from hed__Program_Enrollment__c limit 1];
     Test.startTest();
     Special_Education__c specialEducation = Peak_TestUtils.createSpecialEducation(progEnrollment.Id, false);
     specialEducation.IEPLastUpdated__c = 'Within the last year';
     specialEducation.Gifted__c = 'Documenting';
     insert specialEducation;
     NES_Constants.runAssignment = true;
     System.assertNotEquals(null, specialEducation);
     Test.stopTest();
    }
    
    static testMethod void updateSpecialEducationTest(){
        hed__Program_Enrollment__c progEnrollment = [select Id from hed__Program_Enrollment__c limit 1];
        Special_Education__c specialEducation = Peak_TestUtils.createSpecialEducation(progEnrollment.Id, true);
        Test.startTest();
        specialEducation.IEP__c = 'Documenting';
        specialEducation.IEPLastUpdated__c = 'Within the last year';
        specialEducation.Gifted__c = 'Documenting';
        update specialEducation;
        System.assertEquals(specialEducation.IEP__c ,'Documenting');
        Test.stopTest();
    }
}