force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Document_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Document_End_Date__c</fullName>
    <description>The date/time that document submission stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Submission End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Document_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Document_Start_Date__c</fullName>
    <description>The date/time that document submission will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Submission Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade_Level__c.object
<CustomObject>
    <description>The grade level object stores grade level information for connection to Academic Programs and Caps.</description>
    <label>Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Academic_Program__c</fullName>
    <label>Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Document_Submission_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Document_Submission_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Submission End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NES_EnrollmentUtils.cls
/**
 * Created by raydehler on 2019-03-13.
 */
public without sharing class NES_EnrollmentUtils {

    private static Peak_ApexLog logger = new Peak_ApexLog('EnrollmentUtils');

    // Maps to prevent multiple queries
    private static Map<Id, Map<String, DateTime>> accountGradeStartMap = new Map<Id, Map<String, DateTime>>();
    private static Map<Id, Map<String, DateTime>> accountGradeEndMap = new Map<Id, Map<String, DateTime>>();

    /*
     * Build Maps for Document Submission Start and End
     * Program Grade Level overrides the value set on the Academic Program, if set
     */
    private static void buildAccountGradeMaps(Id accountId) {
        if (!accountGradeStartMap.containsKey(accountId) && !accountGradeEndMap.containsKey(accountId))  {
            accountGradeStartMap.put(accountId, new Map<String, DateTime>());
            accountGradeEndMap.put(accountId, new Map<String, DateTime>());
            logger.logInfo('buildAccountGradeMaps', 'building account map for '+accountId);
        }  else  {
            return;
        }
        for (Program_Grade_Level__c pgl : [
                SELECT Grade_Level__r.Name,
                        Document_Submission_Start_Date__c,
                        Document_Submission_End_Date__c,
                        Academic_Program__r.Document_Start_Date__c,
                        Academic_Program__r.Document_End_Date__c
                FROM Program_Grade_Level__c
                WHERE Academic_Program__c = :accountId]) {

            accountGradeStartMap.get(accountId).put(pgl.Grade_Level__r.Name,
                    pgl.Document_Submission_Start_Date__c != null ? pgl.Document_Submission_Start_Date__c : pgl.Academic_Program__r.Document_Start_Date__c);
            accountGradeEndMap.get(accountId).put(pgl.Grade_Level__r.Name,
                    pgl.Document_Submission_End_Date__c != null ? pgl.Document_Submission_End_Date__c : pgl.Academic_Program__r.Document_End_Date__c);
        }

        logger.logInfo('buildAccountGradeMaps', 'start map: '+accountGradeStartMap);
        logger.logInfo('buildAccountGradeMaps', 'end map: '+accountGradeEndMap);
        logger.saveLogs();
    }

    public static Datetime getDocumentStartDate(Id accountId, String gradeLevel) {
        if (!accountGradeStartMap.containsKey(accountId)) {
            buildAccountGradeMaps(accountId);
        }

        return accountGradeStartMap.get(accountId).get(gradeLevel);
    }

    public static Datetime getDocumentEndDate(Id accountId, String gradeLevel) {
        if (!accountGradeEndMap.containsKey(accountId)) {
            buildAccountGradeMaps(accountId);
        }

        return accountGradeEndMap.get(accountId).get(gradeLevel);
    }

    public static String getStudentName(Id studentId, Id programEnrollmentId) {

        String studentName = '';
        if(String.isNotBlank(studentId)) {
            User currentUser = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
            Id contactId = currentUser.ContactId;
            if (String.isNotBlank(contactId)) {

                List<hed__Relationship__c> relationships = [
                        SELECT Id, hed__Contact__c, hed__RelatedContact__c
                        FROM hed__Relationship__c
                        WHERE hed__Contact__c = :contactId
                        AND hed__RelatedContact__c =: studentId
                ];
                if (relationships.size() > 0) {
                    List<Contact> students = [SELECT Name FROM Contact WHERE Id = :studentId];
                    if (students.size() > 0) {
                        studentName = students[0].Name;
                    } else {
                        studentName = 'InvalidUser';
                    }
                } else {
                    studentName = 'InvalidUser';
                }
            }
        } 

        return studentName;
    }
}