force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Annual_Student_Information__c.object
<CustomObject>
    <description>Student data that is specific to a school year is stored on the Annual Student Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Student Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>Grade_Level_Requested__c</fullName>
        <description>The grade level the student is requesting for the school year.</description>
        <label>Grade Level Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>Kindergarten</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment record for the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The School Year record for the year the data is relevant to.</description>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Student Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Student Information</pluralLabel>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Comparison_Data_Type__c</fullName>
        <label>Comparison Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Date (Years Calculated)</fullName>
                </value>
                <value>
                    <fullName>Datetime</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comparison_Value__c</fullName>
        <description>The value being used on the right side of the criteria comparison. This field should be populated if you are comparing the left side field to a static value.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comparison Value (Right)</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <description>Within the enrollment model, some objects are a one to many off of the Program Enrollment. For example, ASI (Annual Student Information). In those cases, we need to know which Criteria record need recalculating. This field will store the school year that this criteria is related to.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Enrollment_Criteria__c.object
<CustomObject>
    <description>Stores all the criteria records tied to a Program Enrollment and stores the current result (true or false) of that criteria.</description>
    <fields>
        <fullName>Criteria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Program Enrollment Criteria</relationshipLabel>
        <relationshipName>Program_Enrollment_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The PE this criteria is tied to.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Program Enrollment Criteria</relationshipLabel>
        <relationshipName>Program_Enrollment_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The current result of this criteria.</description>
        <label>Result</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <description>Within the enrollment model, some objects are a one to many off of the Program Enrollment.  For example, ASI (Annual Student Information).  In those cases, we need to know which Criteria record need recalculating. This field will store the school year that this criteria is related to.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Program Enrollment Criteria</label>
    <nameField>
        <displayFormat>PEC-{000000}</displayFormat>
        <label>Program Enrollment Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EvaluationUtilsTest.cls
@isTest
public class EvaluationUtilsTest  {
    @TestSetup 
    static void setup(){
    }

    static testMethod void testNumberComparisonsEquals(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Number';
        testItem.comparisonValueRight = '5';
        testItem.newValue = 5;
        testItem.operator = '=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 6;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testNumberComparisonsLessThan(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Number';
        testItem.comparisonValueRight = '6';
        testItem.newValue = 5;
        testItem.operator = '<';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 6;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
        
        testItem.newValue = 7;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testNumberComparisonsGreaterThan(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Number';
        testItem.comparisonValueRight = '4';
        testItem.newValue = 5;
        testItem.operator = '>';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);
        
        testItem.newValue = 4;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);

        testItem.newValue = 3;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testNumberComparisonsNotEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Number';
        testItem.comparisonValueRight = '6';
        testItem.newValue = 5;
        testItem.operator = '!=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 6;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testNumberComparisonsLessThanOrEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Number';
        testItem.comparisonValueRight = '6';
        testItem.newValue = 5;
        testItem.operator = '<=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 6;
        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);
        
        testItem.newValue = 7;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testNumberComparisonsGreaterThanOrEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Number';
        testItem.comparisonValueRight = '6';
        testItem.newValue = 7;
        testItem.operator = '>=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 6;
        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);
        
        testItem.newValue = 4;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }

    static testMethod void testDateComparisonsEquals(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Date';
        testItem.comparisonValueRight = Datetime.now().format('MM/dd/YYYY');
        testItem.newValue = Date.today();
        testItem.operator = '=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        date futureDate = Date.today().addDays(5);
        testItem.newValue = futureDate;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testDateComparisonsLessThan(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Date';
        testItem.comparisonValueRight = Datetime.now().format('MM/dd/YYYY');
        date pastDate = Date.today().addDays(-5);
        testItem.newValue = pastDate;
        testItem.operator = '<';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        date futureDate = Date.today().addDays(5);
        testItem.newValue = futureDate;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testDateComparisonsGreaterThan(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Date';
        testItem.comparisonValueRight = Datetime.now().format('MM/dd/YYYY');
        date futureDate = Date.today().addDays(5);
        testItem.newValue = futureDate;
        testItem.operator = '>';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        futureDate = Date.today().addDays(-5);
        testItem.newValue = futureDate;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testDateComparisonsNotEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Date';
        testItem.comparisonValueRight = Datetime.now().format('MM/dd/YYYY');
        date futureDate = Date.today().addDays(5);
        testItem.newValue = futureDate;
        testItem.operator = '!=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = Date.today();
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testDateComparisonsLessThanOrEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Date';
        testItem.comparisonValueRight = Datetime.now().format('MM/dd/YYYY');
        date futureDate = Date.today().addDays(-5);
        testItem.newValue = futureDate;
        testItem.operator = '<=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = Date.today();
        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);
        
        futureDate = Date.today().addDays(5);
        testItem.newValue = futureDate;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testDateComparisonsGreaterThanOrEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Date';
        testItem.comparisonValueRight = Datetime.now().format('MM/dd/YYYY');
        date futureDate = Date.today().addDays(5);
        testItem.newValue = futureDate;
        testItem.operator = '>=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = Date.today();
        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);
        
        futureDate = Date.today().addDays(-5);
        testItem.newValue = futureDate;
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }

    static testMethod void testOtherComparisonsEquals(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Text';
        testItem.comparisonValueRight = 'dog';
        testItem.newValue = 'dog';
        testItem.operator = '=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 'cat';
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testOtherComparisonsLessThan(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Text';
        testItem.comparisonValueRight = 'dog';
        testItem.newValue = 'cat';
        testItem.operator = '<';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 'mouse';
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testOtherComparisonsGreaterThan(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Text';
        testItem.comparisonValueRight = 'dog';
        testItem.newValue = 'mouse';
        testItem.operator = '>';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 'cat';
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testOtherComparisonsNotEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Text';
        testItem.comparisonValueRight = 'dog';
        testItem.newValue = 'cat';
        testItem.operator = '!=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 'dog';
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testOtherComparisonsLessThanOrEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Text';
        testItem.comparisonValueRight = 'dog';
        testItem.newValue = 'dog';
        testItem.operator = '<=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 'cat';
        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);
        
        testItem.newValue = 'mouse';
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testOtherComparisonsGreaterThanOrEqual(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Text';
        testItem.comparisonValueRight = 'dog';
        testItem.newValue = 'dog';
        testItem.operator = '>=';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.newValue = 'mouse';
        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);
        
        testItem.newValue = 'cat';
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }

    static testMethod void testOtherComparisonsContains(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Text';
        testItem.newValue = 'catdoglike';
        testItem.comparisonValueRight = 'dog'; 
        testItem.operator = 'CONTAINS';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.comparisonValueRight = 'mouse';
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }
    
    static testMethod void testOtherComparisonsDoesNotContain(){
        EvaluationUtils.criteriaItem testItem = new EvaluationUtils.criteriaItem();
        testItem.comparisonDataType = 'Text';
        testItem.newValue = 'catdoglike';
        testItem.comparisonValueRight = 'mouse';
        testItem.operator = 'DOES NOT CONTAIN';

        testItem.calculateNewResult();
        System.assertEquals(true, testItem.newResult);

        testItem.comparisonValueRight = 'cat';
        testItem.calculateNewResult();
        System.assertEquals(false, testItem.newResult);
    }

    static testMethod void testPassingFieldsUpdatesPECriteria(){
        Criteria__c criteria1 = Peak_TestUtils.createCriteriaRecord(null, 'Annual_Student_Information__c.Grade_Level_Requested__c', '=', false);
        criteria1.Comparison_Data_Type__c = 'Text';
        criteria1.Comparison_Value__c = '5';
        insert criteria1;

        //Create Educational Institutional Account i.e.., Parent Account
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        //Insert the School Year record
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());

        //Create Academic Program Account i.e.., Child Account
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
        academicProgram.Registration_Start_Date__c = System.today().addDays(-10);
        academicProgram.Registration_End_Date__c = System.today().addDays(10);
        update academicProgram;

        // Create a Contact with 'Caretaker' record type
        Contact careTakerContact = Peak_TestUtils.createTestContact('Caretaker', institutionAccount.Id);

        //Create a care taker user for community
        User careTaker = Peak_TestUtils.CreatePortalCaretTakerUser(careTakerContact.Id);

        // Create a Contact with 'Students' record type
        Contact student = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);

        hed__program_enrollment__c program_enrollment_1 = Peak_TestUtils.createProgramEnrollment(String.valueOf(academicProgram.Id), String.valueOf(Student.Id), String.valueOf(schoolYear.Id), false);
        insert program_enrollment_1;

        //Insert a Program Enrollment Criteria record that will link the PE to the Criteria record created above.
        Program_Enrollment_Criteria__c newPEC = new Program_Enrollment_Criteria__c (Program_Enrollment__c=program_enrollment_1.Id, Criteria__c = criteria1.id, Result__c = false);
        insert newPEC;

        List<EvaluationUtils.fieldUpdate> fieldUpdateList = new List<EvaluationUtils.fieldUpdate> ();
        EvaluationUtils.fieldUpdate newFieldUpdate = new EvaluationUtils.fieldUpdate ();
        newFieldUpdate.programEnrollmentId = program_enrollment_1.Id;
        newFieldUpdate.objectAndFieldName = 'Annual_Student_Information__c.Grade_Level_Requested__c';
        newFieldUpdate.newValue = '5';
        fieldUpdateList.add(newFieldUpdate);

        Test.startTest();
        EvaluationUtils.evaluateChangedFields  (fieldUpdateList);
        Test.stopTest();

        List<Program_Enrollment_Criteria__c> afterEvaluate = new List<Program_Enrollment_Criteria__c> ([select Result__c from Program_Enrollment_Criteria__c]);

        System.assertEquals(true, afterEvaluate[0].Result__c);
    }


    static testMethod void testPassingFieldsUpdatesPECriteria2(){
        Criteria__c criteria1 = Peak_TestUtils.createCriteriaRecord(null, 'Annual_Student_Information__c.Grade_Level_Requested__c', '=', false);
        criteria1.Comparison_Data_Type__c = 'Text';
        criteria1.Comparison_Value__c = '5';
        insert criteria1;

        //Create Educational Institutional Account i.e.., Parent Account
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        //Insert the School Year record
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());

        //Create Academic Program Account i.e.., Child Account
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
        academicProgram.Registration_Start_Date__c = System.today().addDays(-10);
        academicProgram.Registration_End_Date__c = System.today().addDays(10);
        update academicProgram;

        // Create a Contact with 'Caretaker' record type
        Contact careTakerContact = Peak_TestUtils.createTestContact('Caretaker', institutionAccount.Id);

        //Create a care taker user for community
        User careTaker = Peak_TestUtils.CreatePortalCaretTakerUser(careTakerContact.Id);

        // Create a Contact with 'Students' record type
        Contact student = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);

        hed__program_enrollment__c program_enrollment_1 = Peak_TestUtils.createProgramEnrollment(String.valueOf(academicProgram.Id), String.valueOf(Student.Id), String.valueOf(schoolYear.Id), false);
        insert program_enrollment_1;

        //Insert a Program Enrollment Criteria record that will link the PE to the Criteria record created above.
        Program_Enrollment_Criteria__c newPEC = new Program_Enrollment_Criteria__c (Program_Enrollment__c=program_enrollment_1.Id, Criteria__c = criteria1.id, Result__c = false, School_Year__c = '2019-2020');
        insert newPEC;

        List<EvaluationUtils.fieldUpdate> fieldUpdateList = new List<EvaluationUtils.fieldUpdate> ();
        EvaluationUtils.fieldUpdate newFieldUpdate = new EvaluationUtils.fieldUpdate ();
        newFieldUpdate.programEnrollmentId = program_enrollment_1.Id;
        newFieldUpdate.objectAndFieldName = 'Annual_Student_Information__c.Grade_Level_Requested__c';
        newFieldUpdate.schoolYear = '2019-2020';
        newFieldUpdate.newValue = '5';
        fieldUpdateList.add(newFieldUpdate);

        Test.startTest();
        EvaluationUtils.evaluateChangedFields  (fieldUpdateList);
        Test.stopTest();

        List<Program_Enrollment_Criteria__c> afterEvaluate = new List<Program_Enrollment_Criteria__c> ([select Result__c from Program_Enrollment_Criteria__c]);

        //This test confirms that when the the school year is used and they match, the criteria is updated.
        System.assertEquals(true, afterEvaluate[0].Result__c);
    }

    static testMethod void testPassingFieldsUpdatesPECriteria3(){
        Criteria__c criteria1 = Peak_TestUtils.createCriteriaRecord(null, 'Annual_Student_Information__c.Grade_Level_Requested__c', '=', false);
        criteria1.Comparison_Data_Type__c = 'Text';
        criteria1.Comparison_Value__c = '5';
        insert criteria1;

        //Create Educational Institutional Account i.e.., Parent Account
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        //Insert the School Year record
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());

        //Create Academic Program Account i.e.., Child Account
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
        academicProgram.Registration_Start_Date__c = System.today().addDays(-10);
        academicProgram.Registration_End_Date__c = System.today().addDays(10);
        update academicProgram;

        // Create a Contact with 'Caretaker' record type
        Contact careTakerContact = Peak_TestUtils.createTestContact('Caretaker', institutionAccount.Id);

        //Create a care taker user for community
        User careTaker = Peak_TestUtils.CreatePortalCaretTakerUser(careTakerContact.Id);

        // Create a Contact with 'Students' record type
        Contact student = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);

        hed__program_enrollment__c program_enrollment_1 = Peak_TestUtils.createProgramEnrollment(String.valueOf(academicProgram.Id), String.valueOf(Student.Id), String.valueOf(schoolYear.Id), false);
        insert program_enrollment_1;

        //Insert a Program Enrollment Criteria record that will link the PE to the Criteria record created above.
        Program_Enrollment_Criteria__c newPEC = new Program_Enrollment_Criteria__c (Program_Enrollment__c=program_enrollment_1.Id, Criteria__c = criteria1.id, Result__c = false, School_Year__c = '2019-2020');
        insert newPEC;

        List<EvaluationUtils.fieldUpdate> fieldUpdateList = new List<EvaluationUtils.fieldUpdate> ();
        EvaluationUtils.fieldUpdate newFieldUpdate = new EvaluationUtils.fieldUpdate ();
        newFieldUpdate.programEnrollmentId = program_enrollment_1.Id;
        newFieldUpdate.objectAndFieldName = 'Annual_Student_Information__c.Grade_Level_Requested__c';
        newFieldUpdate.schoolYear = 'NOT2019-2020';  //Notice that the school doesn't match from the school year from the PE Criteria
        newFieldUpdate.newValue = '5';
        fieldUpdateList.add(newFieldUpdate);

        Test.startTest();
        EvaluationUtils.evaluateChangedFields  (fieldUpdateList);
        Test.stopTest();

        List<Program_Enrollment_Criteria__c> afterEvaluate = new List<Program_Enrollment_Criteria__c> ([select Result__c from Program_Enrollment_Criteria__c]);

        //This test confirms that when the the school year is used and they DON'T match, the criteria is NOT updated.
        System.assertEquals(false, afterEvaluate[0].Result__c);
    }
}