force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_File_References__c.object
<CustomObject>
    <label>Document File References</label>
    <nameField>
        <displayFormat>DFR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document File References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_File_References__c/fields/Document_Link__c.field-meta.xml
<CustomField>
    <fullName>Document_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/Enrollment_Document__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Document__c</fullName>
    <label>Enrollment Document</label>
    <referenceTo>Enrollment_Document__c</referenceTo>
    <relationshipLabel>Document File References</relationshipLabel>
    <relationshipName>Document_File_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/File_Path__c.field-meta.xml
<CustomField>
    <fullName>File_Path__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <description>The record containing the document requirements.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Requirements</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Document Notes</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Start Year (calculated)</description>
    <label>Start Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Document_Download__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used in Enrollment Document page.</description>
        <label>Document Download</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used for projects where the developer plans to store many settings for a specific piece of functionality.</description>
    <fields>
        <fullName>Document_Download__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used in Enrollment Document page.</description>
        <label>Document Download</label>
        <type>Checkbox</type>
    </fields>
    <label>Utility Settings</label>
</CustomObject>

force-app/main/default/classes/NES_DocumentFileRefListControllerTest.cls
/*
* Purpose: Test class for NES_DocumentFileReferenceListController 
* Change Log:
*         2019-08-13 initial for #101928 User Story (Chinnamanaidu Neerasa)
*/
@isTest(SeeAllData=false)
private with sharing class NES_DocumentFileRefListControllerTest {
    
    static testMethod void updateDFRTest() {
        
        // Create Program Enrollment Document Record.
        Account account                            = Peak_TestUtils.createTestAccount();
        School_Year__c previousSchoolYear          = Peak_TestUtils.createSchoolYears('2017-2018', date.parse('11/17/2017'));
        Contact contact                            = Peak_TestUtils.createTestContact('Students', account.Id);
        hed__Program_Enrollment__c progEnrollment1 = new hed__Program_Enrollment__c();
        progEnrollment1.Start_Year__c              = previousSchoolYear.Id;
        insert progEnrollment1;
        
        // Create Enrollment Document Record
        List <Document_File_References__c> newlist = new List <Document_File_References__c>();
        Enrollment_Document__c enrolldocmt         = new Enrollment_Document__c ();
        enrolldocmt.Document__c           = 'test document';
        enrolldocmt.Notes__c              = 'notes test';
        enrolldocmt.Program_Enrollment__c = progEnrollment1.id;
        insert enrolldocmt;
        
        // Create Document Reference File Record
        Document_File_References__c documentreference  = new Document_File_References__c ();
        
        documentreference .Document_Link__c = 'test document';
        documentreference .File_Path__c = 'notes test';
        documentreference .Version__c = 2;
        documentreference .Enrollment_Document__c = enrolldocmt.id;
        insert documentreference; 
        
        //create utility settings
        
        Utility_Settings__c userref = new Utility_Settings__c();
        userref.Name='Testdata';
        userref.Document_Download__c=false;
        insert userref;
        
        // start test
        test.startTest();
        
        // calling two methods from classes  
        newlist  = NES_DocumentFileRefListController.getDocList(enrolldocmt.id);
        userref  = NES_DocumentFileRefListController.getUtilitySettings();
        
        // force completion of any async processing
        Test.stopTest();
        
        // retrieve utility settings
        List< Utility_Settings__c > objUser = [SELECT Id, SetupOwnerId, Document_Download__c FROM Utility_Settings__c WHERE SetupOwnerId = : userref.SetupOwnerId ]; 
        
        // comparing method results - positive test and negative test.
        Document_File_References__c dref2 = new Document_File_References__c ();
        for (Document_File_References__c dref1 : newlist) {
            if (dref1.id == documentreference.id){
                dref2.id = dref1.id;
            }
        }
        
        for(Utility_Settings__c usr1 :objUser) {
            if (usr1.setupOwnerId == userref.SetupOwnerId) {
                userref.setupOwnerId = usr1.SetupOwnerId;
            }
        }
        
        // Assert statements for Document file reference
        system.assertEquals( documentreference.id, dref2.id);
        system.assertNotEquals( null, dref2.id);
        
        // Assert statements for Utility settings
        system.assertEquals(userref.SetupOwnerId, userref.SetupOwnerId);
        system.assertnotEquals(null, userref.SetupOwnerId);
        
    }
}