force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Announcement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Academic_Program</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Educational_Institution</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Announcements</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <label>Alert Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Alert</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Body</label>
        <length>1000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Date_Off__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Off</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_On__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dismissable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dismissable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_Grade_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Program Grade Level the Announcement should be displayed for.</description>
        <inlineHelpText>The Program Grade Level the Announcement should be displayed for.</inlineHelpText>
        <label>Program Grade Level</label>
        <referenceTo>Program_Grade_Level__c</referenceTo>
        <relationshipLabel>Announcements</relationshipLabel>
        <relationshipName>Announcements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Announcement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Announcement__c.object
<CustomObject>
    <fields>
        <fullName>Announcement__c</fullName>
        <label>Announcement</label>
        <referenceTo>Announcement__c</referenceTo>
        <relationshipLabel>Contact Announcements</relationshipLabel>
        <relationshipName>Contact_Announcements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Off__c</fullName>
        <description>The date this announcement will be turned off for this contact</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Off</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_On__c</fullName>
        <description>The date this announcement will be turned on for this contact</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dismissed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dismissed</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Announcement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Announcements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade_Level__c.object
<CustomObject>
    <description>The grade level object stores grade level information for connection to Academic Programs and Caps.</description>
    <label>Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Final_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Final_Grade_Level__c</fullName>
    <label>Final Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transitional K</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_AnnouncementsControllerTest.cls
/**
 * Created by Anand on 3/19/2019.
 */
@isTest
private class NES_AnnouncementsControllerTest {

    @TestSetup
    static void testSetup() {
        Account parentAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        School_Year__c schlYear = Peak_TestUtils.createSchoolYears('SchoolTest', System.today());
        Account academicAccount = Peak_TestUtils.createAccountForNewStudentData(parentAccount.Id, schlYear.Id);
        User portalUser = Peak_TestUtils.CreatePortalCaretTakerUser();
        Contact studentContact = Peak_TestUtils.createContact('Student Contact',academicAccount.Id,'Students',true);
        hed__Relationship__c relationship = Peak_TestUtils.createRelationship(portalUser.ContactId,studentContact.Id,true);
        hed__Program_Enrollment__c programEnrollment = Peak_TestUtils.createProgramEnrollment(academicAccount.Id,studentContact.Id,schlYear.Id,false);

        programEnrollment.Final_Grade_Level__c = '8';
        insert programEnrollment;

        Grade_Level__c gradeLevel1 = Peak_TestUtils.createGradeLevel('8',true);
        Grade_Level__c gradeLevel2 = Peak_TestUtils.createGradeLevel('10',true);

        Program_Grade_Level__c programGradeLevel1 = Peak_TestUtils.createProgramGradeLevel('Test PGL1', academicAccount.Id,gradeLevel1.Id,System.today().addDays(50),true);
        Program_Grade_Level__c programGradeLevel2 = Peak_TestUtils.createProgramGradeLevel('Test PGL2', academicAccount.Id,gradeLevel2.Id,System.today().addDays(50),true);

        Announcement__c announcement1 = Peak_TestUtils.createAnnouncement('Test Announcment1',false);
        announcement1.Alert_Type__c = 'Notification';
        announcement1.Body__c = 'Test data for body.';
        announcement1.Date_On__c = System.today().addDays(-20);
        announcement1.Date_Off__c = System.today().addDays(10);
        announcement1.Dismissable__c = false;
        announcement1.Order__c = 1;
        announcement1.Program_Grade_Level__c = programGradeLevel1.Id;
        announcement1.Account__c = null;
        insert announcement1;

        Announcement__c announcement2 = Peak_TestUtils.createAnnouncement('Test Announcment2',false);
        announcement2.Alert_Type__c = 'Notification';
        announcement2.Body__c = 'Test data for body.';
        announcement2.Date_On__c = System.today().addDays(-20);
        announcement2.Date_Off__c = System.today().addDays(10);
        announcement2.Dismissable__c = false;
        announcement2.Order__c = 2;
        announcement2.Program_Grade_Level__c = programGradeLevel1.Id;
        announcement2.Account__c = null;
        insert announcement2;

        Announcement__c announcement3 = Peak_TestUtils.createAnnouncement('Test Announcment3',false);
        announcement3.Alert_Type__c = 'Notification';
        announcement3.Body__c = 'Test data for body.';
        announcement3.Date_On__c = System.today().addDays(-20);
        announcement3.Date_Off__c = System.today().addDays(10);
        announcement3.Dismissable__c = false;
        announcement3.Order__c = 3;
        announcement3.Program_Grade_Level__c = programGradeLevel2.Id;
        announcement3.Account__c = null;
        insert announcement3;

        Contact_Announcement__c contactAnnouncement = Peak_TestUtils.createContactAnnouncement('Test Contact Announcment',portalUser.ContactId,announcement1.Id,false);
        contactAnnouncement.Date_Off__c = System.today().addDays(10);
        contactAnnouncement.Date_On__c = System.today().addDays(-20);
        contactAnnouncement.Dismissed__c = false;
        insert contactAnnouncement;
    }

    static testMethod void unitTestPositiveCases(){
        User portalUser = [SELECT Id FROM User WHERE Username = 'portalUser@gmail.com'];
        Contact_Announcement__c contactAnnouncement = [SELECT Id,Name FROM Contact_Announcement__c Limit 1];
        System.runAs(portalUser) {
            Test.startTest();
            Peak_Response getAnnouncementsResponse = NES_AnnouncementsController.retrieveAnnouncements();
            Peak_Response dismissAnnouncementResponse = NES_AnnouncementsController.dismissAnnouncement(contactAnnouncement.Id);
            System.assertNotEquals(getAnnouncementsResponse,Null);
            System.assert(dismissAnnouncementResponse.success);
            Test.stopTest();
        }
    }
    static testMethod void unitNegativeCases(){
        User stdUser = [SELECT Id FROM User WHERE Id=:userInfo.getUserId()];
        Contact_Announcement__c contactAnnouncement = [SELECT Id,Name FROM Contact_Announcement__c Limit 1];
        System.runAs(stdUser) {
            Test.startTest();
            Peak_Response getAnnouncementsResponse = NES_AnnouncementsController.retrieveAnnouncements();
            //Peak_Response dismissAnnouncementResponse = NES_AnnouncementsController.dismissAnnouncement(contactAnnouncement.Id);
            System.assert(!getAnnouncementsResponse.success);
          //  System.assert(dismissAnnouncementResponse.success);
            Test.stopTest();
        }
    }
}