force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade_Level__c.object
<CustomObject>
    <description>The grade level object stores grade level information for connection to Academic Programs and Caps.</description>
    <label>Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Earliest_Final_Confirmation_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Earliest Final Confirmation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Final_Semester_Indicator__c</fullName>
        <label>Final Semester Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Semester_Indicator__c</fullName>
        <label>Semester Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                    <default>true</default>
                    <label>First</label>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/ActivateWaitlist__c.field-meta.xml
<CustomField>
    <fullName>ActivateWaitlist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>marks when a waitlist has been activated for the program grade level</description>
    <label>Active Waitlist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/EndWaitlist__c.field-meta.xml
<CustomField>
    <fullName>EndWaitlist__c</fullName>
    <description>date time the wait list ends for the program grade level</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Waitlist</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c/fields/StartWaitlist__c.field-meta.xml
<CustomField>
    <fullName>StartWaitlist__c</fullName>
    <description>status of waitlist assignment</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>date time the wait list begins for the program grade level</inlineHelpText>
    <label>Start Waitlist</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_ProgramGradeLevelTriggerTest.cls
/**
* Created by Anushka Bansal on 23-12-2018.
*/

@IsTest
public with sharing class NES_ProgramGradeLevelTriggerTest {
    @TestSetup static void setup() {
        Peak_TestUtils.createNESBusinessLogicSwitch('Waitlist Flag Calculation', true);
        Account account = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019',date.parse('11/17/2018'));
        School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018',date.parse('11/17/2017'));
        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);
        Account academicProgramAccount = Peak_TestUtils.createAccountForNewStudentData(account.Id,currentSchoolYear.Id);
        system.debug(academicProgramaccount + 'academicProgramaccount');
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgramAccount.Id, contact.Id,currentSchoolYear.Id, true);
        Grade_Level__c gradeLevel = Peak_TestUtils.createGradeLevel('TestGrade', true);
        Program_Grade_Level__c programGradeLevel = Peak_TestUtils.createProgramGradeLevel('Test',academicProgramAccount.Id, gradeLevel.Id, System.now(), false);
        programGradeLevel.ActivateWaitlist__c = True;
        programGradeLevel.StartWaitlist__c = System.today();
        programGradeLevel.EndWaitlist__c = System.today();
        insert programGradeLevel;
        Opportunity optyTest1 = Peak_TestUtils.createOpportunity('oldOpty',account.Id,System.Today(),'Open',False);
        optyTest1.Semester_Indicator__c='First';
        optyTest1.Final_Semester_Indicator__c='Second';
        optyTest1.Earliest_Final_Confirmation_Date__c=System.today();
        optyTest1.Program_Enrollment__c=progEnrollment.Id;
        Insert  optyTest1;

    }

    /**
    * Created By Anushka 23/12/2018
    * Purpose : Test waitlistCalculator method on insert
    */
    static testMethod void testInsertProgramGradeLevel(){

        Account acc = [Select id from Account limit 1];
        system.debug('academic ' + acc);
        Grade_Level__c gradeLevel = [select id from Grade_Level__c];
        Program_Grade_Level__c programGradeLevel = Peak_TestUtils.createProgramGradeLevel('Test',acc.Id, gradeLevel.Id, System.now(), false );
        Test.startTest();
        insert programGradeLevel;
        System.assertNotEquals(programGradeLevel, null);
        Test.stopTest();
    }


     /**
    * Created By Anushka 23/12/2018
    * Purpose : Test waitlistCalculator method on update
    */
    static testMethod void testUpdateProgramGradeLevel(){
        Program_Grade_Level__c programGradeLevel = [Select id, ActivateWaitlist__c  from Program_Grade_Level__c limit 1];
        programGradeLevel.ActivateWaitlist__c = True;
        Test.startTest();
        update programGradeLevel;
        System.assertEquals(programGradeLevel.ActivateWaitlist__c, True);
        Test.stopTest();
    }
}