force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Computer_in_Home__c.field-meta.xml
<CustomField>
    <fullName>Computer_in_Home__c</fullName>
    <description>Indicator of whether or not the family has a computer in their home.</description>
    <label>Do you have a computer in your home</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Internet_Connection_Type__c.field-meta.xml
<CustomField>
    <fullName>Internet_Connection_Type__c</fullName>
    <description>Internet connection type for the household.</description>
    <label>Internet Connection Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cable</fullName>
            </value>
            <value>
                <fullName>Dial-up</fullName>
            </value>
            <value>
                <fullName>DSL</fullName>
            </value>
            <value>
                <fullName>Mobile hotspot</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Other - High Speed</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LC_HighestLevelofEducation__c.field-meta.xml
<CustomField>
    <fullName>LC_HighestLevelofEducation__c</fullName>
    <description>The highest level of education recieved by the learning coach</description>
    <label>LC Highest Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>College graduate (Bachelor&apos;s degree)</fullName>
            </value>
            <value>
                <fullName>Graduate school / Post-graduate training</fullName>
            </value>
            <value>
                <fullName>High school graduate</fullName>
            </value>
            <value>
                <fullName>I decline to state</fullName>
            </value>
            <value>
                <fullName>Not a high school graduate</fullName>
            </value>
            <value>
                <fullName>Some college or associate&apos;s degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mktg_Customer_Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Mktg_Customer_Loyalty__c</fullName>
    <description>Returning family with an application for the new school year</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Mktg Customer Loyalty</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Use_Updated_ECA_Process__c.field-meta.xml
<CustomField>
    <fullName>Use_Updated_ECA_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created by Mark Membrino while rewriting the ECA processing.</description>
    <label>Use Updated ECA Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Why_Is_Your_Child_Attending_CA__c</fullName>
        <description>What are the primary reasons the caretaker would like the child to attend Connections Academy?</description>
        <label>Why Is Your Child Attending CA</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>For various reasons, we are dissatisfied with our local public school</fullName>
                </value>
                <value>
                    <fullName>Student did not receive adequate attention from the teacher</fullName>
                </value>
                <value>
                    <fullName>Student has or had mental health concerns</fullName>
                </value>
                <value>
                    <fullName>Student has or had physical health concerns</fullName>
                </value>
                <value>
                    <fullName>Student needs a flexible schedule</fullName>
                </value>
                <value>
                    <fullName>Student was ahead academically</fullName>
                </value>
                <value>
                    <fullName>Student was bullied</fullName>
                </value>
                <value>
                    <fullName>Student was recommended/referred to us by prior school</fullName>
                </value>
                <value>
                    <fullName>Student was struggling academically</fullName>
                </value>
                <value>
                    <fullName>Student was suspended or expelled</fullName>
                </value>
                <value>
                    <fullName>Virtual school will enable me to be more involved with my student&apos;s learning</fullName>
                </value>
                <value>
                    <fullName>I am concerned about my child&apos;s safety at their current school</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Process_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic program associated with the component. This is exclusively used by components with a record type of Process to create a relationship between the account entity and it&apos;s required components. As the child components of the process could be used by multiple processes, there is not a direct relationship between them and a specific academic program and those relationships are inferred from their parent process.</description>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enrollment Components (Academic Program)</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/ELLFlag__c.field-meta.xml
<CustomField>
    <fullName>ELLFlag__c</fullName>
    <description>Flag to mark a student&apos;s potential as an English Learner</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ELL Flag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Enrollment</fullName>
                <default>true</default>
                <label>Initial Enrollment</label>
            </value>
            <value>
                <fullName>Re-enrolling student</fullName>
            </value>
            <value>
                <fullName>Returning Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/LC_HighestLevelofEducation__c.field-meta.xml
<CustomField>
    <fullName>LC_HighestLevelofEducation__c</fullName>
    <description>The highest level of education recieved by the learning coach.</description>
    <label>LC Highest Level of Education</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>College graduate (Bachelor&apos;s degree)</fullName>
            </value>
            <value>
                <fullName>Graduate school / Post-graduate training</fullName>
            </value>
            <value>
                <fullName>High school graduate</fullName>
            </value>
            <value>
                <fullName>I decline to state</fullName>
            </value>
            <value>
                <fullName>Not a high school graduate</fullName>
            </value>
            <value>
                <fullName>Some college or associate&apos;s degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenericSOQLQueries.cls
/* SOQL Queries
Author- Vani
*/

public class GenericSOQLQueries{

public static Set<Id> receivedContactID;
public static list<contact> returnContacts;
    
public static Integer i=0;    

public static Set<Id> enrollmentComIds = new set<id>();
public static Set<Id> ecaIds = new set<id>();

public static list<Enrollment_Component__c> enrollmentComps;// = new list<Enrollment_Component__c>();
public static list<Enrollment_Component_Affiliation__c> ecasList;

public static Set<Id> programEnrollmentIds = new set<id>();
public static list<hed__Program_Enrollment__c> ProgramEnrollmets;

public static Set<Id> criteriaIds;
public static list<Criteria__c> criteriaList; 


    public static list<contact> contactDetails(set<id> contactIdSet){
      //  if(string.isBlank(receivedContactID) || !receivedContactID.equalsIgnoreCase(contactIdSet)){        
       // receivedContactID = new set<Id>();
        if(i==0 || !receivedContactID.containsALL(contactIdSet)){
            i = i+1;
            system.debug('*** Inside IF contactDetails() contactIdSet ==> '+contactIdSet);
            returnContacts= new list<contact>();
            receivedContactID = contactIdSet;
            returnContacts= [select Id, Birthdate__C, Why_Is_Your_Child_Attending_CA__c, accountId, account.LC_HighestLevelofEducation__c, account.Mktg_Customer_Loyalty__c, account.Internet_Connection_Type__c, account.Computer_in_Home__c FROM Contact where id=:contactIdSet];
            System.debug('In If block of -contactDetails');
            return returnContacts;
        }else 
        {
            System.debug('In Else block of -contactDetails');
            return returnContacts;
        }    
    }
    
    public static list<Enrollment_Component__c> enrollmentDetails(set<id> receivedEnroCompID){
            if(enrollmentComIds.isempty() || !enrollmentComIds.containsALL(receivedEnroCompID)){          
                System.debug('inside EC Lists');
                //enrollmentComps = new list<Enrollment_Component__c>();
                enrollmentComIds.addall(receivedEnroCompID);
                enrollmentComps=[SELECT Id, Process_Academic_Program__c FROM Enrollment_Component__c WHERE Process_Academic_Program__c = :receivedEnroCompID];
                return enrollmentComps;
            }else{
                System.debug('In Else block of -enrollmentDetails');
                return enrollmentComps;
            } 
            
        }
    
    public static list<hed__Program_Enrollment__c> programEnrollmentDetails(set<id> receivedProgramEnrollments){
        if(programEnrollmentIds.isempty() || !programEnrollmentIds.containsALL(receivedProgramEnrollments)){
            programEnrollmentIds.addall(receivedProgramEnrollments);   
            ProgramEnrollmets=[SELECT Id, hed__Account__c,ELLFlag__c,hed__Account__r.ParentId, hed__Account__r.Use_Updated_ECA_Process__c,Enrollment_Type__c,hed__Contact__r.RecordType.Name, hed__Contact__r.AccountId,Household_Program_Enrollment__c,Household_Program_Enrollment__r.hed__Contact__c,recordtype.name, hed__Contact__c,hed__Contact__r.Name,Program_Grade_Level__r.Grade_Level__r.Name,V2_External_ID__c,HHPORStatus__c,hed__Contact__r.Account.hed__Primary_Contact__c,LTS__c,LastSchoolType__c,LTSLastCalculation__c,Start_Year__c,Stress_Factors__c,DisciplinaryPastActions__c,Start_Year__r.Name, Start_Year__r.Current_Year__c,WaitlistFlag__c,Program_Grade_Level__c FROM hed__Program_Enrollment__c WHERE Id = :receivedProgramEnrollments];
            return ProgramEnrollmets;
        }else{
            System.debug('In Else block of -programEnrollmentDetails');
            return ProgramEnrollmets;
        }
    }
    //Added for 430196 on 2021-08-09 by Krishna Peddanagammol
    public static list<Enrollment_Component_Affiliation__c> ecaDetails(set<id> receivedECAID){
        if(ecaIds.isempty() || !ecaIds.containsALL(ECAIds)){          
            System.debug('inside ECA Lists');
            ecaIds.addall(receivedECAID);
            ecasList=[SELECT Id,
            Enrollment_Component__r.Waitlist__c,
            Enrollment_Component__r.RecordType.Name,
            Program_Enrollment__c
            FROM Enrollment_Component_Affiliation__c WHERE Id = :receivedECAID];
            return ecasList;
        }else{
            System.debug('In Else block of -ecaDetails');
            return ecasList;
        }             
    }
}