force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Confirmation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_End_Date__c</fullName>
    <description>The date/time that final confirmation stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Confirmation End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <description>The date/time that registration in the academic program stops being available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <description>The date/time that registration in the academic program will become available to CTs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Registration Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Annual_Student_Information__c.object
<CustomObject>
    <description>Student data that is specific to a school year is stored on the Annual Student Information object. All records will include a school year code to indicate what year the record applies for. There may be multiple Annual Student Information records for a single Program Enrollment to track data across multiple years.</description>
    <fields>
        <fullName>Grade_Level_Requested__c</fullName>
        <description>The grade level the student is requesting for the school year.</description>
        <label>Grade Level Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>Kindergarten</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The Program Enrollment record for the student.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The School Year record for the year the data is relevant to.</description>
        <label>School Year</label>
        <referenceTo>School_Year__c</referenceTo>
        <relationshipLabel>Annual Student Information</relationshipLabel>
        <relationshipName>Annual_Student_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Student Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Student Information</pluralLabel>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program Enrollment</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>hed__Program_Enrollment__c.hed__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>hed__Program_Enrollment__c.hed__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <formula>&apos;&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Year</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Comparison_Data_Type__c</fullName>
        <label>Comparison Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Date (Years Calculated)</fullName>
                </value>
                <value>
                    <fullName>Datetime</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <description>Within the enrollment model, some objects are a one to many off of the Program Enrollment. For example, ASI (Annual Student Information). In those cases, we need to know which Criteria record need recalculating. This field will store the school year that this criteria is related to.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flag</fullName>
        <active>true</active>
        <label>Flag</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question_Group</fullName>
        <active>true</active>
        <label>Question Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <recordTypes>
        <fullName>Text</fullName>
        <active>true</active>
        <label>Text</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Enrollment_Criteria__c.object
<CustomObject>
    <description>Stores all the criteria records tied to a Program Enrollment and stores the current result (true or false) of that criteria.</description>
    <fields>
        <fullName>Criteria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Program Enrollment Criteria</relationshipLabel>
        <relationshipName>Program_Enrollment_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <description>The PE this criteria is tied to.</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Program Enrollment Criteria</relationshipLabel>
        <relationshipName>Program_Enrollment_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <description>Within the enrollment model, some objects are a one to many off of the Program Enrollment.  For example, ASI (Annual Student Information).  In those cases, we need to know which Criteria record need recalculating. This field will store the school year that this criteria is related to.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Program Enrollment Criteria</label>
    <nameField>
        <displayFormat>PEC-{000000}</displayFormat>
        <label>Program Enrollment Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PEHierarchyClass.cls
/**
    @class:         ExpressionParserTest           
	@author: 		Mark Membrino
	@date:			8/31/2020
	@description:   Test coverage expression evaluator, part of rewrite of the ECA assignment and completion logic.
    @classes-covered with coverage snapshot: 	
        => SyntaxKind (% coverage)
        
        // ECA_HierarchyStatusUpdateTest
            // Forward: Section is marked completed from Not-Started, Section has only 1 Form, so Stage=completed, next stage goes to 'In Progress'
            // Backward: Section is marked In-progress from Complete, Section has only 1 Form, so Stage/Form/Section go to 'In Progress' & next stage goes to 'Not Started'

        // ECA_CriteriaEvaluatorTest
            // ensure you cover all the test in the Truth-table
            // ensure you fire it on Insert & on Update whe is_Dirty__c flag is set to true.

        // ECA_CriteriaEvaluatorHelperTest (OPTIONAL, in case covrage is low)

*/
@isTest(SeeAllData=false isParallel=true)
public class PEHierarchyClass
{
    @TestSetup
    static void setup()
    {
        // create:  
            // academic-program-account, 
            // caretaker-account, 
            // contact-parent, 
            // contact-child
        // create: school-configuration
            // ECs (Process, Stages (atleast 2), Forms, Sections)
            // criteria (atleast 2)
            // tie criteria to EC.ECCs (atleast 2)
            // add assignment & completion logic to the ECCs.EC
            // Map Process hierarchy in ECRs
        // create: 
            // hh-pe, 
            // stud-pe
                // ECAs 
                    // (Stage-1 & children as In-progress / Not Started)
                    // (Stage-2 & children as Not Started)

        setupTestSchoolReferentialData();
        // setupGenericTestData();
        // setupTestSpecificData();

    }

    public static void setupTestSchoolReferentialData() 
    {

        Account account = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019', Date.parse('11/17/2018'));
        // School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018', Date.parse('11/17/2017'));


        // Create a contact with 'Students' record type
        Contact contact = Peak_TestUtils.createTestContact('Students', account.Id);


        // Create a account with 'Academic Program' record type
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(account.Id, currentSchoolYear.Id);
        academicProgram.Registration_End_Date__c=Date.today().addMonths(1);
        academicProgram.Registration_Start_Date__c=Date.newInstance(2017,11,11);
        academicProgram.Confirmation_End_Date__c = Date.today().addMonths(1);
        update academicProgram;


        // Create STUDENT PE
        hed__Program_Enrollment__c progEnrollment = Peak_TestUtils.createProgramEnrollment(academicProgram.Id, contact.Id, currentSchoolYear.Id, false);
        progEnrollment.Status__c='Inactive';
        insert progEnrollment;


        // NOT SURE WHY WE NEED Relationship
        User u = [SELECT Id,ContactId FROM User WHERE ContactId != NULL AND IsActive = TRUE LIMIT 1];
        hed__Relationship__c  relationship = Peak_TestUtils.createRelationship(u.ContactId, contact.Id, true);


        // Create nodes (w/ECs)
        Enrollment_Component__c processComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Process', false); // Level 1 process
        Enrollment_Component__c stageComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Stage', false); // Level 2 stages 
        Enrollment_Component__c formComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Form', false); // Level 3 forms
        // Level 4 sections
        Enrollment_Component__c sectionComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Section', false);
        Enrollment_Component__c documentComponentForForm = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Document', false);
        // Level 5 questionGroups / questions (for sections)
        Enrollment_Component__c questionGroupComponent = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question_Group', false);
        Enrollment_Component__c questionComponentForSection1 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false); 
        Enrollment_Component__c questionComponentForSection2 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        Enrollment_Component__c messageComponentForSection = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Message', false);
        // Level 6 questions 
        Enrollment_Component__c questionComponentForQG1 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        Enrollment_Component__c questionComponentForQG2 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        Enrollment_Component__c questionComponentForQG3 = Peak_TestUtils.createEnrollmentComponent(academicProgram.Id, 'Question', false);
        

        // insert nodes
        List < Enrollment_Component__c > componentList = new List < Enrollment_Component__c > ();
        componentList.add(processComponent);
        componentList.add(stageComponent);
        componentList.add(formComponent);
        componentList.add(sectionComponent);
        componentList.add(documentComponentForForm);
        componentList.add(questionGroupComponent);
        componentList.add(questionComponentForSection1);
        componentList.add(questionComponentForSection2);
        componentList.add(messageComponentForSection);
        componentList.add(questionComponentForQG1);
        componentList.add(questionComponentForQG2);
        componentList.add(questionComponentForQG3);
        insert componentList;

        // insert Criteria
        // insert ECC
        // update EC Assignment / Completion Criteria
        
        // @todo: Optimize this, currently each record is inserted...
        // tie the nodes (by ECRs)
        Enrollment_Component_Relationship__c stageECR = Peak_TestUtils.createEnrollmentComponentRelationship(stageComponent.Id, processComponent.Id); // level-1
        Enrollment_Component_Relationship__c formECR = Peak_TestUtils.createEnrollmentComponentRelationship(formComponent.Id, stageComponent.Id); // level-2
        Enrollment_Component_Relationship__c sectionECR = Peak_TestUtils.createEnrollmentComponentRelationship(sectionComponent.Id, formComponent.Id); // level-3
        Enrollment_Component_Relationship__c documentECR = Peak_TestUtils.createEnrollmentComponentRelationship(documentComponentForForm.Id, formComponent.Id); // level-3
        
        Enrollment_Component_Relationship__c questionGroupECR = Peak_TestUtils.createEnrollmentComponentRelationship(questionGroupComponent.Id, sectionComponent.Id); // level-4
        Enrollment_Component_Relationship__c questionToSectionECR1 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForSection1.Id, sectionComponent.Id); // level-4
        Enrollment_Component_Relationship__c questionToSectionECR2 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForSection2.Id, sectionComponent.Id); // level-4
        Enrollment_Component_Relationship__c messageToSectionECR2 = Peak_TestUtils.createEnrollmentComponentRelationship(messageComponentForSection.Id, sectionComponent.Id); // level-4

        Enrollment_Component_Relationship__c questionGroupECR1 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForQG1.Id, questionGroupComponent.Id); // level-5
        Enrollment_Component_Relationship__c questionGroupECR2 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForQG2.Id, questionGroupComponent.Id); // level-5
        Enrollment_Component_Relationship__c questionGroupECR3 = Peak_TestUtils.createEnrollmentComponentRelationship(questionComponentForQG3.Id, questionGroupComponent.Id); // level-5

    }

    /**
     * test-scenario: Stage1-Section1 status goes from 'Not Started' to 'Complete'
     *
     *  
     **/

    
    @IsTest
    static void testPassingFieldsUpdatesPECriteria3() 
    {

        Criteria__c criteria1 = Peak_TestUtils.createCriteriaRecord(null, 'Annual_Student_Information__c.Grade_Level_Requested__c', '=', false);
        criteria1.Comparison_Data_Type__c = 'Text';
        criteria1.Comparison_Value__c = '5';
        insert criteria1;

        //Create Educational Institutional Account i.e.., Parent Account
        Account institutionAccount = Peak_TestUtils.createEducationalInstitutionAccount();
        //Insert the School Year record
        School_Year__c schoolYear = Peak_TestUtils.createSchoolYears('Test School Year', System.today());

        //Create Academic Program Account i.e.., Child Account
        Account academicProgram = Peak_TestUtils.createAccountForNewStudentData(institutionAccount.Id, schoolYear.Id);
        academicProgram.Registration_Start_Date__c = System.today().addDays(-10);
        academicProgram.Registration_End_Date__c = System.today().addDays(10);
        update academicProgram;

        // Create a Contact with 'Caretaker' record type
        Contact careTakerContact = Peak_TestUtils.createTestContact('Caretaker', institutionAccount.Id);

        //Create a care taker user for community
        User careTaker = Peak_TestUtils.CreatePortalCaretTakerUser(careTakerContact.Id);

        // Create a Contact with 'Students' record type
        Contact student = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);

        hed__program_enrollment__c program_enrollment_1 = Peak_TestUtils.createProgramEnrollment(String.valueOf(academicProgram.Id), String.valueOf(Student.Id), String.valueOf(schoolYear.Id), false);
        insert program_enrollment_1;

        //Insert a Program Enrollment Criteria record that will link the PE to the Criteria record created above.
        Program_Enrollment_Criteria__c newPEC = new Program_Enrollment_Criteria__c (Program_Enrollment__c=program_enrollment_1.Id, Criteria__c = criteria1.id, Result__c = false, School_Year__c = '2019-2020');
        insert newPEC;

        List<EvaluationUtils.fieldUpdate> fieldUpdateList = new List<EvaluationUtils.fieldUpdate> ();
        EvaluationUtils.fieldUpdate newFieldUpdate = new EvaluationUtils.fieldUpdate ();
        newFieldUpdate.programEnrollmentId = program_enrollment_1.Id;
        newFieldUpdate.objectAndFieldName = 'Annual_Student_Information__c.Grade_Level_Requested__c';
        newFieldUpdate.schoolYear = 'NOT2019-2020';  //Notice that the school doesn't match from the school year from the PE Criteria
        newFieldUpdate.newValue = '5';
        fieldUpdateList.add(newFieldUpdate);

        Test.startTest();
        EvaluationUtils.evaluateChangedFields  (fieldUpdateList);
        Test.stopTest();

        List<Program_Enrollment_Criteria__c> afterEvaluate = new List<Program_Enrollment_Criteria__c> ([select Result__c from Program_Enrollment_Criteria__c]);

        //This test confirms that when the the school year is used and they DON'T match, the criteria is NOT updated.
        System.assertEquals(false, afterEvaluate[0].Result__c);
    }
}