force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Id__c.field-meta.xml
<CustomField>
    <fullName>School_Id__c</fullName>
    <description>This field holds school unique Id values</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>School Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Commuity_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Educational_Institution_SSTF_Mapping__mdt.object
<CustomObject>
    <description>This custom metadata is used to Assign Permission Set to School staff Community User (US#123101 - Task# 160180, 159334 &amp; 158397).</description>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <description>US #123101 - This field is used to capture the associated permission set name belonging to the Internal Staff users. This field gets set when the Batch Job named CS_SSTFPublicGroupUserPermissionBatch is executed.</description>
        <label>Permission Set Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>US #123101 - This field is used to capture the associated school name(Educational Institutions Account ) belonging to the School Staff Community users. This field gets set when the Batch Job named CS_SSTFpermissionBatch is executed.</description>
        <label>School</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Educational Institution_SSTF_Mapping</label>
    <pluralLabel>Educational Institution_SSTF_Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/School_Id__c.field-meta.xml
<CustomField>
    <fullName>School_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used for criteria based sharing rule calculations.</inlineHelpText>
    <label>School Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LcusersValidationHandler.cls
public class LcusersValidationHandler{

    public void provDeprovPermissionSet(List<hed__Relationship__c> relationshipRecs){
    
        //Collect unique student Ids
        Set<Id> studentIdList = new Set<Id>();
        for(hed__Relationship__c relRec: relationshipRecs){
            studentIdList.add(relRec.hed__Contact__c);
        }
        
        //Retrieve program enrollment records for above student Ids
        Map<Id,List<hed__Program_Enrollment__c>> studentIdPrgEnrollRecsMap = new Map<Id,List<hed__Program_Enrollment__c>>();
        for(hed__Program_Enrollment__c peRec: [select hed__Contact__c,hed__Account__c,Status__c,hed__Account__r.Parent.School_Id__c,
                                              hed__Account__r.Parent.Name from hed__Program_Enrollment__c
                                                where hed__Contact__c=:studentIdList]){
            if(studentIdPrgEnrollRecsMap.get(peRec.hed__Contact__c)!=null){
                List<hed__Program_Enrollment__c> enrollRecsList = studentIdPrgEnrollRecsMap.get(peRec.hed__Contact__c);
                enrollRecsList.add(peRec);
                studentIdPrgEnrollRecsMap.put(peRec.hed__Contact__c,enrollRecsList);    
            }else{
                List<hed__Program_Enrollment__c> enrollRecsList = new List<hed__Program_Enrollment__c>();
                enrollRecsList.add(peRec);
                studentIdPrgEnrollRecsMap.put(peRec.hed__Contact__c,enrollRecsList);
            }                                                    
        }
        
        //Main Processing
        Map<String,Set<Id>> SchoolNameLCUsersMap = new Map<String,Set<Id>>();
        for(hed__Relationship__c relRec: relationshipRecs){
            //Retrieve enrollment records for student
            List<hed__Program_Enrollment__c> enrollRecs = studentIdPrgEnrollRecsMap.get(relRec.hed__Contact__c); 
            if(enrollRecs!=null && enrollRecs.size()>0){
                for(hed__Program_Enrollment__c enroll: enrollRecs){
                    if(relRec.hed__Contact__r.Account.Parent.Name == enroll.hed__Account__r.Parent.Name && relRec.hed__Status__c=='Current' && enroll.Status__c=='Complete'){
                        //Add coach to corresponding school permission set
                        if(SchoolNameLCUsersMap.get(relRec.hed__Contact__r.Account.Parent.Name)!=null){
                            Set<Id> LCIds = SchoolNameLCUsersMap.get(relRec.hed__Contact__r.Account.Parent.Name);
                            LCIds.add(relRec.hed__RelatedContact__r.Commuity_User__c);
                            SchoolNameLCUsersMap.put(relRec.hed__Contact__r.Account.Parent.Name,LCIds);
                        }else{
                            Set<Id> LCIds = new Set<Id>();
                            LCIds.add(relRec.hed__RelatedContact__r.Commuity_User__c);
                            SchoolNameLCUsersMap.put(relRec.hed__Contact__r.Account.Parent.Name,LCIds);    
                        }
                    }
                }
            }   
        }
        //get school permission sets from custom metadata type
        List<Educational_Institution_SSTF_Mapping__mdt> scPermList = [Select School__c,Permission_Set_Name__c from Educational_Institution_SSTF_Mapping__mdt where School__c=: SchoolNameLCUsersMap.keySet()];
        List<String> permSetNameList = new List<String>();
        Map<String,String> schoolPermSetNameMap = new Map<String,String>();
        for(Educational_Institution_SSTF_Mapping__mdt mdtRec: scPermList){
            permSetNameList.add(mdtRec.Permission_Set_Name__c);  
            schoolPermSetNameMap.put(mdtRec.School__c,mdtRec.Permission_Set_Name__c);          
        }
        
        //Query Permission Set Assignment to get existing assignments so that duplicates are not added
        List<PermissionSetAssignment> permAssignList = [Select AssigneeId,PermissionSetId,PermissionSet.Name from PermissionSetAssignment where PermissionSet.Name =:permSetNameList];
        Map<String,PermissionSetAssignment> permAssignMap = new Map<String,PermissionSetAssignment>();
        for(PermissionSetAssignment assign: permAssignList){
            permAssignMap.put(assign.PermissionSet.Name+'-'+assign.AssigneeId,assign);    
        }
        
        //Query for PermissionSetIds
        List<PermissionSet> permSets = [Select Id,Name from PermissionSet where Name=: permSetNameList];
        Map<String,Id> permSetNameIdMap = new Map<String,Id>();
        for(PermissionSet perm: permSets){
            permSetNameIdMap.put(perm.Name,perm.Id);       
        }
        
        List<PermissionSetAssignment> assignmentsToBeAdded = new List<PermissionSetAssignment>();
        for(String school: SchoolNameLCUsersMap.keySet()){
            Set<Id> LCusers = SchoolNameLCUsersMap.get(school);
            String permSetName = schoolPermSetNameMap.get(school);
            Id permSetId = permSetNameIdMap.get(permSetName);
            for(Id lcusr: LCusers){
                //check for existing perm set assignment
                String permSetAssignKey = permSetName+'-'+lcusr;
                if(permAssignMap.get(permSetAssignKey)!=null){
                    // do nothing
                    // LC user already exists in permission set
                }else{
                    PermissionSetAssignment newAssignRec = new PermissionSetAssignment();
                    newAssignRec.AssigneeId = lcusr;
                    newAssignRec.PermissionSetId = permSetId;
                    assignmentsToBeAdded.add(newAssignRec);
                }  
            }
        }
        if(assignmentsToBeAdded!=null && assignmentsToBeAdded.size()>0){
            Insert assignmentsToBeAdded;
        }
    }
}