force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>false</active>
    <description>Schools</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Caretaker_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to the Contact records with the Caretaker Record type.It is being used by the student Record Types of Contact</description>
        <label>Caretaker Id</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Caretaker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commuity_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CS_School_PermissionSet_Mapping__mdt.object
<CustomObject>
    <description>Stores the Schools and it corresponding Permission sets for the Student and Caretaker for the US # 123096</description>
    <fields>
        <fullName>Caretaker_PSet__c</fullName>
        <description>ADO # 130549 - (Placeholder KBA Scenarios)
Used to Store the Caretaker Permission Set</description>
        <label>Caretaker PermSet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <description>ADO # 130549 - (Placeholder KBA Scenarios)
Used to Store the School Name</description>
        <label>School Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_PSet__c</fullName>
        <description>ADO # 130549 - (Placeholder KBA Scenarios)
Used to Store the Student Permission Set</description>
        <label>Student PermSet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CS_School_PermissionSet_Mappings</label>
    <pluralLabel>CS_School_PermissionSet_Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <description>User Story No. 164369 &amp; 135049. Developed in Pi-02, Sprint-1, and Sprint-2.
This field is used during developing map collections preparation to capture the School Name that is linked to the Academic Program on the Program Enrollment records associated with a Student. This field is used in the Program Enrollment Batch Job and the Relationship Batch Job code logic to identify the School Names while processing.</description>
    <formula>hed__Account__r.Parent.Name</formula>
    <label>School Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CS_AssignPermissionSetToCT_STDHandler.cls
/*
* Created by:  Sumanth B
* Created date: 2020-Apr-21
* User Story : 130549
* Purpose: Handler class to 

            * Associate the School permission sets(SchoolName_CT & SchoolName_STD) to the existing Caretaker Community user and 
            Student Community User if any when Student enrollment is completed i.e. PE Status = Complete 
*
* Test Class:  CS_AssignPermissionSetToCT_STDBatchTest
* Change Log: 
*
*/
public class CS_AssignPermissionSetToCT_STDHandler {

    public void associatePermissionSets(Set<Id> ctIds, Set<Id> stdIds)
    {
        Set<String> allSchoolsList = new Set<String>();
        Set<Id> allStudentIdList = new Set<Id>();
        Map<String,String> CTPermissionSetsMap = new Map<String,String>(); // Set to house the SchoolName, CT Permissions Set for the Caretaker 
        Map<String,String> StudentPermissionSetsMap = new Map<String,String>(); // Set to house the SchoolName, STD Permissions Set for the Student 
        Map<Id,String> StdUserId_SchoolNameMap = new Map<Id,String>(); //Map to house the Student UserId, SchoolName
        Map<Id,Set<String>> CTUserId_SchoolNameMap = new Map<Id,Set<String>>(); // Map to house the CTUserId and List of Student's School Names
        Map<Id,Set<Id>> CTUserAndPsIdsMap = new Map<Id,Set<Id>>(); //Map to house the CT UserId, Permission Set Ids
        Map<Id,Set<Id>> StdUserAndPsIdMap = new Map<Id,Set<Id>>(); //Map to house the Student UserId, Permission Set Id
        Set<String> AllPermissionSetNames = new Set<String>();
        Map<String,id> PermSetNameAndIdMap = new Map<String,Id>(); // Map to house the Perm set name, id 
		
        Set<Id> studentIdList;
        for(hed__Relationship__c relObject : [SELECT Id, hed__Contact__c,hed__Type__c,
                                                       hed__RelatedContact__c                                                              
                                                       FROM hed__Relationship__c 
                                              		   WHERE hed__RelatedContact__c IN: ctIds]){
                  
                       allStudentIdList.add(relObject.hed__Contact__c);
        }
        System.debug('allStudentIdList -->'+ allStudentIdList);
        System.debug('List of All Students for the Eligible CTs -->'+ allStudentIdList.size());
        if(stdIds.size() >0)
            allStudentIdList.addAll(stdIds);
        System.debug('allStudentIdList with StdIds Size-->'+ allStudentIdList);
		Map<Id,String> StudentAndSchoolMap = new Map<Id,String>();
		//Map the CT Id, Permission Set Name
		if(allStudentIdList.size() > 0)
        {
            for(hed__Program_Enrollment__c pe : [select hed__Contact__c,hed__Contact__r.Caretaker_Id__c,hed__Contact__r.Commuity_User__c,
                                                 hed__Account__r.Parent.Name,School_Name__c,Status__c,
                                                 hed__Contact__r.Caretaker_Id__r.Commuity_User__r.id
                                                 from hed__Program_Enrollment__c where Status__c = 'Complete' 
                                                 AND School_Name__c <> null       
                                                 AND hed__Contact__c in : allStudentIdList order by LastModifiedDate desc])
            {
                  System.debug('Student: '+pe.hed__Contact__c+' Caretaker--> '+pe.hed__Contact__r.Caretaker_Id__c);
                  Set<String> schoolList;		
                  if(!CTUserId_SchoolNameMap.containsKey(pe.hed__Contact__r.Caretaker_Id__r.Commuity_User__r.id))
                  {
                      schoolList = new Set<String>();
                  }
                  else{
                         schoolList = CTUserId_SchoolNameMap.get(pe.hed__Contact__r.Caretaker_Id__r.Commuity_User__r.id);
                   }
                   schoolList.add(pe.School_Name__c);
                   if(pe.hed__Contact__r.Caretaker_Id__c <> null)
                 	 CTUserId_SchoolNameMap.put(pe.hed__Contact__r.Caretaker_Id__r.Commuity_User__r.id, schoolList);
                   if(pe.hed__Contact__c <> null)
                 	 StudentAndSchoolMap.put(pe.hed__Contact__c,pe.School_Name__c); 

                   if(pe.hed__Contact__r.Commuity_User__c <> null)
                   {
                       StdUserId_SchoolNameMap.put(pe.hed__Contact__r.Commuity_User__c,pe.School_Name__c);
                   }	
                   allSchoolsList.addAll(schoolList);
            } 
        }
         system.debug('StudentAndSchoolMap-->: '+StudentAndSchoolMap);
         system.debug('StdUserId_SchoolNameMap-->: '+StdUserId_SchoolNameMap);
         system.debug('CTUserId_SchoolNameMap-->: '+CTUserId_SchoolNameMap);
         system.debug('allSchoolsList-->: '+allSchoolsList+ 'with PE Status=Complete-->: '+allSchoolsList.size());

        //Capture all the Permission Set names from CustomMeta Data (i.e.School names and corresponding Student,Caretaker Permissions Sets)
        for(CS_School_PermissionSet_Mapping__mdt scPS: [SELECT School_Name__c,Student_PSet__c,Caretaker_PSet__c 
                                                    FROM CS_School_PermissionSet_Mapping__mdt 
                                                    where School_Name__c IN : allSchoolsList]){
            CTPermissionSetsMap.put(scPS.School_Name__c,scPS.Caretaker_PSet__c);
            AllPermissionSetNames.add(scPS.Caretaker_PSet__c);
			StudentPermissionSetsMap.put(scPS.School_Name__c,scPS.Student_PSet__c);
            AllPermissionSetNames.add(scPS.Student_PSet__c);
        }
        System.debug('CTPermissionSetsMap--> '+CTPermissionSetsMap);
		System.debug('StudentPermissionSetsMap--> '+StudentPermissionSetsMap);
        System.debug('AllPermissionSetNames--> '+AllPermissionSetNames);
         
	    for(PermissionSet pSet : [select Id,name from PermissionSet where Name IN : AllPermissionSetNames]){
            PermSetNameAndIdMap.put(pSet.Name,pSet.Id);  
        }
        system.debug('PermSetNameAndIdMap-->: '+PermSetNameAndIdMap);

        Set<Id> IdList;	
        Id stdPsetIdVal;
		for(Id Ids : StdUserId_SchoolNameMap.keySet()){
				//StdUserAndPsIdMap.put(Ids,PermSetNameAndIdMap.get(StudentPermissionSetsMap.get(StdUserId_SchoolNameMap.get(Ids))));
            	if(!StdUserAndPsIdMap.containsKey(Ids))
                {
                    IdList = new Set<id>(); 
                    stdPsetIdVal =PermSetNameAndIdMap.get(StudentPermissionSetsMap.get(StdUserId_SchoolNameMap.get(Ids))); 
                    if(stdPsetIdVal <> null)
                    {
                        IdList.add(stdPsetIdVal);
                        StdUserAndPsIdMap.put(Ids,IdList);
                    }
                }
		}
        system.debug('StdUserAndPsIdMap-->: '+StdUserAndPsIdMap);
        
        Set<id> PsIdList;
        Id CTPsetIdVal;
        for(Id Ids : CTUserId_SchoolNameMap.keyset())
        {
            for(String psName : CTUserId_SchoolNameMap.get(Ids))
            {
                if(!CTUserAndPsIdsMap.containsKey(Ids))
                {
                    PsIdList = new Set<id>();
                }
                else
                {
                    PsIdList = CTUserAndPsIdsMap.get(Ids);
                }
                CTPsetIdVal = PermSetNameAndIdMap.get(CTPermissionSetsMap.get(psName));
                if(CTPsetIdVal <> null)
                {
                    PsIdList.add(CTPsetIdVal);
                    CTUserAndPsIdsMap.put(Ids,PsIdList); 
                }
            }
        }
        system.debug('CTUserAndPsIdsMap-->: '+CTUserAndPsIdsMap);
        if(!CTUserAndPsIdsMap.isEmpty()){            
            CS_PermissionSetsAccessUtility.assignPermissionSetToUser(CTUserAndPsIdsMap);
            System.debug('CT Records sent for Association -->');
         }
        if(!StdUserAndPsIdMap.isEmpty()){            
            CS_PermissionSetsAccessUtility.assignPermissionSetToUser(StdUserAndPsIdMap);
            System.debug('Student Records sent for Association-->');
         }
    }
}