force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/System.recordType-meta.xml
<RecordType>
    <fullName>System</fullName>
    <active>false</active>
    <description>Internal Record type for setting up community users</description>
    <label>System</label>
</RecordType>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Year__c</fullName>
        <label>School Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2016-2017</fullName>
                </value>
                <value>
                    <fullName>2017-2018</fullName>
                </value>
                <value>
                    <fullName>2018-2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Caretaker</fullName>
        <active>true</active>
        <description>To capture the Caretaker&apos;s details</description>
        <label>Caretaker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_File_References__c.object
<CustomObject>
    <label>Document File References</label>
    <nameField>
        <displayFormat>DFR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document File References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_File_References__c/fields/Document_Link__c.field-meta.xml
<CustomField>
    <fullName>Document_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/Enrollment_Document__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Document__c</fullName>
    <label>Enrollment Document</label>
    <referenceTo>Enrollment_Document__c</referenceTo>
    <relationshipLabel>Document File References</relationshipLabel>
    <relationshipName>Document_File_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/File_Path__c.field-meta.xml
<CustomField>
    <fullName>File_Path__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Start Year (calculated)</description>
    <label>Start Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School_Year__c.object
<CustomObject>
    <label>School Year</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_DocumentFileRefViewerControllerTest.cls
/*
* Purpose: Test class for NES_DocumentFileRefViewerController 
* Change Log:
*         2019-08-14 initial for #101928 User Story (Andrew Sim)
*          2019-08-14 initial for #102150 User Story (Chinnamanaidu Neerasa).Bug 106220 removed TIF file support as per business.  
*/
@isTest(SeeAllData=false)
public class NES_DocumentFileRefViewerControllerTest {
    
    @TestSetup
    static void setup() {
        
        // Create Program Enrollment Document Record.
        Account institutionAccount = Peak_TestUtils.createTestAccount();
        School_Year__c currentSchoolYear = Peak_TestUtils.createSchoolYears('2018-2019', Date.parse('11/17/2018'));
        School_Year__c previousSchoolYear = Peak_TestUtils.createSchoolYears('2017-2018', Date.parse('11/17/2017'));
        Contact caretaker = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);
        Contact student = Peak_TestUtils.createTestContact('Students', institutionAccount.Id);
        hed__Program_Enrollment__c programEnrollment = new hed__Program_Enrollment__c();
        programEnrollment.Start_Year__c = previousSchoolYear.Id;
        insert programEnrollment;
        
        // Create Enrollment Document Record
        Enrollment_Document__c enrollmentDoc = new Enrollment_Document__c ();
        enrollmentDoc.Program_Enrollment__c = programEnrollment.id;
        insert enrollmentDoc;
        
        // Create Document Reference File Records
        Document_File_References__c dfr;
        dfr = new Document_File_References__c ();
        dfr.Document_Link__c = 'text document';
        dfr.File_Path__c = 'xxx/file.txt';
        dfr.Enrollment_Document__c = enrollmentDoc.id;
        insert dfr; 
        
        dfr = new Document_File_References__c ();
        dfr.Document_Link__c = 'jpg document';
        dfr.File_Path__c = 'xxx/file.jpg';
        dfr.Enrollment_Document__c = enrollmentDoc.id;
        insert dfr; 
        
        dfr = new Document_File_References__c ();
        dfr.Document_Link__c = 'jpeg document';
        dfr.File_Path__c = 'xxx/file.jpeg';
        dfr.Enrollment_Document__c = enrollmentDoc.id;
        insert dfr; 
        
        dfr = new Document_File_References__c ();
        dfr.Document_Link__c = 'tif document';
        dfr.File_Path__c = 'xxx/file.tif';
        dfr.Enrollment_Document__c = enrollmentDoc.id;
        insert dfr; 
        
        dfr = new Document_File_References__c ();
        dfr.Document_Link__c = 'gif document';
        dfr.File_Path__c = 'xxx/file.gif';
        dfr.Enrollment_Document__c = enrollmentDoc.id;
        insert dfr; 
        
        dfr = new Document_File_References__c ();
        dfr.Document_Link__c = 'png document';
        dfr.File_Path__c = 'xxx/file.png';
        dfr.Enrollment_Document__c = enrollmentDoc.id;
        insert dfr; 
        
        dfr = new Document_File_References__c ();
        dfr.Document_Link__c = 'JPG document';
        dfr.File_Path__c = 'xxx/file.JPG';
        dfr.Enrollment_Document__c = enrollmentDoc.id;
        insert dfr; 
        
        dfr = new Document_File_References__c ();
        dfr.Document_Link__c = 'pdf document';
        dfr.File_Path__c = 'xxx/file.pdf';
        dfr.Enrollment_Document__c = enrollmentDoc.id;
        insert dfr; 
        
    }
    
    // public static testMethod void test_isAuthenticated(){
    //     NES_DocumentFileRefViewerController controller = new NES_DocumentFileRefViewerController();
        
    //     Test.startTest();
    //     // check initialized value
    //     System.assertEquals(controller.isAuthenticated, false);
        
    //     // check if setting auth token sets isAuthenticated = true
    //     ApexPages.currentPage().getParameters().put('authToken', 'x');
    //     PageReference page = controller.setAuthToken();
    //     Test.stopTest();
    //     System.assertEquals(controller.isAuthenticated, true);
    // }
    
    public static testMethod void test_checkExtensions(){
        
        Document_File_References__c dfr;
        NES_DocumentFileRefViewerController controller;
        
        Test.startTest();
        // check txt
        dfr = [select Id from Document_File_References__c where Document_Link__c = 'text document' limit 1];
        ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
        controller = new NES_DocumentFileRefViewerController();
        System.assertEquals(controller.isText, true);
        System.assertEquals(controller.isImage, false);
        System.assertEquals(controller.isPDF, false);
        
        // check jpg
        dfr = [select Id from Document_File_References__c where Document_Link__c = 'jpg document' limit 1];
        ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
        controller = new NES_DocumentFileRefViewerController();
        System.assertEquals(controller.isText, false);
        System.assertEquals(controller.isImage, true);
        System.assertEquals(controller.isPDF, false);
        
        // check jpeg
        dfr = [select Id from Document_File_References__c where Document_Link__c = 'jpeg document' limit 1];
        ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
        controller = new NES_DocumentFileRefViewerController();
        System.assertEquals(controller.isText, false);
        System.assertEquals(controller.isImage, true);
        System.assertEquals(controller.isPDF, false);
        
        // check gif
        dfr = [select Id from Document_File_References__c where Document_Link__c = 'gif document' limit 1];
        ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
        controller = new NES_DocumentFileRefViewerController();
        System.assertEquals(controller.isText, false);
        System.assertEquals(controller.isImage, true);
        System.assertEquals(controller.isPDF, false);
        
        // check tif. Commented code as per Bug 106220.
        //dfr = [select Id from Document_File_References__c where Document_Link__c = 'tif document' limit 1];
        //ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
        //controller = new NES_DocumentFileRefViewerController();
        //System.assertEquals(controller.isText, false);
       // System.assertEquals(controller.isImage, true);
        //System.assertEquals(controller.isPDF, false);
        
        // check png
        dfr = [select Id from Document_File_References__c where Document_Link__c = 'png document' limit 1];
        ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
        controller = new NES_DocumentFileRefViewerController();
        System.assertEquals(controller.isText, false);
        System.assertEquals(controller.isImage, true);
        System.assertEquals(controller.isPDF, false);
        
        // check lowercase
        dfr = [select Id from Document_File_References__c where Document_Link__c = 'JPG document' limit 1];
        ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
        controller = new NES_DocumentFileRefViewerController();
        System.assertEquals(controller.isText, false);
        System.assertEquals(controller.isImage, true);
        System.assertEquals(controller.isPDF, false);
        
        // check pdf
        dfr = [select Id from Document_File_References__c where Document_Link__c = 'pdf document' limit 1];
        ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
        controller = new NES_DocumentFileRefViewerController();
        System.assertEquals(controller.isText, false);
        System.assertEquals(controller.isImage, false);
        System.assertEquals(controller.isPDF, true);
        Test.stopTest();
        
    }
    
    // public static testMethod void test_getResponse() {
        
    //     Document_File_References__c dfr;
    //     NES_DocumentFileRefViewerController controller;
        
    //     Test.setMock(HttpCalloutMock.class, new httpCalloutMock200());
    //     Test.startTest();
        
    //     // check pdf response
    //     dfr = [select Id from Document_File_References__c where Document_Link__c = 'pdf document' limit 1];
    //     ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
    //     controller = new NES_DocumentFileRefViewerController();
    //     System.assertEquals(controller.getResponse(),EncodingUtil.base64Encode(System.Blob.valueOf('x')));
        
    //     // check text response
    //     dfr = [select Id from Document_File_References__c where Document_Link__c = 'text document' limit 1];
    //     ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
    //     controller = new NES_DocumentFileRefViewerController();
    //     System.assertEquals(controller.getResponse(),'x');
        
    //     Test.stopTest();
    // }
    
    // public static testMethod void test_getResponseError() {
        
    //     Document_File_References__c dfr;
    //     NES_DocumentFileRefViewerController controller;
        
    //     Test.setMock(HttpCalloutMock.class, new httpCalloutMock404());
    //     Test.startTest();
        
    //     // check error response
    //     dfr = [select Id from Document_File_References__c where Document_Link__c = 'text document' limit 1];
    //     ApexPages.currentPage().getParameters().put('c__dfrId', dfr.Id);
    //     controller = new NES_DocumentFileRefViewerController();
    //     System.debug(controller.getResponse());
        
    //     Test.stopTest();
    // }
    
    // public class httpCalloutMock200 implements HttpCalloutMock {
    //     public HttpResponse respond(HTTPRequest req) {
    //         // Create a fake response
    //         HttpResponse response = new HttpResponse();
    //         response.setBody('x');
    //         response.setBodyAsBlob(System.Blob.valueOf('x'));
    //         response.setStatusCode(200);
    //         return response;
    //     }
    // }
    
    // public class httpCalloutMock404 implements HttpCalloutMock {
    //     public HttpResponse respond(HTTPRequest req) {
    //         // Create a fake response
    //         HttpResponse response = new HttpResponse();
    //         throw new CalloutException();
    //     }
    // }
    
    
}