force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program Enrollment</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>hed__Program_Enrollment__c.hed__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <filterItems>
                <field>hed__Program_Enrollment__c.hed__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Date_Today__c.field-meta.xml
<CustomField>
    <fullName>Date_Today__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Today</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Percent_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percent_Complete__c</fullName>
    <description>user story 184917</description>
    <formula>Total_Forms_Completed__c / Total_Forms__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percent Complete</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NES_Batch_ECAPercent_TaskCreation.cls
/**
* Created by  on 04/05/2020.
* Created for the Spike # 169194 .
* Added by Chinna..
*/

global with sharing class NES_Batch_ECAPercent_TaskCreation  implements DataBase.Batchable<SObject>, Schedulable {
    global List<Task> task_list = new List<Task>();
    global NES_Batch_ECAPercent_TaskCreation() {
       
    }
   
    // Find all the current in progress program enrollments
    global List<SObject> start(Database.BatchableContext BC){
       
        List<hed__Program_Enrollment__c> programEnrollments = [SELECT Id,Date_Today__c,Percent_Complete__c,CreatedDate
                                                               FROM hed__Program_Enrollment__c WHERE Status__c = 'In Progress'
                                                               AND RecordType.Name = 'Student'];
        return programEnrollments;
    }
   
    global void execute(Database.BatchableContext BC, List<SObject> scope) {
       List<Case> caselist = new List<Case>();
        Set<Id> programEnrollmentIds = new Set<Id>();
        for(hed__Program_Enrollment__c programEnrollment : (List<hed__Program_Enrollment__c>)scope) {
            programEnrollmentIds.add(programEnrollment.Id);
        }
        //go find the cases for the PE's in.
         caselist = [select id,OwnerId,Program_Enrollment__c,Program_Enrollment__r.Percent_Complete__c,Program_Enrollment__r.CreatedDate,Program_Enrollment__r.Date_Today__c from Case where Program_Enrollment__c in:programEnrollmentIds];
          
        //to do get all tasks for all the cases in case list.
          // List<Case> caseListe = [select id, subject from Task where WhatId IN :trigger.New];
        
        
        
           //Build a map case id to a list of tasks. Map < id, list < task >> case to task list map.
           Map<Id, List<Task>> caseTask = new Map<Id, List<task>>();
           
        //create custom setting for the different percents.use custom meta data
        ////task, type and sub type
        //task owner is 'case' owner
        //task should not create 2 times, it should be created only once.
        ///iterate
        //test few records
        Percent_Complete__mdt[] percentSettings = [SELECT DeveloperName, MasterLabel,Days__c,Percent__c,Sub_Type__c,Task_Type__c
                                                                  FROM Percent_Complete__mdt ];
       
        for(Case c:caselist){
             Date created = (Date)c.Program_Enrollment__r.CreatedDate;
             Date tod = c.Program_Enrollment__r.Date_Today__c;
             Integer noOfDays = created.daysBetween(tod);
            
           // get the list of the task for the case from the map.
           // loop custom setting
            
            ////should have for loop, and the metadata should loop 
            //task need to create based on metadata type
            
            //check for <10% & within 3 days
            if(c.Program_Enrollment__r.Percent_Complete__c<percentSettings[0].Percent__c && noOfDays<=percentSettings[0].Days__c){
                Task tsk = new Task();
                tsk.OwnerId = c.OwnerId;
                tsk.Type ='Student Progress';
                tsk.TaskSubtype ='within 3 days';
                task_list.add(tsk);
            }
               //check for <33% & within 5 days
            else if(c.Program_Enrollment__r.Percent_Complete__c<percentSettings[1].Percent__c && noOfDays<=percentSettings[1].Days__c){
                Task tsk = new Task();
                tsk.OwnerId = c.OwnerId;
                tsk.Type ='Student Progress';
                tsk.TaskSubtype ='within 5 days';
                task_list.add(tsk);
            }
           //check for <45% & within 7 days
           else if(c.Program_Enrollment__r.Percent_Complete__c<percentSettings[2].Percent__c && noOfDays<=percentSettings[2].Days__c){
                Task tsk = new Task();
                tsk.OwnerId = c.OwnerId;
                tsk.Type ='Student Progress';
                tsk.TaskSubtype ='within 5 days';
                task_list.add(tsk);
            }
           //check for <75% & within 10 days
           else if(c.Program_Enrollment__r.Percent_Complete__c<percentSettings[3].Percent__c && noOfDays<=percentSettings[3].Days__c){
                Task tsk = new Task();
                tsk.OwnerId = c.OwnerId;
                tsk.Type ='Student Progress';
                tsk.TaskSubtype ='within 10 days';
                task_list.add(tsk);
            }
            //check for <90% & within 21 days
            else if(c.Program_Enrollment__r.Percent_Complete__c<percentSettings[4].Percent__c && noOfDays<=percentSettings[4].Days__c){
                Task tsk = new Task();
                tsk.OwnerId = c.OwnerId;
                tsk.Type ='Student Progress';
                tsk.TaskSubtype ='within 21 days';
                task_list.add(tsk);
            }
        }
                          
        if(task_list.size()>0){
            insert task_list;
        }
     }
   
    global void finish(Database.BatchableContext BC) {
       
    }
   
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new NES_Batch_ECAPercent_TaskCreation(), 200);
    }
}