force-app/main/default/objects/Community_Announcement__c.object
<CustomObject>
    <description>Scheduled announcements to surface in Lightning Communities.</description>
    <label>Community Announcement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Announcements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Announcement__c/fields/Announcement_Body__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Announcement Body</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Announcement__c/fields/Announcement_Channel__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Channel__c</fullName>
    <label>Announcement Channel</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Peak Announcements: Product Page</fullName>
            </value>
            <value>
                <fullName>Test Community: Groups</fullName>
            </value>
            <value>
                <fullName>Custom Channel</fullName>
            </value>
            <value>
                <fullName>Page A</fullName>
            </value>
            <value>
                <fullName>Page B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Announcement__c/fields/Announcement_Type__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Type__c</fullName>
    <description>Choose the type of announcement.</description>
    <inlineHelpText>Choose the type of announcement. Notification = general/passive, critical = severe.</inlineHelpText>
    <label>Announcement Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>info</fullName>
                <default>true</default>
                <label>Notification</label>
            </value>
            <value>
                <fullName>warning</fullName>
                <label>Alert</label>
            </value>
            <value>
                <fullName>error</fullName>
                <label>Critical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Announcement__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>Date and time to stop showing this announcement in the community.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date and time to stop showing this announcement in the community.</inlineHelpText>
    <label>End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Community_Announcement__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Date and time to start showing this announcement in the community.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date and time to start showing this announcement in the community.</inlineHelpText>
    <label>Start Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Peak_AnnouncementEmailControllerTest.cls
/**
 * Created by melindagrad on 3/15/18.
 */

@IsTest
public with sharing class Peak_AnnouncementEmailControllerTest {

    @IsTest
    public static void testSendAnnouncementEmail(){

        //Create Test Community_Announcement List
        List<Id> testAnnouncementIDList = new List<Id>();

        //Test Community_Announcement
        Community_Announcement__c testAnnouncement =
                new Community_Announcement__c(Start_Date_Time__c = Date.newInstance(1990, 1, 1),
                        End_Date_Time__c = Date.newInstance(2090, 1, 1), Name = 'Test Announcement',
                        Announcement_Body__c = 'This is a test.', Announcement_Type__c = 'info',
                        Announcement_Channel__c = 'Default');

        insert testAnnouncement;

        testAnnouncementIDList.add(testAnnouncement.Id);

        Peak_AnnouncementEmailController.sendAnnouncementEmail(testAnnouncementIDList);

    }
}