force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Account_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>School Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>School Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/School_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>School_Account_ID__c</fullName>
    <description>User Story No. 164369 &amp; 135049. Developed in Pi-02, Sprint-1, and Sprint-2.
This field is used during developing map collections preparation to uniquely identify Program Enrollment records associated with a Learning Coach come Student under a given School. This field is used in the Program Enrollment Batch Job and the Relationship Batch Job code logic.</description>
    <formula>CASESAFEID(hed__Account__r.ParentId)</formula>
    <label>School Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <description>User Story No. 164369 &amp; 135049. Developed in Pi-02, Sprint-1, and Sprint-2.
This field is used during developing map collections preparation to capture the School Name that is linked to the Academic Program on the Program Enrollment records associated with a Student. This field is used in the Program Enrollment Batch Job and the Relationship Batch Job code logic to identify the School Names while processing.</description>
    <formula>hed__Account__r.Parent.Name</formula>
    <label>School Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Records_Processing_Intervals__mdt.object
<CustomObject>
    <description>This is created for User Story No. 164369 (Pls don&apos;t delete). This MDT is for determining how earlier the records should be taken into consideration based on the days, hours, mins for processing. This is being used in determining the timestamp of the Program Enrollment/Relationship object records for the LC Community Access to School relevant Knowledge Articles based on Topics.</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <description>User Story #164369.
This field on the metadata type is meant for defining the batch size for the Program Enrollment Batch Job and Relationships Batch Job execution. This value defines the batch job lot size for processing.</description>
        <inlineHelpText>Please enter the Batch Job Lot Size for the batch processing on Program Enrollment records and Relationship records. The value to be keyed should be greater than 0.</inlineHelpText>
        <label>Batch Size</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Days that we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions.The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter a negative value say &quot;-1&quot; to pick records updated in the last 1 day&apos;s time. &quot;-2&quot; will imply records that were updated in the last 2 days time interval.</inlineHelpText>
        <label>Days</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Hours by which we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions. The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter the hours in negative values like &quot;-3&quot; to consider records that were updated in the last 3 hours accordingly. &quot;-6&quot; will imply records that were updated in the last 6 hours time interval.</inlineHelpText>
        <label>Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Mins by which we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions. The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter the Minutes in negative values like &quot;-30&quot; to consider records that were updated in the last 30 minutes accordingly. &quot;-40&quot; will imply records that were updated in the last 40 minutes time interval.</inlineHelpText>
        <label>Minutes</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Records Processing Intervals</label>
    <pluralLabel>Records Processing Intervals</pluralLabel>
</CustomObject>

force-app/main/default/classes/CS_LCUserCTPermSetsAccessProgEnrBth_v2.cls
/*
 * Developed By: Rakesh Ramaswamy (NESS TECHNOLOGIES)
 * User Story #. 164369
 * Description - This is a batch job class used to process the Program Enrollment records to determine whether the related KBAs depending on the School that the LC falls under should be made accessible to the LC Community User.
 *               All the Program Enrollment records will be pulled that were updated on a specific time frame (Historical records processing) and based on that the related Relationships records defined for each Student and Learning Coach,
 *               will be processed to determine whether the LC Community user(s) access should be provisioned or revoked to the School CT permission-set accordingly. This batch chains the invocation of the batch job on the Relationship records 
 *               that will have to be processed subsequently.
*/

global class CS_LCUserCTPermSetsAccessProgEnrBth_v2 implements Database.Batchable<sObject>, Database.Stateful{

    global set<Id> studentRecsIdSet = new set<Id>();
    global map<String, list<PermissionSetAssignment>> permissionSetsAssignMap;
   // global list<PermissionSetAssignment> permsSetAssignInsertList;
    global list<PermissionSetAssignment> permsSetAssignDeleteList;
    
    global CS_LCUserCTPermSetsAccessProgEnrBth_v2() {
        permissionSetsAssignMap = new map<String, list<PermissionSetAssignment>>();
       // permsSetAssignInsertList = new list<PermissionSetAssignment>();
        permsSetAssignDeleteList = new list<PermissionSetAssignment>();
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {        
        Id recordTypeIdSTD = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(CS_Constants.CONTACT_RECTYPE_STUDENTS).getRecordTypeId();
        Records_Processing_Intervals__mdt recordProcessInterval = [SELECT Id, Days__c, Hours__c, Minutes__c FROM Records_Processing_Intervals__mdt WHERE DeveloperName = :CS_Constants.LC_KBA_ACCESS_PROGENROLL_RECS_PROCESS];
        DateTime dateTimeInterval = system.now().addDays(Integer.valueOf(recordProcessInterval.Days__c)).addHours(Integer.valueOf(recordProcessInterval.Hours__c)).addMinutes(Integer.valueOf(recordProcessInterval.Minutes__c));       
        String batchQueryStr = 'SELECT Id, Name, hed__Contact__c, hed__Contact__r.Name, hed__Account__c, Status__c, School_Account_ID__c, School_Name__c FROM hed__Program_Enrollment__c WHERE (Status__c = \''+CS_Constants.PE_WITHDRAWN_STATUS+'\' OR Status__c = \''+CS_Constants.PE_COMPLETE_STATUS+'\') AND hed__Contact__r.RecordTypeId = :recordTypeIdSTD AND LastModifiedDate >= :dateTimeInterval';
        return Database.getQueryLocator(batchQueryStr);
    }
    
    global void execute(Database.BatchableContext bc, List<hed__Program_Enrollment__c> programEnrollRecs){        
         set<Id> studentRecsIdSet = new set<Id>();
        
        for(hed__Program_Enrollment__c programEnrollObj : programEnrollRecs){
           studentRecsIdSet.add(programEnrollObj.hed__Contact__c);                  
        }
        
        // Calling the Batch-Apex handler class to process the revoking and provisioning of the CT permission-sets in relation to the Schools that the Learning Coach comes under.
        if((studentRecsIdSet != null) && !studentRecsIdSet.isEmpty()){
            CS_LCUserAccessToSchoolCTKBAsHandler_v2 handlerObj = new CS_LCUserAccessToSchoolCTKBAsHandler_v2();
            permissionSetsAssignMap.putAll(handlerObj.LCUserSchoolCTPermSetsAccessProgEnroll(studentRecsIdSet));
        }
    }        
    
    global void finish(Database.BatchableContext bc){
    
       // Inserting Permission Set Assignments as deemed necessary after processing Program Enrollment batches.
         // permsSetAssignInsertList.addAll(permissionSetsAssignMap.get('To Insert'));
         // if((permsSetAssignInsertList != null) && !permsSetAssignInsertList.isEmpty()){
             // database.insert(permsSetAssignInsertList, false);
         //    CS_Constants.permsSetAssignFinalInsertList.addAll(permsSetAssignInsertList);
        //  }
       // Deleting Permission Set Assignments as necessary after processing Program Enrollment batches.
          permsSetAssignDeleteList.addAll(permissionSetsAssignMap.get('To Delete'));
          if((permsSetAssignDeleteList != null) && !permsSetAssignDeleteList.isEmpty()){
             // database.delete(permsSetAssignDeleteList, false);
             for(PermissionSetAssignment psaRecObj : permsSetAssignDeleteList){
                 CS_Constants_v2.permsSetAssignFinalDeleteMap.put(psaRecObj.Id, psaRecObj); 
             }
          }
    
       // Chaining call to the Relationship Batch Apex process
       // To handle provisioning and revoking of the CT Permission-Sets for the Learning Coach Community Users.
       Records_Processing_Intervals__mdt recordProcessInterval = [SELECT Batch_Size__c FROM Records_Processing_Intervals__mdt WHERE DeveloperName = :CS_Constants.LC_KBA_ACCESS_RELNSHIP_RECS_PROCESS_INTERVAL];
       Integer batchSize = 200;
       if((recordProcessInterval.Batch_Size__c != null) && (recordProcessInterval.Batch_Size__c > 0)){
           batchSize = Integer.valueOf(recordProcessInterval.Batch_Size__c);
       }
       CS_LCUserCTPermSetsAccessRelnshipBth_v2 batchTempObj = new CS_LCUserCTPermSetsAccessRelnshipBth_v2(studentRecsIdSet);
       database.executeBatch(batchTempObj, batchSize);
    }
}