force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program_Enrollment</description>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>V2_External_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>V2 External ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Students</fullName>
        <active>true</active>
        <description>To Capture the Student details</description>
        <label>Students</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Needed_for_Re_enrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needed for Re-enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flag</fullName>
        <active>true</active>
        <label>Flag</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <recordTypes>
        <fullName>Text</fullName>
        <active>true</active>
        <label>Text</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Attended_other_school_since_withdrawing__c.field-meta.xml
<CustomField>
    <fullName>Attended_other_school_since_withdrawing__c</fullName>
    <description>This field is created as part of 215031. Referred in Enrollment configuration.</description>
    <label>Attended other school since withdrawing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Enrollment</fullName>
                <default>true</default>
                <label>Initial Enrollment</label>
            </value>
            <value>
                <fullName>Re-enrolling student</fullName>
            </value>
            <value>
                <fullName>Returning Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Household_Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Household_Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Initial_ECA_Creation_Complete__c.field-meta.xml
<CustomField>
    <fullName>Initial_ECA_Creation_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by the new student creation process to allow the creation of all the ECAs to be async.  When the Caretaker creates the student this will be false.  An async job that creates the ECAs will mark check this when it completes.</description>
    <label>Initial ECA Creation Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Waitlist_Time_Date_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Waitlist_Time_Date_Stamp__c</fullName>
    <description>Waitlist Time/Date Stamp</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Secondary Priority for Review</inlineHelpText>
    <label>Waitlist Time Date Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Waitlist_Time_Date_Stamp_Override__c.field-meta.xml
<CustomField>
    <fullName>Waitlist_Time_Date_Stamp_Override__c</fullName>
    <description>WaitlistTimeDateStampOverride</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Waitlist Time Date Stamp Override</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/WaitlistCounter__c.field-meta.xml
<CustomField>
    <fullName>WaitlistCounter__c</fullName>
    <description>Days since the student was released from the waitlist</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Waitlist Counter</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/WaitlistFlag__c.field-meta.xml
<CustomField>
    <fullName>WaitlistFlag__c</fullName>
    <description>Waitlist Flag</description>
    <label>Waitlist Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active-Reset</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Eligibility</fullName>
            </value>
            <value>
                <fullName>Disciplinary History</fullName>
            </value>
            <value>
                <fullName>Special Education</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>V2_External_ID__c</fullName>
        <description>User Story 102586</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>V2 External ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_StudentReenrollment.cls
/**
 * 
 * Created by ali km on May/04/2020 for [US 168070]
 *      - This class handles Re-enrollment process for STUD_PE rec
 *  Change Log :  
 *  2020-08-18 Added createECAsForMigratedStudent method for the migrated students to create ECAs for #US223531
 */
public without sharing class NES_StudentReenrollment extends NES_EnrollmentReactivationBase {

    public static final String PE_RE_ENROLLMENT_TYPE_DEFAULT = 'Re-enrolling student';

    public NES_StudentReenrollment(String stud_PEID, Reactivation type) {

        super(stud_PEID, type);
        validate();
        setECAList();

    }


    @TestVisible private void validate() { 

        // move to implementing child class...
        if (!PE_WITHDRAWAL_STATUS.equalsIgnoreCase(this.studPE.Status__c)) {
            throw new InvalidParameterValue_Exception(
                'This Program Enrollment is not eligible for Student ' +  this.type 
                    + '; Status:' + this.studPE.Status__c + ', Expected: ' + PE_WITHDRAWAL_STATUS);
        }

    }


    public override void execute() { 
         
        // process ECAs  Added for making Form status as In Progress, for Defect 244255
        processECAs('RE-ENROLLMENT');

        //To Run Assignment Logic
        
        
        // reset fields on PE
        processPE();
       // processECAs('RE-ENROLLMENT');
       
        // run the Opportunity Creation
        createPEOpportunity();
        
         
        //#US223531 Start (Jagadish Babu)
        //Run for migrated students
        createECAsForMigratedStudent();
        //#US223531 End (Jagadish Babu)
    }


    @TestVisible private void processPE() {

        hed__Program_Enrollment__c toUpdatePE = new hed__Program_Enrollment__c( 
            Id = this.studPE.Id,
            Status__c = PE_REACTIVATION_STATUS,
            Enrollment_Type__c = PE_RE_ENROLLMENT_TYPE_DEFAULT,
            WaitlistFlag__c = null,
            WaitlistCounter__c = null,
            Waitlist_Time_Date_Stamp__c = null,
            Waitlist_Time_Date_Stamp_Override__c = null,
            Initial_ECA_Creation_Complete__c = true
        );
        update toUpdatePE;

    }


    @TestVisible private void createPEOpportunity() {

        Opportunity newOppty = this.getNewOpportunity();
        insert newOppty;

    }


    @TestVisible private void setECAList() {

        // query & set ecaList
        ecaList = 
            new List<Enrollment_Component_Affiliation__c>
                ([
                    SELECT  Id, SystemModstamp, Enrollment_Component__c,Status__c,Order__c,
                            Enrollment_Component__r.RecordType.Name, Name,Program_Enrollment__c,Program_Enrollment__r.Enrollment_Type__c,
                            Enrollment_Component__r.Needed_for_Re_enrollment__c,
                            Enrollment_Component__r.RecordTypeId
                    FROM    Enrollment_Component_Affiliation__c 
                    WHERE   
                        Program_Enrollment__c = :studPE.Id 
                        AND ( Enrollment_Component__r.Needed_for_Re_enrollment__c = true) // Only Stage-2 matters? 
                        AND 
                        ( 
                            (
                                ( 
                                    Status__c= 'Complete' 
                                    AND 
                                    Enrollment_Component__r.RecordType.Name 
                                        IN ('Section', 'Form', 'Question', 'Question Group', 'Document', 'Flag', 'Message', 'Text') 
                                )
                                OR 
                                ( 
                                    (  
                                        Status__c IN ('In Progress', 'Complete')
                                        AND 
                                        (
                                            Enrollment_Component__r.RecordType.Name = 'Stage' 
                                            AND 
                                            Order__c != 1
                                        )
                                    )
                                )
                            )
                        )
                ]);

        System.debug('ecalist::' + JSON.serialize(ecaList));
    }
    
    //#US223531 Start (Jagadish Babu)
    //Below method will create ECAs for Migrated Students
    private void createECAsForMigratedStudent(){
        //Retrive PE record with External Id, academic program
        List<hed__Program_Enrollment__c> peRecord = [Select Id,Attended_other_school_since_withdrawing__c,Enrollment_Type__c,
                                                            hed__Account__c,hed__Contact__c,Household_Program_Enrollment__r.hed__Contact__c,hed__Contact__r.AccountId,
                                                            V2_External_ID__c
                                                            from hed__Program_Enrollment__c Where id =: this.studPE.Id];
        //Check to Execute only for Migrated student
        if(String.isNotBlank(peRecord[0].V2_External_ID__c)){
            Set<Id> enrollmentComponentIds = new Set<Id>();
            //Retrive all ECAs if created already
            List<Enrollment_Component_Affiliation__c> allECAList= [Select Id,
                                                            Enrollment_Component__c,
                                                            Program_Enrollment__c
                                                            from Enrollment_Component_Affiliation__c
                                                            Where Program_Enrollment__c =:this.studPE.Id];
            //Add all EC ids to set to exclude while creation of ECA                                                            
            if(!allECAList.isEmpty()){
                for (Enrollment_Component_Affiliation__c eca : allECAList) {
                    enrollmentComponentIds.add(eca.Enrollment_Component__c);
                }
            }
            
            //Retrive process EC with academic program
            List<Enrollment_Component__c> processECRec = [Select Id,Name,
                                                                 RecordType.Name,
                                                                 Process_Academic_Program__c
                                                                 from Enrollment_Component__c where Process_Academic_Program__c=:peRecord[0].hed__Account__c and RecordType.Name =: NES_DashboardUtilities.PROCESS_RT]; 
            
             
            //Retrieve the ECR tree.
            NES_EnrollmentCompentBuilder allECData = NES_EnrollmentCompentBuilder.getInstance();
            NES_EnrollmentCompentBuilder.enrollmentComponentData thisProcessData = allECData.getSpecificProcessECData(processECRec[0].Id);
            List<Enrollment_Component_Affiliation__c> newAffiliations = new List<Enrollment_Component_Affiliation__c>();
           
            //Create Process ECA if not exist
            if(!enrollmentComponentIds.contains(processECRec[0].Id)){
                Enrollment_Component_Affiliation__c processECA = new Enrollment_Component_Affiliation__c();
                processECA.Enrollment_Component__c = processECRec[0].Id;
                processECA.Program_Enrollment__c = peRecord[0].Id;
                processECA.Status__c = 'Not Started';
                processECA.EC_Record_Type__c = NES_DashboardUtilities.PROCESS_RT;   
                newAffiliations.add(processECA);
            }
            
            //Add Stage ECA records if not exist
            for (Enrollment_Component_Relationship__c relationship : thisProcessData.stageRelationships) {  
                System.debug('Needed for Reenroll****'+relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c);             
                if(relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c == true && !enrollmentComponentIds.contains(relationship.Child_Enrollment_Component__c)  && String.isBlank(relationship.Child_Enrollment_Component__r.Assignment_Logic__c)) {
                    Enrollment_Component_Affiliation__c affiliationRecord = new Enrollment_Component_Affiliation__c();
                    affiliationRecord.Enrollment_Component__c = relationship.Child_Enrollment_Component__c;
                    affiliationRecord.Program_Enrollment__c = peRecord[0].Id;
                    affiliationRecord.Status__c = 'Not Started';
                    affiliationRecord.Order__c = relationship.Order__c;
                    affiliationRecord.EC_Record_Type__c = relationship.Child_Enrollment_Component__r.RecordType.Name;   
                    newAffiliations.add(affiliationRecord);
                   
                }    
                
            }
            
            //Add form ECA records
            for (Enrollment_Component_Relationship__c relationship : thisProcessData.formRelationships) { 
                System.debug('Needed for Reenroll****'+relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c);              
                if(relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c == true && !enrollmentComponentIds.contains(relationship.Child_Enrollment_Component__c) && String.isBlank(relationship.Child_Enrollment_Component__r.Assignment_Logic__c))  {
                    Enrollment_Component_Affiliation__c affiliationRecord = new Enrollment_Component_Affiliation__c();
                    affiliationRecord.Enrollment_Component__c = relationship.Child_Enrollment_Component__c;
                    affiliationRecord.Program_Enrollment__c = peRecord[0].Id;
                    affiliationRecord.Status__c = 'Not Started';
                    affiliationRecord.Order__c = relationship.Order__c;
                    affiliationRecord.EC_Record_Type__c = relationship.Child_Enrollment_Component__r.RecordType.Name;   
                    newAffiliations.add(affiliationRecord);
                    
                } 
                
            }

            //Add Section ECA records
            for (Enrollment_Component_Relationship__c relationship : thisProcessData.sectionRelationships) {  
                System.debug('Needed for Reenroll****'+relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c);             
                if(relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c == true && !enrollmentComponentIds.contains(relationship.Child_Enrollment_Component__c) && String.isBlank(relationship.Child_Enrollment_Component__r.Assignment_Logic__c) )  {
                    Enrollment_Component_Affiliation__c affiliationRecord = new Enrollment_Component_Affiliation__c();
                    affiliationRecord.Enrollment_Component__c = relationship.Child_Enrollment_Component__c;
                    affiliationRecord.Program_Enrollment__c = peRecord[0].Id;
                    affiliationRecord.Status__c = 'Not Started';
                    affiliationRecord.Order__c = relationship.Order__c;
                    affiliationRecord.EC_Record_Type__c = relationship.Child_Enrollment_Component__r.RecordType.Name;   
                    newAffiliations.add(affiliationRecord);
                
                }  
                
            }

             //Add Question Group ECA records
             for (Enrollment_Component_Relationship__c relationship : thisProcessData.questionGroupRelationships) {  
                System.debug('Needed for Reenroll****'+relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c);             
                 if(relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c == true && !enrollmentComponentIds.contains(relationship.Child_Enrollment_Component__c) && String.isBlank(relationship.Child_Enrollment_Component__r.Assignment_Logic__c) )  {
                    Enrollment_Component_Affiliation__c affiliationRecord = new Enrollment_Component_Affiliation__c();
                    affiliationRecord.Enrollment_Component__c = relationship.Child_Enrollment_Component__c;
                    affiliationRecord.Program_Enrollment__c = peRecord[0].Id;
                    affiliationRecord.Status__c = 'Not Started';
                    affiliationRecord.Order__c = relationship.Order__c;
                    affiliationRecord.EC_Record_Type__c = relationship.Child_Enrollment_Component__r.RecordType.Name;   
                    newAffiliations.add(affiliationRecord);
                
                }    
                
            }

             //Add Question  ECA records
             for (Enrollment_Component_Relationship__c relationship : thisProcessData.questionRelationships) {             
                System.debug('Needed for Reenroll****'+relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c);
                 if(relationship.Child_Enrollment_Component__r.Needed_for_Re_enrollment__c == true && !enrollmentComponentIds.contains(relationship.Child_Enrollment_Component__c) && String.isBlank(relationship.Child_Enrollment_Component__r.Assignment_Logic__c) ) {
                    Enrollment_Component_Affiliation__c affiliationRecord = new Enrollment_Component_Affiliation__c();
                    affiliationRecord.Enrollment_Component__c = relationship.Child_Enrollment_Component__c;
                    affiliationRecord.Program_Enrollment__c = peRecord[0].Id;
                    affiliationRecord.Status__c = 'Not Started';
                    affiliationRecord.Order__c = relationship.Order__c;
                    affiliationRecord.EC_Record_Type__c = relationship.Child_Enrollment_Component__r.RecordType.Name;   
                    newAffiliations.add(affiliationRecord);                   
                }                    
            }
            System.debug('newAffiliations**********'+newAffiliations);
            if (newAffiliations.size() > 0) {
               insert newAffiliations; 
            }
            //Calling assignment logic to create ECAs to create schooling Info section
            NES_ECAEvaluation.runAssignment(peRecord[0].Id, null, peRecord[0],newAffiliations,processECRec[0].Id);
        }      
        else{
            List<Enrollment_Component_Affiliation__c> ecalist = [Select Id,Enrollment_Component__c,Program_Enrollment__c,Status__c from Enrollment_Component_Affiliation__c where Program_Enrollment__c =: peRecord[0].Id];
            //Retrive process EC with academic program
            List<Enrollment_Component__c> processECRec = [Select Id,
                                                                 RecordType.Name,
                                                                 Process_Academic_Program__c
                                                                 from Enrollment_Component__c where Process_Academic_Program__c=:peRecord[0].hed__Account__c and RecordType.Name =: NES_DashboardUtilities.PROCESS_RT]; 
            NES_ECAEvaluation.runAssignment(peRecord[0].Id, null, peRecord[0],ecalist,processECRec[0].Id);
        }
    }
    //#US223531 End (Jagadish Babu)
    

}