force-app/main/default/objects/Criteria_Group__c.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Component__c</fullName>
        <description>The parent enrollment component for the criteria group.</description>
        <label>Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Criteria Groups</relationshipLabel>
        <relationshipName>Criteria_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>The group number that will be used to reference it in the logic definition on the Enrollment Component. Groups should be numbered 1 - n, where n is the total number of groups associated with the Enrollment Component.</description>
        <label>Group Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Criteria Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_CriteriaGroupTriggerTest.cls
/**
 * Created by Ritvik on 05-11-2018.
 * Purpose - Test class for CriteriaGroupBusinessLogic apex class.
 */
@isTest
private class NES_CriteriaGroupTriggerTest {


    @TestSetup
    static void setup(){
      Peak_TestUtils.createNESBusinessLogicSwitch('CriteriaGroupTrigger', true);
        }
        
    @isTest
    static void UnitTestPositiveScenario1(){

        //Inserting Enrollment Component of record type 'Form'.
        Enrollment_Component__c enrollCompRecord = Peak_TestUtils.createEnrollmentComponent(null,'Form',false);
        enrollCompRecord.Name = 'Test Enrollment Component';
        insert enrollCompRecord;

        //Creating criteria group for the enrollment component inserted above.
        Criteria_Group__c criteriaGroupRecord1 = Peak_TestUtils.createCriteriaGroup('Test Criteria Group1',enrollCompRecord.Id,false);

        Test.startTest();

        insert criteriaGroupRecord1;
        Criteria_Group__c cgRecord = [SELECT ID, Group_Number__c FROM Criteria_Group__c WHERE  Enrollment_Component__c =: enrollCompRecord.Id];
        update criteriaGroupRecord1;
        System.assertEquals(1, cgRecord.Group_Number__c);

        Test.stopTest();


    }

    @isTest
    static void UnitTestPositiveScenario2(){

        //Creating Enrollment Component of record type 'Form'.
        Enrollment_Component__c enrollCompRecord = Peak_TestUtils.createEnrollmentComponent(null,'Form',false);
        enrollCompRecord.Name = 'Test Enrollment Component';
        insert enrollCompRecord;
        //Creating criteria group for the enrollment component inserted above.
        Criteria_Group__c criteriaGroupRecord1 = Peak_TestUtils.createCriteriaGroup('Test Criteria Group1',enrollCompRecord.Id,true);

        Criteria_Group__c criteriaGroupRecord2 = Peak_TestUtils.createCriteriaGroup('Test Criteria Group2',enrollCompRecord.Id,false);


        Test.startTest();

        insert criteriaGroupRecord2;
        Criteria_Group__c criteriaGroupRecord3 = Peak_TestUtils.createCriteriaGroup('Test Criteria Group3',enrollCompRecord.Id,true);

        List<Criteria_Group__c> cgRecord = [SELECT ID, Group_Number__c FROM Criteria_Group__c WHERE Enrollment_Component__c =: enrollCompRecord.Id];
        System.assertEquals(2, cgRecord[1].Group_Number__c);


        Test.stopTest();

    }
}