force-app/main/default/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Comparison_Field__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comparison Field (Right)</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field__c</fullName>
        <description>The API name of the object-field combination being used on the right side of the criteria comparison. This field should be populated if you are comparing the left side field to the value of another field. Example. Account.Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Field (Left)</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Number__c</fullName>
        <description>The criteria number that will be used to reference it in the logic definition on the Criteria Group. Criteria should be numbered 1 - n, where n is the total number of criteria associated with the Enrollment Component.</description>
        <label>Criteria Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Criteria_Type__c</fullName>
        <description>Indicator of whether or not the criteria is used as part of eligibility screening.</description>
        <label>Criteria Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ineligibility</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Completion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The criteria being associated to the Enrollment Component.</description>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Enrollment Component Criteria</relationshipLabel>
        <relationshipName>Enrollment_Component_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Component__c</fullName>
        <description>The parent enrollment component for the component criteria.</description>
        <label>Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Enrollment Component Criteria</relationshipLabel>
        <relationshipName>Enrollment_Component_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Criteria</label>
    <nameField>
        <displayFormat>ECC-{000}</displayFormat>
        <label>Enrollment Component Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_EnrollmentCompCriteriaTriggerTest.cls
/**
 * Created by Ritvik on 05-11-2018.
 * Purpose : Test class for EnrollmentComponentCriteriaBusinessLogic class.
 */

@isTest
private class NES_EnrollmentCompCriteriaTriggerTest {
    @TestSetup
    static void setup(){
        //Inserting Enrollment Component of record type 'Form'.
        Enrollment_Component__c enrollCompRecord = Peak_TestUtils.createEnrollmentComponent(null,'Form',false);
        enrollCompRecord.Name = 'Test Enrollment Component';
        insert enrollCompRecord;

        Criteria__c criteriaRecord = Peak_TestUtils.createCriteriaRecord('Test Criteria','Left field','>',false);
        criteriaRecord.Comparison_Field__c = 'Right field';
        insert criteriaRecord;
    }

    @isTest
    static void UnitTestPositiveScenarioMethodOne(){

        Enrollment_Component__c enrollmentComponent = [SELECT Id FROM Enrollment_Component__c WHERE Name = 'Test Enrollment Component'];
        Criteria__c criteria = [SELECT Id FROM Criteria__c WHERE Criteria_Field__c = 'Left field'];
        //Creating enrollment component criteria for the enrollment component inserted above.
        Enrollment_Component_Criteria__c EnrollCompCriteriaRecord1 = Peak_TestUtils.createEnrollCompCriteria('Test Enrollment Component Criteria1',enrollmentComponent.Id,false);
        EnrollCompCriteriaRecord1.Criteria__c = criteria.Id;
        EnrollCompCriteriaRecord1.Criteria_Type__c = 'Assignment';
        Test.startTest();
        insert EnrollCompCriteriaRecord1;

        Enrollment_Component_Criteria__c eccRecord = [SELECT Id, Criteria_Number__c FROM Enrollment_Component_Criteria__c WHERE Enrollment_Component__c =: enrollmentComponent.Id Limit 1];
        System.assertEquals(1, eccRecord.Criteria_Number__c);
        Test.stopTest();


    }

    @isTest
    static void UnitTestPositiveScenarioMethodTwo(){

        Enrollment_Component__c enrollmentComponent = [SELECT Id FROM Enrollment_Component__c WHERE Name = 'Test Enrollment Component'];
        Criteria__c criteria = [SELECT Id FROM Criteria__c WHERE Criteria_Field__c = 'Left field'];
        //Creating enrollment component criteria for the enrollment component inserted above.
        Enrollment_Component_Criteria__c EnrollCompCriteriaRecord1 = Peak_TestUtils.createEnrollCompCriteria('Test Enrollment Component Criteria1',enrollmentComponent.Id,false);
        EnrollCompCriteriaRecord1.Criteria__c = criteria.Id;
        EnrollCompCriteriaRecord1.Criteria_Type__c = 'Assignment';
        insert EnrollCompCriteriaRecord1;
        //Creating enrollment component criteria for the enrollment component inserted above.
        Enrollment_Component_Criteria__c EnrollCompCriteriaRecord2 = Peak_TestUtils.createEnrollCompCriteria('Test Enrollment Component Criteria2',enrollmentComponent.Id,false);
        EnrollCompCriteriaRecord2.Criteria__c = criteria.Id;
        EnrollCompCriteriaRecord2.Criteria_Type__c = 'Assignment';

        Test.startTest();
        insert EnrollCompCriteriaRecord2;
        //Creating enrollment component criteria for the enrollment component inserted above.
        Enrollment_Component_Criteria__c EnrollCompCriteriaRecord3 = Peak_TestUtils.createEnrollCompCriteria('Test Enrollment Component Criteria3',enrollmentComponent.Id,false);
        EnrollCompCriteriaRecord3.Criteria__c = criteria.Id;
        EnrollCompCriteriaRecord3.Criteria_Type__c = 'Assignment';
        insert EnrollCompCriteriaRecord3;
        List<Enrollment_Component_Criteria__c> eccRecord = [SELECT ID, Criteria_Number__c FROM Enrollment_Component_Criteria__c WHERE  Enrollment_Component__c =: enrollmentComponent.Id];
        System.assertEquals(2, eccRecord[1].Criteria_Number__c);
        Test.stopTest();

    }
}