force-app/main/default/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Comparison_Data_Type__c</fullName>
        <label>Comparison Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Date (Years Calculated)</fullName>
                </value>
                <value>
                    <fullName>Datetime</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comparison_Field__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comparison Field (Right)</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comparison_Value__c</fullName>
        <description>The value being used on the right side of the criteria comparison. This field should be populated if you are comparing the left side field to a static value.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comparison Value (Right)</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field__c</fullName>
        <description>The API name of the object-field combination being used on the right side of the criteria comparison. This field should be populated if you are comparing the left side field to the value of another field. Example. Account.Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Field (Left)</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>The comparison operator used to compare the left and right sides of the criteria.</description>
        <label>Comparison Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>=</fullName>
                </value>
                <value>
                    <fullName>!=</fullName>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&gt;=</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>&lt;=</fullName>
                </value>
                <value>
                    <fullName>CONTAINS</fullName>
                </value>
                <value>
                    <fullName>DOES NOT CONTAIN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Criteria</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Criteria_Group__c.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Component__c</fullName>
        <description>The parent enrollment component for the criteria group.</description>
        <label>Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Criteria Groups</relationshipLabel>
        <relationshipName>Criteria_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_Logic__c</fullName>
        <description>The evaluation logic of the criteria group.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Logic</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>The group number that will be used to reference it in the logic definition on the Enrollment Component. Groups should be numbered 1 - n, where n is the total number of groups associated with the Enrollment Component.</description>
        <label>Group Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Criteria Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Criteria Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Criteria Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Assignment_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component is relevant to the program enrollment the evaluation was completed for and it would then be assigned to the PE through a Enrollment Component Affiliation. If there is no assignment logic defined on a component, it inherits it&apos;s assigment from its parent.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Assignment Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component has been completed by theprogram enrollment the evaluation was completed for and it would then be marked complete on the shared Enrollment Component Affiliation.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Completion Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Indicator of whether the component relates to student or caretaker (household) program enrollments. This field is used for components of the following types: Flag, Form. All child components of a form should implicitly inherit the type of the form when used in the context of that form.</description>
        <label>Component Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Caretaker</fullName>
                    <isActive>false</isActive>
                    <label>Caretaker</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Hidden_Input</fullName>
        <active>true</active>
        <label>Hidden Input</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Number__c</fullName>
        <description>The criteria number that will be used to reference it in the logic definition on the Criteria Group. Criteria should be numbered 1 - n, where n is the total number of criteria associated with the Enrollment Component.</description>
        <label>Criteria Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Criteria_Type__c</fullName>
        <description>Indicator of whether or not the criteria is used as part of eligibility screening.</description>
        <label>Criteria Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ineligibility</fullName>
                </value>
                <value>
                    <fullName>Assignment</fullName>
                </value>
                <value>
                    <fullName>Completion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The criteria being associated to the Enrollment Component.</description>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Enrollment Component Criteria</relationshipLabel>
        <relationshipName>Enrollment_Component_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Component__c</fullName>
        <description>The parent enrollment component for the component criteria.</description>
        <label>Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Enrollment Component Criteria</relationshipLabel>
        <relationshipName>Enrollment_Component_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_or_Household__c</fullName>
        <label>Student or Household</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component Criteria</label>
    <nameField>
        <displayFormat>ECC-{000}</displayFormat>
        <label>Enrollment Component Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <description>The enrollment component that is the parent in the relationship being defined.</description>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_EnrollmentCompentBuilder2WIP.cls
public with sharing class NES_EnrollmentCompentBuilder2WIP {
/**
 *  @ALIKM 20/apr/2020- commenting out changes
    private static NES_EnrollmentCompentBuilder2WIP instance = null;
    private static Map<Id, enrollmentComponentData> allECData;
    //This will hold all the Enrollment Components for all process ids that have been passed in this
    //execution context.  No need to break the data out by process id.
    public Map<Id, Enrollment_Component__c> enrollmentComponentMap;

    private NES_EnrollmentCompentBuilder2WIP() {
        //Only exists to defeat instantiation (Notice it is private)
        allECData = new map<id, enrollmentComponentData> ();
        enrollmentComponentMap = new Map<Id, Enrollment_Component__c>();
    }

    public static NES_EnrollmentCompentBuilder2WIP getInstance() {
        if (instance == null)
            instance = new NES_EnrollmentCompentBuilder2WIP();
        return instance;
    }

    public class enrollmentComponentData {

        public List<Enrollment_Component_Relationship__c> stageRelationships;
        public List<Enrollment_Component_Relationship__c> formRelationships;
        public List<Enrollment_Component_Relationship__c> sectionRelationships;
        public List<Enrollment_Component_Relationship__c> questionGroupRelationships;
        public List<Enrollment_Component_Relationship__c> questionRelationships;

        public Map<Id, Decimal> componentOrderMap = new Map<Id, Decimal>();
        public List<Id> allIds = new List<Id>();
        public Set<Id> questionParentIds;

        // WIP ALI KM 
        public Id ProcessId;
        // public ecrConsumerFormat ecrTreeData {get; private set;}
        // public Boolean isEnabledTreeConfig {get {return true;}; private set;}

        // new constructor
        public enrollmentComponentData() {
            this.stageRelationships          = new List<Enrollment_Component_Relationship__c>();
            this.formRelationships           = new List<Enrollment_Component_Relationship__c>();
            this.sectionRelationships        = new List<Enrollment_Component_Relationship__c>();
            this.questionGroupRelationships  = new List<Enrollment_Component_Relationship__c>();
            this.questionRelationships       = new List<Enrollment_Component_Relationship__c>();
            this.questionParentIds           = new Set<Id>();
        }

        // new constructor
        public enrollmentComponentData(enrollmentComponentData interim) {
            this.allIds                      = interim.allIds;
            this.componentOrderMap           = interim.componentOrderMap;
            this.stageRelationships          = interim.stageRelationships;
            this.formRelationships           = interim.formRelationships;
            this.sectionRelationships        = interim.sectionRelationships;
            this.questionGroupRelationships  = interim.questionGroupRelationships;
            this.questionRelationships       = interim.questionRelationships;
            this.questionParentIds           = interim.questionParentIds;
        }

        // constructor
        public enrollmentComponentData (id ProcessId) {

            this.ProcessId = ProcessId;
            enrollmentComponentData interim = NES_ECDataImportExport.ImportData(this.ProcessId);
            if (interim!=null) {
                this(interim);
            } else {
                this.generateData();
            }

        }

        private void importData() {

        }
        // ALI WIP END

        



        private void generateData() {
            System.debug('In the enrollmentComponentData constructor');

            //Do all the work of getting the EC data.
            stageRelationships = [
                SELECT Child_Enrollment_Component__c, Child_Enrollment_Component__r.Assignment_Logic__c, Id, Order__c, Parent_Enrollment_Component__c,
                    Child_Enrollment_Component__r.RecordType.Name, Parent_Enrollment_Component__r.Completion_Logic__c, Child_Enrollment_Component__r.Completion_Logic__c
                FROM Enrollment_Component_Relationship__c
                WHERE Parent_Enrollment_Component__c = :processId
                AND Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.STAGE_RT ORDER BY Order__c
            ];

            List<Id> stageIds = new List<Id>();

            for (Enrollment_Component_Relationship__c stageRelationship : stageRelationships) {
                stageIds.add(stageRelationship.Child_Enrollment_Component__c);
                componentOrderMap.put(stageRelationship.Child_Enrollment_Component__c, stageRelationship.Order__c);
            }

            formRelationships = [
                    SELECT Child_Enrollment_Component__c, Order__c, Child_Enrollment_Component__r.Assignment_Logic__c,
                            Child_Enrollment_Component__r.Component_Type__c, Parent_Enrollment_Component__c,
                            Child_Enrollment_Component__r.RecordType.Name, Child_Enrollment_Component__r.Completion_Logic__c
                    FROM Enrollment_Component_Relationship__c
                    WHERE Parent_Enrollment_Component__c IN :stageIds
                    AND (Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.FORM_RT
                    OR Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.MESSAGE_RT
                    OR Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.FLAG_RT)
            ];

            List<Id> formIds = new List<Id>();
            for (Enrollment_Component_Relationship__c relationship : formRelationships) {
                formIds.add(relationship.Child_Enrollment_Component__c);
                componentOrderMap.put(relationship.Child_Enrollment_Component__c, relationship.Order__c);
            }

            sectionRelationships = [
                    SELECT Child_Enrollment_Component__c, Order__c, Parent_Enrollment_Component__c, 
                    Child_Enrollment_Component__r.Assignment_Logic__c, Child_Enrollment_Component__r.Component_Type__c,
                    Child_Enrollment_Component__r.RecordType.Name, Child_Enrollment_Component__r.Completion_Logic__c
                    FROM Enrollment_Component_Relationship__c
                    WHERE Parent_Enrollment_Component__c IN :formIds
                    AND (Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.SECTION_RT
                    OR Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.DOCUMENT_RT
                    OR Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.MESSAGE_RT)
            ];

            List<Id> sectionIds = new List<Id>(); 
            for (Enrollment_Component_Relationship__c relationship : sectionRelationships) {
                sectionIds.add(relationship.Child_Enrollment_Component__c);
                componentOrderMap.put(relationship.Child_Enrollment_Component__c, relationship.Order__c);
            }

            questionGroupRelationships = [
                    SELECT Child_Enrollment_Component__c, Order__c, Parent_Enrollment_Component__c, Child_Enrollment_Component__r.Assignment_Logic__c, Child_Enrollment_Component__r.Component_Type__c
                    FROM Enrollment_Component_Relationship__c
                    WHERE Parent_Enrollment_Component__c IN :sectionIds
                    AND Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.QUESTIONGROUP_RT
            ];

            List<Id> groupIds = new List<Id>(); 
            for (Enrollment_Component_Relationship__c relationship : questionGroupRelationships) {
                groupIds.add(relationship.Child_Enrollment_Component__c);
                componentOrderMap.put(relationship.Child_Enrollment_Component__c, relationship.Order__c);
            }

            questionRelationships = [
                    SELECT Child_Enrollment_Component__c, Order__c, Parent_Enrollment_Component__c, Child_Enrollment_Component__r.Assignment_Logic__c, Child_Enrollment_Component__r.Component_Type__c
                    FROM Enrollment_Component_Relationship__c
                    WHERE (Parent_Enrollment_Component__c IN :groupIds
                    OR Parent_Enrollment_Component__c IN :sectionIds)
                    AND (Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.QUESTION_RT
                    OR Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.HIDDEN_INPUT
                    OR Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.TEXT_RT
                    OR Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.FLAG_RT
                    OR Child_Enrollment_Component__r.RecordType.Name = :NES_DashboardUtilities.MESSAGE_RT)
            ];

            // Combine the question groups and the sections
            questionParentIds = new Set<Id>();
            questionParentIds.addAll(sectionIds);
            questionParentIds.addAll(groupIds);

            Set<Id> questionIds = new Set<Id>();

            for (Enrollment_Component_Relationship__c temp : questionRelationships) {
                questionIds.add(temp.Child_Enrollment_Component__c);
                componentOrderMap.put(temp.Child_Enrollment_Component__c, temp.Order__c);
            }

            allIds = new List<Id>();
            allIds.addAll(stageIds);
            allIds.addAll(formIds);
            allIds.addAll(questionParentIds);
            allIds.addAll(questionIds);
        }
    
    }

    public enrollmentComponentData getSpecificProcessECData (id processId)
    {
        //Check the map to see if I already have the data for this PE
        if (!allECData.containsKey(processId) ) {
            //Build the new data set, add it to the map and return it.
            enrollmentComponentData newProcessData = new enrollmentComponentData(processId);
            allECData.put(processId, newProcessData);

            //We have one map for all the enrollment components for all the processes we have in this execution context.
            if (newProcessData.allIds.size() > 0) { 

                List<Enrollment_Component__c> componentChildren = [
                        SELECT Id, RecordType.Name, Assignment_Logic__c, Completion_Logic__c,  (  
                                SELECT Id, Criteria_Type__c, Criteria_Number__c, Criteria__r.Criteria_Field__c,
                                        Criteria__c, Student_or_Household__c,
                                        Criteria__r.Comparison_Field__c, Criteria__r.Operator__c,
                                        Criteria__r.Comparison_Data_Type__c, Criteria__r.Comparison_Value__c,
                                        Enrollment_Component__c, Enrollment_Component__r.Completion_Logic__c,
                                        Enrollment_Component__r.Assignment_Logic__c
                                FROM Enrollment_Component_Criteria__r
                        ), (SELECT Id, Group_Logic__c, Group_Number__c FROM Criteria_Groups__r)
                        FROM Enrollment_Component__c
                        WHERE Id IN:newProcessData.allIds
                ];

                for (Enrollment_Component__c enrollmentComponent : componentChildren) {
                    enrollmentComponentMap.put(enrollmentComponent.Id, enrollmentComponent);
                }
            }
        }

        return allECData.get(ProcessId);
    }
*/
}