force-app/main/default/objects/Data_Deletion__c.object
<CustomObject>
    <fields>
        <fullName>Execute__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Execute</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>account</fullName>
                </value>
                <value>
                    <fullName>Acknowledgement__c</fullName>
                </value>
                <value>
                    <fullName>Annual_Household_Information__c</fullName>
                </value>
                <value>
                    <fullName>Annual_Student_Information__c</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Emergency_Contact__c</fullName>
                </value>
                <value>
                    <fullName>Enrollment__c</fullName>
                </value>
                <value>
                    <fullName>Enrollment_Component_Affiliation__c</fullName>
                </value>
                <value>
                    <fullName>Enrollment_Component_Relationship__c</fullName>
                </value>
                <value>
                    <fullName>Enrollment_Document__c</fullName>
                </value>
                <value>
                    <fullName>Extended_Data__c</fullName>
                </value>
                <value>
                    <fullName>Health_and_Immunization__c</fullName>
                </value>
                <value>
                    <fullName>hed__Program_Enrollment__c</fullName>
                </value>
                <value>
                    <fullName>hed__Relationship__c</fullName>
                </value>
                <value>
                    <fullName>Home_Language_Survey__c</fullName>
                </value>
                <value>
                    <fullName>Intent_To_Return__c</fullName>
                </value>
                <value>
                    <fullName>opportunity</fullName>
                </value>
                <value>
                    <fullName>Placement_and_Elective__c</fullName>
                </value>
                <value>
                    <fullName>program_enrollment_criteria__c</fullName>
                </value>
                <value>
                    <fullName>Special_Education__c</fullName>
                </value>
                <value>
                    <fullName>Student_Custody__c</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>user</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderOfExecution__c</fullName>
        <label>OrderOfExecution</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Data Deletion</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Data Deletion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Deletion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/deleteObjectRecordsController.cls
public with sharing class deleteObjectRecordsController
{
    private ApexPages.StandardSetController standardController;

    public deleteObjectRecordsController(ApexPages.StandardSetController standardController)
    {
        this.standardController = standardController;
    }

    public PageReference deleteRecords()
    {       
        // Get the selected records (optional, you can use getSelected to obtain ID's and do your own SOQL)
        List<Data_Deletion__c> selectedRecords= (List<Data_Deletion__c>) standardController.getSelected();
        // Update records  
        set<string> objectValues= new set<String>(); 
        List< Data_Deletion__c > updateCheckBox= new list<Data_Deletion__c>();
        for(Data_Deletion__c cdt: [select id,objectName__c,OrderOfExecution__c,execute__c from Data_Deletion__c where id=:selectedRecords ]){
            cdt.execute__c= true;
            updateCheckBox.add(cdt );
        }
        if(updateCheckBox.size()>0){
            update updateCheckBox;
            }
           
        for(Data_Deletion__c selectedRecord : [select id,objectName__c,OrderOfExecution__c,execute__c from Data_Deletion__c where id=:selectedRecords and execute__c= true ORDER BY OrderOfExecution__c ASC LIMIT 1]){
            objectValues.add(selectedRecord.objectName__c);
        }       
            if(objectValues.size()>0){
                executeBatchToDeleteRecords.executeBatch(objectValues);
            }
        return null;        
    }
    
    public static void executeNextBatch(){
        set<string> objectValues= new set<String>(); 
         for(Data_Deletion__c selectedRecord : [select id,objectName__c,OrderOfExecution__c,execute__c from Data_Deletion__c where execute__c= true ORDER BY OrderOfExecution__c ASC LIMIT 1]){
            objectValues.add(selectedRecord.objectName__c);
        }       
            if(objectValues.size()>0){
                executeBatchToDeleteRecords.executeBatch(objectValues);
            }
    }
   }