force-app/main/default/objects/Document_File_References__c.object
<CustomObject>
    <label>Document File References</label>
    <nameField>
        <displayFormat>DFR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document File References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_File_References__c/fields/Document_Link__c.field-meta.xml
<CustomField>
    <fullName>Document_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Document Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <formula>text(Enrollment_Document__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Document Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/Enrollment_Document__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Document__c</fullName>
    <label>Enrollment Document</label>
    <referenceTo>Enrollment_Document__c</referenceTo>
    <relationshipLabel>Document File References</relationshipLabel>
    <relationshipName>Document_File_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/File_Path__c.field-meta.xml
<CustomField>
    <fullName>File_Path__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_File_References__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Utility_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used for projects where the developer plans to store many settings for a specific piece of functionality.</description>
    <label>Utility Settings</label>
</CustomObject>

force-app/main/default/classes/NES_DocumentFileRefListController.cls
/*
* Purpose: Server side controller methods for passing data to corresponding LC
* Change Log:
*         2019-08-01 initial for #101928 User Story (Eshwar) 
*         2019-08-02 updates for #101928 User Story (Andrew Sim)
*/
public with sharing class NES_DocumentFileRefListController {
    
    // return a list of Document file references to display
    @AuraEnabled
    public static List <Document_File_References__c> getDocList(Id enrollmentDocumentId) {
        system.debug('getDocList(' + enrollmentDocumentId + ');');
        return [SELECT Document_Link__c,Document_Type__c,Enrollment_Document__c,File_Path__c,Id,Name,Version__c,CreatedDate  FROM Document_File_References__c WHERE Enrollment_Document__c = :enrollmentDocumentId ORDER BY CreatedDate DESC];
    }
    
    // return the utility settings for this user
    @AuraEnabled
    public static Utility_Settings__c getUtilitySettings() {
        return Utility_Settings__c.getInstance();
    }
    
}