force-app/main/default/objects/Document_Reason_Message__mdt.object
<CustomObject>
    <description>Mapping of Enrollment Document Reason__c to the message to display in Document Upload</description>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>This corresponds to the Enrollment Document Type</description>
        <inlineHelpText>This corresponds to the Enrollment Document Type</inlineHelpText>
        <label>Document Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Enrollment_Document_Reason__c</fullName>
        <description>The picklist value of the Enrollment Document Reason__c to display the message for</description>
        <inlineHelpText>The picklist value of the Enrollment Document Reason__c to display the message for</inlineHelpText>
        <label>Enrollment Document Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>The message to display for a given Enrollment Document Reason__c</description>
        <inlineHelpText>The message to display for a given Enrollment Document Reason__c</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Document Reason Message</label>
    <pluralLabel>Document Reason Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Document_Status_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Document type identifier</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/NES_DocReasonMDTWrapper.cls
/**
 * Created by melindagrad on 1/19/19.
 *
 * Custom wrapper for Document_Reason_Message__mdt which queries MDT and returns as a wrapper--
 * this so we can create wrapper for testing because we cannot DML test MDTs
 */

public with sharing class NES_DocReasonMDTWrapper {
    private static Peak_ApexLog logger = new Peak_ApexLog('DocReasonMDTWrapper');

    //Get Enrollment Document Reason MDTs for with the given Enrollment Document Reason
    public static List<NES_DocReasonMDTWrapper.NES_DocReasonMessage> getDocReasonMDTS(Enrollment_Document__c theDocument) {

        List<NES_DocReasonMDTWrapper.NES_DocReasonMessage> enrollmentDocumentReasonMessages = new List<NES_DocReasonMDTWrapper.NES_DocReasonMessage>();

        try {

            //Query the Document_Reason_Message__mdt with the Enrollment_Document_Reason__c to get mapping
            List<Document_Reason_Message__mdt> documentReasonMessages = [
                    SELECT Id, Enrollment_Document_Reason__c, Message__c
                    FROM Document_Reason_Message__mdt
                    WHERE Enrollment_Document_Reason__c = :theDocument.Status_Reason__c
                    AND Document_Type__c = :theDocument.Type__c
            ];


            //If MDTs exist, create wrappers
            if (!Peak_Utils.isNullOrEmpty(documentReasonMessages)) {

                for (Document_Reason_Message__mdt theReasonMDT : documentReasonMessages) {

                    NES_DocReasonMessage theDocReasonWrapper = formatDocReasonMDTWrapper(theReasonMDT);
                    enrollmentDocumentReasonMessages.add(theDocReasonWrapper);
                }
            }

        } catch (Exception e) {
            logger.logException('getDocReasonMDTS', e);
            logger.saveLogs();
            System.debug('Caught Exception ' + e.getMessage());
        }

        //Return list of all MDTs as wrappers
        return enrollmentDocumentReasonMessages;
    }

    //Format the queried MDTs as wrappers
    public static NES_DocReasonMessage formatDocReasonMDTWrapper(Document_Reason_Message__mdt theReasonMDT) {

        NES_DocReasonMessage theDocReasonWrapper = new NES_DocReasonMessage();
        theDocReasonWrapper.message = theReasonMDT.Message__c;
        theDocReasonWrapper.enrollmentDocReason = theReasonMDT.Enrollment_Document_Reason__c;

        return theDocReasonWrapper;

    }

    //Inner class to wrap Document_Reason_Message__mdt
    public class NES_DocReasonMessage {

        @AuraEnabled public String enrollmentDocReason { get; set; }
        @AuraEnabled public String message { get; set; }

    }
}