force-app/main/default/objects/Document_Central_Status_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Level__c</fullName>
        <label>Status Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Under Review</fullName>
                    <default>true</default>
                    <label>Under Review</label>
                </value>
                <value>
                    <fullName>Needs Attention</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reviewed_Further Communication Needed</fullName>
                </value>
                <value>
                    <fullName>Default or Requested</fullName>
                </value>
                <value>
                    <fullName>Incomplete-Missing pages or sections</fullName>
                </value>
                <value>
                    <fullName>Invalid-Illegible</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verified-No Documentation Available</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Invalid-Missing Information</fullName>
                </value>
                <value>
                    <fullName>Invalid-Missing Signature</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Exemption-MKV</fullName>
                </value>
                <value>
                    <fullName>Invalid-File Error</fullName>
                </value>
                <value>
                    <fullName>Received-Complete</fullName>
                </value>
                <value>
                    <fullName>Received-Incomplete</fullName>
                </value>
                <value>
                    <fullName>Received-No Documentation Available</fullName>
                </value>
                <value>
                    <fullName>Reviewed-Further Communication Needed</fullName>
                </value>
                <value>
                    <fullName>Verified-Complete</fullName>
                </value>
                <value>
                    <fullName>Verified-Incomplete</fullName>
                </value>
                <value>
                    <fullName>Invalid-Outdated</fullName>
                </value>
                <value>
                    <fullName>Incomplete-Missing information</fullName>
                </value>
                <value>
                    <fullName>Invalid-Reenrollment</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Awaiting IEP</fullName>
                </value>
                <value>
                    <fullName>Deferred-Extension Approved by Principal</fullName>
                </value>
                <value>
                    <fullName>Deferred-Incomplete-Allow</fullName>
                </value>
                <value>
                    <fullName>Deferred-Non-compliant Allow</fullName>
                </value>
                <value>
                    <fullName>Deferred-Verified-In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Central Status Mapping</label>
    <pluralLabel>Document Central Status Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/PE_ContactID__c.field-meta.xml
<CustomField>
    <fullName>PE_ContactID__c</fullName>
    <formula>Program_Enrollment__r.hed__Contact__c</formula>
    <label>PE_ContactID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Documents</relationshipLabel>
    <relationshipName>Enrollment_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Program_Enrollment_AccountId__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment_AccountId__c</fullName>
    <formula>CASESAFEID(Program_Enrollment__r.hed__Contact__r.AccountId)</formula>
    <label>Program Enrollment AccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Blank Form</fullName>
            </value>
            <value>
                <fullName>Burden</fullName>
            </value>
            <value>
                <fullName>Case # missing</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Digital Signature</fullName>
            </value>
            <value>
                <fullName>Disconnect Notice</fullName>
            </value>
            <value>
                <fullName>District Verified</fullName>
            </value>
            <value>
                <fullName>Extension Approved by Principal</fullName>
            </value>
            <value>
                <fullName>Illegible</fullName>
            </value>
            <value>
                <fullName>Incomplete-Allow</fullName>
            </value>
            <value>
                <fullName>Incomplete Exemption</fullName>
            </value>
            <value>
                <fullName>Incomplete-Hold</fullName>
            </value>
            <value>
                <fullName>Incomplete Lease Agreement</fullName>
            </value>
            <value>
                <fullName>Incorrect CTR-grade level</fullName>
            </value>
            <value>
                <fullName>Incorrect CTR-other</fullName>
            </value>
            <value>
                <fullName>Incorrect CTR-school level</fullName>
            </value>
            <value>
                <fullName>Incorrect Form</fullName>
            </value>
            <value>
                <fullName>Invalid Form</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Mismatch Address</fullName>
            </value>
            <value>
                <fullName>Missing 1st Quarter Grades</fullName>
            </value>
            <value>
                <fullName>Missing 1st Semester</fullName>
            </value>
            <value>
                <fullName>Missing 2nd Quarter Grades</fullName>
            </value>
            <value>
                <fullName>Missing 2nd Semester</fullName>
            </value>
            <value>
                <fullName>Missing 3rd Quarter Grades</fullName>
            </value>
            <value>
                <fullName>Missing 4th Quarter Grades</fullName>
            </value>
            <value>
                <fullName>Missing credits earned</fullName>
            </value>
            <value>
                <fullName>Missing Final Grades</fullName>
            </value>
            <value>
                <fullName>Missing Grade Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/SchoolId__c.field-meta.xml
<CustomField>
    <fullName>SchoolId__c</fullName>
    <formula>CASESAFEID(Program_Enrollment__r.hed__Account__r.ParentId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SchoolId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/SchoolYear__c.field-meta.xml
<CustomField>
    <fullName>SchoolYear__c</fullName>
    <formula>Program_Enrollment__r.Start_Year__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SchoolYear</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Document_Status_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Document type identifier</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SISUpdates.cls
//Swapna:For US 113260
Public class SISUpdates{
 private static Peak_ApexLog logger = new Peak_ApexLog('SISUpdates');
@invocableMethod(label='Push Document Updates to SIS' description='Updates Document Status to SIS')
   

public static void pushDocUpdatetoSIS(List<Id> enrlDocId)
{

//  PE_ContactID__c
  List<Enrollment_Document__c> Ed = [select Name,Type__c,Program_Enrollment__c,Program_Enrollment_AccountId__c,PE_ContactID__c,SchoolId__c,SchoolYear__c,Status_Reason__c,Reason__c from Enrollment_Document__c where Id=:enrlDocId LIMIT 1];
  List<Document_Central_Status_Mapping__mdt> status = [select id,MasterLabel,Status_Level__c,Status__c from Document_Central_Status_Mapping__mdt where Status__c=:Ed[0].Status_Reason__c Limit 1]; 
  String EdStatus ;
   if(status.size() >0)
   EdStatus = status[0].Status_Level__c;
   else
   EdStatus = Ed[0].Status_Reason__c;
  String EnrolDocId = Ed[0].Name;
  String docType = Ed[0].Type__c;
  String HshldId = Ed[0].Program_Enrollment_AccountId__c;
  String StdId =Ed[0].PE_ContactID__c;
  String SchoolYr = Ed[0].SchoolYear__c;
  String SchoolId = Ed[0].SchoolId__c;

  String Rsn =Ed[0].Reason__c;
  pushDocInfo(EnrlDocId,HshldId,StdId,docType,SchoolYr,SchoolId,EdStatus,Rsn);
  
system.debug(enrlDocId);
}
@future(callout=true)
public static void  pushDocInfo(List<Id> EnrlDocId,String HshldId,String StdId,String docType,String SchoolYr,String SchoolId,String EdStatus,String Rsn)
{
      try
      {
           String idamAccessToken =  NES_IdamUtilities.getIdamAccessToken();
           String jsonBody = '{"correlationId": "' + EnrlDocId + '","ApplicationName": "nes","Action":"u","Entity":"Document",' +
                    '"actioncontext": "document_update_status","AdditionalProperties":{"houseHoldId":"' + HshldId + '","studentId":"'+ StdId +'","docType":"'+ docType + '","schoolYear":"'+ SchoolYr + '","schoolId":"'+ SchoolId + '","status":"'+ EdStatus +'","Reason":"' + Rsn + '"}}';
            HttpRequest request = new HttpRequest();
            request.setMethod('POST');
            request.setEndpoint('callout:Event_Emitter/v1/eventemitter');
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('cache-control', 'no-cache');
            request.setHeader('x-ctx-accesstoken', idamAccessToken);
            request.setBody(jsonBody);

            Http http = new Http();
            HttpResponse response = http.send(request);
            
            }
            catch (Exception e) {
                        System.debug('Error: ' + e);
                        logger.logException('SISDocStatusupdateError', e);
                        logger.saveLogs();
                    }

}
}