force-app/main/default/objects/ecrTree__c.object
<CustomObject>
    <description>Holds the JSON representation of Academic Program, built using ECR records.</description>
    <label>ecrTree</label>
    <nameField>
        <displayFormat>ECRT-{00000}</displayFormat>
        <label>rootNode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ecrTree</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ecrTree__c/fields/ecCount__c.field-meta.xml
<CustomField>
    <fullName>ecCount__c</fullName>
    <description>Total no of ECs in the tree</description>
    <inlineHelpText>Total no of ECs in the tree</inlineHelpText>
    <label>ecCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/ecTreeHeight__c.field-meta.xml
<CustomField>
    <fullName>ecTreeHeight__c</fullName>
    <inlineHelpText>Height of the tree</inlineHelpText>
    <label>ecTreeHeight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/ecTypes__c.field-meta.xml
<CustomField>
    <fullName>ecTypes__c</fullName>
    <description>Types of ECs in the tree, ex: Stage, Process, Form, etc...</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Types of ECs in the tree, ex: Stage, Process, Form, etc...</inlineHelpText>
    <label>ecTypes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/parentID__c.field-meta.xml
<CustomField>
    <fullName>parentID__c</fullName>
    <description>Holds the SFDC ID of the parent record</description>
    <encryptionScheme>None</encryptionScheme>
    <label>parentID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/payload__c.field-meta.xml
<CustomField>
    <fullName>payload__c</fullName>
    <description>Holds the JSON format of Academic Program Enrollment Component Tree</description>
    <encryptionScheme>None</encryptionScheme>
    <label>payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <description>Helps identify type of Parent, if its a SUBTREE OR a complete TREE
Ex: Stage, Process, Form etc....</description>
    <encryptionScheme>None</encryptionScheme>
    <label>type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/version__c.field-meta.xml
<CustomField>
    <fullName>version__c</fullName>
    <description>Version number to track changes to the JSON</description>
    <label>version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Assignment_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component is relevant to the program enrollment the evaluation was completed for and it would then be assigned to the PE through a Enrollment Component Affiliation. If there is no assignment logic defined on a component, it inherits it&apos;s assigment from its parent.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Assignment Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component has been completed by theprogram enrollment the evaluation was completed for and it would then be marked complete on the shared Enrollment Component Affiliation.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Completion Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Indicator of whether the component relates to student or caretaker (household) program enrollments. This field is used for components of the following types: Flag, Form. All child components of a form should implicitly inherit the type of the form when used in the context of that form.</description>
        <label>Component Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Caretaker</fullName>
                    <isActive>false</isActive>
                    <label>Caretaker</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Provides a way to systematically export and load Enrollment Components.  Unique.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Determines whether a particular Enrollment Component is required.</inlineHelpText>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic program associated with the component. This is exclusively used by components with a record type of Process to create a relationship between the account entity and it&apos;s required components. As the child components of the process could be used by multiple processes, there is not a direct relationship between them and a specific academic program and those relationships are inferred from their parent process.</description>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enrollment Components (Academic Program)</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flag</fullName>
        <active>true</active>
        <label>Flag</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Message</fullName>
        <active>true</active>
        <label>Message</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <description>The enrollment component that is the parent in the relationship being defined.</description>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/apTreeGenerator.cls
/**
    @class:         apTreeGenerator           
	@description:   Walks over the Academic Program / Process ECRs & builds a tree hierarchy. Populates the ecrProcessData data class.
	@author: 		Mark Membrino
	@createdDate:   9/10/2020
*/
public class apTreeGenerator 
{
    private Map<Id, ecrProcessData> processData { get; private set; }
    private Map<Id, Enrollment_Component__c> processECs { get; private set; }
    private List<Id> processECsNotFound { get; private set; }
    private final Integer TREE_MAX_DEPTH = 3;
    private final String EC_RECORD_TYPE_WHITE_LIST_TXT = 'Process,Stage,Form,Section,Document,Flag,Message'; // @Q: Can we skip: Flag & Message ECs ? 
    private final List<String> EC_RECORD_TYPE_WHITE_LIST = EC_RECORD_TYPE_WHITE_LIST_TXT.split(',');

    public apTreeGenerator()
    {
        this.processECsNotFound = new List<Id>();
    }

    // public apTreeGenerator(List<Id> processIds) 
    // {
    //     this();
    //     try 
    //     {
    //         this.processECs = new Map<Id,Enrollment_Component__c>(ecrTreeUtils.getECsByID(processIds));
    //         if (this.processECs.size()==0)
    //              throw new illegalArgumentECTreeGeneratorException('No processEC records found.');
            
    //         this.processData = new Map<Id, ecrProcessData>();
    //         for (Id processId : processIds)
    //             this.processData.put(processId, new ecrProcessData(processId));
                
    //     } catch (Exception ex ) {
    //         throw new illegalArgumentECTreeGeneratorException('invalid processIds:' + processIds  + '; Exception:' + ex.getMessage());
    //     }
          
    // }

    // USE THIS ONE...
    public apTreeGenerator(List<Id> academicProgramIds) 
    {
        this();
        try 
        {
            this.processECs = new Map<Id,Enrollment_Component__c>(ECA_CriteriaEvaluatorHelper.getECsByAcademicPrograms(academicProgramIds));
            if (this.processECs.size()==0)
                 throw new illegalArgumentECTreeGeneratorException('No processEC records found.');
            
            this.processData = new Map<Id, ecrProcessData>();
            for (Enrollment_Component__c processEC : processECs.values())
                this.processData.put(processEC.Process_Academic_Program__c, new ecrProcessData(processEC.Id, processEC.Process_Academic_Program__c)); // Mapped to academicProgram -> processRecord
                
        } catch (Exception ex ) 
        {
            throw new illegalArgumentECTreeGeneratorException('invalid Academic Program IDs:' + academicProgramIds  + '; Exception:' + ex.getMessage());
        } 
    }
    
    public Map<Id, ecrProcessData> getData()
    {
        return this.processData;
    }

    /**
     * 
     * Using BFS w/iteration to build the tree
     */
    public void generate() {

        if ( this.processData==null || this.processData.size()==0 ) { return; }

        for (ecrProcessData pd : processData.values())
        {
            if (this.processECs.get(pd.processId)==null) 
            { 
                processECsNotFound.add(pd.processId); // @todo: something with this?
                continue; 
            }

            pd.root = new ecNode(this.processECs.get(pd.processId), pd.steps); // xtra
            pd.ecTypes.add(pd.root.kind);
            Map<Id, ecNode> ecNodeMapParent = new Map<Id, ecNode>{pd.root.nodeId => pd.root}; 

            // overloading a 'queue for list of strings' to handle 'any' type of List, in this case a list of deserialized map of ecNodes.
            ecNodeQueue q = new ecNodeQueue();
            q.enqueue(ecNodeMapParent); 

            while (!q.isEmpty()) { // && pd.steps <= TREE_MAX_DEPTH
                
                ecNodeMapParent = q.dequeue();

                // gathering stats...
                pd.countECs += ecNodeMapParent.size();
                pd.steps++;

                // System.debug('::step>>>' + pd.steps + '>>>ecNodeMapParent>>>' + JSON.serialize(ecNodeMapParent));

                // tmpMap, to gather the children
                Map<Id, ecNode> ecNodeMapChildrenTmp = new Map<Id, ecNode>();

                for (Enrollment_Component_Relationship__c ecr : queryECRs(ecNodeMapParent.keySet(), EC_RECORD_TYPE_WHITE_LIST))
                {   
                    // build EC-Parent => EC-Children Map
                    this.addToMap(pd.ecParentToChildrenMap, ecr.Parent_Enrollment_Component__c, ecr.Child_Enrollment_Component__c);
                    
                    // build EC-Child => EC-Parents Map
                    this.addToMap(pd.ecChildToParentsMap, ecr.Child_Enrollment_Component__c, ecr.Parent_Enrollment_Component__c);

                    ecNode child = new ecNode(ecr, pd.steps); // create a child Node
                    pd.ecTypes.add(child.kind); // gathering stats...
                    ecNodeMapParent.get(ecr.Parent_Enrollment_Component__c).addChildren(child);// add child to parentNode
                    ecNodeMapChildrenTmp.put(ecr.Child_Enrollment_Component__c, child); // tmp map to hold child ec -> ecNode
                }

                if (ecNodeMapChildrenTmp.size()>0) {
                    q.enqueue(ecNodeMapChildrenTmp);
                }

            }
        }
        System.debug('processData>>' + JSON.serialize(processData));
    }

    public void addToMap(Map<Id, List<Id>> addToMap, Id key, Id value)
    {
        List<Id> values = addToMap.get(key);
        if (values==null)
            values = new List<Id>();
        values.add(value);
        addToMap.put(key, values);
    }


    // /**
    //  *  save ecrProducerFormat to the database object
    //  *  
    //  */
    // // public List<ecrTree__c> save() 
    // public Set<Id> save()
    // {
    //     List<sObject> forUpdate = new List<sObject>();
    //     List<ecrTree__c> newConfigs = new List<ecrTree__c>();
    //     for ( ecrProcessData pdConfig : this.processData.values())
    //     {
            
    //         // if no payload, skip
    //         if (pdConfig.root==null) {
    //             continue;
    //         }

    //         Integer version = 0;
    //         for (ecrTree__c rec : ecrTreeUtils.getECRTreeByParentIDs(new Set<Id>{pdConfig.root.nodeId})) { // query existing records for the same node.ID
                
    //             Integer configVersion = Integer.valueOf(rec.Version__c);
    //             if (configVersion > version){
    //                 version = configVersion; // grab the latest version
    //             }
                
    //             rec.isActive__c = false; // set older configs to inActive
    //             forUpdate.add(rec);

    //         }
    //         pdConfig.version = ++version; // set the version
            
    //         // ecrTree__c newConfig = ecrTreeUtils.createECRTreeRec(config); // create new record
    //         ecrTree__c newConfig = createECRTreeRec(pdConfig); // create new record

    //         newConfigs.add(newConfig);
    //         // update forUpdate; // update only after newConfig is save successfully
    //         // return newConfig.Id;
    //     }
    //     if (newConfigs.size()>0)
    //         insert newConfigs;

    //     if (forUpdate.size()>0)
    //         update forUpdate;

    //     return (new Map<Id, ecrTree__c>(newConfigs).keySet());
    // }

    /**
     *  This method is used to find a specific node & its children in the processHierarch (rootNode)
     */
    public static ecNode search(ecNode rootNode, Id toFindECId)
    {
        // if (this.processData.get(pgmId)==null)
        //     return null;
    
        if (rootNode==null || toFindECId==null)
            return null;

        if (rootNode.ecId == toFindECId)
            return rootNode;
            
        ecNodeQueue q = new ecNodeQueue();
        q.enqueue(new Map<Id, ecNode>{rootNode.nodeId => rootNode});
        
        // if  (q.peek().values()[0].ecId==toFindECId)
        //     return q.dequeue().values()[0];
        
        Integer level = 0;
        // ecrImport.ecrIDsByLevel

        Map<Id, ecNode> ecNodeTemp; // temp loop variable
        while (!q.isEmpty()) 
        {
            ecNodeTemp = q.dequeue();
            
            // if (toFindECId==ecNodeTemp.values()[0].ecId)
            for (Id ndID : ecNodeTemp.keySet()) 
            {
                ecNode curr = ecNodeTemp.get(ndID);
                // if (toFindECId==ecNodeTemp.values()[0].ecId)
                if (toFindECId==curr.ecId)
                    return curr;
                q.enqueue(curr.getChildrenAsMap());
            }
        }

        return null;

    }

    /**
     *  This method is flattens the given rootNode & its children & returns a Set of EC Ids
     */
    public static Set<Id> getNodeSubTreeAsList(ecNode rootNode)
    {
        Set<Id> subTree = new Set<Id>();

        if (rootNode==null)
            return null;

        // if (rootNode.getChildrenAsMap().size()==0)
        //     return children;
            
        ecNodeQueue q = new ecNodeQueue();
        q.enqueue(new Map<Id, ecNode>{rootNode.nodeId => rootNode});
        
        // if  (q.peek().values()[0].ecId==toFindECId)
        //     return q.dequeue().values()[0];
        
        Integer level = 0;
        // ecrImport.ecrIDsByLevel
        Map<Id, ecNode> ecNodeTemp; // temp loop variable
        while (!q.isEmpty()) 
        {
            ecNodeTemp = q.dequeue();
            
            for (Id ndID : ecNodeTemp.keySet()) 
            {
                ecNode curr = ecNodeTemp.get(ndID);
                subTree.add(curr.ecId);

                Map<Id, ecNode> tmpChildren = curr.getChildrenAsMap();
                if (curr.getChildrenAsMap().size()>0)
                    q.enqueue(curr.getChildrenAsMap());
            }
        }

        return subTree;
    }


    // @returns ecrTree record
    public static ecrTree__c createECRTreeRec(ecrProcessData config) 
    {   
        List<String> ecTypesList = new List<String>();
        ecTypesList.addAll(config.ecTypes); // converting ecTypes from set to list

        ecrTree__c newConfig = new ecrTree__c(
            ParentID__c = config.root.nodeId,
            isActive__c = true, // false // true
            Type__c = config.root.kind,
            ecTreeHeight__c = config.steps, 
            ecCount__c = config.countECs, 
            ecTypes__c = String.join(ecTypesList, ','),
            // Payload__c = JSON.serialize(config.root),
            Payload__c = JSON.serialize(config),
            Version__c = config.version
        );

        return newConfig;
    }

    // query ECR records by ParentIDs
    public static List<Enrollment_Component_Relationship__c> queryECRs(Set<Id> parentIDs, List<String> recordTypeWhiteList) {       
        return [SELECT  Id, Order__c, External_Id__c,
                    Parent_Enrollment_Component__c,
                    Parent_Enrollment_Component__r.Id, 
                    Parent_Enrollment_Component__r.Name, 
                    Parent_Enrollment_Component__r.Completion_Logic__c, 
                    Child_Enrollment_Component__c, 
                    Child_Enrollment_Component__r.Id, 
                    Child_Enrollment_Component__r.Name, 
                    Child_Enrollment_Component__r.RecordTypeId,
                    Child_Enrollment_Component__r.RecordType.Name, 
                    Child_Enrollment_Component__r.Component_Type__c,
                    Child_Enrollment_Component__r.Completion_Logic__c,
                    Child_Enrollment_Component__r.Assignment_Logic__c,
                    Child_Enrollment_Component__r.Is_Required__c,
                    Child_Enrollment_Component__r.External_Id__c
            FROM    Enrollment_Component_Relationship__c
            WHERE   Parent_Enrollment_Component__c =: parentIDs
            AND   Child_Enrollment_Component__r.RecordType.Name IN : recordTypeWhiteList
            ORDER BY Order__c ASC];
    }


    public class illegalArgumentECTreeGeneratorException extends Exception {}

}