force-app/main/default/objects/ecrTree__c.object
<CustomObject>
    <description>Holds the JSON representation of Academic Program, built using ECR records.</description>
    <label>ecrTree</label>
    <nameField>
        <displayFormat>ECRT-{00000}</displayFormat>
        <label>rootNode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ecrTree</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ecrTree__c/fields/ecCount__c.field-meta.xml
<CustomField>
    <fullName>ecCount__c</fullName>
    <description>Total no of ECs in the tree</description>
    <inlineHelpText>Total no of ECs in the tree</inlineHelpText>
    <label>ecCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/parentID__c.field-meta.xml
<CustomField>
    <fullName>parentID__c</fullName>
    <description>Holds the SFDC ID of the parent record</description>
    <encryptionScheme>None</encryptionScheme>
    <label>parentID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/payload__c.field-meta.xml
<CustomField>
    <fullName>payload__c</fullName>
    <description>Holds the JSON format of Academic Program Enrollment Component Tree</description>
    <encryptionScheme>None</encryptionScheme>
    <label>payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <description>Helps identify type of Parent, if its a SUBTREE OR a complete TREE
Ex: Stage, Process, Form etc....</description>
    <encryptionScheme>None</encryptionScheme>
    <label>type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ecrTree__c/fields/version__c.field-meta.xml
<CustomField>
    <fullName>version__c</fullName>
    <description>Version number to track changes to the JSON</description>
    <label>version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Assignment_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component is relevant to the program enrollment the evaluation was completed for and it would then be assigned to the PE through a Enrollment Component Affiliation. If there is no assignment logic defined on a component, it inherits it&apos;s assigment from its parent.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Assignment Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component has been completed by theprogram enrollment the evaluation was completed for and it would then be marked complete on the shared Enrollment Component Affiliation.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Completion Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Indicator of whether the component relates to student or caretaker (household) program enrollments. This field is used for components of the following types: Flag, Form. All child components of a form should implicitly inherit the type of the form when used in the context of that form.</description>
        <label>Component Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Household</fullName>
                </value>
                <value>
                    <fullName>Caretaker</fullName>
                    <isActive>false</isActive>
                    <label>Caretaker</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Provides a way to systematically export and load Enrollment Components.  Unique.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Determines whether a particular Enrollment Component is required.</inlineHelpText>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needed_for_ITR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needed for ITR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needed_for_Re_enrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needed for Re-enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <description>The enrollment component that is the parent in the relationship being defined.</description>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_ECDataImportExport.cls
/** 

    @author: Ali KM (Ness Tech)
    * Created this class on 04/15/2020 for [US 166761]
    * This class helps serialize / deserialize the NES_EnrollmentCompentBuilder.enrollmentComponentData 
        state in-order to reduce the number of soqls consumed in the eca reassignment/completion evaluation.

*/

public with sharing class NES_ECDataImportExport {

    // public static NES_EnrollmentCompentBuilderWIP.enrollmentComponentData {get; set;}
    public static final String EC_DATA_CLASS_TYPE = 'ecDataClass';

    
    /**
     *  @Autor: Ali KM 
     *  @Purpose: dataExport / serialize
     *  @Return: ecrTree__c.Id of inserted config record.
     *  @Usage: 
            String processId ='a2921000001pR9wAAE'; //  
            NES_EnrollmentCompentBuilder.enrollmentComponentData ecData = new NES_EnrollmentCompentBuilder.enrollmentComponentData(processId);
            System.debug('ecrTree RecID:' + NES_ECDataImportExport.ExportData(ecData));
     */
    public static Id ExportData(NES_EnrollmentCompentBuilder.enrollmentComponentData ecData) {
         
        if (ecData==null) {return null;}

        Decimal version = 0;
        List<sObject> toUpdate = new List<sObject>();

        // query older records if they exist & mark then inactive
        for (ecrTree__c config : getECRTreeByParentIDs(new Set<Id>{ecData.ProcessId}, EC_DATA_CLASS_TYPE)) {

            // Integer configVersion = config.version__c; //Integer.valueOf(config.version__c);
            if (config.version__c > version) { version = config.version__c;}

            toUpdate.add(new ecrTree__c(Id=config.Id, isActive__c = false));

        }

        // create a new backup record
        ecrTree__c newConfig = createECRTreeRec(buildECDataExportFormat(ecData));
        newConfig.version__c = ++version;String.valueOf(++version);

        // DMLs
        insert newConfig;
        update toUpdate;

        return newConfig.Id;

    }


    /**
     * 
     @Usage: 
        String processId ='a0f0n000001IAQ2AAO'; //  
        NES_EnrollmentCompentBuilder.enrollmentComponentData data = NES_ECDataImportExport.ImportData(processId);
        NES_ECDataImportExport.ppData(data);
     * 
     * OUTPUT:
        ecData.ProcessId>>>a0f0n000001IAQ2AAO>>>
        ecData.allIds.size>>>467>>>
        ecData.stageRelationships.size>>>5>>>
        ecData.formRelationships.size>>>23>>>
        ecData.sectionRelationships.size>>>54>>>
        ecData.questionGroupRelationships.size>>>33>>>
        ecData.questionRelationships.size>>>385>>>
        ecData.componentOrderMap.size>>>467>>>
        ecData.questionParentIds.size>>>86>>>
        >>>END>>>
     * 
     */
    // dataImport / deserialize
    public static NES_EnrollmentCompentBuilder.enrollmentComponentData ImportData(Id processId) { 
        
        try {
            
            // query the data
            ecrTree__c configRec = getECRTreeByParentIDs(processId, EC_DATA_CLASS_TYPE);
            // System.debug(JSON.serialize(configRec));
            
            if ((new ecrTree__c()) == configRec) {return null;}

            ecDataExportFormat configData = deserialize(configRec);

            return unpackConfigData(configData);

        } catch (Exception ex) {

            System.debug('Exception occured while importing configuration in NES_ECDataImportExport.ImportData(), exception:' + ex.getMessage());
            return null;

        }
    
    }

    public static NES_EnrollmentCompentBuilder.enrollmentComponentData unpackConfigData(ecDataExportFormat configData) {

        NES_EnrollmentCompentBuilder.enrollmentComponentData ecData = new NES_EnrollmentCompentBuilder.enrollmentComponentData();

        // run a query to get the ecr records.
        Map<Id, Enrollment_Component_Relationship__c> ecrMap = new Map<Id, Enrollment_Component_Relationship__c>();
        for (Enrollment_Component_Relationship__c ecr : queryECRById(configData.ecrToECMap.keySet())) {
            ecrMap.put(ecr.Id, ecr);
        }

        if (ecrMap.size()==0) {return null;}

        // copy data over to the enrollmentComponentData object...
        ecData.ProcessId = configData.processID;
        ecData.allIds.addAll(configData.componentOrderMap.keySet());
        ecData.stageRelationships = getECRRecordsByIds(ecrMap, configData.stageECRIds);
        ecData.formRelationships = getECRRecordsByIds(ecrMap, configData.formECRIds);
        ecData.sectionRelationships = getECRRecordsByIds(ecrMap, configData.sectionECRIds);
        ecData.questionGroupRelationships = getECRRecordsByIds(ecrMap, configData.questionGroupECRIds);
        ecData.questionRelationships = getECRRecordsByIds(ecrMap, configData.questionECRIds);
        ecData.componentOrderMap = configData.componentOrderMap;
        ecData.questionParentIds = configData.questionParentIds;

        return ecData;

    }

    public static void ppData(NES_EnrollmentCompentBuilder.enrollmentComponentData ecData) {

        String output = '\n>>>EC DATA SUMMARY>>';
        output += '\necData.ProcessId>>>' + ecData.ProcessId + '>>>';
        output += '\necData.allIds.size>>>' + ecData.allIds.size() + '>>>';
        output += '\necData.stageRelationships.size>>>' + ecData.stageRelationships.size() + '>>>';
        output += '\necData.formRelationships.size>>>' + ecData.formRelationships.size() + '>>>';
        output += '\necData.sectionRelationships.size>>>' + ecData.sectionRelationships.size() + '>>>';
        output += '\necData.questionGroupRelationships.size>>>' + ecData.questionGroupRelationships.size() + '>>>';
        output += '\necData.questionRelationships.size>>>' + ecData.questionRelationships.size() + '>>>';
        output += '\necData.componentOrderMap.size>>>' + ecData.componentOrderMap.size() + '>>>';
        output += '\necData.questionParentIds.size>>>' + ecData.questionParentIds.size() + '>>>';
        output += '\n>>>END>>>';

        System.debug(output);

    }

    public static List<Enrollment_Component_Relationship__c> getECRRecordsByIds(Map<Id, Enrollment_Component_Relationship__c> ecrMap, List<Id> ecrIds) {

        List<Enrollment_Component_Relationship__c> ecrList = new List<Enrollment_Component_Relationship__c>();
        for (Id ecrId: ecrIds) {
            ecrList.add(ecrMap.get(ecrId));
        }
        return ecrList;
    }


    public static ecDataExportFormat deserialize(ecrTree__c configRec) {

        String payload = configRec.Payload__c;
        ecDataExportFormat pak; 

        try {        
            pak = (ecDataExportFormat) JSON.deserializeStrict( payload, ecDataExportFormat.class );
        } 
        catch (Exception ex) {
            throw new ecDataImportException('EnrollmentConponentData Import Exception, unable to deserialize payload. Exception:' + ex.getMessage());
        }

        return pak;
        
    }


    // supporting methods start...
    public static ecrTree__c getECRTreeByParentIDs(Id ecrTreeParentID, String type) {
        return getECRTreeByParentIDs(new Set<Id>{ecrTreeParentID}, type)[0];
    }


    /**
     * // ideally this should return just 1 Active record
     */
    private static List<ecrTree__c> getECRTreeByParentIDs(Set<Id> ecTreeParentIDs, String type) {

        return [SELECT  Id, 
                        name, 
                        parentID__c, 
                        version__c, 
                        isActive__c, 
                        type__c,
                        payload__c
                FROM    ecrTree__c
                WHERE   parentID__c = : ecTreeParentIDs
                AND     isActive__c = true
                AND     Type__c =: type];

    }


    /**
     *  This class converts the enrollmentComponentData object to a leaner ecDataExportFormat object to serialize..
     */
    public static ecDataExportFormat buildECDataExportFormat( NES_EnrollmentCompentBuilder.enrollmentComponentData ecData ) {

        ecDataExportFormat dataFormat = new ecDataExportFormat();

        // copy data to exportFormat
        dataFormat.processID = ecData.ProcessId;
        dataFormat.stageECRIds = copyBuilderListToTargetMap(ecData.stageRelationships, dataFormat);
        dataFormat.formECRIds = copyBuilderListToTargetMap(ecData.formRelationships, dataFormat);
        dataFormat.sectionECRIds = copyBuilderListToTargetMap(ecData.sectionRelationships, dataFormat);
        dataFormat.questionGroupECRIds = copyBuilderListToTargetMap(ecData.questionGroupRelationships, dataFormat);
        dataFormat.questionECRIds = copyBuilderListToTargetMap(ecData.questionRelationships, dataFormat);
        dataFormat.componentOrderMap = ecData.componentOrderMap;
        dataFormat.questionParentIds = ecData.questionParentIds;

        return dataFormat;

    }


    private static List<Id> copyBuilderListToTargetMap(List<Enrollment_Component_Relationship__c> source, ecDataExportFormat target) {

        Map<Id, Id> ecrToECMap = target.ecrToECMap;
        List<Id> ecrIds = new List<Id>();
        for (Enrollment_Component_Relationship__c ecr : source) {
            ecrToECMap.put(ecr.Id, ecr.Child_Enrollment_Component__c);
            ecrIds.add(ecr.Id);
        }
        // System.debug('ecrToECMap.size()>>>' + ecrToECMap.size());
        return ecrIds;

    }


    // data class
    public class ecDataExportFormat {

        public Id processID {get; set;}
        public Map<Id, Id> ecrToECMap {get; set;}
        // public List<Id> allIds {get; set;}
        public List<Id> stageECRIds {get; set;}
        public List<Id> formECRIds {get; set;}
        public List<Id> sectionECRIds {get; set;}
        public List<Id> questionGroupECRIds {get; set;}
        public List<Id> questionECRIds {get; set;}
        public Map<Id, Decimal> componentOrderMap {get; set;}
        public Set<Id> questionParentIds {get; set;}

        public ecDataExportFormat() {
            
            ecrToECMap          = new Map<Id, Id>();
            // allIds              = new List<Id>(); this can be fetched from componentOrderMap or ecrToECMap
            stageECRIds         = new List<Id>();
            formECRIds          = new List<Id>();
            sectionECRIds       = new List<Id>();
            questionGroupECRIds = new List<Id>();
            questionECRIds      = new List<Id>();
            componentOrderMap   = new Map<Id, Decimal>();
            questionParentIds   = new Set<Id>();

        }
    }

    
    // @returns ecrTree record
    public static ecrTree__c createECRTreeRec(ecDataExportFormat config) {

        return (new ecrTree__c(
            parentID__c = config.ProcessId,
            isActive__c = true,
            type__c = EC_DATA_CLASS_TYPE,
            ecCount__c = config.componentOrderMap.size(), 
            payload__c = JSON.serialize(config)
            // Version__c = String.valueOf(config.version)
        ));

    }

     // query ECR records by IDs
    public static List<Enrollment_Component_Relationship__c> queryECRById(Set<Id> recIDs) {       
        return [SELECT  Id, Order__c, 
                    Parent_Enrollment_Component__c,
                    Parent_Enrollment_Component__r.Id, 
                    Parent_Enrollment_Component__r.Name, 
                    Parent_Enrollment_Component__r.Completion_Logic__c, 
                    Child_Enrollment_Component__c, 
                    Child_Enrollment_Component__r.Id, 
                    Child_Enrollment_Component__r.Name, 
                    Child_Enrollment_Component__r.RecordTypeId,
                    Child_Enrollment_Component__r.RecordType.Name, 
                    Child_Enrollment_Component__r.Component_Type__c,
                    Child_Enrollment_Component__r.Completion_Logic__c,
                    Child_Enrollment_Component__r.Assignment_Logic__c,
                    Child_Enrollment_Component__r.Is_Required__c,
                    Child_Enrollment_Component__r.External_Id__c,
                Child_Enrollment_Component__r.Needed_for_Re_enrollment__c,
                Child_Enrollment_Component__r.Needed_for_ITR__c
            FROM    Enrollment_Component_Relationship__c
            WHERE   Id =: recIDs
            //AND   Child_Enrollment_Component__r.RecordType.Name = : NES_DashboardUtilities.STAGE_RT 
            ORDER BY Order__c ASC];
    }

    public class ecDataImportException extends Exception {}
    
}