force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Picklist_Option__c.object
<CustomObject>
    <label>Enrollment Component Picklist Option</label>
    <nameField>
        <displayFormat>PO-{0}</displayFormat>
        <label>Enrollment Component Picklist Option Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Picklist Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Picklist_Option__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <inlineHelpText>Parent Question Record Type, Picklist Type Enrollment Component.</inlineHelpText>
    <label>Enrollment Component</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Enrollment_Component__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Question</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Picklist Options</relationshipLabel>
    <relationshipName>Enrollment_Component_Picklist_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grade_Level__c.object
<CustomObject>
    <description>The grade level object stores grade level information for connection to Academic Programs and Caps.</description>
    <label>Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The parent Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Grade Level</label>
    <referenceTo>Program_Grade_Level__c</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Grade_Level__c.object
<CustomObject>
    <label>Program Grade Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Grade Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Grade Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Grade_Level__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Program Grade Levels</relationshipLabel>
    <relationshipName>Program_Grade_Levels</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NES_QuestionsController.cls
/**
 * Created by triciaigoe on 1/25/19.
 * 2019-10-07 Added Skip For Now #US108687 (Ali Khan)
 */

public without sharing class NES_QuestionsController {

    /**
    * Created by Ashish Sharma on 11/14/18.
    * Parameters: ID
    * Return Type: List<NES_DashboardUtilities.Question>
    * Purpose : This method is used to get the related Child enrollment component of QUESTION_RT record type using sectionComponentId
    and using those child components get the required question components information
    */
    @AuraEnabled
    public static List<NES_EvaluateUtil.Question> getRelatedQuestions(Id sectionComponentId, Id enrollmentId){
        return NES_QuestionsHelper.getRelatedQuestions2(enrollmentId, null, sectionComponentId, true);
    }

    @AuraEnabled
    public static List<NES_EvaluateUtil.Question> getRelatedQuestions2(Id sectionComponentId, Id enrollmentId){
        return NES_QuestionsHelper.getRelatedQuestions2(enrollmentId, null, sectionComponentId, true);
    }

    /**
    * Created by Ashish Sharma on 11/14/18.
    * Parameters: ID
    * Return Type: List<Enrollment_Component_Picklist_Option__c>
    * Purpose : This method is used to retrieve and return all the Enrollment_Component_Picklist_Option__c records related to questionComponentId
    */
    @AuraEnabled
    public static List<Enrollment_Component_Picklist_Option__c> getRelatedPicklistOptions(Id questionComponentId) {
        return NES_QuestionsHelper.getRelatedPicklistOptions(questionComponentId);
    }

    // submit and save answers to the questions
    @AuraEnabled
    public static Peak_Response submitQuestions(Id enrollmentId, String questions, Id processComponentId, Id sectionComponentId) {
        return NES_QuestionsHelper.submitQuestions(enrollmentId, questions, sectionComponentId, processComponentId);
    }

    // #US108687 (Ali Khan)
    @AuraEnabled
    public static Peak_Response grabNextURL(Id enrollmentId, Id processComponentId, Id sectionComponentId) {
        Peak_Response peakResponse = new Peak_Response();
        hed__Program_Enrollment__c programEnrollment = [SELECT Id, hed__Contact__r.Name, Program_Grade_Level__r.Grade_Level__r.Name FROM hed__Program_Enrollment__c WHERE Id = :enrollmentId];
        String urlString = NES_QuestionsHelper.grabNextURL(enrollmentId, sectionComponentId, programEnrollment.hed__Contact__r.Name, processComponentId, programEnrollment.Program_Grade_Level__r.Grade_Level__r.Name, programEnrollment.hed__Contact__c, false);
        peakResponse.success = true;
        peakResponse.messages.add(urlString);
        return peakResponse;
    }    
    // #US108687 (Ali Khan)
   
    //Save one answer and analyze current assignment
    @AuraEnabled
    public static List<NES_EvaluateUtil.Question> evaluateQuestion(Id enrollmentId, String questions, Id sectionComponentId, Id processId) {
        return NES_QuestionsHelper.getRelatedQuestions2(enrollmentId, questions, sectionComponentId, true);
    }

    @AuraEnabled
    public static List<Enrollment_Component__c> getRelatedMessages(Id enrollmentComponentId, Id programEnrollmentId){
        return NES_EnrollmentHelper.getRelatedMessages(enrollmentComponentId, programEnrollmentId);
    }

    @AuraEnabled
    public static Id getSchoolId(Id enrollmentId) {
        return NES_QuestionsHelper.grabSchoolId(enrollmentId);
    }

    @AuraEnabled
    public static String getSectionName(Id sectionId){
        return NES_QuestionsHelper.getSectionName(sectionId);
    }

    @AuraEnabled
    public static String grabNameOfStudent(Id studentId, Id programEnrollmentId) {
        return NES_EnrollmentUtils.getStudentName(studentId, programEnrollmentId);
    }
    
    //Swapna:For GTM
    @AuraEnabled
    public static String getformName(Id sectionId){
        return NES_QuestionsHelper.getformName(sectionId);
    }
    
}