force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <description>The enrollment component that is the parent in the relationship being defined.</description>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_RelationShipUtils.cls
/**
 * Created by ajith on 05/12/18.
 */

public with sharing class NES_RelationShipUtils {

    public static ECDataList getRelatedECInfo(List<Id> childEcIds, Id parentRecTypId){
        ECDataList wrapper = new ECDataList();
        wrapper.parentECIds = new List<Id>();
        wrapper.enrollmentComponentDataSet = new Set<EnrollmentComponentData>();

        Set<EnrollmentComponentData> tempDataSet = new Set<EnrollmentComponentData>();
        for(Enrollment_Component_Relationship__c rel : [SELECT Id, Parent_Enrollment_Component__c, Parent_Enrollment_Component__r.Name, Child_Enrollment_Component__c, Parent_Enrollment_Component__r.RecordTypeId
                                                               FROM Enrollment_Component_Relationship__c
                                                               WHERE Child_Enrollment_Component__c IN :childEcIds AND
                                                                     Parent_Enrollment_Component__r.RecordTypeId =:parentRecTypId]){
            wrapper.parentECIds.add(rel.Parent_Enrollment_Component__c);
            tempDataSet.add(new EnrollmentComponentData(rel.Parent_Enrollment_Component__c, rel.Parent_Enrollment_Component__r.Name));
        }
        if(tempDataSet.size() > 0) {
            wrapper.enrollmentComponentDataSet = tempDataSet;
        }

        return wrapper;
    }

    public static ECDataList getRelatedChildECInfo(List<Id> parentEcIds, Id childRecTypeId){
        ECDataList wrapper = new ECDataList();
        wrapper.childECIds = new List<Id>();
        wrapper.enrollmentComponentDataSet = new Set<EnrollmentComponentData>();

        Set<EnrollmentComponentData> tempDataSet = new Set<EnrollmentComponentData>();
        System.debug(parentEcIds);
        System.debug(childRecTypeId);
        List<Enrollment_Component_Relationship__c> relationships = [SELECT Id, Parent_Enrollment_Component__c, Parent_Enrollment_Component__r.Name, Child_Enrollment_Component__c, Child_Enrollment_Component__r.Name, Child_Enrollment_Component__r.RecordTypeId
                                                                    FROM Enrollment_Component_Relationship__c WHERE Parent_Enrollment_Component__c IN :parentEcIds AND Child_Enrollment_Component__r.RecordTypeId =:childRecTypeId];

        for(Enrollment_Component_Relationship__c rel : relationships ){
            wrapper.childECIds.add(rel.Child_Enrollment_Component__c);
            tempDataSet.add(new EnrollmentComponentData(rel.Child_Enrollment_Component__c, rel.Child_Enrollment_Component__r.Name));
        }
        if(tempDataSet.size() > 0)
            wrapper.enrollmentComponentDataSet = tempDataSet;
        return wrapper;
    }

    public class ECDataList{
        @AuraEnabled public Set<EnrollmentComponentData> enrollmentComponentDataSet {get; set;}
        @AuraEnabled public List<Id> parentECIds {get; set;}
        @AuraEnabled public List<Id> childECIds {get; set;}
    }

    public class EnrollmentComponentData{
        @AuraEnabled public  Id     ecId {get; set;}
        @AuraEnabled public  String ecName {get; set;}

        public EnrollmentComponentData(Id ecId, String ecName){
            this.ecId = ecId;
            this.ecName = ecName;
        }
    }

}