force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Assignment_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component is relevant to the program enrollment the evaluation was completed for and it would then be assigned to the PE through a Enrollment Component Affiliation. If there is no assignment logic defined on a component, it inherits it&apos;s assigment from its parent.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Assignment Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component has been completed by theprogram enrollment the evaluation was completed for and it would then be marked complete on the shared Enrollment Component Affiliation.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Completion Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Provides a way to systematically export and load Enrollment Components.  Unique.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ecNode.cls
/**
 *  @TODO: 
 *      1. rename to ecrNode 
 */
public class ecNode { // rename to ecrNode

    @AuraEnabled
    public Id parentId {get; private set;} // parent.ec.ID

    @AuraEnabled
    public Id nodeId {get; private set;} // ecr.ID

    @AuraEnabled
    public Id ecrId {get; private set;} // ecr.ID

    @AuraEnabled
    public Id ecId {get; private set;} // ec.ID

    @AuraEnabled
    public String ecrExtId {get; private set;} // externalID

    @AuraEnabled
    public String ecExtId {get; private set;} // externalID

    @AuraEnabled
    public String logicAssignment {get; private set;}

    @AuraEnabled
    public String logicCompletion {get; private set;}

    @AuraEnabled
    public List<ecNode> children {get; private set;}

    @AuraEnabled
    public String kind {get; private set;} // ec.rectype.Name

    @AuraEnabled
    public String name {get; private set;} // ec.ID

    @AuraEnabled
    public Integer order {get; private set;} // ecr.Order__c

    @AuraEnabled
    public Integer level {get; private set;}


    public ecNode(ecNode srcNode) {

        this.parentId = srcNode.parentId;
        this.nodeId = srcNode.nodeId;
        this.ecrId = srcNode.ecrId;
        this.ecId = srcNode.ecId;
        this.ecrExtId = srcNode.ecrExtId;
        this.ecExtId = srcNode.ecExtId;
        this.logicAssignment = srcNode.logicAssignment;
        this.logicCompletion = srcNode.logicCompletion;

        this.children = new List<ecNode>();

        this.kind = srcNode.kind;
        this.name = srcNode.name;
        this.order = srcNode.order;
        this.level = srcNode.level;

    }

    public ecNode(Enrollment_Component__c ec, Integer level) {

        this.nodeId = ec.Id;
        this.ecId = ec.Id;
        this.ecExtId = ec.External_Id__c;
        this.ecrId = ec.Id;
        this.ecrExtId = ec.External_Id__c;
        this.logicAssignment = ec.Assignment_Logic__c;
        this.logicCompletion = ec.Completion_Logic__c;

        this.children = new List<ecNode>();

        this.kind = ec.RecordType.Name;
        this.name = ec.name;
        this.level = level;

    }

    public ecNode(Enrollment_Component_Relationship__c ecr, Integer level) {

        this.nodeId = ecr.Id;
        this.ecrId = ecr.Id;
        this.ecId = ecr.Child_Enrollment_Component__c;
        this.ecrExtId = ecr.External_Id__c;
        this.ecExtId = ecr.Child_Enrollment_Component__r.External_Id__c;
        this.logicAssignment = ecr.Child_Enrollment_Component__r.Assignment_Logic__c;
        this.logicCompletion = ecr.Child_Enrollment_Component__r.Completion_Logic__c;
        
        this.children = new List<ecNode>();
        
        this.kind = ecr.Child_Enrollment_Component__r.RecordType.Name;
        this.name = ecr.Child_Enrollment_Component__r.Name;
        this.order = (Integer) ecr.Order__c;
        this.level = level;

    }


    public void setParent(Id parentNodeId) {
        this.parentId = parentNodeId;
    }


    public void addChildren(ecNode child) {
        addChildren(new List<ecNode>{child});
    }


    public void addChildren(List<ecNode> children) {

        for (ecNode child: children) {
            child.setParent(this.nodeId);
        }
        this.children.addAll(children);
        
    }


    public Map<Id, ecNode> getChildrenAsMap() { 

        Map<Id, ecNode> dataToECNodeMap = new Map<Id, ecNode>();
        for (ecNode child : this.children) {
            dataToECNodeMap.put(child.nodeId, child);
        }
        return dataToECNodeMap;

    }
    
}