force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Document</fullName>
        <active>true</active>
        <label>Document</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flag</fullName>
        <active>true</active>
        <label>Flag</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program the student is enrolled in.</description>
    <inlineHelpText>The program the student is enrolled in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ECA_HierarchyStatusUpdateWIP2.cls
public without sharing class ECA_HierarchyStatusUpdateWIP2 
{

    // Constants...
    public static final String VALID_ECA_STATUS = 'Stage, Document, Section, Flag, Form'; // Question

    public static Boolean shouldRunStatusUpdate = true;

    // class variables...
    private static ECA_HierarchyStatusUpdateWIP2 instance = null;
    private Map<Id, ecrProcessData> academicProgramData{ get; set; }
    // private static 	Map<Id, ecrProcessData> ecaData{ get; set; } // maybe introduce this later.


    private Map<Id, Id> mapPEToAcademicProgram { get; set; }
    private Map<Id, hed__Program_Enrollment__c> mapPEs { get; set; }
    private Map<Id, Enrollment_Component_Affiliation__c>  mapECAs { get; set; }
    private Map<Id, Map<Id, Id>> peToECToECAMap { get; set; }
    
    private Boolean initialized = false;
    private Boolean allNA { get; private set; }
    private Map<Id, Id> petoProcessECAId { get; set; }
    private Map<Id, Id> petoCurrentStage { get; set; }
    private Map<Id, Enrollment_Component_Affiliation__c> peLastStageMap { get; set; }
    private Map<Id, Enrollment_Component_Affiliation__c> transactionalECAs { get; set; }
    private Map<Id, Enrollment_Component_Affiliation__c> changedECAs { get; set; } //ECAs received for processing
    private Map<Id, Enrollment_Component_Affiliation__c> forUpdateECAs { get; set; } //ECAs Status__c to-be-updated 
    private List<sObject> sObjectsForUpdate { get; set; }

    // returns singleton instance...
    public static ECA_HierarchyStatusUpdateWIP2 getInstance() 
    {
        if (instance == null)
            instance = new ECA_HierarchyStatusUpdateWIP2();
        return instance;
    }

    // private constructor...
    private ECA_HierarchyStatusUpdateWIP2() 
    {
        this.allNA = true;
        this.petoProcessECAId = new Map<Id, Id>();
        this.peLastStageMap = new Map<Id, Enrollment_Component_Affiliation__c>();
        this.petoCurrentStage = new Map<Id, Id>();

        // NEW STUFF
        this.mapPEToAcademicProgram = new Map<Id, Id>();
        this.mapPEs = new Map<Id, hed__Program_Enrollment__c>();
        this.mapECAs = new Map<Id, Enrollment_Component_Affiliation__c>();
        this.peToECToECAMap = new Map<Id, Map<Id, Id>>();

        this.sObjectsForUpdate = new List<sObject>();
        this.forUpdateECAs = new Map<Id,Enrollment_Component_Affiliation__c>();
    }

    @TestVisible
    private Set<Id> peIDs 
    {   
        get {
            if (peIDs==null && transactionalECAs!=null) {
                peIDs = new Set<Id>();
                for (Enrollment_Component_Affiliation__c eca : transactionalECAs.values()) 
                    peIDs.add(eca.Program_Enrollment__c);
            }
            return peIDs;
        }

        set;
    }

    // kick-off here...
    public void initialize(Map<Id, Enrollment_Component_Affiliation__c> mapECAs)  // Transactional ECAs, EX: Trigger.newMap
    {
        
        if (!shouldRunStatusUpdate || this.initialized || mapECAs==null || mapECAs.size()==0)
            return;

        this.transactionalECAs = mapECAs;

        // build data maps/trees...
        this.initializeProgramEnrollmentData(); // gather PE/ECA related maps 
        // this.initializeAcademicProgramData(); // build AcademicProgram process trees

        this.initialized = true;
    }

    @TestVisible
    private void initializeProgramEnrollmentData() // Gather PE/ECA related maps
    {
        for (hed__Program_Enrollment__c pe : ECA_CriteriaEvaluatorHelper.getPEsWithECAs(peIDs))
        {
            mapPEs.put(pe.Id, pe); // pe map
            mapPEToAcademicProgram.put(pe.Id, pe.hed__Account__c);
            // peToECToECAMap.put(pe, null); // initialize it.
            for (Enrollment_Component_Affiliation__c eca : pe.Enrollment_Component_Affiliation__r)
            {
                mapECAs.put(eca.Id, eca); // eca Map

                Map<Id, Id> mapECToECAtmp = peToECToECAMap.get(pe.Id);
                if (mapECToECAtmp==null)
                    mapECToECAtmp = new Map<Id, Id>();
                mapECToECAtmp.put(eca.Enrollment_Component__c, eca.Id);
                peToECToECAMap.put(pe.Id, mapECToECAtmp); // option 1
                // peToECToECAMap.get(pe).put(mapECToECAtmp); // alternate option 2

                //capture the pe->processId
                if (eca.Enrollment_Component__r.RecordType.Name == 'Process')
                    petoProcessECAId.put(eca.Program_Enrollment__c, eca.Id);

                // map PE => Stage (Status=In Progress)
                if(eca.Enrollment_Component__r.RecordType.Name == 'Stage') 
                {
                    Enrollment_Component_Affiliation__c lastStage = peLastStageMap.get(eca.Program_Enrollment__c);
                    if (lastStage.Status__c!='Not Applicable' && (lastStage==null || lastStage.Order__c < eca.Order__c))
                        peLastStageMap.put(eca.Program_Enrollment__c, eca);
                
                    if(eca.Status__c == 'In Progress') 
                    {
                        petoCurrentStage.put(eca.Program_Enrollment__c, eca.Id);
                    }
                }
            }
        }
    }

    @Testvisible
    private void initializeAcademicProgramData() // Build AcademicProgra/Process Tree
    {   
        if (mapPEToAcademicProgram.values().size()==0)
            // throw an exception ? 
            return;
        
        ecrTreeGeneratorWIP apTreeGenerator = new ecrTreeGeneratorWIP(mapPEToAcademicProgram.values());
        apTreeGenerator.generate();
        this.academicProgramData = apTreeGenerator.getData();

    }

    private Map<Id, Opportunity> mapPEToOppty
    {
        get
        {
            if (mapPEToOppty==null) 
            {
                mapPEToOppty = new Map<Id, Opportunity>();
                for (Opportunity opp : ECA_CriteriaEvaluatorHelper.getOpptyByStudPEIds(peIDs))
                {
                    mapPEToOppty.put(opp.Program_Enrollment__c, opp);
                }
            }
            return mapPEToOppty;
        } 
        
        set;
    }

    public class ECAEvaluationException extends Exception {}



}