force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Answer_Target__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Defines the system location to store the answer to this question. e.g. Household_Income__c.Value__c</inlineHelpText>
        <label>Answer Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>If Form: Contains the referencing Label of the form from the CT perspective.
If Question: Contains the content preceding the input.</inlineHelpText>
        <label>Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>The data type of the question. Used exclusively for components of type Document.</description>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Date/Time</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Checkbox Group</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Address</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>School Search</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <description>The enrollment component that is the parent in the relationship being defined.</description>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_FormController.cls
/**
 * Created by ajith on 01/10/18.
 */

public with sharing class NES_FormController {

    /*public static Map<Id, Enrollment_Component__c> componentMap;

    //This method would list of enrollment Components records that student needs to see based the program he enrolled.
    public static List<Enrollment_Component__c> getComponentsByAffiliation(String programEnrollmentId){
        List<Enrollment_Component__c> enrollmentComponents = new List<Enrollment_Component__c>();
        List<Enrollment_Component_Affiliation__c> enrollmentComponentAffiliations = new List<Enrollment_Component_Affiliation__c>();
        List<String> componentsIds = new List<String>();
        for(Enrollment_Component_Affiliation__c affiliations : [SELECT Id, Enrollment_Component__c, Program_Enrollment__c
                                                                       FROM Enrollment_Component_Affiliation__c WHERE Program_Enrollment__c =: programEnrollmentId]){

            enrollmentComponentAffiliations.add(affiliations);
            componentsIds.add(affiliations.Enrollment_Component__c);
        }

        if(enrollmentComponentAffiliations.size() > 0){
            String allFields = NES_Utilities2.selectAllFields('Enrollment_Component__c');
            String queryString = ' SELECT ' + allFields + ' FROM Enrollment_Component__c WHERE Id IN :componentsIds ORDER BY Order__c ';
            enrollmentComponents = Database.query(queryString);
            componentMap = new map<Id,Enrollment_Component__c>(enrollmentComponents);
        }

        return enrollmentComponents;
    }

    @AuraEnabled
    public static NES_FormResponse getFormInformation(String programEnrollmentId){
        System.debug('programEnrollmentId'+programEnrollmentId);
        List<Enrollment_Component__c> enrollmentComponents = new List<Enrollment_Component__c>();
        List<Enrollment_Component_Affiliation__c> enrollmentComponentAffiliations = new List<Enrollment_Component_Affiliation__c>();
        List<String> componentsIds = new List<String>();
        for(Enrollment_Component_Affiliation__c affiliations : [SELECT Id, Enrollment_Component__c, Program_Enrollment__c
        FROM Enrollment_Component_Affiliation__c WHERE Program_Enrollment__c =: programEnrollmentId]){

            enrollmentComponentAffiliations.add(affiliations);
            componentsIds.add(affiliations.Enrollment_Component__c);
        }

        if(enrollmentComponentAffiliations.size() > 0){
            String allFields = NES_Utilities2.selectAllFields('Enrollment_Component__c');
            String queryString = ' SELECT ' + allFields + ' FROM Enrollment_Component__c WHERE Id IN :componentsIds ORDER BY Order__c ';
            enrollmentComponents = Database.query(queryString);
            componentMap = new map<Id,Enrollment_Component__c>(enrollmentComponents);
        }

        NES_FormResponse response = new NES_FormResponse();
        Set<Id> componentIds = componentMap.keySet();
        String relFields = NES_Utilities2.selectAllFields('Enrollment_Component_Relationship__c');
        String relQuery = ' SELECT ' + relFields + ' ,Parent_Enrollment_Component__r.Label__c, Parent_Enrollment_Component__r.Question_Type__c, Child_Enrollment_Component__r.Label__c, Child_Enrollment_Component__r.Type__c ';
        relQuery += ' FROM Enrollment_Component_Relationship__c WHERE Parent_Enrollment_Component__c IN :componentIds ORDER BY Order__c ';
        System.debug('relQuery'+relQuery);
        List<Enrollment_Component_Relationship__c> enrollmentComponentRelationshipsList = new List<Enrollment_Component_Relationship__c>();
        enrollmentComponentRelationshipsList = Database.query(relQuery);

        for(Enrollment_Component_Relationship__c rel : enrollmentComponentRelationshipsList){
          if(rel.Parent_Enrollment_Component__c != null){
              NES_FormDetail parentForm = new NES_FormDetail();
              parentForm.FieldLabel = rel.Parent_Enrollment_Component__r.Label__c;
              if(rel.Child_Enrollment_Component__c != null){
                  NES_FormDetail childForm = new NES_FormDetail();
                  childForm.FieldLabel = rel.Child_Enrollment_Component__r.Label__c;
                  if(rel.Child_Enrollment_Component__r.Question_Type__c != null){
                      childForm.FieldType = rel.Child_Enrollment_Component__r.Question_Type__c;
                  }
                  parentForm.SubFormDetails.add(childForm);
              }
              response.detail.add(parentForm);
          }
        }
        return response;
    }

    public static void saveFormInformation(String enrollmentId, String response){
        String targetObj;
        String targetField;
        Enrollment_Component__c cmp = [SELECT Id, Type__c, Answer_Target__c FROM Enrollment_Component__c WHERE Id =:enrollmentId ];
        if(String.isNotBlank(response) && String.isNotBlank(cmp.Answer_Target__c)){
            String[] answer = cmp.Answer_Target__c.split('\\.');
            targetObj = answer[0];
            targetField = answer[1];
            sObject sObj = Schema.getGlobalDescribe().get(targetObj).newSObject();
            sObj.put(targetField,response);
            insert sObj;
        }
    }

//    @AuraEnabled
//    public static Pearson_FormResponse getFormInformation() {
//        Pearson_FormResponse peakResponse = new Pearson_FormResponse();
//        try {
//            String allFields = Pearson_Utilities.selectAllFields('Enrollment_Component__c');
//            String formQuery = 'SELECT ' + allFields +  ', (SELECT ' + allFields + ' FROM SubForm_Components__r ORDER BY Order__c) FROM ' +
//                    'Form_Component__c ORDER BY Order__c';
//
//            List<Enrollment_Component__c> whyList = new List<Enrollment_Component__c>();
//            whyList = Database.query(formQuery);
//
//            componentMap = new Map<Id, Enrollment_Component__c>(whyList);
//
//            for (Enrollment_Component__c formComponent : componentMap.values()) {
//                if (formComponent.Enrollment_Component__c == null) {
//                    Dev_FormDetail headerDetail = new Dev_FormDetail();
//                    headerDetail.FieldLabel = formComponent.Label__c;
//                    for (Form_Component__c subComponent : formComponent.SubForm_Components__r) {
//                        Dev_FormDetail detail = new Dev_FormDetail();
//                        detail.FieldLabel = subComponent.Label__c;
//                        if (subComponent.Type__c != null) {
//                            detail.FieldType = subComponent.Type__c;
//                        }
//                        if (subComponent.Values__c != null) {
//                            detail.SelectionOptions = subComponent.Values__c.split(';');
//                        }
//                        if(subComponent.Rule_Applies__c == TRUE){
//
//                        }
//                        if (!componentMap.get(subComponent.Id).SubForm_Components__r.isEmpty()) {
//                            detail.SubFormDetails = getLevel2Details(componentMap.get(subComponent.Id).SubForm_Components__r);
//                        }
//                        headerDetail.SubFormDetails.add(detail);
//                    }
//
//                    peakResponse.detail.add(headerDetail);
//                }
//            }
//
//        } catch (Exception e) {
//            peakResponse.success = false;
//            peakResponse.messages.add(e.getMessage());
//        }
//
//        return peakResponse;
//    }
//
//
//    public static List<Pearson_FormDetail> getLevel2Details(List<Enrollment_Component__c> formComponents) {
//        List<Pearson_FormDetail> level2 = new List<Pearson_FormDetail>();
//        for (Enrollment_Component__c subComponent : formComponents) {
//            Pearson_FormDetail detail = new Pearson_FormDetail();
//            detail.FieldLabel = subComponent.Label__c;
//            if (subComponent.Type__c != null) {
//                detail.FieldType = subComponent.Type__c;
//            }
//            if (subComponent.Values__c != null) {
//                detail.SelectionOptions = subComponent.Values__c.split(';');
//            }
//            if (!componentMap.get(subComponent.Id).SubForm_Components__r.isEmpty()) {
//                detail.SubFormDetails = getLevel3Details(componentMap.get(subComponent.Id).SubForm_Components__r);
//            }
//            level2.add(detail);
//        }
//
//        return level2;
//    }
//
//    public static List<Pearson_FormDetail> getLevel3Details(List<Enrollment_Component__c> formComponents) {
//        List<Pearson_FormDetail> level3 = new List<Pearson_FormDetail>();
//        for (Enrollment_Component__c subComponent : formComponents) {
//            Pearson_FormDetail detail = new Pearson_FormDetail();
//            detail.FieldLabel = subComponent.Label__c;
//            if (subComponent.Type__c != null) {
//                detail.FieldType = subComponent.Type__c;
//            }
//            if (subComponent.Values__c != null) {
//                detail.SelectionOptions = subComponent.Values__c.split(';');
//            }
//            level3.add(detail);
//        }
//
//        return level3;
//    }*/


}