force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Not Complete</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Flag</fullName>
        <active>true</active>
        <label>Flag</label>
    </recordTypes>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Enrollment_Component__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only Applicable to &quot;Form&quot; type Enrollment Components.  All children are derived.</inlineHelpText>
    <label>Enrollment Component</label>
    <referenceTo>Enrollment_Component__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Enrollment Component Affiliation</relationshipLabel>
    <relationshipName>Enrollment_Component_Affiliation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record for the student.</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollments (Program Enrollment)</relationshipLabel>
    <relationshipName>Program_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Time Expired</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Migration In Progress</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NES_Batch_FinalConfirmationNA.cls
/**
* Created by Krishna Peddanagammol on 4/14/20.
* Created for the task #167744.
*/

global with sharing class NES_Batch_FinalConfirmationNA  implements DataBase.Batchable<SObject>, Schedulable {
    private static Peak_ApexLog logger = new Peak_ApexLog('UpdateHardStopTimeConstraint');
    global NES_Batch_FinalConfirmationNA() {
        
    }
    
    // Find all the current in progress program enrollments
    global List<SObject> start(Database.BatchableContext BC){
        
        List<hed__Program_Enrollment__c> programEnrollments = [SELECT Id FROM hed__Program_Enrollment__c WHERE Status__c = 'In Progress' AND RecordType.Name = 'Student' AND V2_External_ID__c = null];
        return programEnrollments;
    }
    
    // Fetch the corresponding ECA's in Confirmation of Enrollment or Intent to Attend (CalCA) stage's
    // and mark the ECA's of EC's with Confirmation of Enrollment form and
    // Confirmation of Enrollment Notice or Intent to Attend Notice section as NA
    // and update the Confirmation Hold flag to released. 
    global void execute(Database.BatchableContext BC, List<SObject> scope) {
       
        Set<Id> programEnrollmentIds = new Set<Id>();
        for(hed__Program_Enrollment__c pe : (List<hed__Program_Enrollment__c>) scope) {
            programEnrollmentIds.add(pe.Id);
        }
      
        // Update ECA's for Confirmation of Enrollment form and 
        // Confirmation of Enrollment Notice or Intent to Attend Notice section to NA
        List<Enrollment_Component_Affiliation__c> ecas = new List<Enrollment_Component_Affiliation__c> ();
        List<Id> ids = new List<Id> ();  
        //Commented for US 216464
        /*for (Enrollment_Component_Affiliation__c affiliation : 
             [SELECT Id
              FROM Enrollment_Component_Affiliation__c
              WHERE Program_Enrollment__c in :programEnrollmentIds AND 
              ( (Enrollment_Component__r.RecordType.Name = 'Section' AND Enrollment_Component__r.Name = 'Confirmation of Enrollment Notice')
               OR (Enrollment_Component__r.RecordType.Name = 'Section' AND Enrollment_Component__r.Name = 'Intent to Attend Notice')
               OR (Enrollment_Component__r.RecordType.Name = 'Section' AND Enrollment_Component__r.Name = 'Final Confirmation') )
             ]) 
        {
            //affiliation.Status__c = 'Not Applicable';
            Enrollment_Component_Affiliation__c n = new Enrollment_Component_Affiliation__c(id = affiliation.id, Status__c = 'Not Applicable' );
            ecas.add(n);
        }*/
        //Updated for US #216464 for first set of updates (Test date: 29-Sep-2020) 
        for (Enrollment_Component_Affiliation__c affiliation : 
             [SELECT Id
              FROM Enrollment_Component_Affiliation__c
              WHERE Program_Enrollment__c in :programEnrollmentIds AND 
              ( (Enrollment_Component__r.RecordType.Name = 'Section' AND Enrollment_Component__r.Name = 'Alternative Shipping Address Information')
               OR (Enrollment_Component__r.RecordType.Name = 'Section' AND Enrollment_Component__r.Name = 'Parent/Legal Guardian (Caretaker) Acknowledgement')
               OR (Enrollment_Component__r.RecordType.Name = 'Section' AND Enrollment_Component__r.Name = 'Parent / Legal Guardian (Caretaker) Acknowledgement') )
             ]) 
        {
            //affiliation.Status__c = 'Not Applicable';
            Enrollment_Component_Affiliation__c n = new Enrollment_Component_Affiliation__c(id = affiliation.id, Status__c = 'Not Applicable' );
            ecas.add(n);
        }
        /*//Updated for US #216464 for first set of updates (Test date: 05-Oct-2020) 
        for (Enrollment_Component_Affiliation__c affiliation : 
             [SELECT Id
              FROM Enrollment_Component_Affiliation__c
              WHERE Program_Enrollment__c in :programEnrollmentIds AND 
              ( (Enrollment_Component__r.RecordType.Name = 'Section' AND Enrollment_Component__r.Name = 'Confirmation of Enrollment Notice for Spring Semester')
               OR (Enrollment_Component__r.RecordType.Name = 'Section' AND Enrollment_Component__r.Name = 'Intent to Attend Notice for Spring Semester') )
             ]) 
        {
            //affiliation.Status__c = 'Not Applicable';
            Enrollment_Component_Affiliation__c n = new Enrollment_Component_Affiliation__c(id = affiliation.id, Status__c = 'Not Applicable' );
            ecas.add(n);
        }*/
        try {
            Database.update(ecas);
        } catch (exception e) {
            System.debug('Dml Exception ::' + e.getMessage());
            logger.logException('execute', e);
            logger.saveLogs();
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new NES_Batch_FinalConfirmationNA(), 200);
    }
    
}