force-app/main/default/objects/Enrollment_Component__c.object
<CustomObject>
    <description>Every part of a form input, all the way down to a question or field.</description>
    <fields>
        <fullName>Assignment_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component is relevant to the program enrollment the evaluation was completed for and it would then be assigned to the PE through a Enrollment Component Affiliation. If there is no assignment logic defined on a component, it inherits it&apos;s assigment from its parent.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Assignment Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Logic__c</fullName>
        <description>Logic for evaluation of the component&apos;s associated criteria groups against each other. If the logic evaluates to true, it indicates that the component has been completed by theprogram enrollment the evaluation was completed for and it would then be marked complete on the shared Enrollment Component Affiliation.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please do not enclose the entire expression in parentheses.</inlineHelpText>
        <label>Completion Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Determines whether a particular Enrollment Component is required.</inlineHelpText>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcessTree__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ProcessTree</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Enrollment Component</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Components</pluralLabel>
    <recordTypes>
        <fullName>Form</fullName>
        <active>true</active>
        <label>Form</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <label>Section</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stage</fullName>
        <active>true</active>
        <label>Stage</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Child_Enrollment_Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The enrollment component that is the child in the relationship being defined.</description>
        <label>Child Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Parent Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order of the child component within the parent.</description>
        <inlineHelpText>Order of the subcomponent on the parent component.</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Enrollment_Component__c</fullName>
        <description>The enrollment component that is the parent in the relationship being defined.</description>
        <label>Parent Enrollment Component</label>
        <referenceTo>Enrollment_Component__c</referenceTo>
        <relationshipLabel>Child Enrollment Components</relationshipLabel>
        <relationshipName>Enrollment_Component_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Component Relationship</label>
    <nameField>
        <displayFormat>ECR-{0}</displayFormat>
        <label>Enrollment Component Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/academicProgram.cls
global class academicProgram {

    /**
     * * 	@ALIKM 20/apr/2020- commenting out changes
     * ## NOTES ##
     * 
     * @todo [2/Apr/2020]
     *  -> Add Criteria Records
     *  -> Class needs to: 
*          -> Parse
*          -> Handle treeRefresh via button  / Button to kick-off
*          -> Return data in different formats
*              Ex:  a. Builder Data format
                    b. Raw
                    c. Search for an item in the tree & return path
                    d. 

*          -> toggle CustomSetting OR MDT
           -> See if we can plugin Ct/Student info to the tree
        Status Update 3/Apr: 
            Writing the processTree Parser (In-progress)
            code optimization & recursion (Not started)
            output builder data format (Not started)
            test serialization/deserialization of the complete processTree w/Process >> Stages >> Forms >> Sections >> QuestionGroups >> Questions (Not started)
            button callable code (Not started)
            test classes for the whole lot (Not started)
        ECA
        ||
        EC (ProcessID)
            \
             \ @TBD: New object w/lookup to Process.EC record. 
             This holds the json for each Stage (OR complete Process depending on the size)
             rec1: Stage-1 
             rec2: Stage-2
             rec3: Stage-3
             rec4: Stage-4

        Existing Structure
            \ 
            Process
            Stage
                Forms
                Sections
                    QuestionGroup
                    Questions
                    Messages
                    Hidden
                documents
        
        // public class acaPgm {

            //     String Name; // academicProgram Name
            //     Enrollment_Component__c process;
            //     Process -> Stages Map;
            //     Stages -> Forms Map;
            //     Forms -> Sections Map;
            //     Sections -> QuestionGroup
            //     QuestionGroup -> Questions
            //     QuestionParents -> QuestionGroup + Sections
            //      allIds
            //     ec.ID => EC.recs

        // }


    
    // Tree
    public class node {

        public id parent {get; private set;}
        public String kind {get; private set;} 
        public Enrollment_Component__c ec {get; private set;} // data
        public List<node> children {get; private set;}
        // kind ? 

        public node(Enrollment_Component__c ec) {
            this.ec = ec;
            this.children = new List<node>();
        }

        public void setParent(Id ecId) {
            this.parent = ecId;
        }

        public void addChild(node child) {
            child.setParent(this.ec.Id);
            children.add(child);
        }

        public void addChildren(List<node> children) {
            for (node child: children) {
                child.setParent(this.ec.Id);
            }
            children.addAll(children);
        }

        public Map<Id, node> getChildrenAsMap() { 
            Map<Id, node> dataToNodeMap = new Map<Id, node>();
            for (node child : this.children) {
                dataToNodeMap.put(child.ec.Id, child);
            }
            return dataToNodeMap;
        }
    }

    global enum Componentkind {
        Process,
        Stage,
        Form,
        Section,
        QuestionGroup,
        Question        
    }


    // // global class parserProcessTree {

        public static Set<Id> nodeParser (node nd, Set<Id> visitedIds) { // bfs => level Order; dfs => pre-order

            // start with the root node
            System.debug(JSON.serialize(nd));
            visitedIds.add(nd.ec.Id);

            Map<Id, node> children = nd.getChildrenAsMap();

            if (children.size()==0)
                return visitedIds;
            
            for (Id idx : children.keySet()) {
                visitedIds.addAll(nodeParser(children.get(idx), visitedIds));
            }
            return visitedIds;
        }
    
    // // }
    // academicProgram.printTree();
    public static void printTree() {

        Enrollment_Component__c acaPgmEC = [Select Id, ProcessTree__c, 
            Name from Enrollment_Component__c where id = 'a0f0n000001VAoJAAW'];
        node importProgramTree = importProcessTree(acaPgmEC.ProcessTree__c);
        Set<Id> visitedNodes = nodeParser(importProgramTree, new Set<Id>());
        System.debug('::visitedIds::count>>' + visitedNodes.size() + '>>nodes>>' + visitedNodes);

    }



    // global class Parser {

    //     private node _payload; 


    //     public Parser(node payload) {
    //         _payload = payload;
    //     }




        
    // }
    

    // query records: 
    public static List<Enrollment_Component_Relationship__c> queryECRs(Set<Id> parentIDs) {       
        return [SELECT  Id, Order__c, 
                        Parent_Enrollment_Component__c,
                        Child_Enrollment_Component__c, 
                        Child_Enrollment_Component__r.Id, 
                        Child_Enrollment_Component__r.Name, 
                        Child_Enrollment_Component__r.Assignment_Logic__c,  
                        Child_Enrollment_Component__r.RecordTypeId,
                        Child_Enrollment_Component__r.RecordType.Name, 
                        Parent_Enrollment_Component__r.Id, 
                        Parent_Enrollment_Component__r.Name, 
                        Parent_Enrollment_Component__r.Completion_Logic__c, 
                        Child_Enrollment_Component__r.Completion_Logic__c,
                        Child_Enrollment_Component__r.Is_Required__c
                FROM    Enrollment_Component_Relationship__c
                WHERE   Parent_Enrollment_Component__c =: parentIDs
                //AND   Child_Enrollment_Component__r.RecordType.Name = : NES_DashboardUtilities.STAGE_RT 
                ORDER BY Order__c ASC];
    }


    // move the children up to Parent for the next iteration...
    public static Map<Id, node> getChildrenAsParent(Map<Id, node> parentNodes) { 
        Map<Id, node> parentNodeMapTmp = new Map<Id, node>();
        for (String id : parentNodes.keySet()) {
            parentNodeMapTmp.putAll(parentNodes.get(id).getChildrenAsMap());
        }
        return parentNodeMapTmp;
    }

    /**
     * @Usage: 
        academicProgram.createProcessTree('a0f0n000001IAQ2AAO');
        @todo: Make this recursive.

    public static void createProcessTree(String processID) {
        
        // process head >>> start flow
        Enrollment_Component__c processEC = new Enrollment_Component__c(id=processID);
        node root = new node(processEC);
        // root.setParent(null);

        // Stages
        // query stages...
        for (Enrollment_Component_Relationship__c ecr : queryECRs(new Set<Id>{processEC.Id})) {
            root.addChild(new node(
                new Enrollment_Component__c( 
                    id = ecr.Child_Enrollment_Component__c, 
                    Name = ecr.Child_Enrollment_Component__r.Name,
                    Description__c = ecr.Child_Enrollment_Component__r.RecordType.Name + '::' + ecr.Order__c,
                    Assignment_Logic__c = ecr.Child_Enrollment_Component__r.Assignment_Logic__c, 
                    Completion_Logic__c = ecr.Child_Enrollment_Component__r.Completion_Logic__c,
                    RecordTypeId = ecr.Child_Enrollment_Component__r.RecordTypeId
                )) // collect the parents here...
            );
            // System.debug(':: inbetween adding children to root >>> root ::' + JSON.serialize(root));
        }

        node tmpRoot = root;
        System.debug(':: inbetween stages >>> root ::' + JSON.serialize(root));

        // Build / LevelDown / ParentNodeMap
        Map<Id, node> parentNodes = new Map<Id, node>();
        parentNodes.put(root.ec.Id, root);
        parentNodes = getChildrenAsParent(parentNodes); // new parent nodes...
        System.debug(':: after stages >>> root ::' + JSON.serialize(root));
        System.debug(':: after stages >>> parentNodes ::' + JSON.serialize(parentNodes));
        // Stages end...
        

        // Forms
        // query Forms... w/parentNodeMap.keySet()
        for (Enrollment_Component_Relationship__c ecr : queryECRs(parentNodes.keySet())) {
            // create a childNode
            node tmpNode = new node(
                new Enrollment_Component__c(
                    id = ecr.Child_Enrollment_Component__c, 
                    Name = ecr.Child_Enrollment_Component__r.Name,
                    Description__c = ecr.Child_Enrollment_Component__r.RecordType.Name + '::' + ecr.Order__c,
                    Assignment_Logic__c = ecr.Child_Enrollment_Component__r.Assignment_Logic__c, 
                    Completion_Logic__c = ecr.Child_Enrollment_Component__r.Completion_Logic__c,
                    RecordTypeId = ecr.Child_Enrollment_Component__r.RecordTypeId
                ));
            // add to the parent
            parentNodes.get(ecr.Parent_Enrollment_Component__c).addChild(tmpNode);
        }
        // #2 alternatively, collect all childrent with same parent & the exit loop.
        // #2 now add to the parent after collecting parent -> childrentMap
        // parentMap.get(child.parentId).addChildren(children)

        // Build / LevelDown / ParentNodeMap
        parentNodes = getChildrenAsParent(parentNodes); // new parent nodes...
        System.debug(':: after Forms >>> root ::' + JSON.serialize(root));
        System.debug(':: after Forms >>> parentNodes ::' + JSON.serialize(parentNodes));
        // Forms end...

        // commit to a new EC record.
        // commitProcessTree(JSON.serialize(root));

        // Sections...
        // query sections... w/parentNodeMap.keySet()
    }

    public static void commitProcessTree(String acaPgmTree) {
        Enrollment_Component__c ecNew 
                = new Enrollment_Component__c(Name = 'AcademicProgramTree', ProcessTree__c = acaPgmTree);
        insert ecNew;
        System.debug('newEC::' + JSON.serialize(ecNew));      
    }

    public static node importProcessTree(String payload) {
        node pak; 
        try {        
            pak = (node)JSON.deserializeStrict(payload, academicProgram.node.class);
        } 
        catch (Exception ex) {
            system.debug(ex.getMessage());
            throw new ProcessTreeImportException('acaPgmImport:importProcessTree: Unable to parse payload.');
        }
        return pak;
    }

    // // Parser 
    //     Map<Kind ==> KindRecords>
    //     Stage => Stage
    //     Forms => Forms
    //     map.get(stages) > 

    public static void testImport() {
        Enrollment_Component__c acaPgmEC = [Select Id, ProcessTree__c, 
            Name from Enrollment_Component__c where id = 'a0f0n000001VAoJAAW'];
        node importProgramTree = importProcessTree(acaPgmEC.ProcessTree__c);
        System.debug(JSON.serialize(importProgramTree));
    }

    public static void testJSONParser() {

        Enrollment_Component__c acaPgmEC = [Select Id, ProcessTree__c, 
            Name from Enrollment_Component__c where id = 'a0f0n000001VAoJAAW'];

        node importProgramTree = importProcessTree(acaPgmEC.ProcessTree__c);

        JSONParser parser = JSON.createParser(acaPgmEC.ProcessTree__c);
        while (parser.nextToken() != null) {

            System.debug(parser.getText());
            parser.nextToken();

            // if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && 
            //     (parser.getText() == 'totalPrice')) {
            //     // Get the value.
            //     parser.nextToken();
            //     // Compute the grand total price for all invoices.
            //     grandTotal += parser.getDoubleValue();
        }
    } 

    public static void testJSONParserWIP() {

        Enrollment_Component__c acaPgmEC = [Select Id, ProcessTree__c, 
            Name from Enrollment_Component__c where id = 'a0f0n000001VAoJAAW'];

        node importProgramTree = importProcessTree(acaPgmEC.ProcessTree__c);

        JSONParser parser = JSON.createParser(acaPgmEC.ProcessTree__c);
        while (parser.nextToken() != null) {

            if (parser.getText().containsIgnoreCase('Stage')) {
                System.debug('::stage token::' + parser.getText());
                parser.nextToken();
                System.debug('::nxtToken for Stage::' + parser.getText());
            }

            // if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && 
            //     (parser.getText() == 'totalPrice')) {
            //     // Get the value.
            //     parser.nextToken();
            //     // Compute the grand total price for all invoices.
            //     grandTotal += parser.getDoubleValue();
        }
    }

    public class ProcessTreeImportException extends Exception {}

*/
}



/**
 * @todo: 
 *  a. parse the Tree
 *  b. Add Recursive bit inside
 * 
 */