force-app/main/default/objects/Enrollment_Document__c.object
<CustomObject>
    <description>The Enrollment Document Upload object stores the data and properties of documents that have been submitted to support the student’s enrollment in the Academic Program.</description>
    <label>Enrollment Document</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Document__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Document_Status_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Document type identifier</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_FieldDescribeUtilTest.cls
/**

    * Created by ali.khan (Ness Tech) on 10/18/19.
    * Test class covers following code coverage: 
        - HL_FieldDescribeUtil.cls
        - PopulatePicklist.cls
        - NES_FBBFetchDependentPicklist.cls

*/

@isTest
public with sharing class HL_FieldDescribeUtilTest {


    public static String sObjectAPIName = 'Enrollment_Document__c';
    public static String ctrlField = 'Type__c';
    public static String theField = 'Status_Reason__c';
    public static String ctrlFieldPicklistValue = 'Proof of Residence'; // '504 Plan'; // 'Evaluation';


    // Test fetching of dependent picklist values from PopulatePicklist
	@isTest
	public static void testFetchPicklistByControllingFieldValue_PopulatePicklist() {

        
        List<Map<String, String>> dependentPicklistOptions;
        Exception err;


        Test.startTest();
        try {

                dependentPicklistOptions = 
                    PopulatePicklist.getDependentPicklistValues(sObjectAPIName, theField, ctrlField, ctrlFieldPicklistValue);

        } catch (Exception e) {

            err = e;

        }
        Test.stopTest();

        system.assertNotEquals(null, dependentPicklistOptions, 'dependentPicklistOptions is null!');
        system.assertEquals(null, err, 'exceptions!');


	}

    // Test fetching of dependent picklist by value from NES_FBBFetchDependentPicklist
	@isTest
	public static void testFetchDependentPicklist_NES_FBBFetchDependentPicklist() {

        
        Map<String, String> dependentPicklistByControllingFieldValue;
        Exception err;


        Test.startTest();
        try {
            
            NES_FBBFetchDependentPicklist.DependentPickDefinition 
                dpld = new NES_FBBFetchDependentPicklist.DependentPickDefinition(sObjectAPIName, theField, ctrlField, ctrlFieldPicklistValue);

            dependentPicklistByControllingFieldValue = NES_FBBFetchDependentPicklist.getDependentOptions(dpld);

        } catch (Exception e) {

            err = e;

        }
        Test.stopTest();

        system.assertNotEquals(null, dependentPicklistByControllingFieldValue, 'dependentPicklistByControllingFieldValue is null!');
        system.assertEquals(null, err, 'exceptions!');


	}

    // Test fetching of dependent picklist values from HL_FieldDescribeUtil
	@isTest
	public static void test_HL_FieldDescribeUtil_fetchDependentPicklist() {

        // String sObjectAPIName = 'Enrollment_Document__c';
        // String ctrlField = 'Type__c';
        // String theField = 'Status_Reason__c';

        Map<String, Map<String, String>> dependentPicklistsMap;

        Exception err;
        Test.startTest();
        try {
            dependentPicklistsMap = HL_FieldDescribeUtil.getDependentOptions(sObjectAPIName, ctrlField, theField);
        } catch (Exception e) {
            err = e;
        }
        Test.stopTest();

        system.assertNotEquals(null, dependentPicklistsMap, 'dependentPicklistsMap is null!');
        system.assertEquals(null, err, 'exceptions!');

	}


}