force-app/main/default/objects/Enrollment_Component_Affiliation__c.object
<CustomObject>
    <label>Enrollment Component Affiliation</label>
    <nameField>
        <displayFormat>ECA-{0}</displayFormat>
        <label>Enrollment Component Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Component Affiliation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment_Component_Affiliation__c/fields/EC_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>EC_Record_Type__c</fullName>
    <description>Initially added to calculate the % complete on the PR</description>
    <label>EC Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Question Group</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Form</fullName>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Flag</fullName>
            </value>
            <value>
                <fullName>Message</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Initial_ECA_Creation_Complete__c.field-meta.xml
<CustomField>
    <fullName>Initial_ECA_Creation_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by the new student creation process to allow the creation of all the ECAs to be async.  When the Caretaker creates the student this will be false.  An async job that creates the ECAs will mark check this when it completes.</description>
    <label>Initial ECA Creation Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NES_ECAEvaluationQueueable.cls
public without sharing class NES_ECAEvaluationQueueable implements Queueable 
{
	@testVisible
    private static Boolean doChainJob = true;
    Public Set<Enrollment_Component_Affiliation__c> newAffiliations =new Set<Enrollment_Component_Affiliation__c>();
    private Id programEnrollmentId;
  
    /*public NES_ECAEvaluationQueueable(Set<Enrollment_Component_Affiliation__c> newAffiliations,Id enrollmentId) {
       this.newAffiliations = newAffiliations;
       this.programEnrollmentId = enrollmentId;
    }*/
    public void execute(QueueableContext context) {
	
        Peak_ApexLog logger = new Peak_ApexLog('ECAEvaluationQueueable');
        logger.logInfo('NES_ECAEvaluationQueueable', 'new affiliations: ' + newAffiliations);

        logger.saveLogs();


        //Mark Membrino 7/16/2020 Order the insert of the affiliations so:
        //  Questions, Messages and Text goes in first.
        //  Sections and Documents second
        //  Forms and Flags third
        //  Stages last.  This was added to prevent forms from being completed early because their children were not interted first.
        List<Enrollment_Component_Affiliation__c> group1 = new List<Enrollment_Component_Affiliation__c>();
        List<Enrollment_Component_Affiliation__c> group2 = new List<Enrollment_Component_Affiliation__c>();
        List<Enrollment_Component_Affiliation__c> group3 = new List<Enrollment_Component_Affiliation__c>();
        List<Enrollment_Component_Affiliation__c> group4 = new List<Enrollment_Component_Affiliation__c>();
        
        for (Enrollment_Component_Affiliation__c i : newAffiliations) {
            if (i.EC_Record_Type__c == NES_DashboardUtilities.QUESTION_RT || i.EC_Record_Type__c == NES_DashboardUtilities.TEXT_RT || i.EC_Record_Type__c == NES_DashboardUtilities.MESSAGE_RT)
                group1.add(i);
            else if (i.EC_Record_Type__c == NES_DashboardUtilities.SECTION_RT || i.EC_Record_Type__c == NES_DashboardUtilities.DOCUMENT_RT)
                group2.add(i);
            else if (i.EC_Record_Type__c == NES_DashboardUtilities.FORM_RT || i.EC_Record_Type__c == NES_DashboardUtilities.FLAG_RT)
                group3.add(i);
            else
                group4.add(i);
        }

        List<Enrollment_Component_Affiliation__c> affilsToInsert = new List<Enrollment_Component_Affiliation__c>();
        affilsToInsert.addAll(group1);
        affilsToInsert.addAll(group2);
        affilsToInsert.addAll(group3);
        affilsToInsert.addAll(group4);

        insert affilsToInsert;
        
        //Mark the PE as ready to be shown to the caretaker in the community.
        hed__Program_Enrollment__c pe = new hed__Program_Enrollment__c (id = programEnrollmentId, Initial_ECA_Creation_Complete__c = true);
        update pe;
        if(doChainJob) {
        
        System.enqueueJob(new NES_AddStudentCBLQueueable(programEnrollmentId));
        }
    }
    
}