force-app/main/default/objects/Health_and_Immunization__c.object
<CustomObject>
    <fields>
        <fullName>Immunization_Status_FollowUp__c</fullName>
        <label>Immunization Status FollowUp</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exemption</fullName>
                </value>
                <value>
                    <fullName>Extension Approved by Principal</fullName>
                </value>
                <value>
                    <fullName>Incomplete - Allow</fullName>
                </value>
                <value>
                    <fullName>Incomplete - Hold</fullName>
                </value>
                <value>
                    <fullName>Incomplete Exemption</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Medical Exemption</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>ORCA Exempt - VEC Required</fullName>
                </value>
                <value>
                    <fullName>ORCA Exempt - VEC Verified</fullName>
                </value>
                <value>
                    <fullName>Pending- IA Review</fullName>
                </value>
                <value>
                    <fullName>Personal Exemption</fullName>
                </value>
                <value>
                    <fullName>Religious Exemption</fullName>
                </value>
                <value>
                    <fullName>Review - Allow</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verified-In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Immunization_Status__c</fullName>
        <description>Enrollment Immunization Status</description>
        <label>Immunization Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exemption</fullName>
                </value>
                <value>
                    <fullName>Extension Approved by Principal</fullName>
                </value>
                <value>
                    <fullName>Incomplete - Allow</fullName>
                </value>
                <value>
                    <fullName>Incomplete - Hold</fullName>
                </value>
                <value>
                    <fullName>Incomplete Exemption</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Invalid Form</fullName>
                </value>
                <value>
                    <fullName>Medical Exemption</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Non-compliant Allow</fullName>
                </value>
                <value>
                    <fullName>ORCA Exempt - VEC Required</fullName>
                </value>
                <value>
                    <fullName>ORCA Exempt - VEC Verified</fullName>
                </value>
                <value>
                    <fullName>Pending- IA Review</fullName>
                </value>
                <value>
                    <fullName>Personal Exemption</fullName>
                </value>
                <value>
                    <fullName>Provisional Certificate Required</fullName>
                </value>
                <value>
                    <fullName>Religious Exemption</fullName>
                </value>
                <value>
                    <fullName>Review - Allow</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Verified-In Progress</fullName>
                </value>
                <value>
                    <fullName>MCK Liaison Waiver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Health and Immunization</label>
    <nameField>
        <displayFormat>HI-{0000}</displayFormat>
        <label>Health and Immunization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health and Immunizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NES_HealthAndImmunizationBusinessLogic.cls
/**
 * Created by Anushka on 11-12-2018.
 * Purpose : BusinessLogic class for HealthAndImmunizationTrigger called by HealthAndImmunizationHandler.
 */

public class NES_HealthAndImmunizationBusinessLogic {
  /**
   * Created by Anushka on 22-11-2018.
   * Purpose : This method updates the Immunization current Status on the Health and Immunization record.
   */
  public static void updateImmunizationStatusCurrent(Map < Id, Health_and_Immunization__c > newMap, Map < Id, Health_and_Immunization__c > oldMap) {
   system.debug('business logic - HNI');
   List < Health_and_Immunization__c > healthAndImmunizationList = new List < Health_and_Immunization__c > ();
   for (Health_and_Immunization__c hni: newMap.values()) {
    if (hni.Immunization_Status_FollowUp__c != oldMap.get(hni.Id).Immunization_Status_FollowUp__c ||
     hni.Immunization_Status__c != oldMap.get(hni.Id).Immunization_Status__c)
     healthAndImmunizationList.add(hni);
   }

   NES_BusinessLogicUtils.updateImmunizationStatusCurrent(healthAndImmunizationList);
   system.debug('list --' + NES_BusinessLogicUtils.updateImmunizationStatusCurrent(healthAndImmunizationList));
  }
}