force-app/main/default/objects/hed__Program_Enrollment__c.object
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed__Program_Enrollment__c/fields/Viewed_Final_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Viewed_Final_Confirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viewed Final Confirmation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NES_ApplicationSummary.cls
/**
 * Created by Ritvik on 30-10-2018.
 * Purpose : Functions for enrollment confirmation under specific program enrolled.
 */

public class NES_ApplicationSummary {

    @AuraEnabled
    public static void setFinalConfirmationViewed(hed__Program_Enrollment__c ProgramEnrollment){
           ProgramEnrollment.Viewed_Final_Confirmation__c = true;
           update ProgramEnrollment;
    }

    @AuraEnabled
    public static String getSuccessfulEnrollmentMessage(hed__Program_Enrollment__c ProgramEnrollment){
        return('Confirmed...');

    }
}