force-app/main/default/objects/Peak_Apex_Log__c.object
<CustomObject>
    <description>Apex Log is a framework to capture info, warnings, and errors in a configurable framework that does not require a user with “Customize Application” to view.  It allows for class-level, user-level, profile-level, and organization wide settings.</description>
    <fields>
        <fullName>Log_Level__c</fullName>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARNING</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Peak_Apex_Log_Persona_Manager__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Container for org-wide defaults, profile, and user-level overrides for custom logging</description>
    <fields>
        <fullName>Log_Level__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>1: ERROR =&gt; Only errors will be logged
2: WARNING =&gt; Warnings and errors will be logged
3: INFO =&gt; Everything will be logged</inlineHelpText>
        <label>Log Level</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Apex Log Persona Manager</label>
</CustomObject>

force-app/main/default/objects/Peak_Apex_Log_Retention_Manager__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Log retention</description>
    <fields>
        <fullName>Days_of_Logs_to_Keep__c</fullName>
        <defaultValue>30</defaultValue>
        <inlineHelpText>Logs from today minus this field in days will be purged</inlineHelpText>
        <label>Days of Logs to Keep</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduled_Job_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Scheduled Job Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Apex Log Retention Manager</label>
</CustomObject>

force-app/main/default/classes/Peak_ApexLogManagerTest.cls
/**
 * Created by raydehler on 2019-03-06.
 */
@isTest
private class Peak_ApexLogManagerTest {
    static testMethod void testSchedule() {
        Peak_ApexLogManager.schedule();
        System.assertNotEquals(null, Peak_Apex_Log_Retention_Manager__c.getInstance().Scheduled_Job_Id__c);
    }

    static testMethod void testScheduleWhenItExists() {
        Peak_ApexLogManager.schedule();
        Peak_ApexLogManager.schedule();
        System.assertNotEquals(null, Peak_Apex_Log_Retention_Manager__c.getInstance().Scheduled_Job_Id__c);
    }

    static testMethod void testScheduleWhenInvalidId() {
        Peak_Apex_Log_Retention_Manager__c palrm = Peak_Apex_Log_Retention_Manager__c.getInstance();
        palrm.Scheduled_Job_Id__c = 'xxxxxxxxxxxxxxx';
        upsert palrm;
        Peak_ApexLogManager.schedule();
        System.assertNotEquals(null, Peak_Apex_Log_Retention_Manager__c.getInstance().Scheduled_Job_Id__c);
    }

    static testMethod void testScheduleWhenValidIdButNotFound() {
        Peak_Apex_Log_Retention_Manager__c palrm = Peak_Apex_Log_Retention_Manager__c.getInstance();
        palrm.Scheduled_Job_Id__c = '001001001001001';
        upsert palrm;
        Peak_ApexLogManager.schedule();
        System.assertNotEquals(null, Peak_Apex_Log_Retention_Manager__c.getInstance().Scheduled_Job_Id__c);
    }


    static testMethod void testBatch() {
        Peak_Apex_Log_Persona_Manager__c palpm = Peak_Apex_Log_Persona_Manager__c.getInstance();
        palpm.Log_Level__c = 3; // Info
        upsert palpm;

        Peak_ApexLog logger = new Peak_ApexLog('Questions');
        logger.logInfo('methodName', 'message');
        logger.saveLogs();

        System.assertEquals(1, [select count() from Peak_Apex_Log__c]);

        Peak_Apex_Log_Retention_Manager__c palrm = Peak_Apex_Log_Retention_Manager__c.getInstance();
        palrm.Days_of_Logs_to_Keep__c = -1;
        upsert palrm;

        Test.startTest();
        Database.executeBatch(new Peak_ApexLogManager());
        Test.stopTest();

        System.assertEquals(0, [select count() from Peak_Apex_Log__c]);
    }
}