force-app/main/default/objects/Peak_Apex_Log__c.object
<CustomObject>
    <description>Apex Log is a framework to capture info, warnings, and errors in a configurable framework that does not require a user with “Customize Application” to view.  It allows for class-level, user-level, profile-level, and organization wide settings.</description>
    <fields>
        <fullName>Log_Level__c</fullName>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARNING</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Peak_Apex_Log_Persona_Manager__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Container for org-wide defaults, profile, and user-level overrides for custom logging</description>
    <fields>
        <fullName>Log_Level__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>1: ERROR =&gt; Only errors will be logged
2: WARNING =&gt; Warnings and errors will be logged
3: INFO =&gt; Everything will be logged</inlineHelpText>
        <label>Log Level</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Apex Log Persona Manager</label>
</CustomObject>

force-app/main/default/classes/Peak_ApexLogTest.cls
/**
 * Created by raydehler on 2019-03-06.
 */
@isTest
private class Peak_ApexLogTest {
    static testMethod void testApexLogManager() {

    }

    static testMethod void testApexLogNoManager() {
        Peak_ApexLog logger = new Peak_ApexLog('Not present');
        logger.logInfo('methodName', 'message');
        logger.logWarn('methodName', 'message');
        logger.logError('methodName', 'message');
        logger.logException('methodName', new Peak_ApexLog.Peak_ApexLogException('message'));
        logger.saveLogs();
        System.assertEquals(0, [select count() from Peak_Apex_Log__c]);
    }

    static testMethod void testApexLogNoPersona() {
        Peak_ApexLog logger = new Peak_ApexLog('Questions');
        logger.logInfo('methodName', 'message');
        logger.logWarn('methodName', 'message');
        logger.logError('methodName', 'message');
        logger.logException('methodName', new Peak_ApexLog.Peak_ApexLogException('message'));
        logger.saveLogs();
        System.assertEquals(0, [select count() from Peak_Apex_Log__c]);
    }


    static testMethod void testApexLogAll() {
        Peak_Apex_Log_Persona_Manager__c palpm = Peak_Apex_Log_Persona_Manager__c.getInstance();
        palpm.Log_Level__c = 3; // Info
        upsert palpm;

        Peak_ApexLog logger = new Peak_ApexLog('Questions');
        logger.logInfo('methodName', 'message');
        logger.logWarn('methodName', 'message');
        logger.logError('methodName', 'message');
        logger.logException('methodName', new Peak_ApexLog.Peak_ApexLogException('message'));
        logger.saveLogs();
        System.assertEquals(4, [select count() from Peak_Apex_Log__c]);
    }

    static testMethod void testApexLogErrors() {
        Peak_Apex_Log_Persona_Manager__c palpm = Peak_Apex_Log_Persona_Manager__c.getInstance();
        palpm.Log_Level__c = 1; // Error
        upsert palpm;

        Peak_ApexLog logger = new Peak_ApexLog('Questions');
        logger.logInfo('methodName', 'message');
        logger.logWarn('methodName', 'message');
        logger.logError('methodName', 'message');
        logger.logException('methodName', new Peak_ApexLog.Peak_ApexLogException('message'));
        logger.saveLogs();
        System.assertEquals(2, [select count() from Peak_Apex_Log__c]);
    }

}