force-app/main/default/objects/Records_Processing_Intervals__mdt.object
<CustomObject>
    <description>This is created for User Story No. 164369 (Pls don&apos;t delete). This MDT is for determining how earlier the records should be taken into consideration based on the days, hours, mins for processing. This is being used in determining the timestamp of the Program Enrollment/Relationship object records for the LC Community Access to School relevant Knowledge Articles based on Topics.</description>
    <fields>
        <fullName>Days__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Days that we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions.The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter a negative value say &quot;-1&quot; to pick records updated in the last 1 day&apos;s time. &quot;-2&quot; will imply records that were updated in the last 2 days time interval.</inlineHelpText>
        <label>Days</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Hours by which we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions. The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter the hours in negative values like &quot;-3&quot; to consider records that were updated in the last 3 hours accordingly. &quot;-6&quot; will imply records that were updated in the last 6 hours time interval.</inlineHelpText>
        <label>Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <description>User Story # 164369.
This field is for capturing the No. Of Mins by which we need to back track to pick records accordingly related to Program Enrollments and Relationships during the respective Batch Job executions. The value must be a negative value to be keyed in this field.</description>
        <inlineHelpText>Enter the Minutes in negative values like &quot;-30&quot; to consider records that were updated in the last 30 minutes accordingly. &quot;-40&quot; will imply records that were updated in the last 40 minutes time interval.</inlineHelpText>
        <label>Minutes</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Records Processing Intervals</label>
    <pluralLabel>Records Processing Intervals</pluralLabel>
</CustomObject>

force-app/main/default/classes/CS_AssignPermissionSetToCT_STDBatchJob.cls
/*
* Created by:  Sumanth B
* Created date: 2020-Apr-21
* User Story : 130549
* Purpose: This Batch Job handles the association of Student's School Permission Sets (SchoolName_CT & SchoolName_STD) 
           to existing Caretakers and Students Users based on Program Enrollment Status = Complete 

*
* Test Class:  CS_AssignPermissionSetToCT_STDBatchTest
* Change Log: 
*
*/
global class CS_AssignPermissionSetToCT_STDBatchJob implements Database.Batchable<sObject>
{
        global String CTProfileName = system.Label.NES_CS_CT_Profile;
        global String STDProfileName = system.Label.NES_CS_Std_Profile;
        global Database.QueryLocator start(Database.BatchableContext bc) {


             Records_Processing_Intervals__mdt recordProcessInterval = [SELECT Id, Days__c, Hours__c, Minutes__c FROM Records_Processing_Intervals__mdt WHERE DeveloperName = :CS_Constants.CTSTD_KBA_ACCESS_RECS_PROCESS];
             DateTime dateTimeInterval = system.now().addDays(Integer.valueOf(recordProcessInterval.Days__c)).addHours(Integer.valueOf(recordProcessInterval.Hours__c)).addMinutes(Integer.valueOf(recordProcessInterval.Minutes__c));
             String QueryString;
            if(Test.isRunningTest()){
            // QueryString = 'select id,ContactId,ProfileId,Profile.Name from User where (Profile.Name =\'' + CTProfileName + '\' OR Profile.Name =\'' + STDProfileName + '\') AND LastModifiedDate >=: dateTimeInterval  LIMIT 200';
               QueryString = 'select id,ContactId,ProfileId,Profile.Name from User where (Profile.Name =\'' + CTProfileName + '\' OR Profile.Name =\'' + STDProfileName + '\') AND LastModifiedDate >= TODAY LIMIT 100';
             System.debug('QueryString-->'+QueryString);
            }else{
             QueryString = 'select id,ContactId,ProfileId,Profile.Name from User where (Profile.Name =\'' + CTProfileName + '\' OR Profile.Name =\'' + STDProfileName + '\') AND LastModifiedDate >=: dateTimeInterval';
             System.debug('QueryString-->'+QueryString);
            }
             return Database.getQueryLocator(QueryString);
                
                
        }
        

        global void execute(Database.BatchableContext bc, List<User> UserRecs){

            Set<Id> ctIds = new Set<Id>();
            Set<Id> studentIds = new Set<Id>();
            for(User userRec : UserRecs){
                    if(userRec.Profile.Name == CTProfileName)
                        ctIds.add(userRec.ContactId);

                    else
                    if(userRec.Profile.Name == STDProfileName)
                        studentIds.add(userRec.ContactId);
            }

            system.debug('ctIds-->'+ctIds);
            system.debug('studentIds-->'+studentIds);
            if(ctIds.size() > 0 || studentIds.size() > 0)    
            {
                system.debug('Invoking Handler-->');
                CS_AssignPermissionSetToCT_STDHandler handlerObj = new CS_AssignPermissionSetToCT_STDHandler();
                 handlerObj.associatePermissionSets(ctIds,studentIds);
            }
        }

        global void finish(Database.BatchableContext bc){
        }
}