force-app/main/default/objects/Records_Processing_Intervals__mdt.object
<CustomObject>
    <description>This is created for User Story No. 164369 (Pls don&apos;t delete). This MDT is for determining how earlier the records should be taken into consideration based on the days, hours, mins for processing. This is being used in determining the timestamp of the Program Enrollment/Relationship object records for the LC Community Access to School relevant Knowledge Articles based on Topics.</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <description>User Story #164369.
This field on the metadata type is meant for defining the batch size for the Program Enrollment Batch Job and Relationships Batch Job execution. This value defines the batch job lot size for processing.</description>
        <inlineHelpText>Please enter the Batch Job Lot Size for the batch processing on Program Enrollment records and Relationship records. The value to be keyed should be greater than 0.</inlineHelpText>
        <label>Batch Size</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Records Processing Intervals</label>
    <pluralLabel>Records Processing Intervals</pluralLabel>
</CustomObject>

force-app/main/default/classes/CS_CTSTDLC_PE_RLTN_KM_BatchSchedule.cls
/*
 * Developed By - Rakesh Ramaswamy (Ness Technologies)
 * Related User Story No. 164369
 * Description - This is a scheduler class to invoke the Program Enrollment batch at a specific time of the day.
 *               This scheduler will be setup for executing at the specific time each day through the "Schedule Apex" feature on Salesforce Setup >> Apex Classes.
 */


global class CS_CTSTDLC_PE_RLTN_KM_BatchSchedule implements Schedulable {              

    global void execute(SchedulableContext sc) {

       Records_Processing_Intervals__mdt recordProcessInterval = [SELECT Batch_Size__c FROM Records_Processing_Intervals__mdt WHERE DeveloperName = :CS_Constants.LC_KBA_ACCESS_PROGENROLL_RECS_PROCESS];
       Integer batchSize = 200;
       if((recordProcessInterval.Batch_Size__c != null) && (recordProcessInterval.Batch_Size__c > 0)){
           batchSize = Integer.valueOf(recordProcessInterval.Batch_Size__c);
       }
       Database.executeBatch(new CS_LCUserCTPermSetsAccessProgEnrollBatch(), batchSize);     
    }     
}